-- Supplement Citoyenneté (matiere_id=31) — tous niveaux
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 31 AND titre = 'Droits et devoirs du citoyen haïtien' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel texte fondamental définit les droits et libertés des citoyens haïtiens ?', '["Le Code Civil","La Constitution de la République d''Haïti","Le Code Pénal","La Déclaration des droits de 1804"]'::jsonb, 'La Constitution de la République d''Haïti', 'La Constitution haïtienne (actuelle : 1987 amendée) définit les droits fondamentaux et l''organisation de l''État.', 'Facile'),
    (chap_id, 'À quel âge le citoyen haïtien acquiert-il le droit de vote ?', '["16 ans","18 ans","21 ans","25 ans"]'::jsonb, '18 ans', 'Selon la Constitution haïtienne, le droit de vote est accordé à l''âge de 18 ans.', 'Facile'),
    (chap_id, 'Qu''est-ce que la nationalité haïtienne selon la Constitution ?', '["Elle ne peut s''acquérir","Elle peut être d''origine (naissance de","Elle est réservée aux natifs du sol","Elle est automatique pour tout résident"]'::jsonb, 'Elle peut être d''origine (naissance de', 'La Constitution définit les conditions d''acquisition et de perte de la nationalité haïtienne.', 'Moyen'),
    (chap_id, 'Quel est le devoir civique le plus fondamental du citoyen dans une démocratie ?', '["Payer des impôts","Participer aux élections et à la vie","Rejoindre un parti","Servir dans l''armée"]'::jsonb, 'Participer aux élections et à la vie', 'La participation électorale est l''acte démocratique fondamental permettant à la volonté populaire de s''exprimer.', 'Facile'),
    (chap_id, 'Qu''est-ce que le principe de séparation des pouvoirs en Haïti ?', '["Le pouvoir est concentré au présidentiel","Le pouvoir est divisé entre exécutif","Le pouvoir appartient au Parlement seul","Le pouvoir est régional"]'::jsonb, 'Le pouvoir est divisé entre exécutif', 'La séparation des pouvoirs (Montesquieu) prévient la tyrannie ; chaque pouvoir contrôle les autres.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''égalité devant la loi signifie en droit haïtien ?', '["Les lois sont différentes selon le statut social","Tous les citoyens sont soumis aux mêmes","Les riches sont traités différemment","La loi ne s''applique qu''aux pauvres"]'::jsonb, 'Tous les citoyens sont soumis aux mêmes', 'L''égalité juridique est un principe fondamental : nul n''est au-dessus de la loi, quel que soit son statut.', 'Facile'),
    (chap_id, 'Qu''est-ce que la liberté d''expression et ses limites ?', '["Une liberté absolue sans limite","Le droit d''exprimer ses opinions","Un droit réservé aux médias","Un droit conditionnel à l''approbation gouvernementale"]'::jsonb, 'Le droit d''exprimer ses opinions', 'La liberté d''expression est fondamentale mais s''arrête où commence le droit d''autrui.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la présomption d''innocence dans le système judiciaire ?', '["L''accusé est coupable jusqu''à preuve du contraire","Toute personne est considérée innocente","L''innocence doit être prouvée","La police décide de la culpabilité"]'::jsonb, 'Toute personne est considérée innocente', 'La présomption d''innocence est un droit fondamental protégeant contre les condamnations arbitraires.', 'Facile'),
    (chap_id, 'Qu''est-ce que la responsabilité civile du citoyen ?', '["L''obligation de servir dans l''armée","L''obligation de réparer les dommages","Le paiement des impôts","Le service militaire"]'::jsonb, 'L''obligation de réparer les dommages', 'La responsabilité civile oblige à indemniser les victimes de dommages causés par sa faute.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le droit à l''éducation consacré par la Constitution haïtienne ?', '["Un droit optionnel","Un droit fondamental de tout enfant","Un droit réservé aux garçons","Un droit des parents uniquement"]'::jsonb, 'Un droit fondamental de tout enfant', 'La Constitution haïtienne consacre le droit à l''éducation et l''obligation scolaire primaire.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le service communautaire comme expression de la citoyenneté active ?', '["Un devoir légal pénible","Une participation volontaire à","Un service militaire","Une activité rémunérée"]'::jsonb, 'Une participation volontaire à', 'La citoyenneté active va au-delà des droits : elle implique de contribuer au bien commun.', 'Facile'),
    (chap_id, 'Qu''est-ce que la laïcité de l''État et son importance en Haïti ?', '["L''État catholique","La neutralité de l''État par rapport à","L''interdiction des religions","L''État vodou"]'::jsonb, 'La neutralité de l''État par rapport à', 'La Constitution haïtienne garantit la liberté de religion ; l''État n''a pas de religion officielle.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la décentralisation en Haïti vise à accomplir ?', '["Concentrer le pouvoir à Port-au-Prince","Rapprocher les décisions du citoyen en","Supprimer les mairies","Privatiser les services publics"]'::jsonb, 'Rapprocher les décisions du citoyen en', 'La décentralisation (objet de nombreuses réformes en Haïti) vise à réduire l''hypertrophie de la capitale.', 'Moyen'),
    (chap_id, 'Quel organisme international proclame les droits fondamentaux de l''homme ?', '["L''OEA","L''ONU","L''UNICEF","La Cour Pénale Internationale"]'::jsonb, 'L''ONU', 'La DUDH (1948) proclame 30 articles sur les droits civils, politiques, économiques et sociaux.', 'Facile'),
    (chap_id, 'Qu''est-ce que le devoir de mémoire dans la citoyenneté haïtienne ?', '["Oublier le passé pour avancer","L''obligation morale de se souvenir de","La mémoire sélective","L''étude exclusive de l''antiquité"]'::jsonb, 'L''obligation morale de se souvenir de', 'Le devoir de mémoire haïtien inclut l''esclavage, la révolution de 1804 et les luttes pour la dignité.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 31 AND titre = 'Institutions haïtiennes et gouvernance' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Comment le Président de la République d''Haïti est-il élu ?', '["Par le Parlement","Au suffrage universel direct à deux","Par le Premier Ministre","Par le Conseil des Ministres"]'::jsonb, 'Au suffrage universel direct à deux', 'Le Président haïtien est élu au suffrage universel ; si nul ne dépasse 50%, un second tour oppose les deux premiers.', 'Moyen'),
    (chap_id, 'Quelle est la durée du mandat présidentiel en Haïti selon la Constitution de 1987 ?', '["4 ans renouvelables","5 ans non consécutivement renouvelables","7 ans","6 ans"]'::jsonb, '5 ans non consécutivement renouvelables', 'Le Président élu pour 5 ans ne peut pas exercer deux mandats consécutifs.', 'Moyen'),
    (chap_id, 'Quelle est la composition du Parlement haïtien (Assemblée Nationale) ?', '["Une seule chambre","Deux chambres","Trois chambres","Le Parlement est unicaméral"]'::jsonb, 'Deux chambres', 'Le Parlement haïtien est bicaméral : Sénat (30 sénateurs) et Chambre des Députés (119 membres).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le Conseil Electoral Permanent (CEP) en Haïti ?', '["Un tribunal","L''institution responsable de","Le Ministère de l''Intérieur","Une commission parlementaire"]'::jsonb, 'L''institution responsable de', 'Le CEP haïtien organise les élections ; son indépendance est essentielle à la crédibilité démocratique.', 'Moyen'),
    (chap_id, 'Quel est le rôle du Conseil Supérieur du Pouvoir Judiciaire (CSPJ) ?', '["Faire les lois","Superviser la magistrature","Exécuter les lois","Organiser les élections"]'::jsonb, 'Superviser la magistrature', 'Le CSPJ est l''instance de contrôle du pouvoir judiciaire haïtien, garant de son indépendance.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Cour Supérieure des Comptes et du Contentieux Administratif (CSC/CA) ?', '["Un tribunal pénale","La juridiction suprême administrative","Le Parlement financier","La Banque centrale"]'::jsonb, 'La juridiction suprême administrative', 'La CSC/CA est l''équivalent haïtien d''une Cour des Comptes, contrôlant l''usage des fonds publics.', 'Moyen'),
    (chap_id, 'Quel est le rôle du Premier Ministre en Haïti ?', '["Dirigeant suprême de l''État","Chef du gouvernement","Un conseiller du Président","Un membre du Sénat"]'::jsonb, 'Chef du gouvernement', 'Le PM haïtien est nommé par le Président mais doit obtenir l''investiture du Parlement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la déclaration de patrimoine des fonctionnaires haïtiens vise à combattre ?', '["Le manque de compétences","La corruption et l''enrichissement","L''évasion fiscale privée","L''immigration clandestine"]'::jsonb, 'La corruption et l''enrichissement', 'La déclaration de patrimoine (ULCC) est un outil anti-corruption permettant de détecter les enrichissements illicites.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la collectivité territoriale de la commune en Haïti ?', '["Un département","L''unité administrative de base dirigée","Une section communale","Un arrondissement"]'::jsonb, 'L''unité administrative de base dirigée', 'La commune est gouvernée par un Conseil Municipal (CASEC/ASEC pour les sections rurales).', 'Moyen'),
    (chap_id, 'Quel est le rôle de la société civile dans la gouvernance démocratique ?', '["Aucun rôle officiel","Surveiller le gouvernement","Remplacer le gouvernement","Administrer les élections"]'::jsonb, 'Surveiller le gouvernement', 'La société civile (ONGs, associations, syndicats) est un contre-pouvoir essentiel en démocratie.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le budget national représente comme outil de gouvernance ?', '["Un document comptable interne","Le plan financier de l''État définissant","Un emprunt international","Le budget du Président"]'::jsonb, 'Le plan financier de l''État définissant', 'Le budget de l''État est une loi votée par le Parlement ; il traduit les priorités politiques en chiffres.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la redevabilité (accountability) dans la gouvernance publique ?', '["L''élection des dirigeants","L''obligation pour les dirigeants de","L''audit interne","Le contrôle budgétaire"]'::jsonb, 'L''obligation pour les dirigeants de', 'La redevabilité est essentielle à la démocratie : les élus doivent répondre de leurs actes.', 'Moyen'),
    (chap_id, 'Quel organe constitutionnel haïtien peut destituer le Président par la procédure d''impeachment ?', '["La Cour Suprême","Le Parlement (Assemblée Nationale)","Le Conseil Electoral","Le Conseil des Ministres"]'::jsonb, 'Le Parlement (Assemblée Nationale)', 'L''Assemblée Nationale peut mettre en accusation le Président pour violation de la Constitution.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la gouvernance locale en Haïti et ses défis ?', '["Un système fonctionnel","Une gouvernance de proximité confrontée","Un modèle de décentralisation réussi","Un système purement rural"]'::jsonb, 'Une gouvernance de proximité confrontée', 'Haïti peine à décentraliser effectivement ; les collectivités locales manquent d''autonomie et de moyens.', 'Difficile');
  END IF;
END $$;
