-- Supplement EPS (matiere_id=29) — tous niveaux
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 29 AND titre = 'Anatomie fonctionnelle et physiologie de l''effort' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le rôle principal du système cardiovasculaire lors de l''effort physique ?', '["Digérer les aliments","Acheminer l''oxygène et les nutriments","Réguler la température","Produire des hormones"]'::jsonb, 'Acheminer l''oxygène et les nutriments', 'Lors de l''effort, le débit cardiaque augmente pour répondre aux besoins métaboliques des muscles.', 'Facile'),
    (chap_id, 'Qu''est-ce que la fréquence cardiaque maximale théorique (FCmax) ?', '["200 battements/min pour tous","Approximativement 220 - âge (en années)","180 battements/min pour tous","La fréquence au repos"]'::jsonb, 'Approximativement 220 - âge (en années)', 'La formule Astrand FCmax ≈ 220 - âge est une estimation de la limite cardiaque maximale théorique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la VO2 max mesure ?', '["La force musculaire maximale","La consommation maximale d''oxygène","La fréquence cardiaque","La flexibilité"]'::jsonb, 'La consommation maximale d''oxygène', 'La VO2 max est le principal indicateur de la capacité cardio-respiratoire ; elle se mesure en mL/kg/min.', 'Moyen'),
    (chap_id, 'Quel type de fibre musculaire est spécialisé dans les efforts de longue durée (endurance) ?', '["Fibres blanches rapides (type II)","Fibres rouges lentes (type I)","Fibres mixtes","Fibres tendineuses"]'::jsonb, 'Fibres rouges lentes (type I)', 'Les fibres lentes (type I) sont riches en mitochondries et myoglobine, résistantes à la fatigue.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la filière anaérobie lactique dans le sport ?', '["Production d''énergie avec oxygène","Production d''énergie sans oxygène avec","Récupération musculaire","Métabolisme des lipides"]'::jsonb, 'Production d''énergie sans oxygène avec', 'La glycolyse anaérobie produit de l''ATP rapidement mais génère des lactates qui fatiguent le muscle.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''échauffement permet d''accomplir physiologiquement ?', '["Réduire la fréquence cardiaque","Augmenter la température musculaire","Augmenter la fatigue","Réduire l''apport sanguin aux muscles"]'::jsonb, 'Augmenter la température musculaire', 'L''échauffement prépare le système cardio-vasculaire, ostéo-articulaire et neuromusculaire à l''effort.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''acide lactique et quel est son rôle dans la fatigue musculaire ?', '["Un carburant musculaire","Un déchet métabolique produit lors des","Une hormone","Un nutriment anti-fatigue"]'::jsonb, 'Un déchet métabolique produit lors des', 'L''accumulation de lactate et d''ions H+ abaisse le pH musculaire et perturbe la contraction.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''hydratation optimale pendant l''effort physique prévient ?', '["L''augmentation de la force","La déshydratation","L''hypertrophie musculaire","La fatigue nerveuse"]'::jsonb, 'La déshydratation', 'Même 2% de déshydratation réduit les performances de 10-20% ; l''hydratation est primordiale.', 'Facile'),
    (chap_id, 'Qu''est-ce que le principe de surcompensation dans l''entraînement sportif ?', '["S''entraîner sans récupération","Après un effort","Le surmenage physique","L''entraînement croisé"]'::jsonb, 'Après un effort', 'La surcompensation est le fondement du progrès sportif : effort → fatigue → récupération → progrès.', 'Moyen'),
    (chap_id, 'Quel macronutriment est la principale source d''énergie lors d''efforts d''intensité modérée à élevée ?', '["Lipides","Protéines","Glucides","Vitamines"]'::jsonb, 'Glucides', 'Les glucides (glycogène musculaire et hépatique) sont le carburant préférentiel lors des efforts intenses.', 'Facile'),
    (chap_id, 'Qu''est-ce que le seuil anaérobie (ou seuil lactique) ?', '["La VO2 max","L''intensité à laquelle la production de","La fréquence cardiaque maximale","Le seuil de douleur"]'::jsonb, 'L''intensité à laquelle la production de', 'Au-delà du seuil anaérobie, le lactate s''accumule ; l''entraînement le repousse pour les sportifs.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la proprioception en EPS ?', '["La vision périphérique","La capacité du corps à percevoir sa","La coordination avec les partenaires","La résistance à la douleur"]'::jsonb, 'La capacité du corps à percevoir sa', 'La proprioception est assurée par les fuseaux neuromusculaires ; elle est essentielle à l''équilibre.', 'Moyen'),
    (chap_id, 'Quel est l''effet de l''entraînement aérobie régulier sur le cœur ?', '["Réduction du cœur","Hypertrophie du ventricule gauche et","Augmentation permanente de la FC","Aucun effet"]'::jsonb, 'Hypertrophie du ventricule gauche et', 'Le "cœur d''athlète" pompe plus de sang à chaque battement, d''où une FC de repos plus basse.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la thermorégulation lors de l''effort physique en chaleur tropicale ?', '["Le corps se refroidit sans effort","La transpiration évaporative est le","Le corps s''adapte en réduisant l''effort","La chaleur améliore la performance"]'::jsonb, 'La transpiration évaporative est le', 'En climat tropical, la thermorégulation est cruciale ; la chaleur humide réduit l''évaporation et le risque.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 29 AND titre = 'Sports collectifs : règles, tactiques et arbitrage' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Combien de joueurs compose une équipe de football sur le terrain ?', '["9","10","11","12"]'::jsonb, '11', 'Le football se joue à 11 contre 11 selon les règles FIFA, incluant le gardien de but.', 'Facile'),
    (chap_id, 'Qu''est-ce que la règle du hors-jeu au football ?', '["Un joueur offensif ne peut pas dépasser la ligne médiane","Un attaquant est hors-jeu s''il est plus","Un joueur ne peut pas revenir en défense","Toute faute en dehors du terrain"]'::jsonb, 'Un attaquant est hors-jeu s''il est plus', 'La règle du hors-jeu (offside) s''applique au moment de la passe, pas du contrôle.', 'Moyen'),
    (chap_id, 'Combien de joueurs compose une équipe de basket-ball sur le terrain ?', '["4","5","6","7"]'::jsonb, '5', 'Le basket-ball se joue à 5 contre 5 selon les règles FIBA.', 'Facile'),
    (chap_id, 'Qu''est-ce que la règle des 24 secondes au basket-ball ?', '["La durée d''un quart-temps","L''équipe en attaque doit tirer au","La durée du temps mort","Le nombre de secondes pour dribbler"]'::jsonb, 'L''équipe en attaque doit tirer au', 'La règle des 24s accélère le jeu ; dépasser ce délai donne la balle à l''adversaire.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un corner au football ?', '["Un but marqué dans un angle","Un coup de pied de récupération botté","Un hors-jeu","Un coup franc"]'::jsonb, 'Un coup de pied de récupération botté', 'Le corner est accordé quand la défense touche le dernier le ballon qui sort par sa ligne de but.', 'Facile'),
    (chap_id, 'Qu''est-ce que la zone de presse (pressing) en sports collectifs ?', '["Un système défensif passif","Un dispositif collectif qui harcèle","Un système offensif","Un signal d''arbitre"]'::jsonb, 'Un dispositif collectif qui harcèle', 'Le pressing est une stratégie collective de récupération haute du ballon utilisée en football, basket, handball.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un pivot au basket-ball ?', '["Le joueur gardien de but","Le mouvement de rotation sur un pied","La ligne centrale","Un tir à trois points"]'::jsonb, 'Le mouvement de rotation sur un pied', 'Le pivot permet au porteur du ballon de changer d''orientation sans marcher, protéger le ballon.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le volley-ball permet dans sa règle fondamentale ?', '["Toucher le sol avec le ballon","Faire tomber le ballon au sol adverse","Garder le ballon longtemps","Marquer uniquement au service"]'::jsonb, 'Faire tomber le ballon au sol adverse', 'Le volley-ball se joue en 3 touches maximum par équipe ; le ballon ne doit pas toucher le sol de son propre camp.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''écran (ou pick) au basket-ball ?', '["Une faute","Une action défensive où un joueur fait","Un signal d''arbitre","Un rebond offensif"]'::jsonb, 'Une action défensive où un joueur fait', 'Le pick (écran) est une technique offensive fondamentale ; l''écranteur doit être immobile pour que l''action soit légale.', 'Moyen'),
    (chap_id, 'Quel est l''objectif tactique du jeu en contre-attaque en sports collectifs ?', '["Défendre lentement","Exploiter rapidement le déséquilibre","Conserver le ballon","Faire des fautes tactiques"]'::jsonb, 'Exploiter rapidement le déséquilibre', 'La contre-attaque vise à attaquer avant que l''adversaire soit replacé défensivement.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un set au volley-ball ?', '["Un service","Une manche du match gagnée à 25 points","Un filet","Un coup de pied"]'::jsonb, 'Une manche du match gagnée à 25 points', 'Un match de volley-ball se joue en 3 ou 5 sets selon le niveau ; le set se gagne à 25 points minimum.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la communication verbale et non verbale dans les sports collectifs ?', '["Un aspect secondaire","Un outil essentiel de coordination","La communication avec l''arbitre","Les signaux de l''entraîneur uniquement"]'::jsonb, 'Un outil essentiel de coordination', 'En sports collectifs, appels de balle, gestes codifiés et communication permettent la cohésion tactique.', 'Moyen'),
    (chap_id, 'Quel est le rôle du gardien de but au football par rapport au champ ?', '["Identique aux joueurs de champ","Le seul joueur autorisé à jouer le","Le capitaine obligatoire","Un attaquant supplémentaire"]'::jsonb, 'Le seul joueur autorisé à jouer le', 'Le gardien a un statut particulier : il peut utiliser ses mains dans sa surface, contrairement aux autres.', 'Facile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 29 AND titre = 'Santé, hygiène et prévention des blessures sportives' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une entorse et comment la traiter en premiers secours ?', '["Une fracture osseuse","Une lésion ligamentaire traitée par le","Une contusion musculaire","Une luxation"]'::jsonb, 'Une lésion ligamentaire traitée par le', 'L''entorse est un étirement ou une déchirure ligamentaire ; RICE (repos, glace, compression, élévation) est le protocole immédiat.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre blessure aiguë et blessure chronique en sport ?', '["Aucune","Aiguë = survient soudainement (choc","L''aiguë est toujours plus grave","La chronique ne se traite pas"]'::jsonb, 'Aiguë = survient soudainement (choc', 'Les blessures de surmenage (tendinite, stress fracture) résultent d''une accumulation de microtraumatismes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le dopage et pourquoi est-il interdit ?', '["L''entraînement intensif","L''usage de substances ou méthodes","Un type de nutrition","Un régime d''entraînement"]'::jsonb, 'L''usage de substances ou méthodes', 'L''AMA (Agence Mondiale Antidopage) gère la liste des substances interdites et les contrôles.', 'Facile'),
    (chap_id, 'Quels sont les dangers des corticoïdes utilisés comme dopants ?', '["Aucun danger","Fragilisation des tendons","Amélioration osseuse","Renforcement ligamentaire"]'::jsonb, 'Fragilisation des tendons', 'Les corticoïdes masquent la douleur mais fragilisent les structures tendineuses à long terme.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''activité physique adaptée (APA) ?', '["Le sport de haut niveau","L''activité physique conçue pour les","L''entraînement des jeunes","Le sport scolaire"]'::jsonb, 'L''activité physique conçue pour les', 'L''APA adapte les pratiques aux capacités de chacun ; elle est reconnue comme bénéfique thérapeutiquement.', 'Moyen'),
    (chap_id, 'Quel est l''effet de la sédentarité sur la santé à long terme ?', '["Bénéfique pour les articulations","Augmentation du risque de maladies","Aucun effet","Renforcement osseux"]'::jsonb, 'Augmentation du risque de maladies', 'L''OMS recommande 150 min d''activité modérée/semaine ; la sédentarité est un facteur de risque majeur.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un claquage musculaire ?', '["Une fracture","Une déchirure partielle ou totale de","Une entorse","Un hématome"]'::jsonb, 'Une déchirure partielle ou totale de', 'Le claquage survient lors d''un effort maximal ou d''un échauffement insuffisant ; la douleur est brutale.', 'Moyen'),
    (chap_id, 'Comment prévenir les blessures sportives liées à la croissance chez les adolescents ?', '["Augmenter l''intensité","Respecter des charges d''entraînement","Éviter tout sport","Spécialisation précoce"]'::jsonb, 'Respecter des charges d''entraînement', 'Les jeunes sportifs sont vulnérables aux lésions des cartilages de croissance ; la spécialisation précoce est risquée.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe de progressivité en entraînement sportif ?', '["Augmenter brutalement les charges","Augmenter les charges de travail","S''entraîner à intensité constante","Réduire progressivement le travail"]'::jsonb, 'Augmenter les charges de travail', 'La progressivité prévient les blessures et optimise les adaptations physiologiques à l''entraînement.', 'Facile'),
    (chap_id, 'Qu''est-ce que le récupération active après l''effort ?', '["Dormir immédiatement","Effectuer un effort léger (footing lent","Prendre un bain glacé","Ne rien faire pendant 24h"]'::jsonb, 'Effectuer un effort léger (footing lent', 'La récupération active maintient la circulation sanguine et favorise l''élimination des déchets métaboliques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la technique du bandage compressif et quand l''utiliser ?', '["Pour toute douleur","Technique d''immobilisation partielle et","Pour les fractures uniquement","Pour améliorer la performance"]'::jsonb, 'Technique d''immobilisation partielle et', 'Le bandage compressif (partie du RICE) réduit l''inflammation et soutient l''articulation lésée.', 'Moyen'),
    (chap_id, 'Quels sont les bénéfices psychologiques reconnus de l''activité physique régulière ?', '["Aucun bénéfice prouvé","Réduction du stress","Augmentation de l''agressivité","Diminution de la concentration"]'::jsonb, 'Réduction du stress', 'L''activité physique stimule les endorphines et la sérotonine, bénéfiques pour la santé mentale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''ergonomie sportive et son rôle en prévention ?', '["La nutrition sportive","L''adaptation du matériel","Le massage sportif","L''arbitrage sportif"]'::jsonb, 'L''adaptation du matériel', 'L''ergonomie sportive inclut le choix des équipements, la technique gestuelle et l''aménagement des espaces.', 'Moyen');
  END IF;
END $$;
