-- Supplément Informatique NS1-NS2 (matiere_id=17) — +15 questions/chapitre

-- Chapitre 1 : Introduction à l'informatique et représentation de l'information NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Introduction à l''informatique et représentation de l''information' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le système de numération utilisé par les ordinateurs en interne ?', '["Le système décimal (base 10)", "Le système binaire (base 2)", "Le système hexadécimal (base 16)", "Le système octal (base 8)"]'::jsonb, 'Le système binaire (base 2)', 'Les ordinateurs utilisent le système binaire car leurs composants électroniques (transistors) ont deux états : courant présent (1) ou absent (0). Tout traitement informatique repose sur des suites de 0 et 1 appelées bits. Un groupe de 8 bits forme un octet (byte).', 'Facile'),
    (chap_id, 'Que représente le nombre binaire 1010 en décimal ?', '["8", "10", "12", "15"]'::jsonb, '10', '1010 en binaire = 1×2³ + 0×2² + 1×2¹ + 0×2⁰ = 8 + 0 + 2 + 0 = 10 en décimal. Pour convertir du binaire au décimal, on multiplie chaque bit par la puissance de 2 correspondant à sa position (en partant de 0 à droite).', 'Moyen'),
    (chap_id, 'Combien de valeurs différentes peut représenter un octet (8 bits) ?', '["8", "16", "128", "256"]'::jsonb, '256', 'Un octet (8 bits) peut représenter 2⁸ = 256 valeurs différentes, de 0 à 255. Chaque bit peut prendre 2 valeurs (0 ou 1), donc n bits peuvent représenter 2ⁿ valeurs. C''est pourquoi les adresses IP IPv4 utilisent des nombres de 0 à 255 pour chaque octet.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre un bit et un octet ?', '["Ce sont des synonymes", "Un bit est la plus petite unité", "Un bit représente une lettre ; un octet représente un chiffre", "Un octet est plus petit qu''un bit"]'::jsonb, 'Un bit est la plus petite unité', 'Le bit (binary digit) est l''unité fondamentale de l''information numérique : 0 ou 1. L''octet (byte) = 8 bits. Les multiples : 1 kilooctet (Ko) = 1024 octets, 1 mégaoctet (Mo) = 1024 Ko, 1 gigaoctet (Go) = 1024 Mo. Un caractère ASCII prend 1 octet, une image HD peut prendre plusieurs Mo.', 'Facile'),
    (chap_id, 'Qu''est-ce que le code ASCII et à quoi sert-il ?', '["Un code de programmation pour créer des interfaces graphiques", "Un standard qui associe chaque", "Un protocole de communication entre ordinateurs sur Internet", "Un système de compression de fichiers"]'::jsonb, 'Un standard qui associe chaque', 'ASCII (American Standard Code for Information Interchange) définit 128 caractères codés sur 7 bits : les lettres A-Z (65-90), a-z (97-122), les chiffres 0-9 (48-57) et les symboles courants. Il est la base de l''encodage Unicode (UTF-8), qui étend la représentation à tous les caractères du monde dont les caractères créoles et accentués.', 'Moyen'),
    (chap_id, 'Comment convertir le nombre décimal 13 en binaire ?', '["1101", "1011", "1110", "1001"]'::jsonb, '1101', '13 ÷ 2 = 6 reste 1 ; 6 ÷ 2 = 3 reste 0 ; 3 ÷ 2 = 1 reste 1 ; 1 ÷ 2 = 0 reste 1. En lisant les restes de bas en haut : 1101. Vérification : 1×8 + 1×4 + 0×2 + 1×1 = 13. La méthode est de diviser successivement par 2 et de lire les restes en remontant.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la mémoire RAM d''un ordinateur ?', '["La mémoire de stockage permanente des données", "La mémoire vive", "Le disque dur de l''ordinateur", "La mémoire graphique de la carte vidéo"]'::jsonb, 'La mémoire vive', 'La RAM (Random Access Memory) est la mémoire de travail de l''ordinateur : elle stocke temporairement les programmes en cours d''exécution et les données actives. Elle est rapide (accès en nanosecondes) mais volatile (son contenu est perdu à l''extinction). Sa taille (4 Go, 8 Go, 16 Go...) conditionne le nombre de tâches simultanées.', 'Facile'),
    (chap_id, 'Quelle est la différence entre un système d''exploitation et une application ?', '["Ce sont des synonymes", "Le système d''exploitation (OS) gère les", "L''OS est payant ; les applications sont gratuites", "L''OS fonctionne sur Internet ; les applications sur l''ordinateur"]'::jsonb, 'Le système d''exploitation (OS) gère les', 'L''OS (Windows, macOS, Linux, Android) est la couche logicielle fondamentale qui gère le processeur, la mémoire, le stockage, les entrées/sorties et permet aux applications de fonctionner. Une application (navigateur web, traitement de texte, jeu) est un programme qui utilise les services de l''OS pour remplir une fonction précise.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un "fichier" en informatique ?', '["Un programme en cours d''exécution", "Un ensemble de données stockées sous un", "Une connexion réseau entre deux ordinateurs", "Un composant matériel de l''ordinateur"]'::jsonb, 'Un ensemble de données stockées sous un', 'Un fichier est une unité de stockage nommée sur un support persistant. Il est identifié par son nom et son extension (.txt, .jpg, .pdf, .py). Les fichiers sont organisés dans des dossiers (répertoires) selon une structure arborescente. Le système de fichiers (NTFS, ext4, FAT32) gère l''organisation physique des fichiers sur le disque.', 'Facile'),
    (chap_id, 'Qu''est-ce que le système hexadécimal et pour quoi est-il utilisé en informatique ?', '["Un système de numération en base 16", "Un système de numération en base 12 utilisé pour les calculs scientifiques", "Un type de code de programmation pour les jeux vidéo", "Un protocole de communication réseau"]'::jsonb, 'Un système de numération en base 16', 'L''hexadécimal (base 16) utilise 0-9 et A(10)-F(15). Il est pratique car 1 chiffre hex = 4 bits exactement : 0xFF = 11111111 en binaire = 255 en décimal. On l''utilise pour les adresses mémoire, les couleurs RGB (#FF5733), les codes d''erreur et les dumps de mémoire. La notation 0x signale un nombre hexadécimal.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre la mémoire RAM et le disque dur (SSD/HDD) ?', '["La RAM est plus grande ; le disque dur est plus petit", "La RAM est rapide et volatile", "La RAM stocke des fichiers ; le disque dur stocke des programmes", "Il n''y a pas de différence fonctionnelle"]'::jsonb, 'La RAM est rapide et volatile', 'Hiérarchie mémoire : registres CPU (ultra-rapide, quelques octets) > cache L1/L2 (très rapide, quelques Mo) > RAM (rapide, 8-32 Go, volatile) > disque dur SSD (moins rapide, 256 Go-4 To, persistant) > disque dur HDD (lent, 1-10 To, persistant). Chaque niveau est plus grand et moins cher mais plus lent que le précédent.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "processeur" (CPU) et quel est son rôle ?', '["Le composant qui affiche l''image sur l''écran", "Le composant qui exécute les", "Le composant qui stocke les données de façon permanente", "Le composant qui gère la connexion Internet"]'::jsonb, 'Le composant qui exécute les', 'Le CPU (Central Processing Unit) est le "cerveau" de l''ordinateur. Il exécute les instructions des programmes en cycles : chercher l''instruction en mémoire, la décoder, l''exécuter, écrire le résultat. Sa vitesse se mesure en GHz (milliards de cycles par seconde). Les CPU modernes ont plusieurs cœurs (2, 4, 8...) pour paralléliser les calculs.', 'Facile'),
    (chap_id, 'Comment représente-t-on un nombre négatif en informatique avec la notation en "complément à deux" ?', '["On ajoute un signe moins devant le nombre binaire", "On inverse tous les bits du nombre", "On met le bit de poids fort à 1 uniquement", "Les ordinateurs ne peuvent pas représenter les nombres négatifs"]'::jsonb, 'On inverse tous les bits du nombre', 'Le complément à deux est la représentation standard des entiers signés. Pour -n : inverser tous les bits de n, puis ajouter 1. Avantage : l''addition fonctionne identiquement pour les positifs et négatifs. Sur 8 bits, les plages : entier non signé 0-255, entier signé -128 à +127. Le bit de poids fort (MSB) indique le signe : 1 = négatif.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''"encodage" des données et pourquoi est-il important ?', '["Une technique de compression des fichiers", "La convention qui définit comment les", "Un procédé de sécurisation des données par chiffrement", "La méthode d''organisation des fichiers sur le disque dur"]'::jsonb, 'La convention qui définit comment les', 'L''encodage est une convention de représentation. UTF-8 encode les caractères Unicode. JPEG encode les images avec compression destructive. MP3 encode l''audio avec compression auditive. Sans encodage commun, l''information est un simple flux de bits incompréhensible. Les problèmes d''encodage (caractères "ù", "é" affichés comme "?") surviennent quand l''encodage de lecture diffère de l''encodage d''écriture.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''architecture "Von Neumann" sur laquelle sont basés la plupart des ordinateurs modernes ?', '["Une architecture graphique pour les interfaces utilisateur", "Un modèle d''ordinateur avec une unité", "Une architecture matérielle uniquement pour les superordinateurs", "Un système d''exploitation développé dans les années 1940"]'::jsonb, 'Un modèle d''ordinateur avec une unité', 'L''architecture Von Neumann (1945) est le modèle de base de la plupart des ordinateurs : une Unité Centrale de Traitement (CPU), une mémoire unique stockant données et programmes, une unité arithmétique et logique (UAL), et des unités d''entrée/sortie. La clé est que données et instructions partagent la même mémoire, permettant aux programmes de se modifier eux-mêmes.', 'Difficile');
  END IF;
END $$;

-- Chapitre 2 : Algorithmique et logique de programmation NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Algorithmique et logique de programmation' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''un algorithme ?', '["Un programme informatique écrit dans un langage de programmation spécifique", "Une suite d''instructions finies et", "Un type de matériel informatique pour accélérer les calculs", "Un virus informatique qui se reproduit automatiquement"]'::jsonb, 'Une suite d''instructions finies et', 'Un algorithme est une procédure de résolution de problème : une suite finie d''étapes claires et non ambiguës qui, appliquées à des données d''entrée, produisent un résultat. Un algorithme est indépendant du langage de programmation. Exemple : la recette de cuisine est un algorithme pour préparer un plat.', 'Facile'),
    (chap_id, 'Que fait une structure "conditionnelle" (if/else) en programmation ?', '["Elle répète des instructions plusieurs fois", "Elle exécute différentes instructions", "Elle définit une nouvelle variable", "Elle appelle une fonction externe"]'::jsonb, 'Elle exécute différentes instructions', 'La structure conditionnelle (if/else) permet au programme de prendre des décisions : "Si la condition est vraie, exécuter le bloc A ; sinon, exécuter le bloc B." C''est la base de la logique de programmation. Exemple : if (age >= 18) { afficher("majeur") } else { afficher("mineur") }', 'Facile'),
    (chap_id, 'Quelle est la différence entre une boucle "for" et une boucle "while" ?', '["Elles font exactement la même chose", "La boucle ''for'' répète un nombre connu", "La boucle ''for'' est plus rapide que la boucle ''while''", "La boucle ''for'' est pour les chiffres ; la boucle ''while'' est pour les textes"]'::jsonb, 'La boucle ''for'' répète un nombre connu', 'La boucle for est adaptée quand on connaît le nombre d''itérations : "for i in range(10) : ..." (10 répétitions). La boucle while répète tant qu''une condition est vraie : "while réponse != ''quit'' : ..." (nombre inconnu d''avance). Une boucle while dont la condition ne devient jamais fausse est une boucle infinie (bug).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "variable" en programmation ?', '["Un type de boucle particulier", "Un espace nommé en mémoire qui stocke", "Une instruction qui arrête le programme", "Une connexion réseau dans le programme"]'::jsonb, 'Un espace nommé en mémoire qui stocke', 'Une variable est un contenant nommé en mémoire. Elle a un nom (identifiant), un type (entier, réel, chaîne, booléen...) et une valeur. En Python : age = 17 (crée une variable "age" avec la valeur 17). La valeur peut être modifiée : age = age + 1 donne 18. Les variables permettent de mémoriser des données et de les réutiliser.', 'Facile'),
    (chap_id, 'Quelle est la complexité temporelle d''un algorithme de recherche linéaire dans un tableau non trié de n éléments ?', '["O(1) - temps constant", "O(log n) - logarithmique", "O(n) - linéaire", "O(n²) - quadratique"]'::jsonb, 'O(n) - linéaire', 'La recherche linéaire parcourt le tableau élément par élément jusqu''à trouver la cible. Dans le pire cas (cible absente ou en fin), elle examine tous les n éléments. Sa complexité est O(n) : le temps double si la taille double. C''est moins efficace que la recherche dichotomique O(log n) mais fonctionne sur un tableau non trié.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "fonction" (ou procédure) en programmation ?', '["Un type de variable qui stocke plusieurs valeurs", "Un bloc de code nommé et réutilisable", "Une boucle qui s''appelle elle-même", "Un commentaire dans le code"]'::jsonb, 'Un bloc de code nommé et réutilisable', 'Une fonction encapsule un traitement réutilisable : def calculer_aire(longueur, largeur): return longueur * largeur. Elle reçoit des paramètres (longueur, largeur), effectue un traitement et retourne un résultat. Les fonctions évitent la répétition de code (principe DRY : Don''t Repeat Yourself) et permettent de décomposer un problème complexe.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un "tableau" (ou liste) comme structure de données ?', '["Un programme organisé en tableaux", "Une collection ordonnée d''éléments du", "Un type de variable qui ne peut contenir qu''un seul chiffre", "Une connexion entre deux fonctions"]'::jsonb, 'Une collection ordonnée d''éléments du', 'Un tableau (array) stocke plusieurs valeurs sous un même nom, accessibles par leur position (indice). En Python : notes = [15, 12, 18, 10]. notes[0] = 15 (indice 0 = premier élément). La plupart des langages commencent les indices à 0. Les tableaux permettent de traiter des collections de données avec des boucles.', 'Facile'),
    (chap_id, 'Qu''est-ce que le "débogage" (debugging) en programmation ?', '["L''action d''écrire un nouveau programme", "Le processus d''identification et de", "La compression d''un programme pour le rendre plus petit", "La traduction d''un programme d''un langage à un autre"]'::jsonb, 'Le processus d''identification et de', 'Le débogage consiste à trouver et corriger les erreurs dans un programme. Types d''erreurs : erreurs de syntaxe (code mal écrit, repérées par le compilateur), erreurs d''exécution (le programme plante), erreurs logiques (le programme s''exécute mais produit un résultat incorrect). Les débogueurs (debuggers) permettent d''exécuter le code pas à pas.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''algorithme de tri par sélection et quelle est sa complexité ?', '["Un tri qui sélectionne aléatoirement les éléments ; complexité O(1)", "Un tri qui recherche le minimum", "Un tri qui divise le tableau en deux à chaque étape ; complexité O(n log n)", "Un tri qui compare des paires adjacentes et les échange ; complexité O(n)"]'::jsonb, 'Un tri qui recherche le minimum', 'Le tri par sélection : trouver le plus petit élément et le mettre en position 0, puis le 2e plus petit en position 1, etc. Pour n éléments : (n-1) + (n-2) + ... + 1 = n(n-1)/2 comparaisons → O(n²). Simple à comprendre mais inefficace pour de grands tableaux. Le tri rapide (QuickSort) ou tri fusion (MergeSort) ont une complexité O(n log n).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "récursivité" en programmation ?', '["Une technique pour accélérer les boucles", "Une technique où une fonction s''appelle", "Un type de variable qui se duplique", "Un algorithme qui trie les données de façon récurrente"]'::jsonb, 'Une technique où une fonction s''appelle', 'Une fonction récursive s''appelle elle-même : def factorielle(n): if n <= 1: return 1; return n * factorielle(n-1). Le cas de base (n <= 1) arrête les appels pour éviter une récursion infinie. La récursivité est naturelle pour certains problèmes (arbres, fractales, divide and conquer). Elle a un coût en mémoire (pile d''appels).', 'Moyen'),
    (chap_id, 'Quelle est la différence entre un "compilateur" et un "interpréteur" ?', '["Ce sont des synonymes", "Un compilateur traduit l''intégralité du", "Un compilateur est pour les langages web ; un interpréteur pour les logiciels de bureau", "Un compilateur est plus lent qu''un interpréteur"]'::jsonb, 'Un compilateur traduit l''intégralité du', 'Compilateur : traduit tout le code source en code machine avant l''exécution (C, C++, Java). Avantage : exécution rapide. Inconvénient : compilation longue, exécutable spécifique à un OS. Interpréteur : lit et exécute ligne par ligne (Python, JavaScript). Avantage : portabilité, débogage facile. Inconvénient : plus lent à l''exécution. Java utilise les deux : compilation en bytecode puis interprétation par la JVM.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "structure de données" et pourquoi son choix est-il important ?', '["Le style de codage utilisé par un programmeur", "Une façon d''organiser et de stocker les", "La taille totale des données d''un programme", "La disposition visuelle du code source"]'::jsonb, 'Une façon d''organiser et de stocker les', 'Les structures de données (tableaux, listes chaînées, piles, files, arbres, tables de hachage) organisent les données différemment, avec des compromis de performances. Un tableau donne un accès rapide par indice O(1) mais une insertion lente O(n). Une liste chaînée a une insertion rapide O(1) mais un accès lent O(n). Choisir la bonne structure est crucial pour les performances du programme.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une "pile" (stack) comme structure de données et quel principe suit-elle ?', '["Une structure d''accès aléatoire par indice", "Une structure LIFO (Last In, First Out)", "Une structure FIFO (First In, First Out) : le premier ajouté est le premier retiré", "Une structure arborescente avec des nœuds parents et enfants"]'::jsonb, 'Une structure LIFO (Last In, First Out)', 'La pile (stack) fonctionne comme une pile d''assiettes : on ajoute (push) et retire (pop) toujours par le dessus. LIFO : dernier entré = premier sorti. Usages : pile d''appels de fonctions, annulation (Ctrl+Z), évaluation d''expressions. Opérations : push (ajouter), pop (retirer), peek (regarder le sommet). La file (queue) est FIFO : premier entré = premier sorti.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "pseudo-code" et pourquoi l''utilise-t-on ?', '["Un code informatique illégal ou non officiel", "Une description informelle d''un", "Un code écrit dans un langage de programmation obsolète", "Un code généré automatiquement par un compilateur"]'::jsonb, 'Une description informelle d''un', 'Le pseudo-code permet de décrire la logique d''un algorithme sans se soucier de la syntaxe d''un langage précis : DEBUT, SI, ALORS, SINON, TANTQUE, POUR, FIN. Il facilite la communication entre développeurs et la conception des algorithmes avant l''implémentation. Les diagrammes de flux (flowcharts) ont le même objectif sous forme visuelle.', 'Facile');
  END IF;
END $$;

-- Chapitre 3 : Réseaux informatiques et Internet NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Réseaux informatiques et Internet' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une adresse IP et à quoi sert-elle ?', '["Un identifiant numérique unique", "Le mot de passe d''une connexion Wi-Fi", "Le nom de domaine d''un site web", "La vitesse de connexion Internet en Mbps"]'::jsonb, 'Un identifiant numérique unique', 'Une adresse IP (ex. 192.168.1.1 en IPv4) identifie de façon unique un appareil sur un réseau. IPv4 : 4 octets (0-255), 32 bits, ~4 milliards d''adresses (épuisées). IPv6 : 128 bits, format hexadécimal, ~340 undécillions d''adresses. Le routeur utilise les adresses IP pour acheminer les paquets de données vers leur destination.', 'Facile'),
    (chap_id, 'Qu''est-ce que le protocole HTTP et HTTPS ?', '["Des types de connexions Wi-Fi", "Des protocoles de transfert de données", "Des systèmes d''exploitation pour serveurs web", "Des langages de programmation pour créer des sites web"]'::jsonb, 'Des protocoles de transfert de données', 'HTTP (HyperText Transfer Protocol) définit comment le navigateur demande des pages web et comment le serveur les envoie. HTTPS est la version sécurisée : les données sont chiffrées par SSL/TLS (cadenas dans la barre d''adresse). HTTPS protège contre l''interception des données (mots de passe, informations bancaires). Aujourd''hui, tous les sites sérieux utilisent HTTPS.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un "routeur" dans un réseau informatique ?', '["Un appareil qui stocke des sites web en cache", "Un équipement réseau qui aiguille les", "Un logiciel de sécurité qui bloque les virus", "Un câble de connexion entre deux ordinateurs"]'::jsonb, 'Un équipement réseau qui aiguille les', 'Le routeur connecte des réseaux différents et achemine les paquets de données. Il maintient une table de routage qui indique par quelle interface envoyer les paquets selon leur adresse IP de destination. Le routeur domestique (box Internet) connecte le réseau local (LAN) à Internet (WAN). Les routeurs d''Internet constituent le "cœur" de réseau.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le protocole TCP/IP et pourquoi est-il fondamental sur Internet ?', '["Un langage de programmation pour créer des applications réseau", "La suite de protocoles fondamentaux", "Un système d''exploitation pour les serveurs web", "Un protocole de sécurité pour les communications chiffrées"]'::jsonb, 'La suite de protocoles fondamentaux', 'TCP/IP est la colonne vertébrale d''Internet. IP (Internet Protocol) gère l''adressage et le routage des paquets. TCP (Transmission Control Protocol) garantit la livraison fiable dans l''ordre, avec gestion des erreurs et retransmission si nécessaire. UDP est une alternative à TCP sans garantie de livraison mais plus rapide (streaming, jeux en ligne).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "DNS" (Domain Name System) ?', '["Un système de sécurité qui protège les sites web des hackers", "Un service qui traduit les noms de", "Un protocole de transfert de fichiers entre ordinateurs", "Un type de connexion Internet haute vitesse"]'::jsonb, 'Un service qui traduit les noms de', 'Le DNS est l''annuaire d''Internet. Quand vous tapez "www.google.com", votre ordinateur interroge un serveur DNS qui retourne l''adresse IP correspondante (ex. 142.250.185.46). Sans DNS, il faudrait mémoriser les adresses IP de tous les sites. La hiérarchie DNS : résolveur local → serveurs racines → serveurs TLD (.com, .ht) → serveur autoritaire du domaine.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre Internet et le Web (World Wide Web) ?', '["Ce sont des synonymes", "Internet est le réseau physique mondial", "Internet est accessible uniquement par ordinateur ; le Web est accessible par smartphone", "Internet est gratuit ; le Web est payant"]'::jsonb, 'Internet est le réseau physique mondial', 'Internet = l''infrastructure réseau (câbles, routeurs, protocoles TCP/IP). Le Web est un SERVICE qui utilise Internet : pages HTML, images, vidéos, liées par des hyperliens, accessibles via HTTP. D''autres services utilisent Internet : email (SMTP), messagerie instantanée, VoIP (téléphone IP), streaming vidéo, jeux en ligne. Le Web est donc une partie d''Internet.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "pare-feu" (firewall) et quel est son rôle ?', '["Un logiciel qui accélère la connexion Internet", "Un système de sécurité réseau qui", "Un type de routeur haute performance", "Un antivirus qui scanne les fichiers téléchargés"]'::jsonb, 'Un système de sécurité réseau qui', 'Le pare-feu analyse les paquets réseau et applique des règles : autoriser ou bloquer selon l''adresse IP source/destination, le port, le protocole. Il protège contre les intrusions depuis Internet vers le réseau local. Types : pare-feu à état (stateful), pare-feu applicatif (WAF). Windows et macOS intègrent un pare-feu logiciel. Les entreprises utilisent des pare-feu matériels.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "adresse MAC" et en quoi diffère-t-elle d''une adresse IP ?', '["Elles sont identiques", "L''adresse MAC est un identifiant", "L''adresse MAC est pour les ordinateurs Apple ; l''adresse IP pour les autres", "L''adresse MAC identifie un réseau ; l''adresse IP identifie un appareil"]'::jsonb, 'L''adresse MAC est un identifiant', 'L''adresse MAC (Media Access Control) est gravée dans la carte réseau à la fabrication : 6 octets en hexadécimal (ex. 00:1A:2B:3C:4D:5E). Elle est unique au monde (en théorie). Elle est utilisée pour la communication au niveau local (couche 2). L''adresse IP est attribuée par le réseau (DHCP) et peut changer. L''ARP fait le lien entre IP et MAC sur le réseau local.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "Wi-Fi" et comment fonctionne-t-il ?', '["Un câble de connexion réseau haute vitesse", "Une technologie de réseau sans fil qui", "Un protocole de sécurité pour les connexions Internet", "Un type de connexion satellite pour les zones rurales"]'::jsonb, 'Une technologie de réseau sans fil qui', 'Le Wi-Fi (IEEE 802.11) transmet les données sans fil via des ondes radio (2,4 GHz ou 5 GHz). La sécurité : WPA3 (le plus sécurisé), WPA2, WEP (obsolète et vulnérable). La portée typique : 30-50 m en intérieur. Les débits : Wi-Fi 4 (150 Mbps) → Wi-Fi 5 (1 Gbps) → Wi-Fi 6 (10 Gbps). Un réseau Wi-Fi public non sécurisé est risqué : données interceptables.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "modèle OSI" et combien de couches compte-t-il ?', '["Un modèle de programmation orientée objet à 3 couches", "Un modèle de référence à 7 couches pour", "Un système d''exploitation pour serveurs à 5 niveaux de sécurité", "Un protocole de sécurité Internet à 4 couches"]'::jsonb, 'Un modèle de référence à 7 couches pour', 'Le modèle OSI (Open Systems Interconnection) à 7 couches standardise les communications réseau : 1-Physique (bits sur câble), 2-Liaison (trames, MAC), 3-Réseau (paquets, IP), 4-Transport (TCP/UDP), 5-Session (connexions), 6-Présentation (encodage, chiffrement), 7-Application (HTTP, FTP, SMTP). Chaque couche offre des services à la couche supérieure.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un "port" réseau en informatique ?', '["Un connecteur physique sur l''ordinateur pour brancher des câbles", "Un numéro de 0 à 65535 qui identifie un", "Un type de routeur réseau haute performance", "La vitesse de transmission des données sur un réseau"]'::jsonb, 'Un numéro de 0 à 65535 qui identifie un', 'Les ports logiques permettent à un même ordinateur de faire tourner plusieurs services réseau : HTTP sur le port 80, HTTPS sur 443, SSH sur 22, FTP sur 21, DNS sur 53, SMTP sur 25. Quand votre navigateur se connecte à un site web, il utilise le port 443 (HTTPS). Le couple IP:Port identifie précisément un service sur un appareil du réseau.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "cloud computing" (informatique en nuage) ?', '["Un type de stockage sur une clé USB en forme de nuage", "La fourniture de ressources", "Une technologie de connexion Internet sans fil par satellite", "Un système de sauvegarde automatique sur le disque dur local"]'::jsonb, 'La fourniture de ressources', 'Le cloud computing offre des services IT via Internet : IaaS (Infrastructure as a Service : serveurs virtuels, stockage), PaaS (Platform as a Service : environnements de développement), SaaS (Software as a Service : Gmail, Google Docs, Office 365). Avantages : élasticité, pas d''infrastructure à gérer, paiement à l''usage. Fournisseurs majeurs : AWS, Google Cloud, Azure.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "bande passante" d''une connexion Internet ?', '["Le nombre d''appareils pouvant se connecter simultanément au Wi-Fi", "La quantité maximale de données pouvant", "Le coût mensuel d''un abonnement Internet", "La distance maximale couverte par un signal Wi-Fi"]'::jsonb, 'La quantité maximale de données pouvant', 'La bande passante est la "largeur" de la connexion : 100 Mbps signifie 100 mégabits par seconde. Elle détermine la vitesse de téléchargement et d''envoi. À ne pas confondre avec la latence (délai de transmission, en ms). Pour streamer une vidéo 4K il faut ~25 Mbps. La bande passante est partagée entre tous les utilisateurs du réseau local.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une "attaque DDoS" (Distributed Denial of Service) ?', '["Un virus qui chiffre les fichiers d''un ordinateur contre rançon", "Une attaque qui submerge un serveur de", "Une technique de vol de mots de passe par ingénierie sociale", "Une intrusion discrète dans un système pour voler des données"]'::jsonb, 'Une attaque qui submerge un serveur de', 'Une attaque DDoS utilise un botnet (réseau de machines compromises) pour inonder un serveur cible de requêtes, saturant sa bande passante ou ses ressources de traitement. Le serveur ne peut plus répondre aux requêtes légitimes. Contre-mesures : filtrage du trafic, CDN, équilibreurs de charge. Les sites gouvernementaux et bancaires sont des cibles fréquentes.', 'Moyen');
  END IF;
END $$;

-- Chapitre 4 : Bases de données et SQL NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Bases de données et SQL' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une base de données relationnelle ?', '["Un fichier Excel avec plusieurs colonnes", "Un ensemble de données organisées en", "Un dossier de fichiers sur un disque dur", "Un programme qui envoie des données sur Internet"]'::jsonb, 'Un ensemble de données organisées en', 'Une base de données relationnelle stocke les données dans des tables (lignes = enregistrements, colonnes = attributs). Les tables sont liées par des clés étrangères. Exemples de SGBDR : MySQL, PostgreSQL, SQLite, Oracle, SQL Server. Le modèle relationnel (Codd, 1970) est basé sur la théorie des ensembles et l''algèbre relationnelle.', 'Facile'),
    (chap_id, 'Que fait la commande SQL SELECT * FROM eleves WHERE note > 10 ?', '["Supprime tous les élèves avec une note supérieure à 10", "Récupère toutes les colonnes de tous", "Met à jour la note de tous les élèves à 10", "Compte le nombre d''élèves avec une note supérieure à 10"]'::jsonb, 'Récupère toutes les colonnes de tous', 'SELECT * FROM eleves WHERE note > 10 : SELECT = choisir les colonnes (* = toutes), FROM = de quelle table, WHERE = condition de filtrage. Résultat : tous les enregistrements d''élèves ayant une note > 10. Pour ne sélectionner que certaines colonnes : SELECT nom, prenom FROM eleves WHERE note > 10.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une "clé primaire" dans une table de base de données ?', '["Le premier enregistrement d''une table", "Un attribut (ou ensemble d''attributs)", "Le mot de passe pour accéder à la base de données", "La colonne la plus importante de la table"]'::jsonb, 'Un attribut (ou ensemble d''attributs)', 'La clé primaire (PRIMARY KEY) garantit l''unicité de chaque enregistrement. Elle est souvent un identifiant numérique auto-incrémenté (id = 1, 2, 3...). Contraintes : valeur unique, valeur non nulle. Une table peut avoir une clé composite (plusieurs colonnes). La clé primaire est référencée par les clés étrangères des autres tables.', 'Moyen'),
    (chap_id, 'Quelle commande SQL permet d''insérer un nouvel enregistrement dans une table ?', '["UPDATE table SET colonne = valeur", "SELECT colonne FROM table", "INSERT INTO table (col1, col2) VALUES", "ALTER TABLE table ADD colonne type"]'::jsonb, 'INSERT INTO table (col1, col2) VALUES', 'INSERT INTO ajoute un nouvel enregistrement : INSERT INTO eleves (nom, note) VALUES (''Dupont'', 15). Les commandes DML (Data Manipulation Language) en SQL : INSERT (insérer), SELECT (lire), UPDATE (modifier), DELETE (supprimer). Ces quatre opérations forment le CRUD (Create, Read, Update, Delete), fondamental dans toute application de gestion de données.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "jointure" (JOIN) en SQL et pourquoi l''utilise-t-on ?', '["Une commande pour fusionner deux bases de données distinctes", "Une opération qui combine les lignes de", "Une opération de tri sur plusieurs colonnes simultanément", "Un index qui accélère les recherches sur une table"]'::jsonb, 'Une opération qui combine les lignes de', 'Les jointures exploitent les relations entre tables. SELECT eleves.nom, cours.titre FROM eleves JOIN inscriptions ON eleves.id = inscriptions.eleve_id JOIN cours ON inscriptions.cours_id = cours.id. Types : INNER JOIN (intersection), LEFT JOIN (tout de la table gauche + correspondances), RIGHT JOIN, FULL OUTER JOIN. Évitent la duplication des données (normalisation).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "normalisation" d''une base de données ?', '["La compression des données pour économiser l''espace disque", "Un processus d''organisation des tables", "La mise à jour automatique des données quand une source change", "La synchronisation d''une base de données locale avec le cloud"]'::jsonb, 'Un processus d''organisation des tables', 'La normalisation organise les données pour réduire les redondances. 1NF : valeurs atomiques (pas de listes dans une cellule). 2NF : pas de dépendance partielle à la clé primaire. 3NF : pas de dépendance transitive. Une base bien normalisée évite les anomalies d''insertion, de mise à jour et de suppression. La dénormalisation est parfois utile pour les performances en lecture.', 'Difficile'),
    (chap_id, 'Quelle est la différence entre une base de données SQL et NoSQL ?', '["SQL est pour les petites données ; NoSQL pour les grandes", "SQL utilise un schéma fixe et des", "SQL est gratuit ; NoSQL est payant", "SQL est plus récent que NoSQL"]'::jsonb, 'SQL utilise un schéma fixe et des', 'SQL (PostgreSQL, MySQL) : schéma strict, transactions ACID, requêtes complexes avec jointures. NoSQL : MongoDB (documents JSON), Redis (clé-valeur), Cassandra (colonnes), Neo4j (graphes). NoSQL est adapté aux grandes quantités de données distribuées, au schéma variable. Le choix dépend du cas d''usage : SQL pour la cohérence, NoSQL pour la scalabilité.', 'Difficile'),
    (chap_id, 'Que fait la commande SQL GROUP BY avec une fonction d''agrégation ?', '["Elle trie les enregistrements par ordre alphabétique", "Elle regroupe les lignes ayant la même", "Elle supprime les doublons d''une table", "Elle crée une nouvelle table à partir des résultats d''un SELECT"]'::jsonb, 'Elle regroupe les lignes ayant la même', 'GROUP BY crée des groupes pour les agrégations : SELECT matiere, AVG(note) FROM resultats GROUP BY matiere donne la note moyenne par matière. Fonctions : COUNT(*) compte, SUM(note) fait la somme, AVG(note) calcule la moyenne, MAX(note) trouve le maximum, MIN(note) trouve le minimum. HAVING filtre les groupes (comme WHERE mais après GROUP BY).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "transaction" en base de données et quelles sont ses propriétés ACID ?', '["Une requête SQL complexe avec plusieurs jointures", "Un ensemble d''opérations atomiques", "Un type de connexion entre client et serveur de base de données", "Un script de sauvegarde automatique de la base"]'::jsonb, 'Un ensemble d''opérations atomiques', 'ACID garantit la fiabilité des transactions. Atomicité : tout ou rien (pas de demi-transaction). Cohérence : la base reste dans un état valide. Isolation : les transactions concurrentes ne s''interfèrent pas. Durabilité : une transaction validée (COMMIT) est définitive. Exemple : un virement bancaire débite un compte ET crédite l''autre dans la même transaction.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un "index" en base de données et quel est son effet sur les performances ?', '["Une liste alphabétique de tous les noms de tables", "Une structure de données auxiliaire qui", "Le numéro d''ordre d''un enregistrement dans une table", "Un résumé statistique des données d''une table"]'::jsonb, 'Une structure de données auxiliaire qui', 'Un index sur la colonne "email" d''une table de 10 millions d''utilisateurs transforme une recherche O(n) en O(log n). Les index accélèrent SELECT et WHERE mais ralentissent INSERT, UPDATE et DELETE (l''index doit être maintenu). La clé primaire est automatiquement indexée. Indexer les colonnes utilisées dans les clauses WHERE, JOIN et ORDER BY améliore les performances.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''"injection SQL" et comment s''en protéger ?', '["Une technique d''optimisation des requêtes SQL", "Une attaque qui insère du code SQL", "Un mécanisme de sauvegarde automatique", "Un outil de migration de données entre bases"]'::jsonb, 'Une attaque qui insère du code SQL', 'Une injection SQL exploite une vulnérabilité : si un formulaire de connexion construit la requête par concaténation, taper '' OR ''1''=''1 dans le champ mot de passe peut contourner l''authentification. Protection : requêtes préparées (paramétrisées), ORM, validation et échappement des entrées. C''est l''une des vulnérabilités OWASP Top 10 les plus critiques.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le langage SQL (Structured Query Language) et quel est son rôle ?', '["Un langage de programmation pour créer des applications web", "Un langage standardisé pour interroger", "Un langage de description de pages web similaire à HTML", "Un protocole de communication entre bases de données distribuées"]'::jsonb, 'Un langage standardisé pour interroger', 'SQL (Structured Query Language) est le langage standard des bases de données relationnelles, créé dans les années 1970. DML (Data Manipulation Language) : SELECT/INSERT/UPDATE/DELETE pour les données. DDL (Data Definition Language) : CREATE TABLE/ALTER TABLE/DROP TABLE pour la structure. DCL (Data Control Language) : GRANT/REVOKE pour les droits d''accès.', 'Facile'),
    (chap_id, 'Quelle commande SQL permet de modifier des enregistrements existants ?', '["INSERT INTO table VALUES (...)", "ALTER TABLE table MODIFY colonne", "UPDATE table SET colonne = valeur WHERE", "REPLACE INTO table VALUES (...)"]'::jsonb, 'UPDATE table SET colonne = valeur WHERE', 'UPDATE modifie des enregistrements existants : UPDATE eleves SET note = 18 WHERE nom = ''Dupont''. Attention : sans clause WHERE, tous les enregistrements sont modifiés ! Toujours tester avec SELECT avant d''exécuter UPDATE ou DELETE. La transaction (BEGIN/COMMIT/ROLLBACK) permet d''annuler une modification accidentelle.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "clé étrangère" (FOREIGN KEY) dans une base de données relationnelle ?', '["Une clé primaire d''une table importée depuis une base étrangère", "Un attribut dans une table qui", "Un index secondaire créé automatiquement par le SGBDR", "Un champ chiffré pour sécuriser les données sensibles"]'::jsonb, 'Un attribut dans une table qui', 'La clé étrangère crée la relation entre tables. Dans une table "commandes", le champ "client_id" est une clé étrangère référençant "clients.id". L''intégrité référentielle garantit qu''on ne peut pas insérer une commande pour un client inexistant, ni supprimer un client qui a des commandes. Elle est déclarée avec FOREIGN KEY ... REFERENCES.', 'Moyen');
  END IF;
END $$;

-- Chapitre 5 : Programmation orientée objet et structures de données NS2
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Programmation orientée objet et structures de données' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la "programmation orientée objet" (POO) ?', '["Un style de programmation qui utilise uniquement des fonctions mathématiques", "Un paradigme de programmation qui", "Un langage de programmation spécifique", "Une méthode de débogage pour les grands programmes"]'::jsonb, 'Un paradigme de programmation qui', 'La POO modélise le programme comme une collection d''objets qui interagissent. Un objet = données (attributs) + comportements (méthodes). Une classe est le moule (modèle) dont les objets sont des instances. Exemple : la classe "Voiture" a des attributs (marque, couleur, vitesse) et des méthodes (démarrer(), accélérer(), freiner()). Python, Java, C++ sont des langages POO.', 'Moyen'),
    (chap_id, 'Quels sont les quatre principes fondamentaux de la POO ?', '["Boucles, conditions, fonctions, variables", "Encapsulation", "Compilation, interprétation, débogage, optimisation", "Classes, méthodes, attributs, instances"]'::jsonb, 'Encapsulation', 'Les 4 piliers de la POO : Encapsulation (cacher les détails d''implémentation, exposer une interface propre). Héritage (une classe hérite des attributs/méthodes d''une autre). Polymorphisme (la même méthode se comporte différemment selon le type d''objet). Abstraction (définir l''interface sans l''implémentation : classes abstraites, interfaces).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"héritage" en POO ?', '["La récupération des données d''un objet supprimé", "Un mécanisme qui permet à une classe", "La copie d''un objet pour en créer un nouveau", "Le partage d''objets entre plusieurs programmes"]'::jsonb, 'Un mécanisme qui permet à une classe', 'L''héritage permet la réutilisation du code. Si "Vehicule" a les attributs vitesse et methode déplacer(), alors "Voiture(Vehicule)" hérite de tout ça et peut ajouter ses propres caractéristiques. Avantage : évite la duplication. L''héritage multiple (plusieurs classes mères) est possible en Python mais déconseillé car il complique la hiérarchie.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"encapsulation" en POO ?', '["La compression d''un objet pour économiser la mémoire", "Le principe de cacher les détails", "La copie d''un objet dans un autre objet", "Le regroupement de plusieurs objets dans une même variable"]'::jsonb, 'Le principe de cacher les détails', 'L''encapsulation protège les données internes d''un objet. Les attributs privés (__nom en Python, private en Java) ne sont accessibles que depuis l''intérieur de la classe. On accède aux données via des méthodes publiques (getters/setters). Avantage : on peut modifier l''implémentation interne sans changer l''interface publique.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "arbre binaire de recherche" (ABR) ?', '["Un algorithme de tri pour les listes", "Une structure de données arborescente", "Un type de tableau à deux dimensions", "Une structure de données circulaire"]'::jsonb, 'Une structure de données arborescente', 'Un ABR permet la recherche, insertion et suppression efficaces en O(log n) si l''arbre est équilibré. Propriété : gauche < nœud < droite. Recherche : partir de la racine, aller à gauche si valeur < nœud, droite si > nœud. Un arbre déséquilibré peut dégénérer en liste chaînée O(n). Les arbres AVL et Red-Black maintiennent l''équilibre automatiquement.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une "table de hachage" (hash table) et quelle est sa complexité d''accès ?', '["Un tableau trié par ordre alphabétique", "Une structure de données qui utilise", "Une structure arborescente à branches multiples", "Un tableau de deux dimensions utilisé pour les matrices"]'::jsonb, 'Une structure de données qui utilise', 'La table de hachage (dict en Python, HashMap en Java) est la structure la plus utilisée pour les associations clé-valeur. La fonction de hachage convertit la clé en un indice du tableau. Accès moyen O(1) ! Mais O(n) en cas de nombreuses collisions. Utilisations : cache, bases de données, index, déduplication. La gestion des collisions (chaînage, adressage ouvert) est cruciale.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "polymorphisme" en POO et comment fonctionne-t-il ?', '["La capacité d''un objet à changer de classe en cours d''exécution", "La capacité d''objets de classes", "La copie d''un objet avec des attributs modifiés", "La fusion de deux objets en un seul"]'::jsonb, 'La capacité d''objets de classes', 'Polymorphisme : "Chien" et "Chat" héritent tous deux de "Animal" et redéfinissent (overrident) la méthode parler(). Chien.parler() retourne "Ouaf", Chat.parler() retourne "Miaou". Si une liste contient des Animaux, appeler parler() sur chacun déclenche le bon comportement. Le polymorphisme rend le code extensible sans modifier le code existant (principe Open/Closed).', 'Moyen'),
    (chap_id, 'Quelle est la complexité temporelle de la recherche dans une table de hachage bien conçue ?', '["O(n²)", "O(n log n)", "O(n)", "O(1) en moyenne"]'::jsonb, 'O(1) en moyenne', 'Une table de hachage bien conçue offre O(1) en moyenne pour les opérations de base (insertion, suppression, recherche). La fonction de hachage transforme la clé en indice en temps constant, et l''accès à l''indice est O(1). En cas de nombreuses collisions, la complexité peut dégénérer vers O(n). C''est pourquoi les implémentations modernes maintiennent un facteur de charge < 0,75.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une "liste chaînée" et en quoi diffère-t-elle d''un tableau ?', '["Ce sont des structures identiques", "Une liste chaînée est une série de", "Une liste chaînée est une liste triée par ordre croissant", "Une liste chaînée utilise moins de mémoire qu''un tableau"]'::jsonb, 'Une liste chaînée est une série de', 'Tableau vs liste chaînée : accès par indice = O(1) tableau vs O(n) liste. Insertion/suppression au milieu = O(n) tableau (décalage) vs O(1) liste (modifier les pointeurs). Mémoire = contigüe (tableau, cache-friendly) vs dispersée (liste, overhead des pointeurs). Le choix dépend des opérations dominantes.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "design pattern" Singleton et quand l''utilise-t-on ?', '["Un patron de conception qui permet de créer des copies identiques d''un objet", "Un patron de conception qui garantit", "Un patron de conception pour organiser les classes en hiérarchie", "Un patron de conception pour simplifier une interface complexe"]'::jsonb, 'Un patron de conception qui garantit', 'Le Singleton est utile quand une seule instance est nécessaire (gestionnaire de connexion à la BDD, logger, configuration). Il empêche la création de plusieurs instances. Implémentation : constructeur privé + méthode statique getInstance(). Critiques : rend le code difficile à tester (couplage fort, état global), considéré comme anti-pattern dans les architectures modernes.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une "interface" (ou classe abstraite) en POO ?', '["Une fenêtre graphique de l''application", "Un contrat qui spécifie les méthodes", "Un type de liste chaînée", "Une méthode qui accepte plusieurs types de paramètres"]'::jsonb, 'Un contrat qui spécifie les méthodes', 'Une interface (Java) ou classe abstraite définit un contrat : toute classe qui l''implémente doit fournir les méthodes définies. Exemple : interface Triable { void trier(); } Force les classes à respecter un contrat sans imposer l''implémentation. Permet le polymorphisme sans héritage direct. Les interfaces sont fondamentales pour les architectures découplées et testables.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "pile d''appels" (call stack) dans l''exécution d''un programme ?', '["L''ordre de compilation des fichiers d''un programme", "Une structure qui suit les appels de", "Une liste de tous les bugs détectés dans un programme", "La mémoire utilisée pour les variables globales"]'::jsonb, 'Une structure qui suit les appels de', 'La pile d''appels est gérée automatiquement. Quand f() appelle g() qui appelle h() : la pile contient 3 cadres. Quand h() retourne, son cadre est dépilé. Un "stack overflow" se produit quand la pile est pleine (récursion infinie). Les débogeurs affichent la "stack trace" pour localiser l''erreur. La taille de la pile est limitée (typiquement 1-8 Mo).', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un "algorithme de tri rapide" (QuickSort) et quelle est sa complexité ?', '["Un tri stable O(n) qui utilise une table de hachage", "Un tri qui choisit un pivot", "Un tri qui divise le tableau en deux moitiés égales et les fusionne ; O(n log n)", "Un tri qui compare des paires adjacentes ; O(n²)"]'::jsonb, 'Un tri qui choisit un pivot', 'QuickSort : choisir un pivot (ex. dernier élément), placer à gauche les éléments < pivot et à droite les > pivot, puis trier récursivement les deux sous-tableaux. Complexité moyenne : O(n log n). Pire cas : O(n²) si le pivot est toujours le minimum ou maximum (tableau déjà trié). QuickSort est souvent plus rapide en pratique que MergeSort O(n log n) grâce à sa localité de cache.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "garbage collector" (ramasse-miettes) dans les langages de programmation modernes ?', '["Un outil de débogage qui détecte les erreurs de mémoire", "Un mécanisme automatique qui libère la", "Un compilateur optimiseur qui supprime le code mort", "Un outil de compression du code source pour réduire sa taille"]'::jsonb, 'Un mécanisme automatique qui libère la', 'Le garbage collector (GC) automatise la gestion de la mémoire en Java, Python, C#. Il identifie les objets non référencés et libère leur mémoire. Algorithmes : comptage de références (Python), marquage et balayage (Java G1GC). Avantage : évite les fuites mémoire et les dangling pointers. Inconvénient : pauses imprévisibles (GC pause). C et C++ exigent la gestion manuelle (malloc/free).', 'Difficile');
  END IF;
END $$;

-- Chapitre 6 : Développement web et applications mobiles NS2
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Développement web et applications mobiles' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le rôle du HTML dans le développement web ?', '["Définir les styles visuels (couleurs, polices, mise en page) d''une page web", "Décrire la structure et le contenu", "Gérer les interactions de l''utilisateur (clics, animations) sur une page web", "Envoyer des requêtes au serveur web pour récupérer des données"]'::jsonb, 'Décrire la structure et le contenu', 'HTML (HyperText Markup Language) définit la structure et le sens du contenu : <h1> pour les titres, <p> pour les paragraphes, <nav> pour la navigation, <article> pour un article. Il ne gère pas la présentation (c''est CSS) ni le comportement (c''est JavaScript). La version actuelle est HTML5 (2014), avec de nombreuses nouvelles balises sémantiques.', 'Facile'),
    (chap_id, 'Quel est le rôle du CSS dans le développement web ?', '["Décrire la structure du contenu d''une page web", "Définir la présentation visuelle (styles", "Gérer la logique et les interactions côté client", "Communiquer avec la base de données du serveur"]'::jsonb, 'Définir la présentation visuelle (styles', 'CSS (Cascading Style Sheets) sépare le style du contenu. Il permet de définir l''apparence visuelle : couleurs, typographie, mise en page (flexbox, grid), responsive design (media queries), animations. CSS3 a apporté les transitions, animations et le design responsive. Séparation des préoccupations : HTML = structure, CSS = présentation, JS = comportement.', 'Facile'),
    (chap_id, 'Quelle est la différence entre le développement "frontend" et "backend" ?', '["Frontend est pour les applications mobiles ; backend pour les applications web", "Frontend est la partie visible par", "Frontend utilise Python ; backend utilise JavaScript", "Il n''y a pas de différence fonctionnelle"]'::jsonb, 'Frontend est la partie visible par', 'Frontend (côté client) : HTML/CSS/JS, frameworks React/Vue/Angular, s''exécute dans le navigateur. Backend (côté serveur) : Python/Django, Node.js/Express, PHP/Laravel, Java/Spring, gère la logique métier et la base de données. Full-stack = maîtrise des deux. L''API (Application Programming Interface) est l''interface entre frontend et backend.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une "API REST" et comment fonctionne-t-elle ?', '["Un type de base de données pour les applications web", "Une architecture d''API web qui utilise", "Un framework de développement frontend JavaScript", "Un protocole de sécurité pour les connexions web"]'::jsonb, 'Une architecture d''API web qui utilise', 'REST (Representational State Transfer) utilise HTTP : GET /utilisateurs (lire tous), GET /utilisateurs/1 (lire un), POST /utilisateurs (créer), PUT /utilisateurs/1 (mettre à jour), DELETE /utilisateurs/1 (supprimer). Les données sont généralement au format JSON. Les API REST permettent la communication entre frontend et backend, ou entre microservices.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "responsive design" et pourquoi est-il important ?', '["Un design qui répond aux clics de l''utilisateur avec des animations", "Une approche de conception web qui", "Un design qui se charge rapidement sur les connexions lentes", "Un design accessible aux personnes handicapées visuelles"]'::jsonb, 'Une approche de conception web qui', 'Le responsive design utilise les media queries (@media (max-width: 768px) {...}), les unités relatives (%, em, rem, vw), flexbox et CSS grid. Mobile-first : concevoir d''abord pour mobile, puis agrandir pour desktop. Plus de 60% du trafic web mondial vient des mobiles → le responsive est indispensable. Google pénalise les sites non responsive dans ses résultats.', 'Moyen'),
    (chap_id, 'Qu''est-ce que JavaScript côté client et quel est son rôle dans une page web ?', '["Un langage de description de données similaire à JSON", "Un langage de programmation qui", "Un protocole de communication entre navigateur et serveur", "Un langage de template pour générer du HTML côté serveur"]'::jsonb, 'Un langage de programmation qui', 'JavaScript (JS) est le seul langage de programmation natif des navigateurs web. Il manipule le DOM (Document Object Model) pour modifier dynamiquement la page, gère les événements (clics, soumission de formulaires), effectue des appels AJAX/fetch vers les API, valide les formulaires. Frameworks populaires : React, Vue.js, Angular. Node.js permet JS côté serveur.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre une application web "native" et une application web progressive (PWA) ?', '["Ce sont des termes synonymes pour les applications mobiles", "Une app native est développée", "Une app native ne nécessite pas Internet ; une PWA nécessite toujours Internet", "Une app native est plus sécurisée qu''une PWA"]'::jsonb, 'Une app native est développée', 'App native (Swift/iOS, Kotlin/Android) : accès complet aux APIs de l''appareil, meilleures performances, distribution via stores. PWA (Progressive Web App) : site web avec service worker (cache offline), manifest (installation), notifications push. Cross-platform sans store. Flutter et React Native proposent une troisième voie : une codebase unique qui génère des apps natives iOS et Android.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "DOM" (Document Object Model) en développement web ?', '["Un langage de programmation pour créer des animations web", "Une représentation en arbre de la", "Un format de base de données utilisé par les navigateurs", "Un protocole de communication entre le navigateur et le serveur"]'::jsonb, 'Une représentation en arbre de la', 'Le DOM représente la page HTML comme un arbre de nœuds. JavaScript accède et modifie le DOM : document.getElementById(''titre'').textContent = ''Nouveau titre'' change le contenu. Les frameworks (React, Vue) maintiennent un Virtual DOM pour optimiser les mises à jour du DOM réel, car les opérations DOM sont coûteuses en performance.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "framework" Flutter et quel est son avantage principal ?', '["Un framework JavaScript pour créer des sites web", "Un framework de Google qui permet de", "Un système d''exploitation mobile open source", "Un outil de débogage pour les applications Android"]'::jsonb, 'Un framework de Google qui permet de', 'Flutter (Google, 2018) utilise le langage Dart et compile vers du code natif (ARM). Un seul code source peut générer des apps iOS, Android, web et desktop. Il ne dépend pas des composants natifs de l''OS mais dessine lui-même l''interface avec son moteur graphique Skia. Avantage : performances proches du natif, cohérence visuelle cross-platform.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le format JSON et pourquoi est-il omniprésent dans le développement web ?', '["Un langage de balisage similaire à HTML pour structurer les pages web", "Un format de données léger basé sur du", "Un protocole de transfert de fichiers entre serveurs", "Un système de chiffrement des communications web"]'::jsonb, 'Un format de données léger basé sur du', 'JSON (JavaScript Object Notation) : {"nom": "Dupont", "age": 25, "notes": [15, 18, 12]}. Il est devenu le format standard d''échange de données entre APIs. Avantages vs XML : plus léger, plus lisible, parseable nativement en JS (JSON.parse()), supporté par tous les langages. Les API REST, les fichiers de configuration (package.json, appsettings.json) utilisent JSON.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "HTTPS" et comment le certificat SSL/TLS protège-t-il les communications ?', '["Un protocole plus rapide que HTTP car il compresse les données", "Un protocole qui chiffre les données", "Un protocole qui authentifie uniquement le navigateur auprès du serveur", "Un protocole réservé aux transactions bancaires en ligne"]'::jsonb, 'Un protocole qui chiffre les données', 'HTTPS utilise TLS (anciennement SSL) pour chiffrer les communications : 1) Le serveur présente son certificat signé par une autorité de certification (Let''s Encrypt, Comodo). 2) Le navigateur vérifie le certificat. 3) Échange de clés pour établir un canal chiffré symétrique. Les données sont illisibles pour un intercepteur. Le cadenas dans la barre d''adresse indique HTTPS.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''"architecture MVC" (Model-View-Controller) dans le développement web ?', '["Un modèle de données pour les bases de données relationnelles", "Un patron d''architecture qui sépare", "Un protocole de communication entre frontend et backend", "Un système de gestion de versions pour le code source"]'::jsonb, 'Un patron d''architecture qui sépare', 'MVC sépare les préoccupations : Model = données et logique métier (classe Utilisateur, BDD). View = interface utilisateur (templates HTML, composants React). Controller = reçoit les requêtes HTTP, interroge le Model, retourne une View. Frameworks MVC : Django (Python), Laravel (PHP), Spring MVC (Java), Ruby on Rails. Cette séparation facilite les tests et la maintenance.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "sécurité XSS" (Cross-Site Scripting) et comment s''en protéger ?', '["Une attaque qui surcharge le serveur de requêtes simultanées", "Une attaque qui injecte du code", "Une attaque qui vole les fichiers du serveur web", "Une technique pour contourner l''authentification d''un site"]'::jsonb, 'Une attaque qui injecte du code', 'XSS : un attaquant injecte <script>document.cookie</script> dans un commentaire. Quand les autres utilisateurs lisent ce commentaire, le script s''exécute dans leur navigateur et peut voler leurs cookies ou mots de passe. Protection : échapper les caractères spéciaux (<, >, ", &) dans les sorties HTML, Content Security Policy (CSP), utiliser des frameworks modernes (React) qui échappent automatiquement.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "versionnage" du code avec Git et pourquoi est-il indispensable ?', '["Un système de sauvegarde automatique des fichiers sur le cloud", "Un système de contrôle de versions qui", "Un outil de débogage pour les applications web", "Un protocole de déploiement d''applications sur les serveurs"]'::jsonb, 'Un système de contrôle de versions qui', 'Git est le système de contrôle de versions dominant. Commandes clés : git commit (sauvegarder les changements), git push/pull (synchroniser), git branch (créer une branche), git merge (fusionner), git clone (copier un repo). GitHub/GitLab hébergent les dépôts. Le workflow GitFlow (branches main, develop, feature) structure la collaboration en équipe.', 'Moyen');
  END IF;
END $$;
