-- Supplement Physique (matiere_id=9) — tous niveaux
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 9 AND titre = 'Grandeurs et mesures physiques' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le Système International d''unités (SI) et combien d''unités de base contient-il ?', '["Un système américain avec 5 unités","Un système de mesure universel","Un système métrique avec 10 unités","Un système avec uniquement des unités dérivées"]'::jsonb, 'Un système de mesure universel', 'Le SI (Bureau International des Poids et Mesures) définit les 7 unités de base dont toutes les autres sont dérivées.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''incertitude de mesure et comment l''exprime-t-on ?', '["L''erreur humaine du physicien","La plage de valeurs dans laquelle la","La précision maximale d''un instrument","Une valeur fixe"]'::jsonb, 'La plage de valeurs dans laquelle la', 'Toute mesure physique a une incertitude ; l''exprimer est fondamental pour la rigueur scientifique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''analyse dimensionnelle en physique ?', '["La mesure des dimensions géométriques","La vérification de la cohérence des","Une méthode graphique","Un calcul d''erreur"]'::jsonb, 'La vérification de la cohérence des', 'L''homogénéité dimensionnelle ([MLT⁻²] = [M][LT⁻²]) est une condition nécessaire mais non suffisante pour la validité d''une équation.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la notation scientifique et comment l''utilise-t-on en physique ?', '["Une écriture littéraire des nombres","L''écriture d''un nombre sous la forme a","Un arrondi approximatif","Une notation réservée aux astronomes"]'::jsonb, 'L''écriture d''un nombre sous la forme a', 'La notation scientifique facilite les calculs avec des ordres de grandeur très différents (noyau atomique ~10⁻¹⁵ m, univers ~10²⁶ m).', 'Facile'),
    (chap_id, 'Quelle est la différence entre une grandeur scalaire et une grandeur vectorielle ?', '["Aucune différence","Un scalaire est défini par sa seule","Les vecteurs n''ont pas de valeur numérique","Les scalaires ne s''utilisent pas en physique"]'::jsonb, 'Un scalaire est défini par sa seule', 'La distinction scalaire/vecteur est fondamentale : F = ma est une équation vectorielle ; chaque membre a même direction et sens.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''ordre de grandeur en physique et pourquoi est-il utile ?', '["Une valeur très précise","L''estimation à la puissance de dix près","Une valeur arrondie à l''entier","Une erreur de mesure"]'::jsonb, 'L''estimation à la puissance de dix près', 'Enrico Fermi était maître des estimations d''ordre de grandeur ; cette compétence est essentielle pour détecter les erreurs de calcul.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la conversion d''unités et comment réalise-t-on un changement d''unités correctement ?', '["On change arbitrairement les chiffres","On multiplie par le facteur de","On arrondit la valeur","On change le symbole uniquement"]'::jsonb, 'On multiplie par le facteur de', 'La méthode des fractions unitaires garantit la cohérence lors des conversions multiples (km/h → m/s : ×1000/3600).', 'Facile'),
    (chap_id, 'Quels sont les principaux instruments de mesure en physique et leur grandeur mesurée ?', '["Uniquement la règle et l''horloge","Multimètre (courant/tension)","Uniquement le microscope","Uniquement la balance"]'::jsonb, 'Multimètre (courant/tension)', 'Chaque instrument a une résolution et une incertitude ; les choisir et les calibrer correctement est essentiel en laboratoire.', 'Facile'),
    (chap_id, 'Qu''est-ce que la précision et l''exactitude en métrologie et comment les distingue-t-on ?', '["Elles sont identiques","La précision = capacité à reproduire la","La précision est plus importante que l''exactitude","Seule l''exactitude compte en science"]'::jsonb, 'La précision = capacité à reproduire la', 'Analogie cible de tir : groupé mais décalé (précis, pas exact) vs. dispersé autour du centre (exact, pas précis).', 'Moyen'),
    (chap_id, 'Quelle est la valeur de g (accélération gravitationnelle à la surface de la Terre) et comment varie-t-elle ?', '["g = 10 km/s² (constante absolue)","g ≈ 9,81 m/s² à la surface de la Terre","g = 1 m/s²","g = 100 m/s²"]'::jsonb, 'g ≈ 9,81 m/s² à la surface de la Terre', 'g = 9,81 m/s² aux pôles, 9,78 m/s² à l''équateur (force centrifuge) ; on utilise g = 10 m/s² en physique scolaire haïtienne.', 'Facile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 9 AND titre = 'Cinématique : mouvement et description' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la vitesse moyenne et comment se calcule-t-elle ?', '["La vitesse à un instant t","Le rapport de la distance parcourue sur","La vitesse maximale atteinte","L''accélération divisée par le temps"]'::jsonb, 'Le rapport de la distance parcourue sur', 'v_moy = Δx/Δt ; ne pas confondre avec vitesse instantanée (dérivée de la position) ni avec accélération.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''accélération et quelle est son unité SI ?', '["Le changement de position","La variation de la vitesse par unité de","La vitesse divisée par la distance","L''unité est m/s"]'::jsonb, 'La variation de la vitesse par unité de', 'L''accélération peut être positive (accélération) ou négative (décélération) selon le sens du mouvement.', 'Facile'),
    (chap_id, 'Pour un mouvement uniformément accéléré (MRUA), quelle est l''équation de la vitesse en fonction du temps ?', '["v = d/t","v(t) = v₀ + a·t","v = a·d","v(t) = ½·a·t²"]'::jsonb, 'v(t) = v₀ + a·t', 'La cinématique du MRUA : v = v₀ + at (vitesse), x = x₀ + v₀t + ½at² (position), v² = v₀² + 2aΔx (sans t).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le mouvement circulaire uniforme (MCU) et quelle est son accélération ?', '["Un mouvement sans accélération","Un mouvement sur un cercle à vitesse","Un mouvement avec vitesse variable","Un mouvement rectiligne"]'::jsonb, 'Un mouvement sur un cercle à vitesse', 'Dans le MCU, le module de la vitesse est constant mais sa direction change → accélération centripète (perpendiculaire au mouvement).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la trajectoire parabolique d''un projectile (tir oblique) ?', '["Une ligne droite","La trajectoire courbe d''un objet lancé","Un mouvement circulaire","Un mouvement aléatoire"]'::jsonb, 'La trajectoire courbe d''un objet lancé', 'Projectile : x = v₀cosθ·t ; y = v₀sinθ·t - ½gt² ; portée R = v₀²sin2θ/g (max à θ = 45°).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la chute libre et quelles en sont les équations ?', '["Un mouvement avec résistance de l''air","La chute d''un objet en l''absence de","Un mouvement sans accélération","Un mouvement horizontal"]'::jsonb, 'La chute d''un objet en l''absence de', 'Galilée a établi que tous les objets tombent avec la même accélération g indépendamment de leur masse (réfutant Aristote).', 'Moyen'),
    (chap_id, 'Comment représente-t-on graphiquement un mouvement rectiligne uniforme (MRU) ?', '["Par une courbe parabolique","Par une droite sur le graphique","Par une droite sur le graphique vitesse-temps uniquement","Par une courbe exponentielle"]'::jsonb, 'Par une droite sur le graphique', 'Dans le MRU : pente du graphe x-t = vitesse ; graphe v-t est horizontal (a=0) ; graphe a-t est sur l''axe des abscisses.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la période et la fréquence dans un mouvement circulaire ou oscillatoire ?', '["La distance parcourue","La période T est le temps pour","L''amplitude du mouvement","La vitesse angulaire uniquement"]'::jsonb, 'La période T est le temps pour', 'T et f sont inverses : T = 0,02 s → f = 50 Hz (fréquence du courant alternatif en Haïti comme dans la plupart des Amériques).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le vecteur déplacement et comment diffère-t-il de la distance parcourue ?', '["Ils sont identiques","Le déplacement est un vecteur entre","La distance est toujours inférieure au déplacement","Le déplacement est toujours plus grand"]'::jsonb, 'Le déplacement est un vecteur entre', 'Ex : tour complet d''un circuit de 100 m → déplacement = 0, distance = 100 m.', 'Facile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 9 AND titre = 'Dynamique : forces et lois de Newton' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la première loi de Newton (loi d''inertie) ?', '["Tout corps accélère naturellement","Tout corps persévère dans son état de","La force est proportionnelle à la masse","À toute action correspond une réaction égale et opposée"]'::jsonb, 'Tout corps persévère dans son état de', 'La 1ère loi de Newton (inertie) définit le référentiel galiléen ; la tendance d''un objet à résister aux changements de mouvement.', 'Facile'),
    (chap_id, 'Quelle est la deuxième loi de Newton et quelle est sa formule ?', '["F = mv","ΣF = m·a","F = m/a","a = m/F"]'::jsonb, 'ΣF = m·a', 'F = ma est la relation fondamentale de la dynamique : plus la masse est grande, plus il faut de force pour la même accélération.', 'Facile'),
    (chap_id, 'Quelle est la troisième loi de Newton (loi des actions réciproques) ?', '["Les forces s''annulent","Lorsque A exerce une force sur B","Les forces s''additionnent toujours","La force dépend de la vitesse"]'::jsonb, 'Lorsque A exerce une force sur B', 'Les paires action-réaction s''appliquent sur des corps différents ; ne pas les confondre avec des forces qui s''équilibrent sur un même corps.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la force de frottement et comment l''exprime-t-on ?', '["Une force toujours nulle","Une force de contact s''opposant au","Une force qui accélère l''objet","Une force gravitationnelle"]'::jsonb, 'Une force de contact s''opposant au', 'Frottement statique (max avant mouvement) > frottement cinétique (pendant le mouvement) ; μ dépend des matériaux en contact.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le poids et comment diffère-t-il de la masse ?', '["Ils sont identiques","La masse m est une propriété","La masse est en Newton","Le poids est en kilogramme"]'::jsonb, 'La masse m est une propriété', 'Sur la Lune (g_Lune ≈ 1,6 m/s²), votre masse reste 70 kg mais votre poids passe de 700 N à ~112 N.', 'Facile'),
    (chap_id, 'Qu''est-ce que la loi de la gravitation universelle de Newton ?', '["La loi de l''inertie","La force attractive entre deux masses","La loi de Coulomb","La loi des ressorts"]'::jsonb, 'La force attractive entre deux masses', 'La gravitation de Newton explique les orbites des planètes (Kepler), la marée et la chute des pommes dans un cadre unifié.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le travail d''une force en physique et comment le calcule-t-on ?', '["L''énergie cinétique d''un objet","W = F·d·cosθ","La puissance fournie","La force multipliée par le temps"]'::jsonb, 'W = F·d·cosθ', 'Si F ⊥ déplacement (θ = 90°), W = 0 (ex. force normale, force centripète ne font aucun travail).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''énergie cinétique et le théorème énergie-travail ?', '["L''énergie de position","Ec = ½mv²","L''énergie potentielle","La puissance mécanique"]'::jsonb, 'Ec = ½mv²', 'Le théorème travail-énergie est une conséquence directe de F=ma ; il permet de calculer des vitesses sans utiliser les équations du mouvement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la conservation de l''énergie mécanique ?', '["L''énergie disparaît après une collision","En l''absence de forces dissipatives","L''énergie cinétique seule se conserve","La conservation ne s''applique pas aux systèmes réels"]'::jsonb, 'En l''absence de forces dissipatives', 'Ep gravitationnelle = mgh ; Ec = ½mv² ; sans frottement : ½mv₁² + mgh₁ = ½mv₂² + mgh₂.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la quantité de mouvement (impulsion) et sa conservation ?', '["La vitesse d''un objet","p = m·v (vecteur)","L''énergie cinétique","La force appliquée"]'::jsonb, 'p = m·v (vecteur)', 'Conservation de p (impulsion) : choc élastique (Ec conservée), choc inélastique parfait (Ec non conservée, objets solidaires).', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 9 AND titre = 'Électricité : charges, courant et circuits' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la loi d''Ohm et comment s''applique-t-elle ?', '["I = R/U","U = R·I","R = U·I","U = I/R"]'::jsonb, 'U = R·I', 'La loi d''Ohm (Georg Ohm, 1827) s''applique aux conducteurs ohmiques à température constante ; U en Volts, I en Ampères, R en Ohms.', 'Facile'),
    (chap_id, 'Quelles sont les lois de Kirchhoff pour l''analyse des circuits électriques ?', '["La loi des charges et la loi des masses","Loi des nœuds (ΣI_entrant = ΣI_sortant)","La loi d''Ohm uniquement","La loi de Faraday"]'::jsonb, 'Loi des nœuds (ΣI_entrant = ΣI_sortant)', 'Les lois de Kirchhoff découlent de la conservation de la charge et de l''énergie ; elles généralisent la loi d''Ohm aux circuits complexes.', 'Moyen'),
    (chap_id, 'Comment calcule-t-on la résistance équivalente en série et en parallèle ?', '["Identique dans les deux cas","En série : Req = R₁ + R₂ + ...","En série : 1/Req = 1/R₁ + 1/R₂","En parallèle : Req = R₁ + R₂"]'::jsonb, 'En série : Req = R₁ + R₂ + ...', 'Série : même courant, tensions additives ; Parallèle : même tension, courants additifs. Req parallèle < toute résistance individuelle.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la puissance électrique et son expression ?', '["L''énergie stockée","P = U·I = R·I² = U²/R, exprimée en watts","La résistance divisée par la tension","Le courant multiplié par la résistance"]'::jsonb, 'P = U·I = R·I² = U²/R, exprimée en watts', '1 kWh = 3 600 000 J = 3,6 MJ ; c''est l''unité commerciale de l''énergie électrique (facture EDF/ED Haïti).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le condensateur et sa capacité ?', '["Un générateur de courant","Un composant stockant de l''énergie","Une résistance variable","Un transformateur"]'::jsonb, 'Un composant stockant de l''énergie', 'Les condensateurs sont omniprésents en électronique (filtrage, stockage d''énergie, mémoire flash).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la loi de Coulomb et la force électrostatique ?', '["La loi gravitationnelle","La force entre deux charges q₁ et q₂","La loi d''Ohm généralisée","La force magnétique"]'::jsonb, 'La force entre deux charges q₁ et q₂', 'La loi de Coulomb est la loi fondamentale de l''électrostatique ; sa forme est analogue à la gravitation de Newton.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le courant alternatif (CA) et en quoi diffère-t-il du courant continu (CC) ?', '["Ils sont identiques","Le CC circule dans un sens fixe (piles)","Le CA est plus dangereux","Le CC est utilisé dans les maisons"]'::jsonb, 'Le CC circule dans un sens fixe (piles)', 'En Haïti : réseau 120 V / 60 Hz (comme en Amérique du Nord) ; l''Europe utilise 230 V / 50 Hz.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le transformateur et quel est son principe de fonctionnement ?', '["Un générateur d''électricité","Un dispositif à deux bobines couplées","Un moteur électrique","Un condensateur haute tension"]'::jsonb, 'Un dispositif à deux bobines couplées', 'Les transformateurs permettent le transport d''électricité en haute tension (moins de pertes) et sa distribution à basse tension.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la mise à la terre (mise à la masse) dans une installation électrique ?', '["Une décoration","La connexion d''un conducteur de","Un court-circuit","Un fusible"]'::jsonb, 'La connexion d''un conducteur de', 'La mise à la terre, les disjoncteurs et les disjoncteurs différentiels forment le système de protection des installations électriques.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 9 AND titre = 'Optique : lumière et propriétés' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la vitesse de la lumière dans le vide et sa signification en physique ?', '["1000 m/s","c = 3 × 10⁸ m/s","c = 3 × 10⁵ m/s","c = 3 × 10⁶ km/s"]'::jsonb, 'c = 3 × 10⁸ m/s', 'c = 299 792 458 m/s (arrondi à 3×10⁸) ; depuis 1983, le mètre est défini par cette valeur fixée.', 'Facile'),
    (chap_id, 'Qu''est-ce que la réfraction de la lumière et la loi de Snell-Descartes ?', '["La réflexion totale","Le changement de direction de la","La diffraction","La polarisation"]'::jsonb, 'Le changement de direction de la', 'L''indice de réfraction n = c/v (vitesse de la lumière dans le vide / dans le milieu) ; n eau ≈ 1,33, n verre ≈ 1,5.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la réflexion totale interne et quelle est son application dans les fibres optiques ?', '["Un miroir ordinaire","Lorsque la lumière passe d''un milieu","Une lentille divergente","L''arc-en-ciel"]'::jsonb, 'Lorsque la lumière passe d''un milieu', 'La fibre optique (réflexion totale dans le cœur de silice) transmet des milliards de bits/s sur des milliers de km.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la dispersion de la lumière et comment explique-t-elle l''arc-en-ciel ?', '["Un défaut des lentilles","La décomposition de la lumière blanche","Une réflexion","Une absorption"]'::jsonb, 'La décomposition de la lumière blanche', 'Newton (1666) a dispersé la lumière blanche avec un prisme et démontré qu''elle est composée de toutes les couleurs.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la nature duale de la lumière (onde-corpuscule) ?', '["La lumière est exclusivement une onde","La lumière se comporte comme une onde","La lumière est exclusivement un corpuscule","La dualité n''existe que pour les électrons"]'::jsonb, 'La lumière se comporte comme une onde', 'Einstein (1905, Nobel 1921) a expliqué l''effet photoélectrique en traitant la lumière comme des photons d''énergie E = hν.', 'Moyen'),
    (chap_id, 'Comment fonctionne une lentille convergente et où se forme l''image d''un objet ?', '["Elle diffuse la lumière","Elle concentre les rayons parallèles en","Elle n''a pas de foyer","Elle crée uniquement des images droites"]'::jsonb, 'Elle concentre les rayons parallèles en', 'Les lentilles convergentes (verres correcteurs myopie, loupe, objectif photo) forment des images réelles (si objet au-delà de f'') ou virtuelles (objet entre O et F).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le spectre électromagnétique et quels types de rayonnements comprend-il ?', '["Uniquement la lumière visible","L''ensemble des ondes électromagnétiques","La lumière visible et l''ultraviolet uniquement","Uniquement les rayons X et gamma"]'::jsonb, 'L''ensemble des ondes électromagnétiques', 'Toutes les ondes EM voyagent à c dans le vide ; seule leur fréquence (ou λ) diffère ; elles se propagent sans support matériel.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la polarisation de la lumière et ses applications pratiques ?', '["Un filtre de couleur","La propriété de la lumière dont les","La diffraction","La réflexion totale"]'::jsonb, 'La propriété de la lumière dont les', 'La polarisation confirme la nature transverse des ondes lumineuses ; les verres de soleil polarisants réduisent l''éblouissement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''effet Doppler pour la lumière et ses applications en astronomie ?', '["Un effet uniquement sonore","Le décalage de fréquence d''une source","Un type de réfraction","Un effet de miroir"]'::jsonb, 'Le décalage de fréquence d''une source', 'Le redshift cosmologique (Edwin Hubble, 1929) a révélé l''expansion de l''univers et permis d''estimer l''âge du Big Bang (~13,8 Ga).', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 9 AND titre = 'Thermodynamique et transferts thermiques' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le premier principe de la thermodynamique et sa signification ?', '["L''énergie peut être créée","La variation d''énergie interne d''un","L''entropie augmente toujours","La chaleur va du froid au chaud"]'::jsonb, 'La variation d''énergie interne d''un', 'Le 1er principe (conservation) interdit les machines de 1er espèce (produisant de l''énergie ex nihilo).', 'Moyen'),
    (chap_id, 'Quel est le deuxième principe de la thermodynamique et la notion d''entropie ?', '["L''entropie peut diminuer dans un système isolé","Dans un système isolé","L''énergie se conserve","L''entropie ne change jamais"]'::jsonb, 'Dans un système isolé', 'Le 2e principe interdit les machines de 2e espèce (moteur prélevant chaleur d''une seule source) ; il donne le sens du temps.', 'Moyen'),
    (chap_id, 'Quels sont les trois modes de transfert thermique et leurs caractéristiques ?', '["Uniquement la conduction","Conduction (contact direct","Uniquement le rayonnement","Conduction et radiation uniquement"]'::jsonb, 'Conduction (contact direct', 'La Terre reçoit l''énergie solaire par rayonnement ; la convection dans l''atmosphère crée le vent ; la conduction chauffe les casseroles.', 'Facile'),
    (chap_id, 'Qu''est-ce que la chaleur latente et comment intervient-elle lors des changements d''état ?', '["La chaleur transmise par conduction","L''énergie absorbée ou libérée lors d''un","La chaleur massique","La conduction thermique"]'::jsonb, 'L''énergie absorbée ou libérée lors d''un', 'Q = m·L (chaleur latente) ; la sudation dissipe la chaleur grâce à la chaleur latente de vaporisation de l''eau.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la capacité calorifique massique et la formule de la chaleur sensible ?', '["La chaleur latente","Q = m·c·ΔT","Q = m·L","Q = m·c/ΔT"]'::jsonb, 'Q = m·c·ΔT', 'c(eau) = 4180 J/(kg·K) est anormalement élevé, expliquant le rôle de l''eau dans la régulation du climat.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la loi des gaz parfaits (loi de Boyle-Mariotte, Gay-Lussac, Charles) ?', '["P×V = constante uniquement","PV = nRT","P/T = constante","V/T = constante uniquement"]'::jsonb, 'PV = nRT', 'PV=nRT unifie les lois de Boyle (T const.), Charles (P const.) et Gay-Lussac (V const.) dans une équation unique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le rendement d''un moteur thermique et la limite de Carnot ?', '["100% toujours","Le rendement η = W_utile / Q_absorbé ≤ 1","Le rendement d''un moteur est toujours supérieur à celui de Carnot","Carnot s''applique uniquement aux réfrigérateurs"]'::jsonb, 'Le rendement η = W_utile / Q_absorbé ≤ 1', 'Le cycle de Carnot (1824) définit le rendement maximal thermodynamique ; les moteurs réels l''atteignent rarement.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 9 AND titre = 'Physique nucléaire et moderne' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la radioactivité naturelle et quels sont ses types principaux ?', '["Un phénomène artificiel uniquement","L''émission spontanée de rayonnements","Un type de chimie","Un phénomène uniquement terrestre"]'::jsonb, 'L''émission spontanée de rayonnements', 'Becquerel (1896) et les Curie (Nobel 1903, 1911) ont découvert et étudié la radioactivité naturelle.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la demi-vie radioactive (période) et comment l''utilise-t-on en datation ?', '["Le temps pour désintégration totale","Le temps T₁/₂ après lequel la moitié","Le temps pour doublement","La durée de vie d''un neutron"]'::jsonb, 'Le temps T₁/₂ après lequel la moitié', 'Libby (Nobel 1960) a développé la datation C-14 ; la loi de désintégration radioactive est exponentielle.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la fission nucléaire et comment est-elle utilisée dans les centrales ?', '["La fusion de deux noyaux légers","La division d''un noyau lourd","La désintégration alpha","La radioactivité bêta"]'::jsonb, 'La division d''un noyau lourd', 'La fission libère ~200 MeV/noyau ; une centrale nucléaire contrôle la réaction en chaîne avec des modérateurs et barres de contrôle.', 'Moyen'),
    (chap_id, 'Quelle est la relation énergie-masse d''Einstein et son application à la physique nucléaire ?', '["E = mv","E = mc²","E = m/c²","E = c/m"]'::jsonb, 'E = mc²', 'E = mc² (Einstein, 1905) explique pourquoi la fission et la fusion libèrent d''énormes quantités d''énergie à partir d''infimes pertes de masse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la fusion nucléaire et son intérêt énergétique ?', '["La fission de l''uranium","L''union de deux noyaux légers formant","La radioactivité naturelle","La désintégration bêta"]'::jsonb, 'L''union de deux noyaux légers formant', 'La fusion (ITER, projet international) est l''énergie du futur prometteur : carburant abondant (eau de mer), peu de déchets, pas de CO2.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le modèle quantique de l''atome et ses différences avec le modèle de Bohr ?', '["Le modèle planétaire de Rutherford","Le modèle quantique remplace les","Le modèle de Thomson","Le modèle classique de Dalton"]'::jsonb, 'Le modèle quantique remplace les', 'Le modèle quantique (s, p, d, f) décrit correctement le tableau périodique et les liaisons chimiques ; le modèle de Bohr était une approximation.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe d''incertitude de Heisenberg et sa signification ?', '["On peut mesurer précisément position et vitesse simultanément","Il est fondamentalement impossible de","C''est une limitation technique","Il s''applique uniquement aux photons"]'::jsonb, 'Il est fondamentalement impossible de', 'Le principe de Heisenberg (1927) est une propriété fondamentale de la nature quantique, pas une limitation instrumentale.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''effet photoélectrique et comment Einstein l''a-t-il expliqué ?', '["Un phénomène mécanique","L''émission d''électrons par un métal","Un effet magnétique","Un effet thermique"]'::jsonb, 'L''émission d''électrons par un métal', 'L''explication de l''effet photoélectrique (Nobel 1921) a fondé la physique quantique et les technologies photovoltaïques.', 'Moyen'),
    (chap_id, 'Quel est le rôle de la physique dans le développement durable et les énergies renouvelables ?', '["La physique n''a pas de rôle","La physique sous-tend toutes les","La physique concerne uniquement la recherche fondamentale","Les énergies renouvelables ne nécessitent pas de physique"]'::jsonb, 'La physique sous-tend toutes les', 'Le développement d''Haïti en énergie solaire (fort ensoleillement) repose sur des principes de physique quantique et d''électronique.', 'Moyen');
  END IF;
END $$;
