-- Supplement Biologie (matiere_id=11) — NS3 et NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'ADN, réplication et expression génétique' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui a déterminé la structure en double hélice de l''ADN et en quelle année ?', '["Mendel en 1865","Watson et Crick en 1953","Pasteur en 1870","Lamarck en 1809"]'::jsonb, 'Watson et Crick en 1953', 'Watson, Crick et Franklin (données de diffraction X) ont établi le modèle de la double hélice antiparallèle de l''ADN.', 'Facile'),
    (chap_id, 'Qu''est-ce que la complémentarité des bases azotées dans l''ADN ?', '["Toutes les bases s''apparient avec toutes","Adénine (A) s''apparie avec Thymine (T)","A-G et T-C s''apparient","Les bases ne s''apparient pas"]'::jsonb, 'Adénine (A) s''apparie avec Thymine (T)', 'La règle de Chargaff (%A=%T, %G=%C) découle de l''appariement spécifique ; la paire G-C est plus stable (3 liaisons H).', 'Facile'),
    (chap_id, 'Qu''est-ce que la réplication semi-conservative de l''ADN ?', '["Chaque brin parental est dégradé","Chaque brin parental sert de matrice","Les deux brins sont reconstruits entièrement","La réplication est conservative (les deux brins parentaux restent ensemble)"]'::jsonb, 'Chaque brin parental sert de matrice', 'Meselson et Stahl (1958) ont confirmé la réplication semi-conservative par l''expérience aux isotopes N14/N15.', 'Moyen'),
    (chap_id, 'Quel est le rôle de l''ADN polymérase dans la réplication ?', '["Couper l''ADN","Synthétiser le nouveau brin d''ADN en","Dérouler la double hélice","Lier les fragments d''Okazaki"]'::jsonb, 'Synthétiser le nouveau brin d''ADN en', 'L''ADN polymérase ne peut synthétiser que dans le sens 5''→3'' ; d''où la différence entre brin continu et brin discontinu.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la transcription et où se déroule-t-elle dans une cellule eucaryote ?', '["La synthèse d''une protéine","La synthèse d''un ARNm à partir d''un","La réplication de l''ADN","La traduction de l''ARNm"]'::jsonb, 'La synthèse d''un ARNm à partir d''un', 'La transcription (ADN→ARNm) se déroule dans le noyau chez les eucaryotes ; l''ARNm est ensuite exporté dans le cytoplasme.', 'Facile'),
    (chap_id, 'Qu''est-ce que la traduction et où se déroule-t-elle ?', '["La transcription de l''ADN","La synthèse d''une chaîne polypeptidique","La réplication de l''ARN","La dégradation des protéines"]'::jsonb, 'La synthèse d''une chaîne polypeptidique', 'La traduction (ARNm→protéine) requiert l''ARNm, les ARNt, les ribosomes et l''ARNr (rRNA dans les ribosomes).', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un codon et comment code-t-il pour un acide aminé ?', '["Un nucléotide unique","Une séquence de 3 nucléotides de l''ARNm","Une protéine","Un intron"]'::jsonb, 'Une séquence de 3 nucléotides de l''ARNm', 'Le code génétique est triplet (64 codons pour 20 AA + 3 stop) : il est universel, redondant et sans chevauchement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le traitement (maturation) de l''ARNm chez les eucaryotes ?', '["L''ARNm est directement traduit sans modification","La coiffe 5''","L''ARNm est dégradé immédiatement","L''ARN polymérase modifie l''ARNm"]'::jsonb, 'La coiffe 5''', 'Le pré-ARNm eucaryote est matured dans le noyau : coiffe 5''-méthylguanosine, poly-A 3'', épissage (splicing) des introns.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''épissage alternatif et quelle est son importance ?', '["Un type de mutation","La possibilité d''inclure ou d''exclure","Un mécanisme de réplication","Un processus de dégradation de l''ARN"]'::jsonb, 'La possibilité d''inclure ou d''exclure', 'L''épissage alternatif explique pourquoi ~20 000 gènes humains produisent plus de 100 000 protéines différentes.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une mutation ponctuelle et quels en sont les types ?', '["Le remplacement d''un chromosome entier","Un changement d''un seul nucléotide dans","Une mutation chromosomique","Une polyploïdie"]'::jsonb, 'Un changement d''un seul nucléotide dans', 'Les mutations ponctuelles peuvent être silencieuses, faux-sens, non-sens ou de décalage du cadre de lecture (frameshift).', 'Moyen'),
    (chap_id, 'Quel est le rôle de l''ARN de transfert (ARNt) dans la traduction ?', '["Il code pour les protéines","Il transporte un acide aminé spécifique","Il sert de matrice pour l''ARNm","Il dégrade les protéines"]'::jsonb, 'Il transporte un acide aminé spécifique', 'L''ARNt est la molécule adaptatrice entre le code nucléique (triplets ARNm) et la séquence protéique (acides aminés).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''opéron lac chez E. coli et son intérêt pour comprendre la régulation des gènes ?', '["Un gène unique","Un ensemble de gènes structuraux sous","Un mécanisme de recombinaison","Un plasmide"]'::jsonb, 'Un ensemble de gènes structuraux sous', 'Le modèle de Jacob et Monod (1961, Nobel 1965) sur l''opéron lactose a révolutionné la compréhension de la régulation génique.', 'Moyen'),
    (chap_id, 'Quel est le rôle de la télomérase dans les cellules eucaryotes ?', '["Initier la réplication","Allonger les télomères qui","Réparer les cassures double brin","Épissage des introns"]'::jsonb, 'Allonger les télomères qui', 'Sans télomérase, les cellules somatiques vieillissent (sénescence) ; la télomérase active est un marqueur de certains cancers.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Évolution et classification du vivant' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la théorie de l''évolution par la sélection naturelle proposée par Darwin ?', '["Les espèces sont immuables","Les individus les mieux adaptés à leur","L''évolution est dirigée vers la complexité","Les caractères acquis sont héréditaires"]'::jsonb, 'Les individus les mieux adaptés à leur', 'Darwin (1859) : variation + hérédité + sélection naturelle = évolution. L''adaptation est graduelle et sans direction fixée.', 'Facile'),
    (chap_id, 'Quelle est la différence entre l''évolution de Lamarck et celle de Darwin ?', '["Elles sont identiques","Lamarck proposait l''hérédité des","Darwin est antérieur à Lamarck","Lamarck n''a pas théorisé l''évolution"]'::jsonb, 'Lamarck proposait l''hérédité des', 'La théorie de Lamarck (girafe allongeant le cou) est réfutée ; celle de Darwin est confirmée par la génétique moderne.', 'Facile'),
    (chap_id, 'Qu''est-ce que la dérive génétique et comment diffère-t-elle de la sélection naturelle ?', '["Elles sont identiques","La dérive génétique est une variation","La dérive génétique augmente toujours l''adaptation","La sélection naturelle est aléatoire"]'::jsonb, 'La dérive génétique est une variation', 'La dérive génétique (effet stochastique) peut fixer des allèles neutres ou même délétères dans les petites populations.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la spéciation allopatrique et quand se produit-elle ?', '["La spéciation par compétition directe","La formation d''une nouvelle espèce","La spéciation en sympatrie","La spéciation par polyploïdie uniquement"]'::jsonb, 'La formation d''une nouvelle espèce', 'L''isolement géographique (chaîne de montagnes, bras de mer) permet à des populations de diverger génétiquement jusqu''à l''isolement reproducteur.', 'Moyen'),
    (chap_id, 'Quelles sont les preuves moléculaires de l''évolution commune ?', '["L''absence de similitudes","La comparaison des séquences","La différence de taille entre espèces","L''absence de fossiles"]'::jsonb, 'La comparaison des séquences', 'La phylogénétique moléculaire utilise les homologies de séquences (ADNr 16S, cytochrome c) pour établir les liens évolutifs.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la classification phylogénétique (cladistique) ?', '["Classer les organismes par ressemblance morphologique","Regrouper les organismes selon leur","Classer par habitat","Classer par taille"]'::jsonb, 'Regrouper les organismes selon leur', 'La cladistique (Hennig, 1950) cherche des groupes monophylétiques (clades) ; elle a remplacé la classification purement morphologique.', 'Moyen'),
    (chap_id, 'Quel est le principe de la théorie synthétique de l''évolution (néo-darwinisme) ?', '["La sélection naturelle seule explique tout","La synthèse de la sélection naturelle","L''évolution est uniquement moléculaire","Les espèces n''évoluent pas"]'::jsonb, 'La synthèse de la sélection naturelle', 'La théorie synthétique (années 1930-1940) unifie Darwin, Mendel, la génétique des populations (Hardy-Weinberg).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un organe homologue et comment diffère-t-il d''un organe analogue ?', '["Ils sont identiques","Les organes homologues ont une même","Les analogues ont la même origine","Les homologues ont des fonctions identiques"]'::jsonb, 'Les organes homologues ont une même', 'Les homologues révèlent un ancêtre commun (évolution divergente) ; les analogues montrent l''évolution convergente.', 'Moyen'),
    (chap_id, 'Quelle est la signification de la nomenclature binominale de Linné ?', '["Un nom unique pour chaque individu","Chaque espèce est nommée par deux mots","Une classification en 3 règnes","Un système de classification numérique"]'::jsonb, 'Chaque espèce est nommée par deux mots', 'La nomenclature binominale (Linné, 1753) est universelle et en italique : Homo sapiens, Canis lupus, etc.', 'Facile'),
    (chap_id, 'Qu''est-ce que la coévolution et quel en est un exemple classique ?', '["L''évolution indépendante de deux espèces","L''évolution mutuelle de deux espèces","L''évolution uniquement parasitaire","La convergence évolutive"]'::jsonb, 'L''évolution mutuelle de deux espèces', 'Coévolution : orchidées de Madagascar et Xanthopan morganii (Darwin l''avait prédit avant sa découverte).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''endosymbiose et comment explique-t-elle l''origine des mitochondries et des chloroplastes ?', '["Une théorie réfutée","La théorie selon laquelle des bactéries","Une forme de parasitisme","Un mécanisme de division cellulaire"]'::jsonb, 'La théorie selon laquelle des bactéries', 'La théorie endosymbiotique est confirmée par l''ADN circulaire des mitochondries/chloroplastes et leurs propres ribosomes 70S.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la sélection sexuelle et comment diffère-t-elle de la sélection naturelle de survie ?', '["Elles sont identiques","La sélection sexuelle favorise les","La sélection sexuelle est purement aléatoire","Elle n''existe que chez les insectes"]'::jsonb, 'La sélection sexuelle favorise les', 'La queue du paon (handicap de survie mais avantage reproducteur) illustre la sélection sexuelle inter-sexuelle.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Écologie et dynamique des écosystèmes' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''un écosystème et quels en sont les composants principaux ?', '["Uniquement les organismes vivants","L''ensemble formé par une communauté","Un groupe d''espèces de même genre","Un habitat forestier uniquement"]'::jsonb, 'L''ensemble formé par une communauté', 'Un écosystème intègre les facteurs abiotiques (T°, lumière, sol) et biotiques (prédation, compétition, symbiose).', 'Facile'),
    (chap_id, 'Qu''est-ce que la chaîne alimentaire et le réseau trophique ?', '["Des séquences de décomposeurs","La chaîne alimentaire montre les","Des relations symbiotiques uniquement","Des cycles biogéochimiques"]'::jsonb, 'La chaîne alimentaire montre les', 'Le réseau trophique réel est beaucoup plus complexe qu''une chaîne simple ; les espèces ont souvent plusieurs proies et prédateurs.', 'Facile'),
    (chap_id, 'Qu''est-ce que le flux d''énergie dans un écosystème et la règle des 10% ?', '["L''énergie est recyclée indéfiniment","L''énergie circule à sens unique","Toute l''énergie est transférée","L''énergie augmente à chaque niveau trophique"]'::jsonb, 'L''énergie circule à sens unique', 'La règle des 10% (Lindeman) explique pourquoi les pyramides de biomasse s''amenuisent vers les prédateurs supérieurs.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le cycle du carbone et son importance pour le climat ?', '["Un cycle mineur","Le mouvement du carbone entre","Un cycle uniquement terrestre","Un processus sans lien avec le vivant"]'::jsonb, 'Le mouvement du carbone entre', 'L''excès de CO2 atmosphérique (combustion fossile) amplifie l''effet de serre et perturbe le cycle du carbone naturel.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la succession écologique et quels en sont les types ?', '["Un phénomène de migration","Le remplacement progressif de","Une extinction d''espèces","Un cycle saisonnier"]'::jsonb, 'Le remplacement progressif de', 'La succession aboutit à une communauté climacique (stable) ; ex. lagon comblé → marais → forêt.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la biodiversité et comment la mesure-t-on ?', '["Le nombre total d''espèces","La variété du vivant à l''échelle des","La biomasse totale","Le nombre d''individus"]'::jsonb, 'La variété du vivant à l''échelle des', 'La biodiversité (alpha, beta, gamma) est le résultat de milliards d''années d''évolution ; elle fournit des services écosystémiques.', 'Moyen'),
    (chap_id, 'Quelles sont les principales causes actuelles de l''érosion de la biodiversité ?', '["Uniquement la pollution","La destruction et fragmentation des","Uniquement le changement climatique","L''introduction d''espèces sauvages"]'::jsonb, 'La destruction et fragmentation des', 'Le taux d''extinction actuel est estimé 1000× supérieur au taux de fond naturel ; nous vivons la 6ème extinction de masse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la niche écologique d''une espèce ?', '["Son habitat géographique","L''ensemble des rôles fonctionnels et","Son nom scientifique","Sa taille de population"]'::jsonb, 'L''ensemble des rôles fonctionnels et', 'Hutchinson définit la niche en n dimensions ; deux espèces occupant la même niche entrent en compétition exclusive.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe d''exclusion compétitive de Gause ?', '["Les espèces coexistent toujours","Deux espèces occupant exactement la","Les espèces se partagent toujours les ressources","La compétition est rare en nature"]'::jsonb, 'Deux espèces occupant exactement la', 'Le principe de Gause (1934) explique la diversification des niches et la divergence des caractères entre espèces sympatriques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le changement climatique et ses effets sur les écosystèmes haïtiens ?', '["Un phénomène naturel sans importance","Le réchauffement global causé","Un phénomène limité aux pôles","Un problème exclusivement industriel"]'::jsonb, 'Le réchauffement global causé', 'Haïti est parmi les pays les plus vulnérables au CC : déforestation (couverture forestière ~2%), érosion des sols, blanchissement corallien.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la biorestauration et comment peut-elle aider des écosystèmes dégradés ?', '["La destruction des écosystèmes","L''utilisation d''organismes vivants","Un processus uniquement chimique","Une technique agricole uniquement"]'::jsonb, 'L''utilisation d''organismes vivants', 'La biorestauration (phytoremédiation, biorémédiation bactérienne) est une alternative économique aux méthodes physico-chimiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la biologie de la conservation et ses outils principaux ?', '["La gestion des fermes","La discipline scientifique visant à","La biologie moléculaire uniquement","L''agriculture intensive"]'::jsonb, 'La discipline scientifique visant à', 'La biologie de la conservation utilise : corridors écologiques, programmes d''élevage ex situ, banques de gènes, aires protégées.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Biotechnologies et applications de la biologie' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la PCR (réaction en chaîne par polymérase) et à quoi sert-elle ?', '["Une technique de séquençage","Une technique d''amplification in vitro","Une technique de chromatographie","Une méthode d''électrophorèse"]'::jsonb, 'Une technique d''amplification in vitro', 'La PCR (Mullis, 1983, Nobel 1993) utilise Taq polymérase, amorces et cycles thermiques (dénaturation, hybridation, élongation).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la technologie CRISPR-Cas9 et ses applications ?', '["Un type de PCR","Un système d''édition génomique précis","Une technique de séquençage","Un outil de clonage classique"]'::jsonb, 'Un système d''édition génomique précis', 'CRISPR-Cas9 (Doudna & Charpentier, Nobel 2020) révolutionne la médecine, l''agriculture et la recherche fondamentale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le clonage moléculaire et ses étapes principales ?', '["La reproduction asexuée d''un animal","L''insertion d''un fragment d''ADN dans un","Une technique de PCR","Le séquençage de génome"]'::jsonb, 'L''insertion d''un fragment d''ADN dans un', 'Le clonage moléculaire (gènes recombinants) a permis de produire l''insuline humaine par des bactéries dès 1982.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les organismes génétiquement modifiés (OGM) et leurs controverses ?', '["Des mutants naturels","Des organismes dont le génome a été","Des organismes clonés","Des hybrides naturels"]'::jsonb, 'Des organismes dont le génome a été', 'OGM : maïs Bt (résistant aux insectes), riz doré (vitamine A) ; controverses : effets sur biodiversité, monopoles semenciers.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la thérapie génique et quels sont ses principes ?', '["La chirurgie traditionnelle","L''introduction d''une version","La chimiothérapie","La greffe d''organes"]'::jsonb, 'L''introduction d''une version', 'La thérapie génique (ex. Luxturna pour la rétinite pigmentaire, Zolgensma pour SMA) utilise des vecteurs viraux (AAV).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la médecine personnalisée et comment la génomique y contribue-t-elle ?', '["La médecine traditionnelle","L''adaptation des traitements médicaux","La médecine homéopathique","La médecine préventive classique"]'::jsonb, 'L''adaptation des traitements médicaux', 'La pharmacogénomique identifie les variants génétiques influençant la réponse aux médicaments (métabolisme, cibles).', 'Moyen'),
    (chap_id, 'Qu''est-ce que les cellules souches et leurs types principaux ?', '["Des cellules différenciées","Des cellules indifférenciées capables","Des cellules cancéreuses","Des cellules reproductrices"]'::jsonb, 'Des cellules indifférenciées capables', 'Les cellules souches iPSC (Yamanaka, Nobel 2012) sont créées en reprogrammant des cellules adultes différenciées.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la bioinformatique et quel est son rôle en biologie moderne ?', '["La biologie des insectes","L''utilisation de l''informatique et des","La biotechnologie agricole","La biologie marine informatisée"]'::jsonb, 'L''utilisation de l''informatique et des', 'La bioinformatique (BLAST, phylogénomique, prédiction de structure AlphaFold) est indispensable à la biologie moderne.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le Projet Génome Humain et ses résultats principaux ?', '["Un projet d''agriculture","Le projet international (1990-2003) qui","Un projet uniquement américain","Un projet de clonage humain"]'::jsonb, 'Le projet international (1990-2003) qui', 'Le PGH a révélé que ~1,5% du génome code pour des protéines et que >95% était considéré «ADN non codant» (maintenant partiellement fonctionnel).', 'Moyen'),
    (chap_id, 'Quelles sont les applications de la biologie en agroalimentaire et en médecine en Haïti ?', '["Aucune application locale","Les biotechnologies peuvent améliorer","Uniquement des applications ornementales","Les biotechnologies sont inaccessibles aux pays en développement"]'::jsonb, 'Les biotechnologies peuvent améliorer', 'Haïti peut bénéficier des biotechnologies : sélection variétale, biofortification, diagnostics moléculaires adaptés au climat tropical.', 'Moyen');
  END IF;
END $$;
