-- Supplement Économie NS3-NS4 (matiere_id=15)
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'Commerce international et mondialisation' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le théorème HOS (Heckscher-Ohlin-Samuelson) sur le commerce international ?', '["Les pays échangent des biens identiques","Chaque pays se spécialise dans les biens intensifs en son facteur de production abondant","Le libre-échange est toujours bénéfique","Le protectionnisme augmente le bien-être"]'::jsonb, 'Chaque pays se spécialise dans les biens intensifs en son facteur de production abondant', 'HOS : un pays abondant en travail exporte des biens intensifs en travail et importe des biens intensifs en capital.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un tarif douanier et son effet ?', '["Une taxe sur les importations qui augmente leur prix et protège les producteurs locaux","Une subvention aux exportateurs","Un quota d''importation","Un accord commercial"]'::jsonb, 'Une taxe sur les importations qui augmente leur prix et protège les producteurs locaux', 'Le tarif réduit les importations, protège les producteurs nationaux mais pénalise les consommateurs.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un quota d''importation ?', '["Une taxe sur les biens importés","Une limite quantitative sur les importations d''un bien","Une subvention à l''exportation","Un accord de libre-échange"]'::jsonb, 'Une limite quantitative sur les importations d''un bien', 'Le quota fixe un plafond aux importations, créant une rente pour les importateurs disposant des licences.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la balance commerciale ?', '["Le total des dettes d''un pays","La différence entre exportations et importations de biens","Le PIB net","Le solde budgétaire"]'::jsonb, 'La différence entre exportations et importations de biens', 'Si X > M : excédent commercial ; si X < M : déficit commercial. Composante du compte courant.', 'Facile'),
    (chap_id, 'Quel organisme régule le commerce international depuis 1995 ?', '["FMI","Banque Mondiale","OMC (Organisation Mondiale du Commerce)","OCDE"]'::jsonb, 'OMC (Organisation Mondiale du Commerce)', 'L''OMC succède au GATT et supervise les règles du commerce international, le règlement des différends.', 'Facile'),
    (chap_id, 'Qu''est-ce que le dumping dans le commerce international ?', '["Exporter des matières premières","Vendre un bien à l''étranger en dessous de son coût de production pour conquérir des parts de marché","Un accord commercial bilatéral","Une subvention cachée"]'::jsonb, 'Vendre un bien à l''étranger en dessous de son coût de production pour conquérir des parts de marché', 'Le dumping est considéré comme une pratique déloyale ; l''OMC autorise des droits antidumping en réponse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la balance des paiements ?', '["Le budget de l''État","Le document qui enregistre toutes les transactions économiques d''un pays avec le reste du monde","Le solde commercial","La dette extérieure"]'::jsonb, 'Le document qui enregistre toutes les transactions économiques d''un pays avec le reste du monde', 'La balance des paiements comprend le compte courant, le compte de capital et le compte financier.', 'Moyen'),
    (chap_id, 'Quel est le paradoxe de Leontief ?', '["Les États-Unis exportent des biens capital-intensifs alors qu''ils sont le pays le plus capitalisé","Les pays pauvres exportent plus","Le libre-échange nuit aux riches","Les tarifs stimulent la croissance"]'::jsonb, 'Les États-Unis exportent des biens capital-intensifs alors qu''ils sont le pays le plus capitalisé', 'Leontief (1953) contredit HOS : les USA, très capitalisés, exportent des biens travail-intensifs (en réalité capital humain).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la globalisation financière ?', '["L''unification des monnaies","L''intégration croissante des marchés financiers mondiaux et la libre circulation des capitaux","Le commerce de marchandises","L''aide internationale"]'::jsonb, 'L''intégration croissante des marchés financiers mondiaux et la libre circulation des capitaux', 'La globalisation financière depuis les années 1980 accélère les flux de capitaux mais amplifie les crises.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "triade" dans le commerce mondial ?', '["Trois grandes banques","Les États-Unis, l''Europe et le Japon qui dominaient le commerce mondial dans les années 1990","Trois matières premières","Les trois plus grands pays exportateurs"]'::jsonb, 'Les États-Unis, l''Europe et le Japon qui dominaient le commerce mondial dans les années 1990', 'La triade de Kenichi Ohmae désigne les trois pôles dominants de la mondialisation économique.', 'Difficile'),
    (chap_id, 'Quel est l''argument de l''industrie naissante pour le protectionnisme ?', '["Protéger les industries déclinantes","Protéger temporairement une nouvelle industrie jusqu''à ce qu''elle atteigne des économies d''échelle compétitives","Restreindre toutes les importations","Subventionner les exportations"]'::jsonb, 'Protéger temporairement une nouvelle industrie jusqu''à ce qu''elle atteigne des économies d''échelle compétitives', 'Friedrich List : les pays en développement ont intérêt à protéger leurs industries embryonnaires.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "maladie hollandaise" ?', '["Une pandémie économique","La désindustrialisation causée par l''appréciation de la monnaie suite à une ressource naturelle abondante","Un problème bancaire","Une crise de la dette"]'::jsonb, 'La désindustrialisation causée par l''appréciation de la monnaie suite à une ressource naturelle abondante', 'La découverte de gaz naturel en Hollande (1960s) renchérit la monnaie et déstabilisa l''industrie manufacturière.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une zone de libre-échange ?', '["Un pays sans douane interne","Un accord entre pays supprimant les barrières commerciales entre membres, chacun gardant sa politique vis-à-vis des tiers","Une union monétaire","Un accord tarifaire commun"]'::jsonb, 'Un accord entre pays supprimant les barrières commerciales entre membres, chacun gardant sa politique vis-à-vis des tiers', 'Ex : ALENA/USMCA. Différent de l''union douanière qui fixe un tarif extérieur commun.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'Macroéconomie : chômage, inflation et politiques économiques' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le chômage frictionnel ?', '["Le chômage dû à la crise","Le chômage temporaire lié à la transition entre emplois","Le chômage de longue durée","Le sous-emploi"]'::jsonb, 'Le chômage temporaire lié à la transition entre emplois', 'Le chômage frictionnel est inévitable et bénin : il correspond aux délais normaux de recherche d''emploi.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la courbe de Phillips originale (années 1960) établit ?', '["Une relation positive entre inflation et chômage","Une relation inverse entre inflation et chômage","Une relation entre PIB et emploi","La neutralité de la monnaie"]'::jsonb, 'Une relation inverse entre inflation et chômage', 'Phillips (1958) : baisse du chômage → hausse des salaires → hausse des prix. Arbitrage inflation/chômage.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le taux de chômage naturel (NAIRU) ?', '["Zéro chômage","Le taux de chômage compatible avec une inflation stable (ni accélérante ni décélérante)","Le taux de chômage en pleine crise","Le plein emploi absolu"]'::jsonb, 'Le taux de chômage compatible avec une inflation stable (ni accélérante ni décélérante)', 'Le NAIRU (Friedman, Phelps) est le taux d''équilibre à long terme ; toute tentative de le dépasser génère de l''inflation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la politique budgétaire ?', '["La politique de la banque centrale","L''utilisation des dépenses publiques et de la fiscalité pour influencer l''activité économique","La politique commerciale","La régulation financière"]'::jsonb, 'L''utilisation des dépenses publiques et de la fiscalité pour influencer l''activité économique', 'La politique budgétaire (gouvernement) stimule (déficit) ou freine (excédent) l''économie.', 'Facile'),
    (chap_id, 'Qu''est-ce que le déficit public ?', '["La dette totale d''un pays","L''excès des dépenses publiques sur les recettes fiscales en une année","Le déficit commercial","L''inflation budgétaire"]'::jsonb, 'L''excès des dépenses publiques sur les recettes fiscales en une année', 'Déficit = dépenses - recettes > 0. Il s''accumule pour former la dette publique.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''austérité budgétaire et ses effets débattus ?', '["Des dépenses illimitées","Réduction du déficit par coupes dans les dépenses ou hausses d''impôts, pouvant réduire la croissance à court terme","Une politique de relance","La nationalisation d''entreprises"]'::jsonb, 'Réduction du déficit par coupes dans les dépenses ou hausses d''impôts, pouvant réduire la croissance à court terme', 'Le débat austérité/relance oppose ordolibéraux/FMI à Keynes/Krugman sur les multiplicateurs en récession.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le quantitative easing (QE) ?', '["Un impôt sur les transactions","Des achats d''actifs par la banque centrale pour injecter des liquidités dans l''économie","Une réforme fiscale","Un contrôle des capitaux"]'::jsonb, 'Des achats d''actifs par la banque centrale pour injecter des liquidités dans l''économie', 'Le QE (Fed, BCE) a été massivement utilisé après 2008 pour stimuler l''économie quand les taux étaient à zéro.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la trappe à liquidité (Keynes) ?', '["Un excès d''épargne","Une situation où la politique monétaire devient inefficace car les taux sont proches de zéro","Une crise bancaire","Un déficit de consommation"]'::jsonb, 'Une situation où la politique monétaire devient inefficace car les taux sont proches de zéro', 'Dans la trappe à liquidité, les agents thésaurisent au lieu d''investir même avec des taux nuls.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la règle de Taylor en politique monétaire ?', '["Un accord international","Une règle prescrivant le taux directeur optimal en fonction de l''inflation et de l''output gap","Un indicateur de croissance","Un modèle de change"]'::jsonb, 'Une règle prescrivant le taux directeur optimal en fonction de l''inflation et de l''output gap', 'La règle de Taylor (1993) : i = r* + π + 0.5(π-π*) + 0.5(y-y*). Guide les banques centrales.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''effet d''éviction en politique budgétaire ?', '["Un effet multiplicateur positif","Des dépenses publiques financées par emprunt qui font monter les taux et réduisent l''investissement privé","Une réduction des impôts","Un effet de la politique monétaire"]'::jsonb, 'Des dépenses publiques financées par emprunt qui font monter les taux et réduisent l''investissement privé', 'L''effet d''éviction atténue l''impact du multiplicateur : l''État emprunte au détriment du secteur privé.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la théorie quantitative de la monnaie (MV = PQ) ?', '["La valeur de la monnaie","La relation entre masse monétaire (M), vitesse (V), niveau des prix (P) et production (Q)","Le taux de change","Le multiplicateur de crédit"]'::jsonb, 'La relation entre masse monétaire (M), vitesse (V), niveau des prix (P) et production (Q)', 'Fisher : toute augmentation de M non compensée par Q génère de l''inflation (P augmente).', 'Difficile'),
    (chap_id, 'Qu''est-ce que le paradoxe de l''épargne (Keynes) ?', '["Épargner est toujours bénéfique","Ce qui est raisonnable pour un ménage (épargner plus) peut nuire à l''économie si tout le monde le fait","L''épargne est inutile","L''investissement dépend du revenu"]'::jsonb, 'Ce qui est raisonnable pour un ménage (épargner plus) peut nuire à l''économie si tout le monde le fait', 'Le paradoxe de parcimonie : une hausse collective de l''épargne réduit la demande et le revenu global.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "taper tantrum" et quel risque illustre-t-il ?', '["Un type de crise agricole","La volatilité des marchés émergents quand la Fed signale un durcissement de sa politique monétaire","Une crise de la zone euro","Un choc pétrolier"]'::jsonb, 'La volatilité des marchés émergents quand la Fed signale un durcissement de sa politique monétaire', 'Le taper tantrum (2013) illustre la dépendance des marchés émergents à la liquidité mondiale américaine.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'Économie du développement et Haïti' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quels sont les principaux indicateurs de la pauvreté selon la Banque Mondiale ?', '["PIB et exportations","Pauvreté monétaire (seuil < 2,15$/jour), IDH, taux de malnutrition, accès aux services","Taux de change et inflation","Dette extérieure et déficit"]'::jsonb, 'Pauvreté monétaire (seuil < 2,15$/jour), IDH, taux de malnutrition, accès aux services', 'La Banque Mondiale utilise le seuil de 2,15 $ PPA/jour et des indicateurs multidimensionnels.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le cercle vicieux de la pauvreté (Nurkse) ?', '["Les pauvres ne veulent pas travailler","Faible revenu → faible épargne → faible investissement → faible productivité → faible revenu","La corruption gouvernementale","Le manque d''aide internationale"]'::jsonb, 'Faible revenu → faible épargne → faible investissement → faible productivité → faible revenu', 'Nurkse : les pays pauvres sont pris dans un équilibre de faible niveau d''où ils peinent à sortir sans aide.', 'Difficile'),
    (chap_id, 'Quel rôle jouent les transferts de la diaspora pour les économies comme Haïti ?', '["Aucun rôle significatif","Principal flux de revenus extérieurs, dépassant souvent l''aide publique au développement","Uniquement des investissements","Un fardeau pour l''économie"]'::jsonb, 'Principal flux de revenus extérieurs, dépassant souvent l''aide publique au développement', 'En Haïti, les remises de la diaspora représentent une part majeure du PIB (>30%), source vitale de devises.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "dutch disease" (maladie hollandaise) appliqué aux pays pétroliers ?', '["Une épidémie économique","L''appréciation de la monnaie et la désindustrialisation causées par les revenus pétroliers","Un avantage concurrentiel","La dépendance aux importations"]'::jsonb, 'L''appréciation de la monnaie et la désindustrialisation causées par les revenus pétroliers', 'Les pays pétroliers voient leur monnaie s''apprécier, rendant leurs exportations non-pétrolières non compétitives.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''ajustement structurel imposé par le FMI aux pays en développement ?', '["Des aides sans conditions","Des réformes libérales conditionnant les prêts : privatisations, déréglementation, coupes budgétaires","Des nationalisations","Des politiques protectionnistes"]'::jsonb, 'Des réformes libérales conditionnant les prêts : privatisations, déréglementation, coupes budgétaires', 'Les PAS (Plans d''Ajustement Structurel) des années 1980-90 ont été critiqués pour leurs effets sociaux.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''économie informelle dans les pays en développement ?', '["L''économie souterraine criminelle","L''ensemble des activités économiques non déclarées, non régulées, hors du cadre légal formel","Le secteur agricole","Le commerce de rue légal"]'::jsonb, 'L''ensemble des activités économiques non déclarées, non régulées, hors du cadre légal formel', 'En Haïti et dans les PED, le secteur informel représente souvent plus de 50% de l''emploi.', 'Moyen'),
    (chap_id, 'Quel est l''impact du séisme de 2010 sur l''économie haïtienne ?', '["Un impact mineur","Une destruction d''une part considérable du PIB, des infrastructures et du capital humain","Une opportunité de croissance","Un renforcement des institutions"]'::jsonb, 'Une destruction d''une part considérable du PIB, des infrastructures et du capital humain', 'Le séisme de janvier 2010 a causé des dégâts estimés à 120% du PIB haïtien, amplifiant la vulnérabilité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la microfinance comme outil de développement ?', '["Des prêts aux grandes entreprises","Des services financiers (microcrédit, épargne) destinés aux populations exclues du système bancaire traditionnel","Une politique monétaire","Des subventions directes"]'::jsonb, 'Des services financiers (microcrédit, épargne) destinés aux populations exclues du système bancaire traditionnel', 'La microfinance (Grameen Bank, Yunus) vise à réduire la pauvreté en donnant accès au crédit aux exclus.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "big push" en économie du développement (Rosenstein-Rodan) ?', '["Une aide humanitaire","L''idée qu''un investissement massif et coordonné est nécessaire pour sortir d''un équilibre de faible croissance","Une politique commerciale","Un plan d''austérité"]'::jsonb, 'L''idée qu''un investissement massif et coordonné est nécessaire pour sortir d''un équilibre de faible croissance', 'Le "grand bond" nécessite un investissement simultané dans plusieurs secteurs pour créer des externalités réciproques.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la dépendance au sentier (path dependency) appliquée aux économies ? ', '["Un pays ne peut jamais changer","Les choix passés (institutions, technologies) contraignent les options futures même si de meilleures existent","Le développement linéaire","Le déterminisme géographique"]'::jsonb, 'Les choix passés (institutions, technologies) contraignent les options futures même si de meilleures existent', 'North : les institutions héritées de l''histoire créent des "lock-in" qui perpétuent des équilibres sous-optimaux.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le consensus de Washington et ses critiques ?', '["Un accord de paix","Un ensemble de politiques libérales (privatisation, ouverture) prescrit aux PED, critiqué pour ignorer le contexte local","Un traité commercial","Une doctrine militaire"]'::jsonb, 'Un ensemble de politiques libérales (privatisation, ouverture) prescrit aux PED, critiqué pour ignorer le contexte local', 'Williamson (1989) : 10 politiques. Critiqué par Stiglitz pour ses effets sociaux et son uniformité.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la trappe à conflits (Paul Collier) et comment affecte-t-elle les PED ?', '["Un problème alimentaire","La tendance des pays pauvres et fragiles à entrer dans des cycles de violence qui perpétuent la pauvreté","La dépendance à l''aide","Le protectionnisme militaire"]'::jsonb, 'La tendance des pays pauvres et fragiles à entrer dans des cycles de violence qui perpétuent la pauvreté', 'Collier dans Le Milliard du bas : les conflits civils détruisent le capital et les institutions, piégeant les pays.', 'Difficile'),
    (chap_id, 'Quel est le rôle des institutions dans le développement économique selon North et Acemoglu ?', '["Aucun rôle","Les institutions inclusives créent les incitations nécessaires à l''investissement et à l''innovation","Seule la géographie détermine le développement","L''aide internationale suffit"]'::jsonb, 'Les institutions inclusives créent les incitations nécessaires à l''investissement et à l''innovation', 'Acemoglu et Robinson dans Why Nations Fail : institutions inclusives vs extractives déterminent la prospérité.', 'Difficile');
  END IF;
END $$;
