-- Supplément Créole NS1-NS2 (matiere_id=26) — +18 questions/chapitre pour atteindre 20 minimum

-- Chapitre 1 : Istwa lang kreyòl ayisyen ak fonoloji NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 26 AND titre = 'Istwa lang kreyòl ayisyen ak fonoloji' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'En quelle période le créole haïtien a-t-il principalement émergé comme langue ?', '["XVe siècle", "XVIIe–XVIIIe siècle", "XIXe siècle", "XXe siècle"]'::jsonb, 'XVIIe–XVIIIe siècle', 'Le créole haïtien s''est développé pendant la colonisation française de Saint-Domingue aux XVIIe et XVIIIe siècles, comme langue de communication entre esclaves africains d''origines diverses et avec les colons.', 'Facile'),
    (chap_id, 'Quelle langue a fourni la majeure partie du vocabulaire du créole haïtien ?', '["L''espagnol", "Le français", "Le portugais", "L''anglais"]'::jsonb, 'Le français', 'Le créole haïtien est une langue à base lexicale française : environ 90 % de son vocabulaire provient du français, bien que sa grammaire soit fortement influencée par les langues africaines.', 'Facile'),
    (chap_id, 'Quelle famille de langues africaines a le plus influencé la structure grammaticale du créole haïtien ?', '["Les langues bantoues", "Les langues gbe (fon, ewe)", "Les langues nilotiques", "Les langues berbères"]'::jsonb, 'Les langues gbe (fon, ewe)', 'Les langues gbe, notamment le fon du Dahomey (actuel Bénin) et l''ewe, ont fortement influencé la syntaxe et la phonologie du créole haïtien. Les esclaves du Dahomey étaient nombreux dans les plantations coloniales.', 'Moyen'),
    (chap_id, 'En quelle année le créole haïtien a-t-il été reconnu comme langue officielle dans la Constitution d''Haïti ?', '["1957", "1971", "1987", "2010"]'::jsonb, '1987', 'La Constitution haïtienne de 1987 a reconnu le créole haïtien comme langue officielle au même titre que le français, mettant fin à sa marginalisation institutionnelle après des siècles de minorisation.', 'Facile'),
    (chap_id, 'Combien de langues officielles Haïti possède-t-elle ?', '["Une seule (le créole)", "Deux (le français et le créole)", "Trois (le français, le créole et l''anglais)", "Aucune langue officielle"]'::jsonb, 'Deux (le français et le créole)', 'Haïti a deux langues officielles : le français et le créole haïtien. Le créole est parlé par l''ensemble de la population, tandis que le français est surtout utilisé dans les contextes formels et éducatifs.', 'Facile'),
    (chap_id, 'Quel peuple autochtone d''Haïti a également contribué au vocabulaire du créole haïtien ?', '["Les Aztèques", "Les Mayas", "Les Taïnos (Arawaks)", "Les Incas"]'::jsonb, 'Les Taïnos (Arawaks)', 'Les Taïnos, habitants autochtones d''Haïti avant la colonisation européenne, ont laissé des traces dans le vocabulaire créole, notamment pour désigner les plantes, les animaux et les réalités locales.', 'Moyen'),
    (chap_id, 'Quelle caractéristique phonologique héritée du français retrouve-t-on dans le créole haïtien ?', '["Les tons musicaux", "Les voyelles nasales", "Les clics linguaux", "Les consonnes roulées"]'::jsonb, 'Les voyelles nasales', 'Comme le français, le créole haïtien possède des voyelles nasales (an, on, en), une caractéristique phonologique qui le distingue de nombreuses langues africaines mais lie au français son lexificateur.', 'Moyen'),
    (chap_id, 'Comment appelle-t-on la langue qui fournit l''essentiel du vocabulaire d''une langue créole ?', '["La langue substrat", "La langue lexificatrice", "La langue pidgin", "La langue morte"]'::jsonb, 'La langue lexificatrice', 'La langue lexificatrice (ou superstrat) est celle qui fournit l''essentiel du vocabulaire d''une langue créole. Pour le créole haïtien, c''est le français qui remplit ce rôle.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un "substrat linguistique" dans le contexte du créole haïtien ?', '["La langue officielle de l''État", "Les langues africaines qui ont influencé la structure profonde du créole", "Les emprunts modernes à l''anglais", "La langue des colons français"]'::jsonb, 'Les langues africaines qui ont influencé la structure profonde du créole', 'Le substrat linguistique désigne les langues qui ont influencé la structure profonde (phonologie, syntaxe, morphologie) d''une langue, même si elles n''en constituent pas le vocabulaire principal. Les langues africaines forment le substrat du créole haïtien.', 'Difficile'),
    (chap_id, 'Dans quel contexte historique précis le créole haïtien s''est-il développé ?', '["Lors de la colonisation espagnole", "Dans les plantations coloniales françaises de Saint-Domingue", "Lors de la Révolution haïtienne de 1804", "Lors de l''Occupation américaine (1915-1934)"]'::jsonb, 'Dans les plantations coloniales françaises de Saint-Domingue', 'Le créole haïtien est né dans les plantations coloniales françaises de Saint-Domingue, où des esclaves africains d''origines très diverses devaient trouver un moyen de communiquer entre eux et avec les colons francophones.', 'Facile'),
    (chap_id, 'Quel est le nombre approximatif de locuteurs du créole haïtien dans le monde ?', '["Moins de 2 millions", "Entre 5 et 7 millions", "Entre 10 et 12 millions", "Plus de 50 millions"]'::jsonb, 'Entre 10 et 12 millions', 'Le créole haïtien est parlé par environ 10 à 12 millions de personnes, principalement en Haïti et dans la diaspora haïtienne aux États-Unis, au Canada, en France et dans d''autres pays.', 'Moyen'),
    (chap_id, 'Comment appelle-t-on le système des sons d''une langue ?', '["La morphologie", "La syntaxe", "La phonologie", "La sémantique"]'::jsonb, 'La phonologie', 'La phonologie est la branche de la linguistique qui étudie les sons d''une langue et leur organisation en système. Elle analyse les phonèmes (unités sonores distinctives) et les règles de leur combinaison.', 'Facile'),
    (chap_id, 'Quelle caractéristique distingue le créole haïtien du français en matière de genre grammatical ?', '["Le créole a plus de genres que le français", "Le créole n''a pas de genre grammatical", "Le créole a trois genres : masculin, féminin et neutre", "Le créole utilise le genre uniquement pour les êtres animés"]'::jsonb, 'Le créole n''a pas de genre grammatical', 'Contrairement au français, le créole haïtien ne distingue pas les noms selon le genre masculin ou féminin. Cette absence de genre est une influence des langues africaines du substrat qui n''ont généralement pas de genre grammatical.', 'Moyen'),
    (chap_id, 'Sur quel dialecte régional le créole haïtien standardisé est-il principalement basé ?', '["Le créole du Cap-Haïtien", "Le créole des Cayes", "Le créole de Port-au-Prince", "Le créole de Jacmel"]'::jsonb, 'Le créole de Port-au-Prince', 'Le créole haïtien standardisé est basé sur le dialecte de la région de Port-au-Prince, capitale et centre médiatique et culturel du pays, qui concentre la majorité de la population urbaine.', 'Facile'),
    (chap_id, 'Quel organisme officiel est chargé de normaliser la langue créole en Haïti ?', '["L''Académie française", "L''Akademi Kreyòl Ayisyen (AKA)", "L''Institut de Sauvegarde du Patrimoine National (ISPAN)", "L''UNESCO"]'::jsonb, 'L''Akademi Kreyòl Ayisyen (AKA)', 'L''Akademi Kreyòl Ayisyen (AKA), fondée en 2014, est l''institution officielle haïtienne chargée de normaliser et de réglementer la langue créole haïtienne, à l''image de l''Académie française pour le français.', 'Moyen'),
    (chap_id, 'Quelle est la particularité de l''orthographe officielle du créole haïtien établie en 1979 ?', '["Elle est basée sur l''alphabet phonétique international (API)", "Elle est entièrement phonétique (chaque son correspond à un symbole unique)", "Elle reprend exactement l''orthographe française", "Elle utilise des tons marqués par des accents toniques"]'::jsonb, 'Elle est entièrement phonétique (chaque son correspond à un symbole unique)', 'L''orthographe officielle du créole haïtien, établie par le décret de 1979 (système IPN), est phonétique : chaque phonème est représenté par un seul graphème, rendant la correspondance son-lettre beaucoup plus régulière qu''en français.', 'Difficile'),
    (chap_id, 'Quel mot créole haïtien d''origine taïno désigne le maïs ?', '["Diri", "Mayi", "Pwa", "Bannann"]'::jsonb, 'Mayi', 'Le mot "mayi" (maïs) est d''origine taïno. Les Taïnos étaient les habitants autochtones d''Haïti, et plusieurs mots relatifs aux plantes, aux aliments et à la nature locale leur ont été empruntés par le créole haïtien.', 'Difficile'),
    (chap_id, 'Quel phénomène linguistique décrit la transformation d''un pidgin en langue maternelle d''une communauté ?', '["La pidginisation", "La créolisation", "La décréolisation", "La diglossie"]'::jsonb, 'La créolisation', 'La créolisation est le processus par lequel un pidgin (langue de contact rudimentaire) se transforme en langue créole complète, devenant la langue maternelle d''une communauté avec une grammaire stabilisée et un vocabulaire étendu.', 'Difficile');
  END IF;
END $$;

-- Chapitre 2 : Gramè kreyòl ayisyen : mòfoloji ak sentaks NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 26 AND titre = 'Gramè kreyòl ayisyen : mòfoloji ak sentaks' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel marqueur verbal indique l''aspect progressif (être en train de) en créole haïtien ?', '["Te", "Ap", "Va", "An"]'::jsonb, 'Ap', 'En créole haïtien, "ap" est le marqueur de l''aspect progressif : "Mwen ap manje" = "Je suis en train de manger". Il précède toujours le verbe et indique une action en cours au moment de l''énonciation.', 'Facile'),
    (chap_id, 'Comment forme-t-on le pluriel des noms en créole haïtien ?', '["En ajoutant -s à la fin du nom", "En changeant l''article", "En ajoutant ''yo'' après le nom", "En redoublant le nom"]'::jsonb, 'En ajoutant ''yo'' après le nom', 'En créole haïtien, le pluriel se forme en ajoutant le marqueur "yo" après le nom : "timoun yo" (les enfants), "kay yo" (les maisons). Ce "yo" est aussi le pronom de la 3e personne du pluriel.', 'Facile'),
    (chap_id, 'Quel marqueur verbal indique le passé en créole haïtien ?', '["Ap", "Va", "Te", "La"]'::jsonb, 'Te', '"Te" est le marqueur du passé en créole haïtien : "Mwen te manje" = "J''ai mangé / Je mangeais". Il se place avant le verbe. Combiné avec "ap", il forme le passé progressif : "Mwen te ap manje" (j''étais en train de manger).', 'Facile'),
    (chap_id, 'Quelle est la structure de base d''une phrase affirmative en créole haïtien ?', '["Verbe - Sujet - Objet", "Sujet - Verbe - Objet (SVO)", "Objet - Sujet - Verbe", "Sujet - Objet - Verbe"]'::jsonb, 'Sujet - Verbe - Objet (SVO)', 'Le créole haïtien utilise la structure SVO (Sujet - Verbe - Objet) : "Mwen renmen liv" (J''aime les livres). Cette structure est partagée avec le français et l''anglais, et caractéristique des créoles à base lexicale française.', 'Facile'),
    (chap_id, 'Comment exprime-t-on la négation en créole haïtien ?', '["Ne...pas, comme en français", "Pa devant le verbe", "Non après le verbe", "Pwen à la fin de la phrase"]'::jsonb, 'Pa devant le verbe', 'La négation en créole haïtien s''exprime avec "pa" placé directement avant le verbe : "Mwen pa manje" (Je ne mange pas). Cette structure est plus simple qu''en français qui nécessite deux éléments (ne...pas).', 'Facile'),
    (chap_id, 'Quel article défini en créole haïtien s''utilise après un mot terminant par une consonne ?', '["A", "An", "La", "Nan"]'::jsonb, 'La', 'En créole haïtien, l''article défini varie selon le son final du mot : "la" après une consonne (men la = la main), "a" après une voyelle orale (tèt a = la tête), "an" après une nasale ou voyelle nasale (chanm nan = la chambre).', 'Moyen'),
    (chap_id, 'Quel est le pronom personnel sujet de la 1ère personne du singulier en créole haïtien ?', '["Ou", "Li", "Mwen", "Nou"]'::jsonb, 'Mwen', '"Mwen" est le pronom de la 1ère personne du singulier, équivalent du "je" français. Les autres pronoms sujets sont : ou (tu), li (il/elle), nou (nous), nou (vous), yo (ils/elles).', 'Facile'),
    (chap_id, 'Comment indique-t-on le futur en créole haïtien ?', '["Avec ''te''", "Avec ''ap''", "Avec ''va'' ou ''a''", "Avec ''de''"]'::jsonb, 'Avec ''va'' ou ''a''', 'Le futur en créole haïtien s''exprime avec "va" (forme pleine) ou "a" (forme réduite, enclitique) : "Mwen va manje" ou "Mwen a manje" (Je vais manger). Ces marqueurs précèdent le verbe.', 'Moyen'),
    (chap_id, 'Qu''étudie la morphologie dans une langue ?', '["La structure des phrases", "La formation et la structure des mots", "Les sons de la langue", "Le sens des mots en contexte"]'::jsonb, 'La formation et la structure des mots', 'La morphologie est la branche de la linguistique qui étudie la formation et la structure des mots. Elle s''intéresse à la façon dont les mots sont construits à partir de morphèmes (plus petites unités de sens).', 'Moyen'),
    (chap_id, 'En créole haïtien, comment exprime-t-on la possession ?', '["Avec ''de'' entre possesseur et possédé", "En plaçant le possesseur après le possédé, sans préposition", "Avec ''li'' pour toute possession", "Avec le suffixe -yo"]'::jsonb, 'En plaçant le possesseur après le possédé, sans préposition', 'La possession en créole haïtien s''exprime en plaçant le possesseur directement après le possédé : "liv Pòl" (le livre de Paul), "kay mwen" (ma maison). Cette structure juxtapositive diffère du français qui utilise "de".', 'Difficile'),
    (chap_id, 'Le verbe créole haïtien se conjugue-t-il selon la personne, comme en français ?', '["Oui, avec des terminaisons variables comme en français", "Non, le verbe reste invariable et seuls les marqueurs temporels changent", "Oui, mais seulement pour les 3 premières personnes", "Non, mais l''article du sujet change à la place"]'::jsonb, 'Non, le verbe reste invariable et seuls les marqueurs temporels changent', 'En créole haïtien, le verbe ne se conjugue pas : il reste sous la même forme quelle que soit la personne ou le nombre. C''est le pronom sujet qui indique la personne, et les marqueurs préverbaux (te, ap, va) qui indiquent le temps et l''aspect.', 'Difficile'),
    (chap_id, 'Quelle est la double fonction grammaticale de "yo" en créole haïtien ?', '["Seulement pronom de 3e personne du pluriel", "Seulement marqueur du pluriel des noms", "Pronom de 3e personne du pluriel ET marqueur du pluriel des noms", "Marqueur du passé et du futur"]'::jsonb, 'Pronom de 3e personne du pluriel ET marqueur du pluriel des noms', '"Yo" remplit deux fonctions en créole haïtien : pronom sujet de la 3e personne du pluriel ("Yo manje" = Ils mangent) et marqueur du pluriel des noms ("Timoun yo" = les enfants). C''est une caractéristique importante de la langue.', 'Difficile'),
    (chap_id, 'Quelle préposition créole haïtienne exprime la localisation "dans" ou "en" ?', '["Sou", "Nan", "Devan", "Anba"]'::jsonb, 'Nan', '"Nan" est la préposition créole exprimant "dans" ou "en" : "Mwen nan kay" (Je suis dans la maison), "Mwen nan Ayiti" (Je suis en Haïti). Les autres prépositions : sou (sur), devan (devant), anba (sous).', 'Facile'),
    (chap_id, 'Comment dit-on "comment" (question de manière) en créole haïtien ?', '["Ki kote", "Ki jan", "Kilè", "Ki moun"]'::jsonb, 'Ki jan', '"Ki jan" est l''interrogatif de manière en créole haïtien, équivalent de "comment" en français. Les autres interrogatifs : ki kote (où), kilè (quand), ki moun (qui), kisa (quoi/qu''est-ce que), poukisa (pourquoi).', 'Facile'),
    (chap_id, 'Comment forme-t-on le passé progressif en créole haïtien ?', '["Jis te + verbe", "Te + ap + verbe", "Ap + te + verbe", "Va + ap + verbe"]'::jsonb, 'Te + ap + verbe', 'Le passé progressif ("était en train de") combine "te" (passé) + "ap" (progressif) + le verbe : "Mwen te ap manje lè li rive" (J''étais en train de manger quand il est arrivé). L''ordre est toujours te + ap + verbe.', 'Difficile'),
    (chap_id, 'Qu''étudie la syntaxe dans une langue ?', '["La prononciation des sons", "La structure et l''ordre des mots dans les phrases", "Le sens des mots isolés", "L''écriture et l''orthographe"]'::jsonb, 'La structure et l''ordre des mots dans les phrases', 'La syntaxe est la branche de la linguistique qui étudie comment les mots se combinent pour former des phrases grammaticalement correctes. Elle analyse l''ordre des mots et les relations entre les constituants de la phrase.', 'Moyen'),
    (chap_id, 'En créole haïtien, comment demande-t-on "Qui es-tu ?" ?', '["Kisa ou ye ?", "Ki moun ou ye ?", "Ki jan ou ye ?", "Kilè ou ye ?"]'::jsonb, 'Ki moun ou ye ?', '"Ki moun ou ye ?" signifie littéralement "Quelle personne tu es ?" et s''utilise pour demander l''identité de quelqu''un. "Kisa ou ye ?" demande plutôt "Qu''est-ce que tu es ?" (une fonction ou rôle).', 'Moyen'),
    (chap_id, 'Comment indique-t-on qu''une action est accomplie (résultat persistant) en créole haïtien ?', '["Avec ''fini'' (déjà) devant le verbe", "Avec ''va'' après le verbe", "Avec ''an'' devant le verbe", "Avec le préfixe re-"]'::jsonb, 'Avec ''fini'' (déjà) devant le verbe', 'En créole haïtien, l''aspect accompli s''exprime avec "fini" ou "deja" placé devant ou après le verbe : "Mwen fini manje" (J''ai fini de manger / J''ai déjà mangé). C''est un marqueur d''aspect différent du simple passé "te".', 'Difficile');
  END IF;
END $$;

-- Chapitre 3 : Literati oral ayisyen : pwovèb, kont ak devinen NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 26 AND titre = 'Literati oral ayisyen : pwovèb, kont ak devinen' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Que signifie le proverbe créole haïtien "Konstitisyon se papye, bayonet se fè" ?', '["La constitution est plus forte que les armes", "La constitution écrite n''a pas de valeur face à la force des armes", "Les lois doivent être protégées par l''armée", "La démocratie est supérieure à la dictature"]'::jsonb, 'La constitution écrite n''a pas de valeur face à la force des armes', 'Ce célèbre proverbe haïtien attribué à Duvalier père signifie que le pouvoir réel ne se trouve pas dans les lois écrites mais dans la force militaire. Il illustre le cynisme politique de certaines élites face aux institutions démocratiques.', 'Difficile'),
    (chap_id, 'Quelle est la formule traditionnelle qui ouvre un conte haïtien (kont) ?', '["Il était une fois...", "Krik... Krak !", "Pran sa, ban mwen sa", "Tim Tim... Bwa sèch !"]'::jsonb, 'Krik... Krak !', 'En Haïti, les contes (kont) s''ouvrent par un dialogue rituel : le conteur dit "Krik !" et l''audience répond "Krak !". Cette formule d''appel-réponse établit un contrat entre le conteur et ses auditeurs et crée un espace sacré pour le récit.', 'Facile'),
    (chap_id, 'Que signifie le mot "devinen" dans la littérature orale haïtienne ?', '["Un conte populaire", "Une charade ou devinette", "Un proverbe", "Une chanson traditionnelle"]'::jsonb, 'Une charade ou devinette', '"Devinen" désigne les devinettes ou charades dans la tradition orale haïtienne. Elles commencent souvent par "Tim Tim !" (le poseur de devinette) suivi de "Bwa sèch !" (la réponse de l''audience), avant que la devinette soit posée.', 'Facile'),
    (chap_id, 'Que signifie le proverbe haïtien "Deye mòn gen mòn" ?', '["Les montagnes sont des obstacles insurmontables", "Au-delà des montagnes, il y a d''autres montagnes (les difficultés n''ont pas de fin)", "Les montagnes appartiennent à ceux qui les gravissent", "Il faut fuir les montagnes pour réussir"]'::jsonb, 'Au-delà des montagnes, il y a d''autres montagnes (les difficultés n''ont pas de fin)', '"Deye mòn gen mòn" (Derrière la montagne il y a une montagne) est le proverbe national haïtien. Il signifie que les difficultés de la vie se succèdent sans fin, et invite à la persévérance. C''est aussi une description du relief montagneux d''Haïti.', 'Moyen'),
    (chap_id, 'Quel rôle social jouent les proverbes (pwovèb) dans la culture haïtienne ?', '["Seulement divertir les enfants", "Transmettre la sagesse collective, enseigner des valeurs et commenter les comportements sociaux", "Servir uniquement dans les cérémonies religieuses", "Remplacer les lois écrites"]'::jsonb, 'Transmettre la sagesse collective, enseigner des valeurs et commenter les comportements sociaux', 'Les proverbes haïtiens jouent un rôle fondamental dans la transmission de la sagesse collective, l''éducation morale, et le commentaire social. Ils condensent des expériences multigénérationnelles et sont utilisés dans les conversations courantes pour illustrer des points ou donner des conseils.', 'Moyen'),
    (chap_id, 'Dans quel contexte traditionnel les contes haïtiens (kont) étaient-ils principalement racontés ?', '["Le matin, avant de partir aux champs", "Le soir, après le coucher du soleil, en famille ou en communauté", "Pendant les marchés publics", "Dans les églises le dimanche"]'::jsonb, 'Le soir, après le coucher du soleil, en famille ou en communauté', 'Traditionnellement, les kont haïtiens se racontent la nuit, après le coucher du soleil, dans un cadre familial ou communautaire. Il existe une croyance populaire selon laquelle raconter des contes le jour porterait malheur.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "griyo" ou griot dans la tradition orale haïtienne ?', '["Un plat de viande de porc", "Un musicien traditionnel haïtien", "Un gardien de la mémoire collective et des traditions orales", "Un type de proverbe court"]'::jsonb, 'Un gardien de la mémoire collective et des traditions orales', 'Dans la tradition africaine et haïtienne, le griot est un gardien de la mémoire collective. Il préserve et transmet les histoires, généalogies et sagesses communautaires. La tradition griote est une des sources de la littérature orale haïtienne.', 'Difficile'),
    (chap_id, 'Quel personnage trickster (rusé) est le héros récurrent des contes haïtiens, incarnant l''intelligence des opprimés ?', '["Bouki", "Malice (Ti Malice)", "Basile", "Zamba"]'::jsonb, 'Malice (Ti Malice)', 'Ti Malice est le personnage trickster des contes haïtiens, toujours en opposition avec le naïf Bouki. Il représente l''intelligence et la ruse comme armes des faibles contre les puissants, une tradition héritée des contes africains (Anansi l''araignée, Lièvre rusé).', 'Moyen'),
    (chap_id, 'Quel personnage naïf et souvent dupé est le partenaire de Ti Malice dans les contes haïtiens ?', '["Basile", "Zamba", "Bouki", "Figuier"]'::jsonb, 'Bouki', 'Bouki est le personnage naïf et souvent dupé dans les contes haïtiens, toujours en opposition avec le rusé Ti Malice. Ces deux personnages forment une paire comique et didactique qui illustre la victoire de l''intelligence sur la force et la sottise.', 'Facile'),
    (chap_id, 'Que signifie le proverbe haïtien "Men anpil, chay pa lou" ?', '["Une main d''œuvre nombreuse est mal payée", "À plusieurs, le fardeau est léger (l''union fait la force)", "Les mains ne mentent jamais", "Le travail manuel est le plus noble"]'::jsonb, 'À plusieurs, le fardeau est léger (l''union fait la force)', '"Men anpil, chay pa lou" (Beaucoup de mains, la charge n''est pas lourde) exprime l''importance de la solidarité et du travail collectif. Il correspond à l''adage français "L''union fait la force" et est lié à la tradition du "konbit" (travail collectif haïtien).', 'Moyen'),
    (chap_id, 'Quelle est la principale différence entre la littérature orale et la littérature écrite ?', '["La littérature orale n''a aucune valeur artistique", "La littérature orale est transmise de génération en génération par la parole, sans support écrit", "La littérature écrite est toujours plus complexe", "La littérature orale n''existe qu''en créole"]'::jsonb, 'La littérature orale est transmise de génération en génération par la parole, sans support écrit', 'La littérature orale se transmet par la parole, de génération en génération, sans nécessairement passer par l''écriture. Elle comprend les contes, légendes, proverbes, devinettes, chants et épopées. Elle est vivante, évolutive et adaptée au contexte de la performance.', 'Facile'),
    (chap_id, 'Que signifie le proverbe haïtien "Bouche vann, zorèy achte" ?', '["Les vendeurs sont toujours malhonnêtes", "Ce qui se dit trouve toujours des oreilles (les paroles se répandent)", "Le commerce enrichit ceux qui savent écouter", "Les rumeurs ne sont que du vent"]'::jsonb, 'Ce qui se dit trouve toujours des oreilles (les paroles se répandent)', '"Bouche vann, zorèy achte" (La bouche vend, les oreilles achètent) signifie que les paroles se répandent inévitablement, qu''il faut faire attention à ce que l''on dit car quelqu''un l''entendra toujours. C''est un avertissement contre les commérages et les confidences imprudentes.', 'Difficile'),
    (chap_id, 'Quel est l''équivalent haïtien du "konbit" dans la tradition du travail collectif ?', '["Une fête religieuse communautaire", "Un système traditionnel d''entraide pour les travaux agricoles", "Une institution bancaire coopérative", "Un rassemblement politique"]'::jsonb, 'Un système traditionnel d''entraide pour les travaux agricoles', 'Le "konbit" est le système traditionnel haïtien d''entraide collective pour les travaux agricoles, où les membres d''une communauté se réunissent pour aider l''un d''eux. Cette pratique est célébrée dans de nombreux proverbes et chants traditionnels haïtiens.', 'Moyen'),
    (chap_id, 'Les devinettes haïtiennes (devinen) s''ouvrent généralement par quelle formule rituelle ?', '["Krik ! Krak !", "Tim Tim ! Bwa sèch !", "Ayen ayen ! Bagay la !", "Misye ! Madann !"]'::jsonb, 'Tim Tim ! Bwa sèch !', 'Les devinettes haïtiennes s''ouvrent par "Tim Tim !" (lancé par celui qui pose la devinette) et "Bwa sèch !" (répondu par l''audience), créant un rituel d''appel-réponse qui prépare l''esprit à la résolution du problème posé.', 'Facile'),
    (chap_id, 'Que représentent généralement les personnages animaux dans les contes haïtiens ?', '["Des animaux réels des forêts haïtiennes", "Des types humains ou forces sociales symboliques (la ruse, la force, la naïveté)", "Des dieux africains transformés", "Des ancêtres héroïques"]'::jsonb, 'Des types humains ou forces sociales symboliques (la ruse, la force, la naïveté)', 'Dans les contes haïtiens, les animaux incarnent des traits humains ou des forces sociales : le lapin ou l''araignée symbolisent la ruse des faibles, le lion la puissance des dominants, etc. Ces personnages permettent de traiter des sujets sociaux de façon détournée et souvent humoristique.', 'Moyen'),
    (chap_id, 'Quel est le rôle éducatif des proverbes haïtiens dans la formation des jeunes ?', '["Ils enseignent uniquement la langue créole écrite", "Ils transmettent les valeurs morales, sociales et pratiques d''une génération à l''autre", "Ils servent uniquement à divertir lors des fêtes", "Ils remplacent l''enseignement scolaire formel"]'::jsonb, 'Ils transmettent les valeurs morales, sociales et pratiques d''une génération à l''autre', 'Les proverbes jouent un rôle pédagogique central dans la culture haïtienne : ils transmettent des valeurs comme le travail, la solidarité, la prudence, le respect des aînés, et commentent les réalités sociales. Ils constituent une "école de la vie" informelle et efficace.', 'Moyen'),
    (chap_id, 'Que signifie le proverbe haïtien "Ravèt pa janm gen rezon devan poul" ?', '["Les cafards sont plus forts que les poules", "Les faibles n''ont jamais raison face aux puissants (la loi du plus fort)", "Les animaux vivent en harmonie dans la nature", "Il faut protéger les petits animaux"]'::jsonb, 'Les faibles n''ont jamais raison face aux puissants (la loi du plus fort)', '"Ravèt pa janm gen rezon devan poul" (Le cafard n''a jamais raison devant la poule) illustre l''inégalité des rapports de force : dans les conflits, c''est souvent le plus puissant qui a "raison". Ce proverbe critique avec ironie la justice des forts.', 'Difficile'),
    (chap_id, 'Quelle pratique artistique et sociale illustre le mieux la tradition de la littérature orale dans les cérémonies vodou haïtiennes ?', '["La peinture naïve", "Les chants rituels (chante lwà), récits mythiques et proverbes des cérémonies vodou", "La sculpture en bois", "La décoration des drapo (drapeaux) vodou"]'::jsonb, 'Les chants rituels (chante lwà), récits mythiques et proverbes des cérémonies vodou', 'Les cérémonies vodou sont un lieu privilégié de la littérature orale haïtienne : les "chante lwà" (chants rituels), les récits des mythes des lwa (esprits), les formules et proverbes constituent un corpus oral riche qui préserve une mémoire africaine et haïtienne profonde.', 'Difficile');
  END IF;
END $$;

-- Chapitre 4 : Lekti ak analiz tèks kreyòl : Frankétienne ak lòt NS2
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 26 AND titre = 'Lekti ak analiz tèks kreyòl : Frankétienne ak lòt' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le titre du premier roman écrit entièrement en créole haïtien, publié en 1975 ?', '["Mur à midi", "Gouverneurs de la rosée", "Dezafi", "Ultravocal"]'::jsonb, 'Dezafi', '"Dezafi" (1975) de Frankétienne (Frank Étienne) est le premier roman haïtien écrit entièrement en créole haïtien. Ce roman spiraliste marque un tournant dans la littérature haïtienne en affirmant le statut de langue littéraire du créole.', 'Moyen'),
    (chap_id, 'Qui est l''auteur du premier roman en créole haïtien "Dezafi" (1975) ?', '["Jacques Roumain", "René Depestre", "Frankétienne (Frank Étienne)", "Dany Laferrière"]'::jsonb, 'Frankétienne (Frank Étienne)', 'Frankétienne, de son vrai nom Frank Étienne (né en 1936), est le père du spiralisme haïtien et l''auteur de "Dezafi" (1975), premier roman haïtien en créole. Il est considéré comme l''un des plus grands écrivains haïtiens vivants.', 'Facile'),
    (chap_id, 'Qu''est-ce que le "spiralisme" dans la littérature haïtienne dont Frankétienne est le représentant majeur ?', '["Un mouvement qui prône l''usage exclusif du créole dans la littérature", "Un mouvement artistique utilisant des structures en spirale (répétition, fragmentation, polyphonie) pour rendre le chaos de l''existence haïtienne", "Un mouvement politique de résistance à la dictature Duvalier", "Un style poétique inspiré des formes africaines traditionnelles"]'::jsonb, 'Un mouvement artistique utilisant des structures en spirale (répétition, fragmentation, polyphonie) pour rendre le chaos de l''existence haïtienne', 'Le spiralisme, fondé par Frankétienne avec Jean-Claude Fignolé et René Philoctète, utilise des structures narratives en spirale : répétitions, fragmentations, polyphonie et ruptures de chronologie pour rendre l''expérience chaotique de la vie haïtienne sous la dictature et au-delà.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''analyse textuelle d''un texte littéraire cherche principalement à faire ?', '["Résumer l''histoire racontée", "Identifier les éléments stylistiques, thématiques et narratifs pour comprendre le sens profond du texte", "Traduire le texte en français standard", "Compter les mots et les phrases"]'::jsonb, 'Identifier les éléments stylistiques, thématiques et narratifs pour comprendre le sens profond du texte', 'L''analyse textuelle vise à décomposer un texte littéraire pour en comprendre le sens profond : elle s''intéresse au style de l''auteur (figures de style, rythme), aux thèmes traités, à la structure narrative, aux personnages et au contexte de production.', 'Moyen'),
    (chap_id, 'Quel grand écrivain haïtien a écrit "Gouverneurs de la rosée" (1944), roman en français sur la vie paysanne haïtienne ?', '["Frankétienne", "Jacques Roumain", "René Depestre", "Marie Vieux-Chauvet"]'::jsonb, 'Jacques Roumain', '"Gouverneurs de la rosée" (1944) est le chef-d''œuvre de Jacques Roumain (1907-1944), fondateur du Parti Communiste Haïtien. Ce roman en français, traduit dans de nombreuses langues, célèbre la culture paysanne haïtienne et le créole y joue un rôle fondamental même si le roman est écrit en français.', 'Moyen'),
    (chap_id, 'Quelle est la signification du titre "Dezafi" de Frankétienne ?', '["Une menace", "Un défi", "Un espoir", "Une prière"]'::jsonb, 'Un défi', '"Dezafi" signifie "défi" en créole haïtien. Le roman représentait lui-même un défi lancé à l''ordre littéraire et linguistique haïtien en affirmant que le créole pouvait être une langue littéraire à part entière, capable d''accueillir une œuvre romanesque complexe.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une "figure de style" dans l''analyse d''un texte littéraire ?', '["Une illustration ou image dans le texte", "Un procédé stylistique particulier qui enrichit l''expression (métaphore, comparaison, anaphore, etc.)", "Un personnage secondaire du récit", "Un paragraphe de transition"]'::jsonb, 'Un procédé stylistique particulier qui enrichit l''expression (métaphore, comparaison, anaphore, etc.)', 'Une figure de style est un procédé d''expression particulier qui modifie la langue ordinaire pour produire un effet stylistique : métaphore (comparaison implicite), comparaison, anaphore (répétition en début de phrase), hyperbole (exagération), personnification, etc.', 'Moyen'),
    (chap_id, 'Dans "Dezafi", le créole haïtien de Frankétienne est décrit comme quel type de langue littéraire ?', '["Simple et accessible à tous les niveaux de lecture", "Riche, inventif, dense et expérimental, refusant la simplification", "Proche du créole oral quotidien sans élaboration stylistique", "Mélangé de français pour faciliter la compréhension"]'::jsonb, 'Riche, inventif, dense et expérimental, refusant la simplification', 'Dans "Dezafi", Frankétienne utilise un créole haïtien littéraire riche, inventif et dense, exploitant toutes les ressources de la langue créole : néologismes, jeux de mots, images poétiques, structures répétitives. C''est une démonstration de la richesse expressive du créole.', 'Difficile'),
    (chap_id, 'Quel genre littéraire est "Dezafi" de Frankétienne ?', '["Un recueil de poèmes", "Un roman", "Une pièce de théâtre", "Un essai philosophique"]'::jsonb, 'Un roman', '"Dezafi" (1975) est un roman, plus précisément un roman spiraliste. Il raconte l''histoire d''un village haïtien sous l''emprise d''un chef de bande (zombie métaphorique du pouvoir dictatorial), traitant des thèmes de l''oppression et de la résistance.', 'Facile'),
    (chap_id, 'Qu''est-ce que le "narrateur" dans un texte littéraire ?', '["L''auteur réel du texte", "La voix qui raconte l''histoire dans un texte narratif, pouvant être un personnage ou une voix extérieure", "Le personnage principal du roman", "Le lecteur qui interprète le texte"]'::jsonb, 'La voix qui raconte l''histoire dans un texte narratif, pouvant être un personnage ou une voix extérieure', 'Le narrateur est la voix qui prend en charge le récit dans un texte narratif. Il peut être interne à l''histoire (narrateur à la 1ère personne, personnage) ou externe (narrateur omniscient à la 3e personne). Il ne faut pas confondre le narrateur et l''auteur réel.', 'Moyen'),
    (chap_id, 'Quel thème central "Dezafi" de Frankétienne aborde-t-il à travers la métaphore du zombie ?', '["La beauté de la nature haïtienne", "L''oppression politique et la déshumanisation sous la dictature", "L''amour romantique impossible", "La modernisation économique d''Haïti"]'::jsonb, 'L''oppression politique et la déshumanisation sous la dictature', '"Dezafi" utilise le mythe haïtien du zombie comme métaphore de la déshumanisation par le pouvoir dictatorial duvalièrien : les zombies du roman représentent les Haïtiens privés de leur volonté et de leur humanité par un régime oppressif.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une "métaphore" dans l''analyse littéraire ?', '["Une comparaison explicite utilisant ''comme'' ou ''tel''", "Une figure de style qui identifie implicitement deux réalités sans outil comparatif", "Un retour en arrière dans la narration", "Une description détaillée d''un lieu"]'::jsonb, 'Une figure de style qui identifie implicitement deux réalités sans outil comparatif', 'La métaphore est une figure de style qui établit une identification implicite entre deux réalités : "La vie est un voyage" (pas "La vie est comme un voyage", qui serait une comparaison). Elle crée une image poétique plus forte et immédiate que la comparaison.', 'Moyen'),
    (chap_id, 'Quel est le rôle de la langue créole dans l''identité culturelle haïtienne selon les écrivains créolistes ?', '["La langue créole est un obstacle au développement d''Haïti", "La langue créole est le vecteur essentiel de l''identité culturelle haïtienne et doit être valorisée littérairement", "La langue créole doit être remplacée par le français dans tous les domaines", "La langue créole n''a pas de valeur littéraire"]'::jsonb, 'La langue créole est le vecteur essentiel de l''identité culturelle haïtienne et doit être valorisée littérairement', 'Les écrivains créolistes haïtiens (Frankétienne et d''autres) défendent que le créole, langue de tous les Haïtiens, est le vecteur authentique de l''identité nationale haïtienne. Sa valorisation littéraire est un acte politique et culturel de réappropriation identitaire.', 'Moyen'),
    (chap_id, 'En analyse de texte, qu''est-ce que le "champ lexical" ?', '["L''ensemble du vocabulaire difficile d''un texte", "L''ensemble des mots se rapportant à un même thème dans un texte", "La liste des personnages du récit", "Les notes et références au bas de la page"]'::jsonb, 'L''ensemble des mots se rapportant à un même thème dans un texte', 'Le champ lexical est l''ensemble des mots (noms, verbes, adjectifs, expressions) qui se rapportent à un même thème ou domaine sémantique dans un texte. Identifier les champs lexicaux dominants permet de cerner les thèmes principaux de l''œuvre.', 'Moyen'),
    (chap_id, 'Quel autre grand auteur haïtien contemporain de Frankétienne est connu pour ses romans écrits partiellement en créole et en français ?', '["Dany Laferrière", "Jean-Claude Fignolé", "Émile Ollivier", "Kettly Mars"]'::jsonb, 'Jean-Claude Fignolé', 'Jean-Claude Fignolé, co-fondateur du spiralisme avec Frankétienne et René Philoctète, a produit des œuvres expérimentales mêlant créole et français. Il est l''auteur de "Les Possédés de la Pleine Lune" (1987), roman spiraliste fondamental.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "diglossie" dans le contexte linguistique haïtien ?', '["Un trouble du langage", "La coexistence de deux langues (créole et français) avec des statuts et fonctions sociales différenciés", "L''utilisation exclusive du créole dans l''éducation", "Une forme de traduction simultanée"]'::jsonb, 'La coexistence de deux langues (créole et français) avec des statuts et fonctions sociales différenciés', 'La diglossie décrit la situation haïtienne où deux langues coexistent avec des statuts inégaux : le français, langue "haute" réservée aux contextes formels, éducatifs et officiels ; le créole, langue "basse" mais parlée par tous. Cette inégalité est un enjeu majeur de la politique linguistique haïtienne.', 'Difficile'),
    (chap_id, 'Que cherche à dénoncer la littérature haïtienne en créole de la période post-1986 ?', '["La beauté perdue du paysage haïtien", "Les inégalités sociales, l''exclusion linguistique des créolophones et la recherche d''une identité nationale authentique", "L''influence négative de la diaspora haïtienne", "Le manque de développement économique"]'::jsonb, 'Les inégalités sociales, l''exclusion linguistique des créolophones et la recherche d''une identité nationale authentique', 'Après la chute de Duvalier en 1986, la littérature haïtienne en créole s''engage dans une quête identitaire : elle dénonce l''exclusion des créolophones de la vie culturelle et éducative, les inégalités sociales et cherche à définir une identité nationale fondée sur la culture populaire créole.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "narration à la première personne" dans un texte littéraire ?', '["Un texte écrit par l''auteur lui-même sous son vrai nom", "Un récit où le narrateur-personnage utilise ''je/mwen'' pour raconter l''histoire de l''intérieur", "Un texte traduit littéralement du créole au français", "Un type de poème lyrique"]'::jsonb, 'Un récit où le narrateur-personnage utilise ''je/mwen'' pour raconter l''histoire de l''intérieur', 'La narration à la première personne (''je'' en français, ''mwen'' en créole) signifie que le narrateur est un personnage interne à l''histoire. Ce choix crée une proximité avec le lecteur mais limite la vision aux seules perceptions de ce personnage.', 'Moyen');
  END IF;
END $$;
