-- Supplément Créole NS3-NS4 (matiere_id=26) — +18 questions/chapitre pour atteindre 20 minimum

-- Chapitre 1 : Analiz diskoutif : agimantasyon ak debat an kreyòl NS3
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 26 AND titre = 'Analiz diskoutif : agimantasyon ak debat an kreyòl' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''un "discours argumentatif" ?', '["Un texte qui raconte une histoire", "Un texte qui vise à convaincre le", "Un texte qui décrit un lieu ou une personne", "Un texte qui explique un phénomène scientifique"]'::jsonb, 'Un texte qui vise à convaincre le', 'Le discours argumentatif cherche à convaincre : il présente une thèse (position défendue), des arguments (raisons de la soutenir), des exemples (illustrations concrètes) et une réfutation possible des contre-arguments. C''est la base du débat et de la rhétorique.', 'Facile'),
    (chap_id, 'Dans un texte argumentatif, qu''est-ce que la "thèse" ?', '["L''ensemble des exemples utilisés", "La position ou l''affirmation principale", "La conclusion finale du texte", "Les citations d''autres auteurs"]'::jsonb, 'La position ou l''affirmation principale', 'La thèse est la position centrale d''un texte argumentatif : c''est l''idée principale que l''auteur veut faire accepter au lecteur. Tous les arguments, exemples et raisonnements du texte servent à étayer (soutenir) cette thèse.', 'Facile'),
    (chap_id, 'Quelle est la différence entre un "argument" et un "exemple" dans une argumentation ?', '["Il n''y a aucune différence", "Un argument est une raison générale qui", "Un argument est toujours chiffré ; un exemple ne l''est jamais", "Un exemple est plus convaincant qu''un argument"]'::jsonb, 'Un argument est une raison générale qui', 'Dans une argumentation, l''argument fournit une raison générale ou logique de soutenir la thèse, tandis que l''exemple l''illustre avec un cas concret, réel ou fictif. L''argument convainc par la logique, l''exemple rend l''argument tangible et mémorable.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une "antithèse" dans un débat ou texte argumentatif ?', '["La répétition de la thèse principale", "La position contraire à la thèse", "La conclusion du débat", "Une figure de style poétique"]'::jsonb, 'La position contraire à la thèse', 'L''antithèse (ou contre-argument) est la position adverse à la thèse défendue. Dans un débat ou texte argumentatif bien construit, l''auteur doit reconnaître les antithèses possibles pour les réfuter ou les nuancer, ce qui renforce la crédibilité de son argumentation.', 'Moyen'),
    (chap_id, 'Dans un débat formel en créole haïtien, quelle expression utilise-t-on pour prendre la parole poliment ?', '["Kite m pale", "Mwen ta renmen di", "Bouch mwen ouvri", "Pale pou ou"]'::jsonb, 'Mwen ta renmen di', 'Dans un contexte formel ou semi-formel en créole haïtien, "Mwen ta renmen di" (Je voudrais dire) est une formule polie pour demander la parole et introduire son point de vue. Le conditionnel "ta" marque la politesse.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "connecteur logique" dans un texte argumentatif ?', '["Un mot qui désigne une chose concrète", "Un mot ou expression qui organise les", "Un nom propre de personne ou de lieu", "Un adjectif qualificatif"]'::jsonb, 'Un mot ou expression qui organise les', 'Les connecteurs logiques (poutèt sa = donc, paske = parce que, men = mais, epitou = de plus, sepandan = cependant) organisent la progression des idées et marquent les relations logiques entre elles : cause, conséquence, opposition, addition, concession.', 'Moyen'),
    (chap_id, 'Comment dit-on "cependant" ou "mais" (pour marquer une opposition) en créole haïtien ?', '["Epitou", "Donk", "Men / Sepandan", "Poukisa"]'::jsonb, 'Men / Sepandan', '"Men" (mais) et "Sepandan" (cependant) sont les connecteurs d''opposition en créole haïtien. "Epitou" signifie "de plus/et aussi" (addition), "Donk" signifie "donc" (conséquence), "Poukisa" signifie "pourquoi" (question).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "rhétorique" en argumentation ?', '["L''art de la calligraphie créole", "L''art de bien s''exprimer et de", "L''étude des sons de la langue", "La grammaire normative du créole"]'::jsonb, 'L''art de bien s''exprimer et de', 'La rhétorique est l''art de la persuasion par le discours. Elle inclut le choix des mots, l''organisation des arguments, les figures de style, le ton et la relation à l''auditoire. Dans les débats, la maîtrise de la rhétorique est déterminante pour convaincre.', 'Difficile'),
    (chap_id, 'Dans un débat, qu''est-ce que "réfuter un argument" signifie ?', '["Accepter entièrement l''argument de l''adversaire", "Démontrer qu''un argument de", "Répéter l''argument pour mieux le comprendre", "Changer de sujet"]'::jsonb, 'Démontrer qu''un argument de', 'Réfuter un argument consiste à montrer qu''il est faux (en apportant des preuves contraires), logiquement insuffisant (non-sequitur), ou non pertinent par rapport à la question débattue. La réfutation est une compétence essentielle dans tout débat structuré.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "sophisme" dans une argumentation ?', '["Un argument particulièrement solide et irréfutable", "Un raisonnement qui semble valide mais", "Une conclusion provisoire", "Un exemple tiré de l''histoire haïtienne"]'::jsonb, 'Un raisonnement qui semble valide mais', 'Un sophisme est un raisonnement formellement incorrect mais qui paraît convaincant. Par exemple, l''argument "ad hominem" (attaquer la personne plutôt que ses idées) ou la fausse généralisation ("tous les X font Y"). Reconnaître les sophismes est crucial dans l''analyse des discours.', 'Difficile'),
    (chap_id, 'Comment commence-t-on une argumentation structurée en créole haïtien ?', '["\"Nan lide mwen...\" (À mon avis...)", "Bonjou tout moun", "Pwoblem nan se...", "Mwen paka dakò"]'::jsonb, '"Nan lide mwen..." (À mon avis...)', 'En créole haïtien, une argumentation structurée peut commencer par "Nan lide mwen..." (À mon avis), "Dapre mwen..." (Selon moi) ou "Pozisyon mwen se ke..." (Ma position est que...) pour clairement énoncer la thèse que l''on va défendre.', 'Moyen'),
    (chap_id, 'Quelle est la structure classique d''un discours argumentatif bien organisé ?', '["Introduction - Développement - Conclusion", "Thèse - Antithèse - Synthèse", "Situation - Complication - Résolution", "Présentation - Arguments - Exemples - Fin"]'::jsonb, 'Thèse - Antithèse - Synthèse', 'La structure dialectique classique d''un discours argumentatif est : Thèse (position défendue) - Antithèse (positions adverses reconnues et réfutées) - Synthèse (conclusion nuancée intégrant les points valables des deux côtés). C''est la forme la plus rigoureuse de l''argumentation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''"ethos" dans la rhétorique classique (adapté aux débats en créole) ?', '["L''appel aux émotions du public", "La crédibilité et le caractère moral de", "Les preuves logiques et factuelles avancées", "La conclusion persuasive du discours"]'::jsonb, 'La crédibilité et le caractère moral de', 'Dans la rhétorique classique (Aristote), l''ethos désigne la crédibilité et l''autorité morale de l''orateur. Un orateur crédible, connu pour son honnêteté et sa compétence, sera plus convaincant. Dans les débats haïtiens, la réputation et la légitimité de celui qui parle influencent son impact.', 'Difficile'),
    (chap_id, 'Comment appelle-t-on la technique argumentative qui consiste à anticiper les objections de l''adversaire pour les réfuter d''avance ?', '["La prolepse ou procatalepse", "L''anaphore", "La synecdoque", "L''hyperbole"]'::jsonb, 'La prolepse ou procatalepse', 'La prolepse (ou procatalepse) est la technique qui consiste à anticiper et à réfuter les objections possibles avant qu''elles ne soient soulevées : "On pourrait objecter que... cependant...". Elle renforce la crédibilité de l''argumentation et montre que l''auteur a considéré tous les angles.', 'Difficile'),
    (chap_id, 'Dans un débat, que signifie "écouter activement" l''adversaire ?', '["Attendre silencieusement que l''adversaire finisse de parler", "Écouter avec attention", "Interrompre l''adversaire dès qu''on est en désaccord", "Prendre des notes sur tout ce qui est dit sans réfléchir"]'::jsonb, 'Écouter avec attention', 'L''écoute active dans un débat consiste à écouter attentivement l''adversaire, identifier ses arguments clés, ses points faibles et ses présupposés, pour construire une réponse ciblée et pertinente. C''est une compétence indispensable dans tout débat académique ou public.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre "convaincre" et "persuader" dans un discours ?', '["Il n''y a aucune différence", "Convaincre fait appel à la raison et", "Persuader est toujours malhonnête ; convaincre est toujours honnête", "Convaincre s''adresse à un groupe ; persuader s''adresse à un individu"]'::jsonb, 'Convaincre fait appel à la raison et', 'Convaincre (utilisant le logos et l''ethos) fait appel à la raison : arguments logiques, preuves, faits. Persuader (utilisant le pathos) fait appel aux émotions : sentiments, valeurs, désirs de l''auditoire. Un bon orateur combine les deux stratégies pour maximiser son efficacité.', 'Difficile'),
    (chap_id, 'Quel connecteur logique créole exprime la conséquence ou la conclusion ?', '["Men", "Epitou", "Donk / Se poutèt sa", "Malgre"]'::jsonb, 'Donk / Se poutèt sa', '"Donk" (donc) et "Se poutèt sa" (c''est pour cela que / par conséquent) expriment la conséquence logique en créole haïtien. "Men" exprime l''opposition, "Epitou" l''addition, "Malgre" la concession.', 'Moyen'),
    (chap_id, 'Pourquoi l''argumentation en créole haïtien est-elle un enjeu politique et social important en Haïti ?', '["Le créole est plus facile à argumenter que le français", "Parce que l''exclusion des créolophones", "Parce que le créole est la seule langue d''Haïti", "Parce que le créole est plus précis que le français pour les questions politiques"]'::jsonb, 'Parce que l''exclusion des créolophones', 'En Haïti, les débats publics formels se tiennent traditionnellement en français, excluant de facto la majorité créolophone. Développer l''argumentation en créole est un acte de démocratisation qui permet à tous les citoyens de participer aux délibérations publiques, réduisant ainsi les inégalités d''accès au discours.', 'Difficile');
  END IF;
END $$;

-- Chapitre 2 : Politique lingwistik ak kreyòl nan monn kontemporèn NS4
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 26 AND titre = 'Politique lingwistik ak kreyòl nan monn kontemporèn' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une "politique linguistique" ?', '["L''étude de la grammaire d''une langue officielle", "L''ensemble des décisions et mesures", "Une langue utilisée exclusivement dans la politique", "L''interdiction d''utiliser certaines langues"]'::jsonb, 'L''ensemble des décisions et mesures', 'Une politique linguistique englobe toutes les décisions relatives aux langues dans une société : choix des langues officielles, langues d''enseignement, financement des langues minoritaires, normalisation orthographique, etc. En Haïti, la politique linguistique concerne le rapport entre le créole et le français.', 'Facile'),
    (chap_id, 'Qu''est-ce que la "diglossie" dans le contexte sociolinguistique haïtien ?', '["Un trouble de la parole", "La situation où deux langues coexistent", "L''utilisation alternée de deux langues dans la même phrase", "La politique d''enseignement bilingue"]'::jsonb, 'La situation où deux langues coexistent', 'La diglossie haïtienne décrit la coexistence du français (langue "haute" : prestige, administration, éducation formelle) et du créole (langue "basse" : usage quotidien, famille, marchés). Cette hiérarchie linguistique reflète et perpétue des inégalités sociales profondes.', 'Moyen'),
    (chap_id, 'Quel est le principal défi de la politique éducative haïtienne en matière linguistique ?', '["Éliminer complètement le français du système éducatif", "Réaliser une transition vers un", "Imposer l''anglais comme langue d''enseignement", "Maintenir le statu quo avec le français comme seule langue d''instruction"]'::jsonb, 'Réaliser une transition vers un', 'Le défi majeur est la mise en œuvre d''un véritable enseignement bilingue : si la Constitution de 1987 reconnaît le créole comme langue officielle et d''enseignement, la réalité montre que le système éducatif reste dominé par le français, au détriment des enfants monolingues créoles.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "code-switching" (chanjman kòd) en sociolinguistique ?', '["Une erreur grammaticale commise par des bilingues", "L''alternance volontaire entre deux", "Un type de traduction littérale du créole au français", "Un dialecte mixte français-créole"]'::jsonb, 'L''alternance volontaire entre deux', 'Le code-switching (chanjman kòd) est le passage d''une langue à l''autre dans une conversation. En Haïti, les bilingues alternent fréquemment entre créole et français. Ce phénomène n''est pas un manque de maîtrise mais une compétence communicative qui répond à des besoins sociaux et identitaires.', 'Moyen'),
    (chap_id, 'Quelle organisation internationale a reconnu le droit des langues autochtones et des langues régionales comme le créole haïtien ?', '["La Banque Mondiale", "L''ONU et l''UNESCO", "L''Organisation des États Américains (OEA)", "L''OTAN"]'::jsonb, 'L''ONU et l''UNESCO', 'L''UNESCO et l''ONU ont adopté des textes reconnaissant les droits linguistiques des communautés, notamment le droit à l''éducation dans sa langue maternelle. La Déclaration universelle des droits linguistiques (1996) affirme le droit de chaque peuple à utiliser sa langue dans tous les domaines.', 'Moyen'),
    (chap_id, 'Que signifie la "glottophagie" ou "linguicide" dans le contexte des politiques linguistiques mondiales ?', '["La promotion et le soutien aux langues minoritaires", "L''élimination progressive d''une langue", "L''étude scientifique de la disparition des langues", "La traduction de textes sacrés en langues locales"]'::jsonb, 'L''élimination progressive d''une langue', 'La glottophagie (terme du sociolinguiste Louis-Jean Calvet) désigne le processus par lequel une langue dominante (ex. le français colonial) "mange" et fait disparaître progressivement les langues dominées. Le créole haïtien a été historiquement menacé par la glottophagie du français.', 'Difficile'),
    (chap_id, 'Quelle est la situation du créole haïtien dans la diaspora haïtienne aux États-Unis ?', '["Le créole disparaît complètement dès la première génération d''immigrants", "Le créole est maintenu comme langue", "Le créole est interdit aux États-Unis", "Le créole est devenu une langue officielle dans certains États américains"]'::jsonb, 'Le créole est maintenu comme langue', 'Dans la diaspora haïtienne aux États-Unis (Floride, New York), le créole haïtien est fortement maintenu comme langue d''identité communautaire. Cependant, il incorpore de nombreux anglicismes et les locuteurs pratiquent intensément le code-switching créole-anglais, créant un parler diasporal spécifique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "normalisation linguistique" d''une langue ?', '["L''interdiction des variantes et dialectes régionaux", "Le processus d''établissement de règles", "La traduction d''une langue vers une autre", "La simplification extrême d''une langue pour la rendre accessible"]'::jsonb, 'Le processus d''établissement de règles', 'La normalisation établit des normes officielles pour une langue : orthographe standardisée, règles grammaticales codifiées, lexique de référence. Pour le créole haïtien, le décret de 1979 (orthographe IPN) et la création de l''Akademi Kreyòl Ayisyen (2014) sont des étapes de normalisation.', 'Difficile'),
    (chap_id, 'Pourquoi certains linguistes et éducateurs haïtiens militent-ils pour l''enseignement en créole dès l''école primaire ?', '["Parce que le français est une langue trop difficile pour les enfants haïtiens", "Parce que les recherches en", "Parce que le créole est plus riche que le français", "Parce que cela est obligatoire selon les lois internationales"]'::jsonb, 'Parce que les recherches en', 'Les recherches psycholinguistiques et pédagogiques démontrent que les enfants apprennent mieux dans leur langue maternelle. En enseignant en créole d''abord, puis en transition vers le français, on favorise la compréhension conceptuelle, la confiance en soi et finalement de meilleurs résultats scolaires.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "revitalisation linguistique" d''une langue en danger ?', '["L''interdiction d''une langue dominante", "L''ensemble des efforts pour relancer", "La création d''une nouvelle orthographe simplifiée", "La traduction de textes religieux dans la langue concernée"]'::jsonb, 'L''ensemble des efforts pour relancer', 'La revitalisation linguistique englobe toutes les actions visant à ranimer une langue en déclin : programmes scolaires, médias dans la langue, documentation et archivage, création littéraire, politique officielle de soutien. Pour le créole haïtien, bien qu''il ne soit pas en danger, ces efforts visent à lui redonner son prestige perdu.', 'Difficile'),
    (chap_id, 'Quel rôle jouent les médias (radio, télévision, internet) dans la politique linguistique haïtienne actuelle ?', '["Les médias n''ont aucun impact sur les langues", "Les médias en créole (radios", "Les médias haïtiens ne diffusent qu''en français", "Les médias internet ont fait disparaître le créole au profit de l''anglais"]'::jsonb, 'Les médias en créole (radios', 'Les radios communautaires haïtiennes (largement diffusées en créole), les telenovelas doublées en créole, les réseaux sociaux et les médias numériques en créole jouent un rôle crucial dans la diffusion d''un créole standardisé et dans la valorisation de la langue comme outil de communication moderne.', 'Moyen'),
    (chap_id, 'Quel est le lien entre la politique linguistique et les droits humains ?', '["La politique linguistique n''a aucun lien avec les droits humains", "Refuser à une personne l''accès à", "Seules les langues officielles méritent une protection par les droits humains", "Les droits linguistiques ne s''appliquent qu''aux langues autochtones en danger"]'::jsonb, 'Refuser à une personne l''accès à', 'Les droits linguistiques sont reconnus comme droits fondamentaux : le droit à l''éducation dans sa langue maternelle, le droit d''utiliser sa langue devant les tribunaux, le droit à l''information dans sa langue. En Haïti, la marginalisation du créole dans le système judiciaire et éducatif constitue une violation de ces droits pour la majorité créolophone.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "prestige linguistique" et comment influence-t-il les comportements langagiers ?', '["La richesse littéraire d''une langue", "La valeur sociale positive accordée à", "Le nombre de locuteurs d''une langue dans le monde", "La complexité grammaticale d''une langue"]'::jsonb, 'La valeur sociale positive accordée à', 'Le prestige linguistique est la valeur sociale positive associée à une langue : le français a un prestige élevé en Haïti (associé à l''éducation, l''ascension sociale), tandis que le créole, malgré sa vitalité, souffre d''un manque de prestige. Cela explique pourquoi certains Haïtiens hésitent à utiliser le créole dans des contextes formels.', 'Difficile'),
    (chap_id, 'Quel impact a eu le tremblement de terre de 2010 sur la politique linguistique haïtienne ?', '["Il a renforcé la domination du français dans les médias haïtiens", "Il a mis en évidence l''urgence de", "Il a conduit à l''abandon du créole au profit de l''anglais dans les ONG", "Il n''a eu aucun impact sur la politique linguistique"]'::jsonb, 'Il a mis en évidence l''urgence de', 'Le séisme de 2010 a révélé cruellement les conséquences pratiques de la marginalisation du créole : les informations d''urgence, les consignes de sécurité et les communications humanitaires devaient être en créole pour être comprises de toute la population. Cela a renforcé les arguments pour la valorisation du créole dans les communications officielles.', 'Moyen'),
    (chap_id, 'Comment le créole haïtien a-t-il évolué à l''ère numérique et des réseaux sociaux ?', '["Le créole est en déclin sur internet car les jeunes préfèrent l''anglais", "Le créole s''est adapté au numérique", "Le créole ne s''écrit pas sur internet", "Le numérique a standardisé le créole en éliminant les variations"]'::jsonb, 'Le créole s''est adapté au numérique', 'Le créole haïtien vit une expansion numérique : les réseaux sociaux haïtiens sont massivement en créole, avec une orthographe informelle (souvent phonétique), des néologismes technologiques créolisés (twit, tiktoker, lajounen), des podcasts culturels et politiques en créole. Cette présence numérique contribue à sa vitalité et à sa modernisation.', 'Moyen'),
    (chap_id, 'Quel rôle les intellectuels et écrivains haïtiens ont-ils joué dans la valorisation politique du créole ?', '["Ils ont toujours préféré écrire en français pour atteindre un public plus large", "Ils ont milité pour la reconnaissance", "Ils se sont opposés à l''usage du créole dans la littérature sérieuse", "Leur rôle a été minimal car la politique linguistique relève uniquement de l''État"]'::jsonb, 'Ils ont milité pour la reconnaissance', 'Des intellectuels comme Frankétienne, Félix Morisseau-Leroy (qui a traduit Antigone en créole), Pradel Pompilus (grammairien du créole) et d''autres ont joué un rôle essentiel dans la valorisation du créole : en écrivant en créole, en normalisant son orthographe et en militant pour son usage officiel, ils ont contribué au changement culturel et politique.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "glocalisation" linguistique dans le contexte du créole haïtien contemporain ?', '["L''abandon du créole pour les langues globales", "La capacité du créole à s''adapter aux", "L''uniformisation du créole sur le modèle du français international", "La disparition des dialectes régionaux du créole"]'::jsonb, 'La capacité du créole à s''adapter aux', 'La glocalisation du créole haïtien désigne sa capacité à être simultanément global (présent sur internet, dans la diaspora mondiale, adapté aux nouvelles technologies) et local (ancré dans l''identité et la culture haïtienne). Le créole n''est pas figé mais une langue vivante qui s''adapte à son époque.', 'Difficile');
  END IF;
END $$;
