-- Supplement Littérature Haïtienne NS1-NS3 (matiere_id=23)
-- ATTENTION : NS1, NS2, NS3 SEULEMENT — aucun chapitre NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 23 AND titre = 'Les fondateurs de la littérature haïtienne' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui est considéré comme le premier poète haïtien avec "L''Union fait la force" ?', '["Ignace Nau","Juste Chanlatte","Madiou","Liautaud Ethéart"]'::jsonb, 'Juste Chanlatte', 'Juste Chanlatte (1766-1828), secrétaire de Dessalines, est le premier poète officiel de la République d''Haïti.', 'Moyen'),
    (chap_id, 'Qui a fondé la première revue littéraire haïtienne L''Union en 1837 ?', '["Ignace Nau","Thomas Madiou","B. Ardouin","Demesvar Delorme"]'::jsonb, 'Ignace Nau', 'Ignace Nau (1808-1845) cofonde L''Union (1837) avec son frère Émile, impulsant le romantisme haïtien.', 'Moyen'),
    (chap_id, 'Quel écrivain haïtien du XIXe s. est l''auteur de Sous les bambous (poèmes) ?', '["Oswald Durand","Justin Lhérisson","Antoine Innocent","Georges Sylvain"]'::jsonb, 'Oswald Durand', 'Oswald Durand (1840-1906) est le poète national haïtien, célèbre pour son poème "Choucoune" en créole.', 'Moyen'),
    (chap_id, 'Quel est le thème principal du poème "Choucoune" d''Oswald Durand ?', '["La révolution","Un amour déçu avec une mulâtresse séduite par un étranger","L''histoire d''Haïti","La mort d''un héros"]'::jsonb, 'Un amour déçu avec une mulâtresse séduite par un étranger', 'Choucoune (1883) est un poème d''amour en créole, premier poème majeur en langue haïtienne.', 'Moyen'),
    (chap_id, 'Quel roman historique de Justin Lhérisson décrit la société haïtienne rurale ?', '["La famille des Pitite-Caille","Le fils noir","Mimola","Thémistocle Épaminondas Labasterre"]'::jsonb, 'La famille des Pitite-Caille', 'Justin Lhérisson (1873-1907) peint la société populaire haïtienne avec humour dans ses deux romans.', 'Moyen'),
    (chap_id, 'Quel auteur haïtien du XIXe s. a écrit une Histoire d''Haïti en 3 volumes (1847-1848) ?', '["Beaubrun Ardouin","Thomas Madiou","Hannibal Price","Demesvar Delorme"]'::jsonb, 'Thomas Madiou', 'Thomas Madiou (1814-1884) est le premier grand historien haïtien avec son Histoire d''Haïti.', 'Moyen'),
    (chap_id, 'Quel est le premier roman haïtien publié ?', '["Stella d''Émeric Bergeaud","La Famille des Pitite-Caille","Mimola","Les Thazard"]'::jsonb, 'Stella d''Émeric Bergeaud', 'Stella (1859) d''Émeric Bergeaud est le premier roman haïtien, allégorie de l''indépendance d''Haïti.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le mouvement indigéniste haïtien des années 1920-1940 ?', '["Un mouvement politique","Un mouvement littéraire valorisant les cultures africaines et populaires haïtiennes contre l''influence étrangère","Un mouvement religieux","Un courant réaliste"]'::jsonb, 'Un mouvement littéraire valorisant les cultures africaines et populaires haïtiennes contre l''influence étrangère', 'L''indigénisme (Price-Mars, Roumain) répond à l''occupation américaine en affirmant l''identité haïtienne.', 'Moyen'),
    (chap_id, 'Qui est l''auteur du roman Gouverneurs de la Rosée (1944) ?', '["René Depestre","Jean Price-Mars","Jacques Roumain","Frankétienne"]'::jsonb, 'Jacques Roumain', 'Gouverneurs de la Rosée (1944) de Jacques Roumain est considéré comme le chef-d''œuvre du roman haïtien.', 'Facile'),
    (chap_id, 'Quel est le thème central de Gouverneurs de la Rosée de Jacques Roumain ?', '["La vie urbaine","La réconciliation d''un village divisé autour de l''eau et de la solidarité paysanne","La politique nationale","L''occupation américaine"]'::jsonb, 'La réconciliation d''un village divisé autour de l''eau et de la solidarité paysanne', 'Manuel revient de Cuba et tente de réconcilier deux familles ennemies en trouvant de l''eau pour le village.', 'Moyen'),
    (chap_id, 'Quel ouvrage de Jean Price-Mars fonde l''indigénisme haïtien en valorisant le vodou et la culture africaine ?', '["Panorama de la Littérature","Ainsi parla l''Oncle","De Saint-Domingue à Haïti","La Vocation de l''Élite"]'::jsonb, 'Ainsi parla l''Oncle', 'Ainsi Parla l''Oncle (1928) de Jean Price-Mars est le manifeste de l''indigénisme haïtien.', 'Moyen'),
    (chap_id, 'Quel est le style narratif dominant dans Gouverneurs de la Rosée ?', '["Réalisme magique","Réalisme poétique avec des éléments du parler créole et de la nature tropicale","Naturalisme zolien","Existentialisme sartrien"]'::jsonb, 'Réalisme poétique avec des éléments du parler créole et de la nature tropicale', 'Roumain combine réalisme social, lyrisme de la nature haïtienne et oralité créole.', 'Moyen'),
    (chap_id, 'Quel poète haïtien a publié Étincelles (1901) et milité pour les droits des Noirs ?', '["Oswald Durand","Massillon Coicou","Georges Sylvain","Alcibiade Fleury-Battier"]'::jsonb, 'Massillon Coicou', 'Massillon Coicou (1867-1908) est poète patriotique et nationaliste, fusillé pour complot.', 'Difficile'),
    (chap_id, 'Quel premier auteur haïtien du XIXe s. a écrit des fables en créole (Cric ? Crac !) ?', '["Oswald Durand","Justin Lhérisson","Georges Sylvain","Ignace Nau"]'::jsonb, 'Georges Sylvain', 'Georges Sylvain (1866-1925) adapte les fables de La Fontaine en créole haïtien dans Cric ? Crac ! (1901).', 'Difficile'),
    (chap_id, 'Quel thème est récurrent dans la poésie patriotique du XIXe siècle haïtien ?', '["L''amour romantique uniquement","La fierté de l''indépendance, la défense de la race noire et la résistance coloniale","La nature tropicale uniquement","La religion catholique"]'::jsonb, 'La fierté de l''indépendance, la défense de la race noire et la résistance coloniale', 'La poésie haïtienne du XIXe s. est profondément marquée par la conscience de la première République noire libre.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 23 AND titre = 'La négritude et la littérature haïtienne moderne' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le mouvement de la Négritude et qui en sont les fondateurs ?', '["Un mouvement politique africain","Un mouvement littéraire affirmant la fierté de l''identité noire, fondé par Senghor, Césaire et Damas","Un mouvement haïtien seul","Un mouvement religieux"]'::jsonb, 'Un mouvement littéraire affirmant la fierté de l''identité noire, fondé par Senghor, Césaire et Damas', 'La Négritude (années 1930, Paris) oppose la culture africaine à l''assimilation coloniale.', 'Moyen'),
    (chap_id, 'Quel lien existe entre la Négritude et le mouvement indigéniste haïtien ?', '["Aucun lien","L''indigénisme haïtien (Price-Mars) précède et influence la Négritude qui amplifie l''affirmation noire","La Négritude précède l''indigénisme","Ce sont des mouvements opposés"]'::jsonb, 'L''indigénisme haïtien (Price-Mars) précède et influence la Négritude qui amplifie l''affirmation noire', 'Price-Mars inspire Césaire ; les mouvements se rejoignent dans la valorisation des cultures africaines diasporiques.', 'Difficile'),
    (chap_id, 'Quel écrivain haïtien a écrit Compère Général Soleil (1955) et Black Label ?', '["René Depestre","Jacques Stéphen Alexis","Frankétienne","Edwidge Danticat"]'::jsonb, 'Jacques Stéphen Alexis', 'Alexis (1922-1961) est l''un des grands romanciers du XXe siècle haïtien, disparu mystérieusement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le réalisme merveilleux défini par Jacques Stéphen Alexis ?', '["Le réalisme magique","La fusion du réel haïtien avec le merveilleux issu des croyances populaires et du vodou","Le surréalisme","La science-fiction haïtienne"]'::jsonb, 'La fusion du réel haïtien avec le merveilleux issu des croyances populaires et du vodou', 'Alexis propose en 1956 un réalisme spécifiquement haïtien intégrant le merveilleux culturel.', 'Difficile'),
    (chap_id, 'Qui est Frankétienne et quelle est son importance dans la littérature haïtienne ?', '["Un historien","Le créateur du spiralisme, mouvement littéraire haïtien, et auteur de Dezafi en créole","Un poète classique","Un conteur populaire"]'::jsonb, 'Le créateur du spiralisme, mouvement littéraire haïtien, et auteur de Dezafi en créole', 'Frankétienne (né 1936) est le plus grand auteur haïtien contemporain, créateur du mouvement spiraliste.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le spiralisme de Frankétienne ?', '["Un courant réaliste","Un mouvement esthétique haïtien cherchant à rompre les formes linéaires par une écriture tournoyante","Le surréalisme haïtien","Le réalisme merveilleux"]'::jsonb, 'Un mouvement esthétique haïtien cherchant à rompre les formes linéaires par une écriture tournoyante', 'Le spiralisme (Frankétienne, Philoctète, Morisseau-Leroy) utilise une esthétique éclatée, non linéaire.', 'Difficile'),
    (chap_id, 'Quel roman de René Depestre est considéré son chef-d''œuvre ?', '["Pays sans chapeau","Hadriana dans tous mes rêves","Le Mât de cocagne","Bonjour et adieu à la négritude"]'::jsonb, 'Hadriana dans tous mes rêves', 'Hadriana dans tous mes rêves (1988) de René Depestre mêle érotisme, vodou et identité haïtienne.', 'Moyen'),
    (chap_id, 'Quel est le thème central du roman Les Arbres Musiciens de Jacques Stéphen Alexis ?', '["La révolution politique","La tension entre modernité, vodou et catholicisme dans la société haïtienne","L''exil haïtien","La nature tropicale"]'::jsonb, 'La tension entre modernité, vodou et catholicisme dans la société haïtienne', 'Les Arbres Musiciens (1957) explore le conflit spirituel entre la campagne haïtienne et la modernité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que Dezafi de Frankétienne représente dans l''histoire littéraire haïtienne ?', '["Le premier roman policier","Le premier roman écrit en créole haïtien, publié en 1975","La première épopée","Le premier roman réaliste"]'::jsonb, 'Le premier roman écrit en créole haïtien, publié en 1975', 'Dezafi (1975) de Frankétienne est le premier roman entièrement rédigé en créole haïtien.', 'Moyen'),
    (chap_id, 'Quel poète haïtien de la diaspora a écrit Poèmes d''une saison en enfer haïtien ?', '["René Depestre","Jean-Claude Charles","Anthony Phelps","Marc Exavier"]'::jsonb, 'Anthony Phelps', 'Anthony Phelps (né 1928) est un poète spiraliste haïtien en exil, voix importante de la diaspora.', 'Difficile'),
    (chap_id, 'Qu''est-ce qui caractérise la littérature haïtienne de la période duvaliériste (1957-1986) ?', '["Un épanouissement créatif","L''exil massif des écrivains, la censure et l''émergence d''une littérature de la diaspora","Une production abondante locale","L''indigénisme renouvelé"]'::jsonb, 'L''exil massif des écrivains, la censure et l''émergence d''une littérature de la diaspora', 'Sous Duvalier, les intellectuels fuient (Depestre, Morisseau-Leroy, Alexis) ou sont réduits au silence.', 'Moyen'),
    (chap_id, 'Quel roman de Marie Vieux-Chauvet aborde la répression duvaliériste ?', '["Gouverneurs de la Rosée","Amour, Colère et Folie","Les Rapaces","La Danse sur le Volcan"]'::jsonb, 'Amour, Colère et Folie', 'Marie Vieux-Chauvet (1916-1973) publie Amour, Colère et Folie (1968), dénonciation voilée du régime.', 'Moyen'),
    (chap_id, 'Quel écrivain haïtien a reçu le Prix Médicis en 2011 pour L''Art de perdre ?', '["Dany Laferrière","Yanick Lahens","Gary Victor","Kettly Mars"]'::jsonb, 'Dany Laferrière', 'Dany Laferrière (né 1953) est l''auteur haïtien le plus célèbre mondialement, élu à l''Académie française (2013).', 'Moyen'),
    (chap_id, 'Quel thème est central dans Comment Faire l''Amour avec un Nègre sans se Fatiguer de Dany Laferrière ?', '["L''histoire d''Haïti","Le regard croisé sur la race, l''identité et la sexualité dans l''exil montréalais","La nostalgie du pays","La religion vodou"]'::jsonb, 'Le regard croisé sur la race, l''identité et la sexualité dans l''exil montréalais', 'Premier roman de Laferrière (1985), provocateur et humoristique, il déconstruit les stéréotypes raciaux.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 23 AND titre = 'Littérature haïtienne contemporaine et diaspora' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel roman de Yanick Lahens décrit la vie haïtienne après le séisme de 2010 ?', '["Bain de Lune","Caïque","Failles","Pendant ce temps"]'::jsonb, 'Bain de Lune', 'Bain de Lune (2014, Prix Femina) de Yanick Lahens décrit une famille haïtienne sur plusieurs générations.', 'Moyen'),
    (chap_id, 'Quel est le thème de Pays sans chapeau de Dany Laferrière ?', '["L''exil en Amérique","Le retour en Haïti et le voyage dans le monde des morts (vodou)","La révolution haïtienne","L''enfance en province"]'::jsonb, 'Le retour en Haïti et le voyage dans le monde des morts (vodou)', 'Pays sans chapeau (1996) : Laferrière retourne en Haïti et explore la frontière entre vivants et morts.', 'Moyen'),
    (chap_id, 'Qui est Edwidge Danticat et pourquoi est-elle importante ?', '["Une historienne","Une écrivaine haïtienne-américaine qui donne une voix mondiale à la diaspora haïtienne","Une poète classique","Une journaliste"]'::jsonb, 'Une écrivaine haïtienne-américaine qui donne une voix mondiale à la diaspora haïtienne', 'Danticat (née 1969) écrit en anglais sur Haïti (Breath, Eyes, Memory ; The Dew Breaker) pour un public international.', 'Moyen'),
    (chap_id, 'Quel roman de Gary Victor mêle policier, vodou et critique sociale haïtienne ?', '["Clair de manbo","Le diable dans un thé à la citronnelle","Les masques déchirés","Avec le cœur de l''arbre"]'::jsonb, 'Le diable dans un thé à la citronnelle', 'Gary Victor (né 1958) est le maître du roman policier haïtien, mêlant fantastique, vodou et satire sociale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la question de la langue dans la littérature haïtienne contemporaine ?', '["Une question résolue","Un débat central sur l''usage du français vs créole comme langues de création littéraire","Une question politique uniquement","Un problème technique d''édition"]'::jsonb, 'Un débat central sur l''usage du français vs créole comme langues de création littéraire', 'L''écrivain haïtien navigue entre le français (langue d''élite) et le créole (langue populaire) : enjeu identitaire.', 'Moyen'),
    (chap_id, 'Quel thème unit la plupart des œuvres de la diaspora haïtienne ?', '["L''oubli d''Haïti","La tension entre appartenance à Haïti et intégration dans le pays d''accueil","La nostalgie uniquement","La politique haïtienne"]'::jsonb, 'La tension entre appartenance à Haïti et intégration dans le pays d''accueil', 'L''œuvre diasporique haïtienne explore l''identité hybride, le déracinement et le lien au pays natal.', 'Moyen'),
    (chap_id, 'Quel roman de Louis-Philippe Dalembert traite de l''expérience migratoire haïtienne en Méditerranée ?', '["Maître-Minuit","Avant que les ombres s''effacent","Maudite Education","Así en la tierra"]'::jsonb, 'Avant que les ombres s''effacent', 'Dalembert (né 1962) explore dans Avant que les ombres s''effacent la mémoire juive et les migrations.', 'Difficile'),
    (chap_id, 'Quel est le rôle du vodou dans la littérature haïtienne contemporaine ?', '["Un élément exotique sans signification","Un système de valeurs culturelles, cosmologiques et résistance identitaire représenté comme patrimoine","Une superstition condamnée","Un simple décor narratif"]'::jsonb, 'Un système de valeurs culturelles, cosmologiques et résistance identitaire représenté comme patrimoine', 'La littérature haïtienne contemporaine réhabilite le vodou comme expression culturelle légitime.', 'Difficile'),
    (chap_id, 'Quel écrivain haïtien a reçu le Prix des Amériques en 2021 ?', '["Dany Laferrière","Yanick Lahens","Kettly Mars","James Noël"]'::jsonb, 'Yanick Lahens', 'Yanick Lahens (née 1953) est la grande dame de la littérature haïtienne contemporaine, Prix Femina 2014.', 'Moyen'),
    (chap_id, 'Que représente le roman Mémoire en Colin-Maillard de Syto Cavé dans la littérature haïtienne ?', '["Un roman historique","Une exploration de la mémoire traumatique haïtienne sous la dictature duvaliériste","Un roman d''amour","Un roman de formation"]'::jsonb, 'Une exploration de la mémoire traumatique haïtienne sous la dictature duvaliériste', 'Syto Cavé représente la génération d''après-Duvalier portant les traumatismes de la dictature.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "créolité" comme concept littéraire caribéen ?', '["La langue créole uniquement","L''identité caribéenne comme synthèse de l''Afrique, l''Europe et l''Amérique indienne (Chamoiseau, Confiant)","Le réalisme magique","La Négritude renouvelée"]'::jsonb, 'L''identité caribéenne comme synthèse de l''Afrique, l''Europe et l''Amérique indienne (Chamoiseau, Confiant)', 'L''Éloge de la Créolité (1989) dépasse la Négritude pour une identité composite, créole, archipelique.', 'Difficile'),
    (chap_id, 'Comment la littérature haïtienne post-séisme 2010 a-t-elle traité la catastrophe ?', '["En l''ignorant","En témoignant du traumatisme, de la solidarité et en réinterrogeant l''identité haïtienne","En glorifiant l''aide internationale","En abandonnant toute fiction"]'::jsonb, 'En témoignant du traumatisme, de la solidarité et en réinterrogeant l''identité haïtienne', 'Lahens (Failles), Laferrière (Tout bouge autour de moi), Victor : le séisme relance la réflexion sur la condition haïtienne.', 'Moyen'),
    (chap_id, 'Quel aspect de l''œuvre de Kettly Mars la distingue dans la littérature haïtienne ?', '["La poésie épique","L''exploration de la sexualité féminine, du corps et de la politique sous la dictature","Le roman policier","L''histoire coloniale"]'::jsonb, 'L''exploration de la sexualité féminine, du corps et de la politique sous la dictature', 'Kettly Mars (Saisons sauvages, Je suis vivant) donne une voix aux femmes sous la dictature duvaliériste.', 'Moyen');
  END IF;
END $$;
