-- Supplement Philosophie NS3-NS4 (matiere_id=16)
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'Philosophie de l''art et du langage' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Selon Platon, pourquoi l''art est-il une menace pour la cité idéale ?', '["Il est trop coûteux","C''est une imitation d''imitation éloignant du Vrai","Il distrait les guerriers","Il glorifie les tyrans"]'::jsonb, 'C''est une imitation d''imitation éloignant du Vrai', 'Pour Platon, l''art imite le sensible qui imite déjà les Idées ; il est au troisième degré de la réalité.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le sublime chez Kant ?', '["La beauté parfaite","Une émotion face à ce qui dépasse notre faculté de représentation","L''art classique","La beauté naturelle"]'::jsonb, 'Une émotion face à ce qui dépasse notre faculté de représentation', 'Le sublime kantien naît de la confrontation avec l''illimité (nature, grandeur morale) qui dépasse l''imagination.', 'Difficile'),
    (chap_id, 'Quel philosophe a théorisé l''art comme "jeu libre" des facultés (imagination et entendement) ?', '["Hegel","Nietzsche","Kant","Heidegger"]'::jsonb, 'Kant', 'Dans la Critique de la faculté de juger, Kant analyse le beau comme harmonie libre entre imagination et entendement.', 'Difficile'),
    (chap_id, 'Selon Hegel, quel est le sens de l''histoire de l''art ?', '["L''art est éternel","L''art est le devenir de l''Esprit absolu vers la pleine conscience de lui-même","L''art décline progressivement","L''art est purement subjectif"]'::jsonb, 'L''art est le devenir de l''Esprit absolu vers la pleine conscience de lui-même', 'Hegel : l''art (symbolique→classique→romantique) est une étape du cheminement de l''Esprit vers lui-même.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "mort de l''art" selon Hegel ?', '["L''art a disparu","La philosophie et la religion ont supplanté l''art comme expression de l''Absolu","Les artistes sont morts","L''art est devenu commercial"]'::jsonb, 'La philosophie et la religion ont supplanté l''art comme expression de l''Absolu', 'Pour Hegel, l''art romantique a épuisé sa mission ; la religion puis la philosophie expriment mieux l''Absolu.', 'Difficile'),
    (chap_id, 'Selon Wittgenstein, les limites de mon langage signifient ?', '["Les limites de ma culture","Les limites de mon monde","Les limites de ma grammaire","Les limites de la logique"]'::jsonb, 'Les limites de mon monde', 'Dans le Tractatus : "Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt" — langage et monde coextensifs.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "jeu de langage" chez Wittgenstein tardif ?', '["Une métaphore littéraire","L''ensemble des pratiques sociales dans lesquelles s''inscrit l''usage d''un mot","Un exercice logique","Un jeu de mots"]'::jsonb, 'L''ensemble des pratiques sociales dans lesquelles s''inscrit l''usage d''un mot', 'Dans les Investigations philosophiques, le sens d''un mot est son usage dans un jeu de langage.', 'Difficile'),
    (chap_id, 'Quel philosophe a développé la théorie des actes de langage (speech acts) ?', '["Saussure","Chomsky","Austin","Searle seulement"]'::jsonb, 'Austin', 'Austin dans Quand dire c''est faire distingue les performatifs (promettre, jurer) qui font des choses en les disant.', 'Difficile'),
    (chap_id, 'Quelle est la différence entre signe et symbole selon Saussure ?', '["Aucune","Le signe est arbitraire (lien conventionnel), le symbole a un lien naturel avec ce qu''il représente","Le symbole est plus abstrait","Le signe est iconique"]'::jsonb, 'Le signe est arbitraire (lien conventionnel), le symbole a un lien naturel avec ce qu''il représente', 'Saussure : le signe linguistique unit un signifiant et un signifié par convention arbitraire, sans ressemblance.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''herméneutique selon Gadamer ?', '["L''analyse logique","L''art de l''interprétation des textes et la compréhension comme fusion des horizons","La sémiologie","La phénoménologie"]'::jsonb, 'L''art de l''interprétation des textes et la compréhension comme fusion des horizons', 'Gadamer dans Vérité et Méthode : comprendre, c''est fusionner son horizon interprétatif avec celui du texte.', 'Difficile'),
    (chap_id, 'Selon Nietzsche, quelle est la vision apollinienne et dionysiaque de l''art ?', '["Apollinien = ordre, dionysiaque = chaos créateur","Apollinien = beau, dionysiaque = vrai","Apollinien = art classique, dionysiaque = art moderne","Apollinien = plastique, dionysiaque = musique uniquement"]'::jsonb, 'Apollinien = ordre, dionysiaque = chaos créateur', 'Dans La Naissance de la tragédie, Nietzsche oppose Apollon (forme, mesure) à Dionysos (ivresse, débordement).', 'Difficile'),
    (chap_id, 'Que critique Benjamin dans "L''œuvre d''art à l''ère de sa reproductibilité technique" ?', '["La photographie est mauvaise","La reproduction technique détruit l''aura de l''original","L''art moderne est dégénéré","Le cinéma n''est pas un art"]'::jsonb, 'La reproduction technique détruit l''aura de l''original', 'Benjamin : l''aura (présence unique, ici-et-maintenant) disparaît quand l''œuvre est reproduite à l''infini.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la déconstruction chez Derrida ?', '["La destruction des textes","Une lecture qui dévoile les tensions et hiérarchies cachées dans le texte","Une méthode scientifique","La critique littéraire classique"]'::jsonb, 'Une lecture qui dévoile les tensions et hiérarchies cachées dans le texte', 'Derrida déconstruit les oppositions binaires (parole/écriture, etc.) pour montrer leur instabilité.', 'Difficile'),
    (chap_id, 'Quel philosophe a dit que "la vérité est femme" en parlant de la philosophie ?', '["Platon","Hegel","Nietzsche","Schopenhauer"]'::jsonb, 'Nietzsche', 'Nietzsche dans Par-delà bien et mal compare la philosophie à une femme qui résiste à ceux qui la forcent.', 'Difficile'),
    (chap_id, 'Selon Heidegger, que fait l''œuvre d''art ?', '["Elle imite la réalité","Elle "met en œuvre la vérité" en dévoilant un monde","Elle divertit","Elle embellit le monde"]'::jsonb, 'Elle "met en œuvre la vérité" en dévoilant un monde', 'Dans L''Origine de l''œuvre d''art, Heidegger : l''art est Ereignis, dévoilement de l''être dans le conflit terre/monde.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'Philosophie de la religion et philosophie contemporaine' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel argument cosmologique classique tente de prouver l''existence de Dieu ?', '["L''argument ontologique","L''argument de la contingence : tout ce qui existe a une cause, il faut donc une cause première","L''argument moral","L''argument du pari"]'::jsonb, 'L''argument de la contingence : tout ce qui existe a une cause, il faut donc une cause première', 'L''argument cosmologique (Aquinas, Leibniz) : les êtres contingents renvoient à un être nécessaire.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''argument ontologique de saint Anselme ?', '["Dieu est cause du monde","L''idée d''un être parfait implique son existence, car l''existence est une perfection","La complexité du monde prouve Dieu","Dieu est moral"]'::jsonb, 'L''idée d''un être parfait implique son existence, car l''existence est une perfection', 'Anselme : si l''on conçoit un être tel qu''on ne puisse en concevoir de plus grand, il existe nécessairement.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "pari de Pascal" ?', '["Il vaut mieux croire en Dieu car si Dieu existe on gagne tout, si non on ne perd rien","La prière est rationnelle","La foi est supérieure à la raison","Dieu est évident"]'::jsonb, 'Il vaut mieux croire en Dieu car si Dieu existe on gagne tout, si non on ne perd rien', 'Pascal fonde la foi non sur la raison mais sur un calcul des espérances ; le gain éternel vaut le pari.', 'Moyen'),
    (chap_id, 'Quel philosophe a affirmé que "Dieu est mort" ?', '["Marx","Nietzsche","Feuerbach","Comte"]'::jsonb, 'Nietzsche', '"Dieu est mort" (Ainsi parlait Zarathoustra) signifie la fin de la croyance en des valeurs transcendantes absolues.', 'Facile'),
    (chap_id, 'Qu''est-ce que le problème du mal (théodicée) ?', '["Pourquoi les hommes font le mal","Si Dieu est bon et tout-puissant, pourquoi existe-t-il du mal ?","La question du péché originel","Le problème de la punition divine"]'::jsonb, 'Si Dieu est bon et tout-puissant, pourquoi existe-t-il du mal ?', 'La théodicée tente de concilier l''existence de Dieu avec le mal dans le monde (Leibniz, Augustin).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la phénoménologie de Husserl ?', '["L''étude des phénomènes naturels","Retour aux choses mêmes par suspension des présuppositions (épochè)","La philosophie du langage","Le structuralisme"]'::jsonb, 'Retour aux choses mêmes par suspension des présuppositions (épochè)', 'Husserl suspend le "monde naturel" (épochè) pour décrire les structures pures de la conscience.', 'Difficile'),
    (chap_id, 'Que signifie "être-dans-le-monde" chez Heidegger ?', '["Vivre sur la Terre","L''existence humaine est fondamentalement engagée dans un monde avant toute réflexion","L''homme est un animal","La finitude humaine"]'::jsonb, 'L''existence humaine est fondamentalement engagée dans un monde avant toute réflexion', 'L''être-dans-le-monde (In-der-Welt-sein) est la structure fondamentale du Dasein : on est toujours déjà là.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le structuralisme en philosophie (Lévi-Strauss, Saussure, Lacan) ?', '["L''étude des structures sociales","La recherche des structures inconscientes qui organisent la culture, le langage et l''esprit","Une méthode historique","L''analyse des institutions"]'::jsonb, 'La recherche des structures inconscientes qui organisent la culture, le langage et l''esprit', 'Le structuralisme cherche les systèmes de relations (structures) sous-jacents aux phénomènes observables.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le post-structuralisme (Derrida, Foucault, Deleuze) remet en question ?', '["La nécessité de la philosophie","Les structures stables, les centres et les métarécits des structuralistes","La science","La politique"]'::jsonb, 'Les structures stables, les centres et les métarécits des structuralistes', 'Les post-structuralistes critiquent les structures fixes et les grands récits de légitimation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "volonté de puissance" chez Nietzsche ?', '["Le désir de dominer autrui","La force créatrice fondamentale qui cherche à se surpasser et à affirmer la vie","L''instinct de mort","La politique du fort"]'::jsonb, 'La force créatrice fondamentale qui cherche à se surpasser et à affirmer la vie', 'La volonté de puissance n''est pas domination mais puissance créatrice qui donne un sens au monde.', 'Difficile'),
    (chap_id, 'Selon Foucault, qu''est-ce que le pouvoir ?', '["La force militaire","Un réseau diffus de relations qui traverse toute la société, non localisé dans une institution","L''État seul","L''autorité des experts"]'::jsonb, 'Un réseau diffus de relations qui traverse toute la société, non localisé dans une institution', 'Foucault : le pouvoir est partout, il "circule" et produit des sujets, des savoirs, des normes.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le féminisme philosophique remet en question ?', '["Le rationalisme","Les structures de domination patriarcale et l''androcentrisme dans la philosophie traditionnelle","La logique formelle","La métaphysique classique"]'::jsonb, 'Les structures de domination patriarcale et l''androcentrisme dans la philosophie traditionnelle', 'Le féminisme philosophique (Beauvoir, Butler) critique la construction sociale du genre et la domination masculine.', 'Moyen'),
    (chap_id, 'Que signifie "On ne naît pas femme, on le devient" (Beauvoir) ?', '["La biologie détermine le sexe","La féminité est une construction sociale et culturelle, non une essence naturelle","Les femmes sont plus évoluées","Le genre est inné"]'::jsonb, 'La féminité est une construction sociale et culturelle, non une essence naturelle', 'Beauvoir dans Le Deuxième Sexe (1949) : le genre est culturellement construit, non biologiquement déterminé.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''éthique de la responsabilité selon Jonas ?', '["Responsabilité des actes passés","Responsabilité envers les générations futures et la nature, face aux risques technologiques","Responsabilité civile","Responsabilité juridique"]'::jsonb, 'Responsabilité envers les générations futures et la nature, face aux risques technologiques', 'Jonas dans Le Principe responsabilité : l''ère technologique exige une éthique du futur et de la précaution.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''intersubjectivité en philosophie contemporaine ?', '["La communication entre sujets","La structure de la conscience qui se constitue dans la relation à autrui","L''objectivité scientifique","La subjectivité absolue"]'::jsonb, 'La structure de la conscience qui se constitue dans la relation à autrui', 'L''intersubjectivité (Husserl, Merleau-Ponty) montre que le sujet se constitue dans et par la relation à l''autre.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'Philosophie des sciences et épistémologie avancée' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Selon Kuhn, qu''est-ce qu''un paradigme scientifique ?', '["Un exemple de raisonnement","Un ensemble de croyances, valeurs et méthodes partagées par une communauté scientifique","Une théorie réfutée","Un modèle mathématique"]'::jsonb, 'Un ensemble de croyances, valeurs et méthodes partagées par une communauté scientifique', 'Dans La Structure des révolutions scientifiques, Kuhn : la science normale opère dans un paradigme jusqu''à une révolution.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une révolution scientifique selon Kuhn ?', '["Un progrès graduel","Le remplacement d''un paradigme par un autre incompatible lors d''une crise","Une découverte importante","Un changement de méthode"]'::jsonb, 'Le remplacement d''un paradigme par un autre incompatible lors d''une crise', 'Les révolutions (Copernic, Newton, Einstein) sont des changements de paradigme, non des accumulations.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le réalisme scientifique ?', '["Les théories sont de simples outils","Les théories scientifiques décrivent la réalité telle qu''elle est, indépendamment de nous","La science est une construction sociale","Seul ce qui est observable existe"]'::jsonb, 'Les théories scientifiques décrivent la réalité telle qu''elle est, indépendamment de nous', 'Le réalisme scientifique affirme que les entités théoriques (électrons, etc.) existent réellement.', 'Difficile'),
    (chap_id, 'Quelle est la position de l''instrumentalisme en philosophie des sciences ?', '["Les théories décrivent la réalité","Les théories sont des instruments de prédiction, sans valeur de vérité sur ce qui n''est pas observable","La science est infaillible","Toute théorie est vraie"]'::jsonb, 'Les théories sont des instruments de prédiction, sans valeur de vérité sur ce qui n''est pas observable', 'L''instrumentalisme (Duhem, Mach) : les théories ne sont ni vraies ni fausses, elles servent à prédire.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le problème de la sous-détermination des théories ?', '["Les théories manquent de données","Les mêmes données empiriques peuvent être compatibles avec plusieurs théories différentes","Les théories sont trop complexes","Les expériences sont subjectives"]'::jsonb, 'Les mêmes données empiriques peuvent être compatibles avec plusieurs théories différentes', 'La sous-détermination (Duhem-Quine) montre qu''on ne peut logiquement choisir entre théories par l''expérience seule.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''unité des sciences selon le positivisme logique (Cercle de Vienne) ?', '["Toutes les sciences utilisent les mathématiques","Toutes les propositions scientifiques sont réductibles à des propositions d''observation","Les sciences sociales sont fausses","La physique prime sur tout"]'::jsonb, 'Toutes les propositions scientifiques sont réductibles à des propositions d''observation', 'Le Cercle de Vienne (Carnap, Schlick) cherche un langage physicaliste commun à toutes les sciences.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''épistémologie naturalisée de Quine ?', '["L''épistémologie doit rester normative","L''épistémologie doit devenir une branche de la psychologie empirique","La connaissance est a priori","La logique est fondement de tout"]'::jsonb, 'L''épistémologie doit devenir une branche de la psychologie empirique', 'Quine dissout la frontière entre philosophie et science : l''épistémologie doit étudier empiriquement la connaissance.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le holisme épistémologique (Duhem-Quine) ?', '["Chaque théorie est testée isolément","Une théorie ne peut être testée séparément : c''est tout un réseau de croyances qui affronte l''expérience","Toutes les théories sont vraies ensemble","Le holisme est une position religieuse"]'::jsonb, 'Une théorie ne peut être testée séparément : c''est tout un réseau de croyances qui affronte l''expérience', 'La thèse Duhem-Quine : on ne teste jamais une hypothèse isolée, toujours avec des hypothèses auxiliaires.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le réductionnisme en philosophie des sciences ?', '["Simplifier les théories","Expliquer les phénomènes complexes en termes de composants plus simples","Rejeter les grandes théories","La méthode historique"]'::jsonb, 'Expliquer les phénomènes complexes en termes de composants plus simples', 'Le réductionnisme cherche à ramener la biologie à la chimie, la chimie à la physique, etc.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le concept de "boîte noire" en épistémologie ?', '["Un ordinateur mystérieux","Traiter un système complexe uniquement par ses entrées et sorties sans examiner son mécanisme","Une théorie secrète","Un problème insoluble"]'::jsonb, 'Traiter un système complexe uniquement par ses entrées et sorties sans examiner son mécanisme', 'La boîte noire (Latour, cybernétique) décrit l''acceptation sans examen des mécanismes d''une théorie stabilisée.', 'Difficile'),
    (chap_id, 'Selon Lakatos, qu''est-ce qu''un programme de recherche scientifique ?', '["Une seule théorie","Un noyau dur de postulats entourés d''une ceinture protectrice d''hypothèses auxiliaires","Un paradigme au sens de Kuhn","Un ensemble d''observations"]'::jsonb, 'Un noyau dur de postulats entourés d''une ceinture protectrice d''hypothèses auxiliaires', 'Lakatos affine Popper : on ne réfute pas le noyau dur directement, mais les hypothèses auxiliaires.', 'Difficile'),
    (chap_id, 'Que signifie "tout est bon" (anything goes) chez Feyerabend ?', '["L''anarchisme scientifique : aucune méthode unique ne définit la science","La tolérance morale","L''absence de vérité","Le relativisme absolu en morale"]'::jsonb, 'L''anarchisme scientifique : aucune méthode unique ne définit la science', 'Feyerabend dans Contre la méthode : les grandes découvertes violent les règles méthodologiques établies.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la sociologie des sciences (Bloor, Latour) étudie ?', '["Les lois de la nature","La production sociale des faits scientifiques et des controverses","La logique des théories","La psychologie des chercheurs"]'::jsonb, 'La production sociale des faits scientifiques et des controverses', 'Le programme fort de la SSK (Bloor) et l''anthropologie des sciences (Latour) montrent que la science est socialement construite.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le problème de l''explication causale en philosophie des sciences ?', '["Trouver les causes premières","Comment une théorie explique un phénomène : loi de couverture (Hempel) ou mécanisme ?","La causalité divine","La corrélation statistique"]'::jsonb, 'Comment une théorie explique un phénomène : loi de couverture (Hempel) ou mécanisme ?', 'Hempel propose le modèle DN (déduction depuis des lois) ; d''autres exigent un mécanisme causal.', 'Difficile'),
    (chap_id, 'Que signifie l''indétermination de la traduction chez Quine ?', '["On ne peut pas traduire les langues mortes","Plusieurs traductions radicalement différentes sont toutes également compatibles avec le comportement observable","La traduction est subjective","Les langues sont incommensurables"]'::jsonb, 'Plusieurs traductions radicalement différentes sont toutes également compatibles avec le comportement observable', 'Quine dans Mot et Objet : la "traduction radicale" montre l''indétermination de la référence linguistique.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'Philosophie de l''histoire et philosophies critiques' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Selon Hegel, l''histoire est le déploiement de quoi ?', '["La Providence divine","L''Esprit absolu (Geist) vers la pleine conscience de lui-même","La nature","Les forces économiques"]'::jsonb, 'L''Esprit absolu (Geist) vers la pleine conscience de lui-même', 'Hegel : l''histoire universelle est le "progrès de la conscience de la liberté" de l''Esprit absolu.', 'Difficile'),
    (chap_id, 'Selon Marx, qu''est-ce qui détermine l''histoire ?', '["Les idées des grands hommes","Les forces et rapports de production matériels (infrastructure économique)","La religion","Le hasard"]'::jsonb, 'Les forces et rapports de production matériels (infrastructure économique)', 'Le matérialisme historique marxiste : la superstructure (idéologie, État) est déterminée par l''infrastructure économique.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "ruse de la raison" (List der Vernunft) chez Hegel ?', '["La tromperie des philosophes","La Raison use des passions et intérêts particuliers pour réaliser ses fins universelles","Le cynisme politique","L''ironie socratique"]'::jsonb, 'La Raison use des passions et intérêts particuliers pour réaliser ses fins universelles', 'Hegel : Napoléon, Cromwell réalisaient inconsciemment le plan de la Raison historique.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "fin de l''histoire" selon Fukuyama ?', '["La destruction de la civilisation","La victoire définitive de la démocratie libérale et de l''économie de marché","Le déclin de l''Occident","L''apocalypse"]'::jsonb, 'La victoire définitive de la démocratie libérale et de l''économie de marché', 'Fukuyama après 1989 : la démocratie libérale est la forme finale et universelle du gouvernement humain.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''École de Francfort (Horkheimer, Adorno, Marcuse) critique ?', '["La démocratie","La raison instrumentale et la domination de la technique sur l''humain","La science naturelle","Le marxisme orthodoxe"]'::jsonb, 'La raison instrumentale et la domination de la technique sur l''humain', 'La Théorie critique dénonce la "dialectique des Lumières" : la raison libératrice devient instrument de domination.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "société du spectacle" selon Debord ?', '["Le cinéma","La vie sociale remplacée par une accumulation de spectacles marchands","La politique démocratique","Le capitalisme industriel"]'::jsonb, 'La vie sociale remplacée par une accumulation de spectacles marchands', 'Debord : le capitalisme tardif transforme toute l''expérience en représentation et consommation passive.', 'Difficile'),
    (chap_id, 'Quel concept d''Arendt désigne la banalité du mal dans le nazisme ?', '["La volonté de mal","L''absence de pensée critique chez des fonctionnaires obéissants (Eichmann)","Le totalitarisme ordinaire","La cruauté calculée"]'::jsonb, 'L''absence de pensée critique chez des fonctionnaires obéissants (Eichmann)', 'Arendt après le procès Eichmann : le mal peut être accompli sans intention mauvaise, par pure absence de jugement.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le postmodernisme en philosophie selon Lyotard ?', '["Le retour aux Lumières","La méfiance envers les grands récits de légitimation (science, progrès, émancipation)","Le structuralisme renouvelé","Le néo-marxisme"]'::jsonb, 'La méfiance envers les grands récits de légitimation (science, progrès, émancipation)', 'Lyotard dans La Condition postmoderne : la postmodernité est "l''incrédulité à l''égard des métarécits".', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "choc des civilisations" selon Huntington ?', '["L''accord universel","Les futurs conflits seront culturels et civilisationnels, non idéologiques","La fin de la géopolitique","L''unification mondiale"]'::jsonb, 'Les futurs conflits seront culturels et civilisationnels, non idéologiques', 'Huntington prédit que les grandes fractures du monde post-guerre froide seront entre civilisations.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la philosophie décoloniale (Quijano, Dussel) conteste ?', '["Les sciences naturelles","L''universalisme européen et la colonialité du savoir qui efface les épistémologies non-occidentales","La démocratie","La modernité technique"]'::jsonb, 'L''universalisme européen et la colonialité du savoir qui efface les épistémologies non-occidentales', 'La pensée décoloniale critique la "colonialité du pouvoir/savoir" et revendique des épistémologies du Sud.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''herméneutique des soupçons selon Ricoeur (Marx, Nietzsche, Freud) ?', '["La suspicion envers les autres","Ces penseurs remettent en question la transparence de la conscience et du sens apparent","La critique littéraire","Le doute cartésien renouvelé"]'::jsonb, 'Ces penseurs remettent en question la transparence de la conscience et du sens apparent', 'Les "maîtres du soupçon" dévoilent ce qui se cache derrière les discours (intérêts, pulsions, idéologie).', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "tournant linguistique" (linguistic turn) en philosophie du XXe siècle ?', '["L''étude des langues étrangères","Le déplacement de l''attention vers le langage comme condition de toute pensée et connaissance","La grammaire structurale","La traductologie"]'::jsonb, 'Le déplacement de l''attention vers le langage comme condition de toute pensée et connaissance', 'Le tournant linguistique (Wittgenstein, Heidegger, Saussure) : on ne pense et ne connaît qu''à travers le langage.', 'Difficile'),
    (chap_id, 'Selon Benjamin, qu''est-ce que la "dialectique à l''arrêt" ?', '["Le marxisme sans lutte","L''image dialectique qui cristallise le passé et le présent dans un éclair de reconnaissance","La fin du temps","L''instant statique"]'::jsonb, 'L''image dialectique qui cristallise le passé et le présent dans un éclair de reconnaissance', 'Benjamin : l''histoire est discontinue ; les images dialectiques "font sauter le continuum de l''histoire".', 'Difficile'),
    (chap_id, 'Qu''est-ce que le concept de "reconnaissance" (Anerkennung) chez Honneth ?', '["La connaissance des autres","Un besoin fondamental que les individus et groupes ont de voir leur valeur confirmée par autrui","L''identité nationale","La solidarité économique"]'::jsonb, 'Un besoin fondamental que les individus et groupes ont de voir leur valeur confirmée par autrui', 'Honneth développe une éthique de la reconnaissance (amour, droit, estime sociale) comme fondement de l''identité.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la mondialisation selon Bauman (modernité liquide) ?', '["Un progrès uniforme","La fluidification des identités, liens et structures sous la pression des flux économiques mondiaux","L''uniformisation culturelle","La disparition des États"]'::jsonb, 'La fluidification des identités, liens et structures sous la pression des flux économiques mondiaux', 'Bauman : la modernité "liquide" dissout les formes solides (emploi, identité, liens) dans l''instabilité permanente.', 'Difficile');
  END IF;
END $$;
