-- Supplement Chimie (matiere_id=10) — tous niveaux
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Structure de la matière et tableau périodique' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui a proposé le tableau périodique des éléments et en quelle année ?', '["Dalton en 1803","Dmitri Mendeleïev en 1869, en classant les éléments par masse atomique croissante et en découvrant la périodicité des propriétés","Einstein en 1905","Lavoisier en 1789"]'::jsonb, 'Dmitri Mendeleïev en 1869, en classant les éléments par masse atomique croissante et en découvrant la périodicité des propriétés', 'Mendeleïev a prédit l''existence d''éléments inconnus (gallium, germanium) par les lacunes dans son tableau ; ses prédictions furent confirmées.', 'Facile'),
    (chap_id, 'Qu''est-ce que le numéro atomique Z et le nombre de masse A d''un élément ?', '["Z est le nombre de neutrons, A est le nombre de protons","Z est le nombre de protons dans le noyau (caractérise l''élément) ; A = Z + N est la somme des protons et neutrons (nucléons)","Z est la masse atomique","A est le numéro de période"]'::jsonb, 'Z est le nombre de protons dans le noyau (caractérise l''élément) ; A = Z + N est la somme des protons et neutrons (nucléons)', 'Un élément est défini par Z ; ses isotopes ont même Z mais N différent (ex. ¹²C et ¹⁴C : Z=6, A=12 ou 14).', 'Facile'),
    (chap_id, 'Qu''est-ce que la configuration électronique d''un atome et comment la détermine-t-on ?', '["L''arrangement des protons","La distribution des électrons dans les couches et sous-couches (1s, 2s, 2p, 3s, 3p, etc.) selon les règles de Aufbau, Pauli et Hund ; ex. sodium (Z=11) : 1s²2s²2p⁶3s¹","Le nombre de neutrons","La masse atomique"]'::jsonb, 'La distribution des électrons dans les couches et sous-couches (1s, 2s, 2p, 3s, 3p, etc.) selon les règles de Aufbau, Pauli et Hund ; ex. sodium (Z=11) : 1s²2s²2p⁶3s¹', 'La configuration électronique détermine la position dans le tableau périodique et les propriétés chimiques de l''élément.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les électrons de valence et pourquoi sont-ils importants en chimie ?', '["Tous les électrons d''un atome","Les électrons de la couche externe (couche de valence) qui participent aux liaisons chimiques ; leur nombre détermine la réactivité chimique et la valence","Les électrons du noyau","Les électrons de cœur"]'::jsonb, 'Les électrons de la couche externe (couche de valence) qui participent aux liaisons chimiques ; leur nombre détermine la réactivité chimique et la valence', 'Les métaux alcalins (groupe 1) ont 1 électron de valence ; les halogènes (groupe 17) en ont 7 ; les gaz nobles (groupe 18) ont 8 (couche complète).', 'Moyen'),
    (chap_id, 'Quelles sont les tendances générales de l''électronégativité dans le tableau périodique ?', '["L''électronégativité augmente de droite à gauche","L''électronégativité augmente de gauche à droite dans une période et de bas en haut dans un groupe ; le fluor (F) est l''élément le plus électronégatif","L''électronégativité est constante","L''électronégativité augmente de haut en bas"]'::jsonb, 'L''électronégativité augmente de gauche à droite dans une période et de bas en haut dans un groupe ; le fluor (F) est l''élément le plus électronégatif', 'L''électronégativité (Pauling) mesure l''attirance d''un atome pour les électrons d''une liaison ; elle détermine la polarité des liaisons.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les isotopes d''un élément et en quoi diffèrent-ils ?', '["Des éléments différents","Des atomes du même élément (même Z) ayant des nombres de neutrons différents (donc des masses atomiques différentes) ; ex. ¹H, ²H (deutérium), ³H (tritium)","Des ions de charge différente","Des composés chimiques différents"]'::jsonb, 'Des atomes du même élément (même Z) ayant des nombres de neutrons différents (donc des masses atomiques différentes) ; ex. ¹H, ²H (deutérium), ³H (tritium)', 'Les isotopes ont des propriétés chimiques presque identiques mais des propriétés nucléaires différentes (stabilité, radioactivité).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un ion et comment se forme-t-il ?', '["Un atome neutre","Un atome ou groupe d''atomes ayant perdu ou gagné des électrons : cation (perte d''e⁻, charge positive) ou anion (gain d''e⁻, charge négative) ; ex. Na⁺ (Z=11, 10e⁻), Cl⁻ (Z=17, 18e⁻)","Un mélange d''éléments","Une molécule neutre"]'::jsonb, 'Un atome ou groupe d''atomes ayant perdu ou gagné des électrons : cation (perte d''e⁻, charge positive) ou anion (gain d''e⁻, charge négative) ; ex. Na⁺ (Z=11, 10e⁻), Cl⁻ (Z=17, 18e⁻)', 'Les ions se forment lors des réactions d''oxydoréduction et des dissociations ; ils transportent le courant électrique dans les solutions.', 'Facile'),
    (chap_id, 'Qu''est-ce que la différence entre un métal, un métalloïde et un non-métal dans le tableau périodique ?', '["Il n''y a pas de distinction","Les métaux (à gauche) sont conducteurs, malléables, brillants ; les non-métaux (à droite) sont isolants, souvent gazeux ; les métalloïdes (semi-conducteurs) sont à la frontière (Si, Ge, As)","Tous les éléments sont des métaux","Les non-métaux sont toujours liquides"]'::jsonb, 'Les métaux (à gauche) sont conducteurs, malléables, brillants ; les non-métaux (à droite) sont isolants, souvent gazeux ; les métalloïdes (semi-conducteurs) sont à la frontière (Si, Ge, As)', 'Les métalloïdes (silicium, germanium) sont la base de l''électronique moderne (semi-conducteurs, transistors, puces).', 'Facile'),
    (chap_id, 'Qu''est-ce que la règle de l''octet et ses exceptions ?', '["Tous les atomes veulent 4 électrons de valence","La tendance des atomes à acquérir une configuration de 8 électrons de valence (octets) lors des liaisons ; exceptions : H (2e⁻), BF₃ (6e⁻), PCl₅ (10e⁻)","La règle s''applique à tous les atomes sans exception","Seul le carbone suit cette règle"]'::jsonb, 'La tendance des atomes à acquérir une configuration de 8 électrons de valence (octets) lors des liaisons ; exceptions : H (2e⁻), BF₃ (6e⁻), PCl₅ (10e⁻)', 'La règle de l''octet (Lewis) explique la formation des liaisons covalentes et ioniques pour les éléments de la 2ème période.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''énergie d''ionisation et ses tendances dans le tableau périodique ?', '["L''énergie libérée lors d''une liaison","L''énergie nécessaire pour arracher un électron à un atome à l''état gazeux ; elle augmente de gauche à droite et de bas en haut (tendances inverses de l''électronégativité)","La chaleur de combustion","L''énergie de liaison C-H"]'::jsonb, 'L''énergie nécessaire pour arracher un électron à un atome à l''état gazeux ; elle augmente de gauche à droite et de bas en haut (tendances inverses de l''électronégativité)', 'Les métaux alcalins (Li, Na, K) ont de faibles énergies d''ionisation → facilement oxydés ; les gaz nobles ont les plus élevées.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Liaisons chimiques et propriétés des composés' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la différence entre une liaison ionique et une liaison covalente ?', '["Elles sont identiques","Liaison ionique : transfert d''électron(s) entre métal et non-métal formant des ions (NaCl) ; liaison covalente : partage d''électron(s) entre non-métaux (H₂O, CH₄)","La liaison covalente implique des métaux","La liaison ionique forme des molécules"]'::jsonb, 'Liaison ionique : transfert d''électron(s) entre métal et non-métal formant des ions (NaCl) ; liaison covalente : partage d''électron(s) entre non-métaux (H₂O, CH₄)', 'La différence d''électronégativité décide : ΔEN > 1,7 → ionique ; 0,4-1,7 → covalente polaire ; < 0,4 → covalente apolaire.', 'Facile'),
    (chap_id, 'Qu''est-ce que la liaison hydrogène et son importance en chimie ?', '["Une liaison covalente forte","Une liaison faible entre un H lié à un atome très électronégatif (N, O, F) et un autre atome électronégatif ; responsable de la tension de surface de l''eau, de la structure de l''ADN et des points d''ébullition élevés","Une liaison ionique","Une liaison métallique"]'::jsonb, 'Une liaison faible entre un H lié à un atome très électronégatif (N, O, F) et un autre atome électronégatif ; responsable de la tension de surface de l''eau, de la structure de l''ADN et des points d''ébullition élevés', 'Les liaisons H expliquent pourquoi l''eau est liquide à T ambiante (PE=100°C vs -60°C attendu) et la stabilité de l''ADN (bases appariées).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géométrie moléculaire selon la théorie VSEPR ?', '["Les molécules sont toujours sphériques","La forme géométrique d''une molécule est déterminée par la répulsion des paires d''électrons (liants et non-liants) autour de l''atome central ; ex. H₂O : angulaire (2 paires non-liantes), CH₄ : tétraédrique","Toutes les molécules sont linéaires","La géométrie ne dépend que des liaisons doubles"]'::jsonb, 'La forme géométrique d''une molécule est déterminée par la répulsion des paires d''électrons (liants et non-liants) autour de l''atome central ; ex. H₂O : angulaire (2 paires non-liantes), CH₄ : tétraédrique', 'VSEPR (Valence Shell Electron Pair Repulsion) : les paires se disposent pour minimiser les répulsions ; détermine les angles de liaison.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la polarité d''une molécule et quels en sont les exemples ?', '["Toutes les molécules sont polaires","Une molécule est polaire si elle possède un moment dipolaire net (liaisons polaires asymétriquement arrangées) ; ex. H₂O est polaire (V-shape) ; CO₂ est apolaire (linéaire, dipôles opposés)","Les molécules polaires ne se dissolvent pas dans l''eau","La polarité ne dépend pas de la géométrie"]'::jsonb, 'Une molécule est polaire si elle possède un moment dipolaire net (liaisons polaires asymétriquement arrangées) ; ex. H₂O est polaire (V-shape) ; CO₂ est apolaire (linéaire, dipôles opposés)', 'Règle «like dissolves like» : polaire (eau) dissout polaire (sel) ; apolaire (hexane) dissout apolaire (graisses).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la liaison métallique et comment explique-t-elle les propriétés des métaux ?', '["Une liaison ionique forte","Un nuage d''électrons délocalisés autour d''un réseau d''ions positifs (cations métalliques) ; explique la conductivité électrique (e⁻ libres), la malléabilité (glissement des couches) et la brillance des métaux","Une liaison covalente polaire","Une liaison de Van der Waals"]'::jsonb, 'Un nuage d''électrons délocalisés autour d''un réseau d''ions positifs (cations métalliques) ; explique la conductivité électrique (e⁻ libres), la malléabilité (glissement des couches) et la brillance des métaux', 'La liaison métallique (mer d''électrons de Drude) explique toutes les propriétés caractéristiques des métaux.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la structure de Lewis d''une molécule et comment la dessiner ?', '["Un diagramme des niveaux d''énergie","La représentation des liaisons et des paires d''électrons non-liants autour des atomes d''une molécule ; étapes : compter les électrons de valence, placer les liaisons, compléter les octets","Un spectre d''absorption","La configuration électronique"]'::jsonb, 'La représentation des liaisons et des paires d''électrons non-liants autour des atomes d''une molécule ; étapes : compter les électrons de valence, placer les liaisons, compléter les octets', 'G.N. Lewis (1916) a proposé ces structures ; elles permettent de déduire la géométrie VSEPR et la réactivité chimique.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une liaison covalente simple, double et triple et leurs caractéristiques ?', '["Toutes les liaisons sont identiques","Liaison simple (σ, 1 paire partagée), double (σ + π, 2 paires), triple (σ + 2π, 3 paires) ; les liaisons multiples raccourcissent la liaison et augmentent son énergie : C-C < C=C < C≡C en longueur","Les liaisons doubles sont plus faibles que les simples","Les liaisons triples sont les plus longues"]'::jsonb, 'Liaison simple (σ, 1 paire partagée), double (σ + π, 2 paires), triple (σ + 2π, 3 paires) ; les liaisons multiples raccourcissent la liaison et augmentent son énergie : C-C < C=C < C≡C en longueur', 'Ex. : N₂ (N≡N, très stable, 945 kJ/mol) vs. F₂ (F-F, 159 kJ/mol, facilement rompu) ; les liaisons π sont plus réactives que σ.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la résonance en chimie et quand s''applique-t-elle ?', '["Une vibration moléculaire","Lorsqu''une structure de Lewis unique ne représente pas bien une molécule et que la vraie structure est un hybride de plusieurs structures de résonance (ex. CO₃²⁻, benzène C₆H₆) : les électrons sont délocalisés","Une réaction réversible","Un type de liaison ionique"]'::jsonb, 'Lorsqu''une structure de Lewis unique ne représente pas bien une molécule et que la vraie structure est un hybride de plusieurs structures de résonance (ex. CO₃²⁻, benzène C₆H₆) : les électrons sont délocalisés', 'Le benzène (Kekulé, 1865) est l''exemple classique : ses 6 liaisons C-C sont équivalentes, ni simples ni doubles, grâce à la délocalistion.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les interactions de Van der Waals et leur importance ?', '["Des liaisons covalentes faibles","Les forces intermoléculaires faibles (London/dispersion, dipôle-dipôle, Keesom) résultant de fluctuations ou permanences de dipôles ; elles expliquent la cohésion des gaz nobles liquéfiés et des molécules apolaires","Des liaisons ioniques","Des liaisons hydrogène renforcées"]'::jsonb, 'Les forces intermoléculaires faibles (London/dispersion, dipôle-dipôle, Keesom) résultant de fluctuations ou permanences de dipôles ; elles explique la cohésion des gaz nobles liquéfiés et des molécules apolaires', 'Les forces de London (dispersion) existent entre toutes les molécules ; elles augmentent avec la masse molaire et la surface de contact.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Réactions chimiques et stœchiométrie' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la stœchiométrie et la mole en chimie ?', '["L''étude des propriétés des matériaux","L''étude quantitative des réactifs et produits d''une réaction chimique ; la mole (n = m/M = N/Nₐ) est l''unité de quantité de matière contenant Nₐ = 6,022×10²³ entités","L''étude des catalyseurs","La mesure de la vitesse des réactions"]'::jsonb, 'L''étude quantitative des réactifs et produits d''une réaction chimique ; la mole (n = m/M = N/Nₐ) est l''unité de quantité de matière contenant Nₐ = 6,022×10²³ entités', 'La stœchiométrie et la mole sont fondamentales pour calculer les quantités dans les réactions : «autant de moles d''A réagissent avec n moles de B».', 'Moyen'),
    (chap_id, 'Comment équilibre-t-on une équation chimique et quelle loi respecte-t-on ?', '["En ajoutant des éléments","En ajustant les coefficients stœchiométriques pour que le nombre d''atomes de chaque élément soit identique des deux côtés : loi de conservation de la masse (Lavoisier)","En changeant les formules chimiques","En ajoutant des flèches"]'::jsonb, 'En ajustant les coefficients stœchiométriques pour que le nombre d''atomes de chaque élément soit identique des deux côtés : loi de conservation de la masse (Lavoisier)', 'Lavoisier (1789) : «rien ne se perd, rien ne se crée, tout se transforme» ; les atomes sont conservés dans une réaction chimique.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un réactif limitant dans une réaction chimique ?', '["Le réactif le plus abondant","Le réactif qui est entièrement consommé en premier, déterminant la quantité maximale de produit formé ; l''autre réactif est en excès","Le réactif le moins réactif","Le réactif dont la masse molaire est la plus grande"]'::jsonb, 'Le réactif qui est entièrement consommé en premier, déterminant la quantité maximale de produit formé ; l''autre réactif est en excès', 'Identifier le réactif limitant : calculer les ratios molaires et comparer avec les coefficients stœchiométriques de l''équation.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le rendement d''une réaction et comment le calcule-t-on ?', '["Toujours 100%","η = (quantité obtenue / quantité théorique) × 100% ; les rendements < 100% s''expliquent par des réactions parasites, des pertes et des équilibres incomplets","η = masse des réactifs / masse des produits","η = vitesse de réaction"]'::jsonb, 'η = (quantité obtenue / quantité théorique) × 100% ; les rendements < 100% s''expliquent par des réactions parasites, des pertes et des équilibres incomplets', 'En industrie chimique, optimiser le rendement est un enjeu économique et environnemental majeur (réduction des déchets).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une réaction d''oxydoréduction (redox) et ses composants ?', '["Une réaction acide-base uniquement","Une réaction avec transfert d''électrons : l''oxydant gagne des électrons (est réduit) et le réducteur perd des électrons (est oxydé) ; l''oxydation augmente le nombre d''oxydation, la réduction le diminue","Une réaction de précipitation","Une réaction uniquement inorganique"]'::jsonb, 'Une réaction avec transfert d''électrons : l''oxydant gagne des électrons (est réduit) et le réducteur perd des électrons (est oxydé) ; l''oxydation augmente le nombre d''oxydation, la réduction le diminue', 'Mnémotechnique : OIL RIG = Oxidation Is Loss (of electrons), Reduction Is Gain. Les réactions redox incluent combustion, corrosion, photosynthèse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la théorie acide-base de Brønsted-Lowry ?', '["Les acides ont un goût sucré","Un acide de Brønsted-Lowry est un donneur de proton (H⁺) et une base est un accepteur de proton ; ex. HCl (acide) + H₂O (base) → H₃O⁺ + Cl⁻","Seuls les hydroxides sont des bases","Les acides sont uniquement inorganiques"]'::jsonb, 'Un acide de Brønsted-Lowry est un donneur de proton (H⁺) et une base est un accepteur de proton ; ex. HCl (acide) + H₂O (base) → H₃O⁺ + Cl⁻', 'Brønsted-Lowry (1923) étend la définition d''Arrhenius (H⁺/OH⁻ en solution) aux réactions sans eau (Lewis plus générale encore).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le pH et comment se calcule-t-il ?', '["La pression hydrostatique","pH = -log[H₃O⁺] ; pH < 7 = acide, pH = 7 = neutre, pH > 7 = basique ; une variation d''une unité de pH représente un facteur 10 de changement de concentration","pH = [H₃O⁺]","pH = masse molaire / volume"]'::jsonb, 'pH = -log[H₃O⁺] ; pH < 7 = acide, pH = 7 = neutre, pH > 7 = basique ; une variation d''une unité de pH représente un facteur 10 de changement de concentration', 'Le pH du sang humain est 7,35-7,45 (légèrement basique) ; un écart de ±0,2 est fatal (acidose ou alcalose).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un équilibre chimique et la constante d''équilibre K ?', '["Une réaction qui n''avance pas","L''état où les vitesses de la réaction directe et inverse sont égales ; K = [produits]/[réactifs] (rapport à l''équilibre) ; K>>1 : réaction favorise les produits, K<<1 : réactifs favorisés","Une réaction complète","Une réaction sans produits"]'::jsonb, 'L''état où les vitesses de la réaction directe et inverse sont égales ; K = [produits]/[réactifs] (rapport à l''équilibre) ; K>>1 : réaction favorise les produits, K<<1 : réactifs favorisés', 'L''équilibre chimique (Guldberg et Waage, 1864) est dynamique : les deux sens se poursuivent simultanément à l''équilibre.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe de Le Chatelier et comment s''applique-t-il ?', '["Les équilibres ne peuvent pas être déplacés","Si on perturbe un système à l''équilibre (concentration, pression, température), il se déplace pour s''opposer à la perturbation ; ex. augmenter la pression déplace vers le côté avec moins de moles de gaz","L''équilibre est immuable","La température ne déplace pas l''équilibre"]'::jsonb, 'Si on perturbe un système à l''équilibre (concentration, pression, température), il se déplace pour s''opposer à la perturbation ; ex. augmenter la pression déplace vers le côté avec moins de moles de gaz', 'Le Chatelier (1888) permet de prédire les effets des modifications sur les équilibres industriels (synthèse de l''ammoniac, Haber-Bosch).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la cinétique chimique et les facteurs influençant la vitesse de réaction ?', '["L''étude de l''énergie des réactions","L''étude de la vitesse des réactions chimiques ; elle dépend de la concentration des réactifs, de la température (loi d''Arrhenius : vitesse double ~tous les 10°C), des catalyseurs et de l''état de la matière","La stœchiométrie uniquement","L''équilibre chimique"]'::jsonb, 'L''étude de la vitesse des réactions chimiques ; elle dépend de la concentration des réactifs, de la température (loi d''Arrhenius : vitesse double ~tous les 10°C), des catalyseurs et de l''état de la matière', 'La loi d''Arrhenius (k = A·e^(-Ea/RT)) montre l''effet de la température ; les enzymes sont des biocatalyseurs abaissant l''énergie d''activation.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Chimie organique : structure et réactivité' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la chimie organique et pourquoi le carbone est-il au cœur de cette chimie ?', '["L''étude des organismes vivants uniquement","L''étude des composés du carbone (sauf CO, CO₂, carbonates) ; le C est tétravalent, forme 4 liaisons covalentes, des chaînes et cycles, permettant une diversité quasi-infinie de molécules","La chimie des métaux","La chimie des minéraux"]'::jsonb, 'L''étude des composés du carbone (sauf CO, CO₂, carbonates) ; le C est tétravalent, forme 4 liaisons covalentes, des chaînes et cycles, permettant une diversité quasi-infinie de molécules', 'Le carbone forme plus de 10 millions de composés connus ; sa capacité à former des chaînes (catenation) est unique.', 'Facile'),
    (chap_id, 'Quels sont les groupes fonctionnels principaux en chimie organique et leurs propriétés ?', '["Uniquement les alcools","Alcool (-OH), aldéhyde (-CHO), cétone (C=O), acide carboxylique (-COOH), amine (-NH₂), ester (-COO-) ; chaque groupe confère des propriétés chimiques spécifiques","Uniquement les acides","Uniquement les esters"]'::jsonb, 'Alcool (-OH), aldéhyde (-CHO), cétone (C=O), acide carboxylique (-COOH), amine (-NH₂), ester (-COO-) ; chaque groupe confère des propriétés chimiques spécifiques', 'Les groupes fonctionnels déterminent la réactivité ; une molécule peut en avoir plusieurs (ex. acides aminés : -NH₂ + -COOH).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''isomérie en chimie organique et quels en sont les types ?', '["Des molécules identiques","Des composés de même formule brute mais de structures différentes : isomères constitutionnels (chaîne, position, fonction) et stéréoisomères (géométrique Z/E, optique R/S)","Des molécules de masses différentes","Des allotropes du carbone"]'::jsonb, 'Des composés de même formule brute mais de structures différentes : isomères constitutionnels (chaîne, position, fonction) et stéréoisomères (géométrique Z/E, optique R/S)', 'La thalidomide (R = sédatif, S = tératogène) illustre l''importance dramatique de la stéréoisomérie en pharmacologie.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les réactions de substitution nucléophile (SN1/SN2) en chimie organique ?', '["Des réactions d''oxydation","Des réactions où un nucléophile (riche en e⁻) remplace un groupe partant (X) sur un carbone ; SN2 : bimolécule, inversion de configuration ; SN1 : unimolécule, racémisation","Des réactions d''addition uniquement","Des réactions de polymérisation"]'::jsonb, 'Des réactions où un nucléophile (riche en e⁻) remplace un groupe partant (X) sur un carbone ; SN2 : bimolécule, inversion de configuration ; SN1 : unimolécule, racémisation', 'SN2 : substrat primaire + nucléophile fort ; SN1 : substrat tertiaire + nucléophile faible, via carbocation intermédiaire.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la polymérisation et ses types principaux ?', '["La décomposition des polymères","La réaction assemblant de nombreuses petites molécules (monomères) en une longue chaîne (polymère) ; types : addition (polyéthylène) et condensation (Nylon, polyester) avec ou sans élimination d''eau","Une réaction de combustion","Une réaction d''hydrolyse"]'::jsonb, 'La réaction assemblant de nombreuses petites molécules (monomères) en une longue chaîne (polymère) ; types : addition (polyéthylène) et condensation (Nylon, polyester) avec ou sans élimination d''eau', 'Les polymères sont omniprésents : plastiques (PE, PP, PVC), fibres synthétiques (Nylon, Dacron), caoutchouc, biopolymères (ADN, protéines).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la nomenclature IUPAC des composés organiques et ses règles de base ?', '["Un système arbitraire","Un système international basant le nom sur la chaîne carbonée la plus longue (méthane/éthane/propane... = 1/2/3... carbones), les ramifications et les groupes fonctionnels","Le nom vulgaire des composés","Un système uniquement français"]'::jsonb, 'Un système international basant le nom sur la chaîne carbonée la plus longue (méthane/éthane/propane... = 1/2/3... carbones), les ramifications et les groupes fonctionnels', 'IUPAC : méth(1C)-éth(2C)-prop(3C)-but(4C)-pent(5C)-hex(6C) + suffixe selon fonction (-ane,-ène,-anol,-al,-one,-anoïque,-anoate).', 'Moyen'),
    (chap_id, 'Qu''est-ce que les hydrocarbures aromatiques (benzène et dérivés) et leurs propriétés ?', '["Des composés aliphatiques","Des composés cycliques insaturés stabilisés par délocalisation d''électrons (aromaticité) ; le benzène (C₆H₆) et ses dérivés (toluène, naphtalène) sont peu réactifs aux additions mais réactifs en substitution","Des alcanes cycliques","Des polymères naturels"]'::jsonb, 'Des composés cycliques insaturés stabilisés par délocalisation d''électrons (aromaticité) ; le benzène (C₆H₆) et ses dérivés (toluène, naphtalène) sont peu réactifs aux additions mais réactifs en substitution', 'L''aromaticité (critère de Hückel : 4n+2 électrons π) confère stabilité exceptionnelle ; le benzène est cancérigène avéré.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les lipides en chimie organique et leur structure ?', '["Des glucides","Des biomolécules hydrophobes incluant triglycérides (esters glycérol+acides gras), phospholipides (membranes), stérols (cholestérol, hormones stéroïdes)","Des protéines non polaires","Des acides nucléiques"]'::jsonb, 'Des biomolécules hydrophobes incluant triglycérides (esters glycérol+acides gras), phospholipides (membranes), stérols (cholestérol, hormones stéroïdes)', 'La saponification (hydrolyse basique des triglycérides) produit du savon et du glycérol ; connue depuis l''Antiquité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les glucides (saccharides) et leur structure en chimie organique ?', '["Des lipides","Des biomolécules de formule générale (CH₂O)n comprenant monosaccharides (glucose, fructose), disaccharides (saccharose, lactose) et polysaccharides (amidon, cellulose, glycogène)","Des acides aminés","Des nucléotides"]'::jsonb, 'Des biomolécules de formule générale (CH₂O)n comprenant monosaccharides (glucose, fructose), disaccharides (saccharose, lactose) et polysaccharides (amidon, cellulose, glycogène)', 'Le glucose (C₆H₁₂O₆) est la principale source d''énergie cellulaire ; la cellulose (même formule que l''amidon, liaison β-1,4) est indigeste.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la chimie verte (chimie durable) et ses 12 principes ?', '["La chimie des plantes vertes","La philosophie de conception chimique minimisant l''utilisation et la génération de substances dangereuses, réduisant les déchets, utilisant des réactifs renouvelables et des processus économes en énergie","La chimie uniquement biologique","La chimie des pesticides"]'::jsonb, 'La philosophie de conception chimique minimisant l''utilisation et la génération de substances dangereuses, réduisant les déchets, utilisant des réactifs renouvelables et des processus économes en énergie', 'Les 12 principes de la chimie verte (Anastas & Warner, 1998) guident l''industrie chimique vers la durabilité et la prévention de la pollution.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Électrochimie et applications' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une pile électrochimique et comment produit-elle de l''électricité ?', '["Un condensateur","Un dispositif transformant l''énergie chimique en énergie électrique via une réaction redox spontanée ; à l''anode (oxydation) les e⁻ circulent vers la cathode (réduction) via un circuit externe","Un transformateur","Un générateur mécanique"]'::jsonb, 'Un dispositif transformant l''énergie chimique en énergie électrique via une réaction redox spontanée ; à l''anode (oxydation) les e⁻ circulent vers la cathode (réduction) via un circuit externe', 'La pile de Volta (1800) est la première pile électrochimique ; les piles modernes (lithium-ion) fonctionnent sur le même principe.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''électrolyse et comment diffère-t-elle d''une pile galvanique ?', '["L''électrolyse est spontanée","L''électrolyse utilise de l''électricité pour forcer une réaction chimique non spontanée (inverse d''une pile) ; applications : raffinage des métaux, galvanoplastie, production de chlore et aluminium","L''électrolyse produit de l''électricité","L''électrolyse et la pile sont identiques"]'::jsonb, 'L''électrolyse utilise de l''électricité pour forcer une réaction chimique non spontanée (inverse d''une pile) ; applications : raffinage des métaux, galvanoplastie, production de chlore et aluminium', 'La production d''aluminium (Hall-Héroult) et de chlore (électrolyse de NaCl) sont des procédés industriels majeurs par électrolyse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la corrosion et comment la prévenir ?', '["Un processus bénéfique","La dégradation électrochimique d''un métal en milieu humide/acide (réaction redox spontanée) ; prévention : revêtements protecteurs, protection cathodique, alliages résistants (acier inoxydable)","Un simple ternissement","Une réaction de combustion"]'::jsonb, 'La dégradation électrochimique d''un métal en milieu humide/acide (réaction redox spontanée) ; prévention : revêtements protecteurs, protection cathodique, alliages résistants (acier inoxydable)', 'La corrosion coûte ~3,4% du PIB mondial annuellement ; en Haïti, le climat tropical humide et salin accélère la rouille des infrastructures.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la force électromotrice (FEM) d''une pile et comment la calculer ?', '["La résistance interne","E = E°_cathode - E°_anode (potentiels standards de réduction) ; si E > 0, la réaction est spontanée ; la FEM diminue avec l''utilisation selon la loi de Nernst","La charge de la pile","L''intensité du courant"]'::jsonb, 'E = E°_cathode - E°_anode (potentiels standards de réduction) ; si E > 0, la réaction est spontanée ; la FEM diminue avec l''utilisation selon la loi de Nernst', 'La FEM (Volta) mesure la «pression» électrique de la pile ; E°(Zn²⁺/Zn) = -0,76 V vs SHE (électrode de référence).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une batterie lithium-ion et pourquoi domine-t-elle dans les appareils portables ?', '["Une pile zinc-carbone améliorée","Une batterie rechargeable où les ions Li⁺ migrent entre électrodes de graphite et d''oxyde de cobalt-lithium, offrant haute densité d''énergie, légèreté et longue durée de vie, contrairement aux batteries Ni-Cd","Une batterie au plomb","Une batterie à combustible"]'::jsonb, 'Une batterie rechargeable où les ions Li⁺ migrent entre électrodes de graphite et d''oxyde de cobalt-lithium, offrant haute densité d''énergie, légèreté et longue durée de vie, contrairement aux batteries Ni-Cd', 'Goodenough, Whittingham et Yoshino (Nobel 2019) ont développé les batteries Li-ion ; elles équipent smartphones, laptops et véhicules électriques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les lois de Faraday en électrolyse ?', '["Des lois de la thermodynamique","1ère : la masse déposée est proportionnelle à la charge électrique : m = (M × I × t) / (n × F) ; 2ème : à même charge, les masses déposées sont proportionnelles aux masses molaires divisées par la charge","Les lois d''Ohm généralisées","Les lois de Newton appliquées aux ions"]'::jsonb, '1ère : la masse déposée est proportionnelle à la charge électrique : m = (M × I × t) / (n × F) ; 2ème : à même charge, les masses déposées sont proportionnelles aux masses molaires divisées par la charge', 'F = 96 485 C/mol (constante de Faraday) = charge d''une mole d''électrons ; les lois de Faraday sont fondamentales pour l''industrie électrolytique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les piles à combustible et leur potentiel pour l''énergie propre ?', '["Des batteries rechargeables classiques","Des dispositifs électrochimiques convertissant directement un combustible (hydrogène, méthane) en électricité via une réaction redox, avec eau et chaleur comme seuls sous-produits pour H₂/O₂","Des moteurs à explosion améliorés","Des panneaux solaires"]'::jsonb, 'Des dispositifs électrochimiques convertissant directement un combustible (hydrogène, méthane) en électricité via une réaction redox, avec eau et chaleur comme seuls sous-produits pour H₂/O₂', 'Les piles à combustible à H₂ (Toyota Mirai, bus à hydrogène) ont un rendement ~60% vs ~25-30% pour les moteurs thermiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la photochimie et l''effet photovoltaïque en chimie ?', '["Un type de chromographie","L''étude des réactions déclenchées par la lumière ; l''effet photovoltaïque dans les cellules solaires au silicium (semi-conducteur) convertit les photons en électrons via la création de paires électron-trou dans une jonction p-n","Un type d''électrolyse","Un procédé de synthèse thermique"]'::jsonb, 'L''étude des réactions déclenchées par la lumière ; l''effet photovoltaïque dans les cellules solaires au silicium (semi-conducteur) convertit les photons en électrons via la création de paires électron-trou dans une jonction p-n', 'Les cellules photovoltaïques (rendement ~15-22%) sont une source d''énergie prometteuse pour Haïti (fort ensoleillement caribéen).', 'Moyen'),
    (chap_id, 'Comment la chimie contribue-t-elle à la sécurité alimentaire et à l''agriculture en Haïti ?', '["La chimie n''a aucun rôle en agriculture","La chimie fournit les engrais minéraux (NPK), les pesticides, les herbicides, et les biotechnologies agricoles ; en Haïti, l''accès limité aux intrants chimiques de qualité et les alternatives organiques (compostage, biofertilisants) sont des enjeux majeurs","Uniquement les pesticides","Uniquement les engrais chimiques"]'::jsonb, 'La chimie fournit les engrais minéraux (NPK), les pesticides, les herbicides, et les biotechnologies agricoles ; en Haïti, l''accès limité aux intrants chimiques de qualité et les alternatives organiques (compostage, biofertilisants) sont des enjeux majeurs', 'La révolution verte (Borlaug) a multiplié les rendements via N-P-K et OGM ; les alternatives agro-écologiques sont essentielles dans les pays à faibles intrants.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la spectroscopie et son utilisation en chimie analytique ?', '["Une technique de séparation","L''ensemble des techniques d''analyse basées sur l''interaction de la matière avec les ondes électromagnétiques (IR, UV-Vis, RMN, masse) permettant d''identifier et de quantifier les composés chimiques","Une méthode de synthèse","Une technique de filtration"]'::jsonb, 'L''ensemble des techniques d''analyse basées sur l''interaction de la matière avec les ondes électromagnétiques (IR, UV-Vis, RMN, masse) permettant d''identifier et de quantifier les composés chimiques', 'La RMN (IRM médicale), la spectrométrie de masse (protéomique), l''IR (identification fonctionnels) sont les outils analytiques de référence.', 'Moyen');
  END IF;
END $$;
