-- Supplement Biologie (matiere_id=11) — NS1 et NS2
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'La cellule : unité du vivant' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la théorie cellulaire fondamentale formulée au XIXe siècle ?', '["Les cellules se forment spontanément","Toute cellule provient d''une cellule préexistante, et la cellule est l''unité de base du vivant","Les cellules ne se divisent pas","Seules les cellules animales ont un noyau"]'::jsonb, 'Toute cellule provient d''une cellule préexistante, et la cellule est l''unité de base du vivant', 'Schleiden, Schwann et Virchow ont établi la théorie cellulaire : omnis cellula e cellula.', 'Facile'),
    (chap_id, 'Quelle est la principale différence entre cellule procaryote et eucaryote ?', '["La taille","La présence ou l''absence d''un noyau membranaire","La présence de ribosomes","La présence d''ADN"]'::jsonb, 'La présence ou l''absence d''un noyau membranaire', 'Les procaryotes (bactéries) n''ont pas de noyau délimité par une membrane ; les eucaryotes en ont un.', 'Facile'),
    (chap_id, 'Quel organite est responsable de la synthèse des protéines ?', '["Le noyau","La mitochondrie","Le ribosome","Le réticulum endoplasmique"]'::jsonb, 'Le ribosome', 'Les ribosomes lisent l''ARNm et assemblent les acides aminés en protéines (traduction).', 'Facile'),
    (chap_id, 'Quelle est la fonction principale de la mitochondrie ?', '["Synthèse des protéines","Production d''ATP par respiration cellulaire aérobie","Stockage de l''ADN","Digestion intracellulaire"]'::jsonb, 'Production d''ATP par respiration cellulaire aérobie', 'La mitochondrie est la «centrale énergétique» de la cellule : elle produit l''ATP via le cycle de Krebs et la chaîne respiratoire.', 'Facile'),
    (chap_id, 'Quelle est la composition de la membrane plasmique selon le modèle de la mosaïque fluide ?', '["Uniquement des protéines","Une bicouche phospholipidique avec des protéines insérées","De l''ADN et des lipides","Du glucose et des acides aminés"]'::jsonb, 'Une bicouche phospholipidique avec des protéines insérées', 'Singer et Nicolson (1972) ont proposé le modèle de mosaïque fluide : bicouche de phospholipides avec protéines intégrales et périphériques.', 'Moyen'),
    (chap_id, 'Quel organite est exclusif aux cellules végétales et permet la photosynthèse ?', '["La mitochondrie","Le chloroplaste","La vacuole","Le centrosome"]'::jsonb, 'Le chloroplaste', 'Les chloroplastes contiennent la chlorophylle et sont le siège de la photosynthèse chez les végétaux.', 'Facile'),
    (chap_id, 'Qu''est-ce que le réticulum endoplasmique rugueux (RER) ?', '["Un organite de dégradation","Un réseau de membranes parsemé de ribosomes, synthétisant et triant les protéines sécrétées","Le siège de la photosynthèse","Un organite de stockage énergétique"]'::jsonb, 'Un réseau de membranes parsemé de ribosomes, synthétisant et triant les protéines sécrétées', 'Le RER synthétise les protéines destinées à être sécrétées ou intégrées aux membranes, aidé des ribosomes attachés.', 'Moyen'),
    (chap_id, 'Quelle est la fonction de l''appareil de Golgi ?', '["Synthèse d''ADN","Tri, modification et emballage des protéines en vésicules pour l''exportation","Production d''énergie","Digestion des déchets cellulaires"]'::jsonb, 'Tri, modification et emballage des protéines en vésicules pour l''exportation', 'L''appareil de Golgi reçoit du RER, modifie les protéines (glycosylation) et les dirige vers leur destination finale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la paroi cellulaire végétale et quel est son composant principal ?', '["Une membrane lipidique riche en protéines","Une enveloppe rigide externe composée principalement de cellulose","Un organite interne","Une structure exclusivement animale"]'::jsonb, 'Une enveloppe rigide externe composée principalement de cellulose', 'La paroi cellulaire végétale en cellulose confère rigidité et protection ; les cellules animales n''en ont pas.', 'Facile'),
    (chap_id, 'Quel est le rôle du lysosome dans la cellule animale ?', '["Photosynthèse","Digestion des macromolécules et des organites endommagés par des enzymes hydrolytiques","Production d''ATP","Synthèse des lipides"]'::jsonb, 'Digestion des macromolécules et des organites endommagés par des enzymes hydrolytiques', 'Les lysosomes (pH acide) dégradent les déchets cellulaires et les particules ingérées par endocytose.', 'Moyen'),
    (chap_id, 'Comment se réalise la diffusion simple à travers la membrane plasmique ?', '["Du milieu le moins concentré vers le plus concentré avec dépense d''énergie","Du milieu le plus concentré vers le moins concentré, sans énergie","Uniquement pour les ions","Uniquement pour les grandes molécules"]'::jsonb, 'Du milieu le plus concentré vers le moins concentré, sans énergie', 'La diffusion simple est passive et suit le gradient de concentration ; elle ne nécessite pas d''ATP.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''osmose et son importance pour les cellules vivantes ?', '["Le transport actif du glucose","Le mouvement de l''eau à travers une membrane semi-perméable du milieu hypotonique vers le milieu hypertonique","La diffusion des ions","Le transport des protéines"]'::jsonb, 'Le mouvement de l''eau à travers une membrane semi-perméable du milieu hypotonique vers le milieu hypertonique', 'L''osmose explique la turgescence des cellules végétales et la lyse ou plasmolysis cellulaire.', 'Moyen'),
    (chap_id, 'Quel microscope utilise-t-on pour observer la structure interne fine d''une cellule (ultrastructure) ?', '["Le microscope optique","Le microscope électronique à transmission (MET)","La loupe binoculaire","Le microscope à fluorescence"]'::jsonb, 'Le microscope électronique à transmission (MET)', 'Le MET utilise des électrons et atteint une résolution de l''ordre du nanomètre, révélant les organites.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la spécialisation cellulaire (différenciation) dans les organismes pluricellulaires ?', '["Toutes les cellules d''un organisme sont identiques","Le processus par lequel des cellules identiques au départ acquièrent des structures et fonctions différentes selon l''expression différentielle des gènes","La division cellulaire","La mort programmée des cellules"]'::jsonb, 'Le processus par lequel des cellules identiques au départ acquièrent des structures et fonctions différentes selon l''expression différentielle des gènes', 'Neurones, globules rouges, cellules musculaires ont le même ADN mais expriment des gènes différents.', 'Moyen'),
    (chap_id, 'Quel est le rôle du centrosome dans la division cellulaire ?', '["Synthèse des protéines","Organisation du fuseau mitotique permettant la ségrégation des chromosomes","Production d''énergie","Stockage des nutriments"]'::jsonb, 'Organisation du fuseau mitotique permettant la ségrégation des chromosomes', 'Le centrosome (avec ses centrioles) nucléarise les microtubules du fuseau qui séparent les chromosomes.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'La division cellulaire : mitose et méiose' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la différence fondamentale entre mitose et méiose en termes de résultats ?', '["Aucune différence","La mitose produit 2 cellules diploïdes identiques ; la méiose produit 4 cellules haploïdes génétiquement différentes","La mitose produit 4 cellules ; la méiose en produit 2","La méiose est plus rapide que la mitose"]'::jsonb, 'La mitose produit 2 cellules diploïdes identiques ; la méiose produit 4 cellules haploïdes génétiquement différentes', 'La mitose conserve la ploïdie (2n→2n) ; la méiose la réduit (2n→n) pour la reproduction sexuée.', 'Facile'),
    (chap_id, 'Dans quel ordre se succèdent les phases de la mitose ?', '["Interphase, anaphase, prophase, métaphase, télophase","Prophase, métaphase, anaphase, télophase","Métaphase, prophase, anaphase, télophase","Anaphase, métaphase, télophase, prophase"]'::jsonb, 'Prophase, métaphase, anaphase, télophase', 'La mitose suit l''ordre PMAT : Prophase (condensation), Métaphase (alignement), Anaphase (séparation), Télophase (reconstitution noyaux).', 'Facile'),
    (chap_id, 'Qu''est-ce que la cytocinèse et quand se produit-elle ?', '["La condensation des chromosomes","La division du cytoplasme se produisant après la télophase pour former deux cellules filles","La séparation des chromatides","La réplication de l''ADN"]'::jsonb, 'La division du cytoplasme se produisant après la télophase pour former deux cellules filles', 'Après la caryocinèse (division nucléaire), la cytocinèse divise le cytoplasme et complète la division.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le crossing-over (enjambement) en méiose et son importance ?', '["Une mutation délétère","L''échange de segments homologues entre chromosomes pendant la méiose I, créant de nouvelles combinaisons génétiques","Une réplication d''ADN supplémentaire","Un arrêt de la division cellulaire"]'::jsonb, 'L''échange de segments homologues entre chromosomes pendant la méiose I, créant de nouvelles combinaisons génétiques', 'Le crossing-over est une source majeure de variabilité génétique ; il se produit au stade pachytène de la prophase I.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le cycle cellulaire et quelles en sont les phases principales ?', '["Uniquement la mitose","L''ensemble des étapes de la vie d''une cellule : interphase (G1, S, G2) + phase mitotique","La différenciation cellulaire","La mort cellulaire programmée"]'::jsonb, 'L''ensemble des étapes de la vie d''une cellule : interphase (G1, S, G2) + phase mitotique', 'Le cycle cellulaire comprend l''interphase (préparation, réplication ADN) et la division (mitose + cytocinèse).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un chromosome homologue et comment diffère-t-il d''une chromatide sœur ?', '["Ils sont identiques","Les chromosomes homologues sont des paires de même taille et séquence, une d''origine maternelle/paternelle ; les chromatides sœurs sont les deux copies d''un chromosome répliqué","Les chromatides sœurs sont différentes génétiquement","Les chromosomes homologues sont toujours identiques"]'::jsonb, 'Les chromosomes homologues sont des paires de même taille et séquence, une d''origine maternelle/paternelle ; les chromatides sœurs sont les deux copies d''un chromosome répliqué', 'Distinction essentielle : homologues (paires parentales) vs chromatides sœurs (copies après réplication, reliées au centromère).', 'Moyen'),
    (chap_id, 'Quel est le rôle des points de contrôle (checkpoints) du cycle cellulaire ?', '["Accélérer la division","Vérifier que chaque phase est correctement complétée avant de passer à la suivante, évitant les erreurs génétiques","Arrêter définitivement la division","Permettre la différenciation cellulaire"]'::jsonb, 'Vérifier que chaque phase est correctement complétée avant de passer à la suivante, évitant les erreurs génétiques', 'Les checkpoints G1/S, G2/M et spindle assembly contrôlent la fidélité de la division ; leurs défauts favorisent le cancer.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''apoptose et quel est son rôle dans l''organisme ?', '["Une division cellulaire rapide","La mort cellulaire programmée permettant d''éliminer les cellules endommagées ou en surnombre","Une mutation génétique","Un processus uniquement pathologique"]'::jsonb, 'La mort cellulaire programmée permettant d''éliminer les cellules endommagées ou en surnombre', 'L''apoptose est essentielle au développement embryonnaire, à l''immunité et à la prévention des tumeurs.', 'Moyen'),
    (chap_id, 'En méiose, à quelle phase les chromosomes homologues se séparent-ils ?', '["Anaphase II","Anaphase I","Métaphase I","Prophase II"]'::jsonb, 'Anaphase I', 'En anaphase I, les paires de chromosomes homologues (bivalents) se séparent vers les pôles opposés (réduction de ploïdie).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la polyploïdie et dans quel règne est-elle fréquente ?', '["Une diminution du nombre de chromosomes","La présence de plus de deux sets de chromosomes, fréquente chez les végétaux","Une anomalie létale","Un phénomène uniquement animal"]'::jsonb, 'La présence de plus de deux sets de chromosomes, fréquente chez les végétaux', 'La polyploïdie (ex. blé hexaploïde 6n=42) est courante chez les plantes cultivées et contribue à leur évolution.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la spermatogenèse et où se déroule-t-elle ?', '["La formation des ovules dans les ovaires","La formation des spermatozoïdes par méiose dans les testicules","La fécondation","La nidation de l''embryon"]'::jsonb, 'La formation des spermatozoïdes par méiose dans les testicules', 'La spermatogenèse se déroule dans les tubes séminifères des testicules ; elle produit 4 spermatozoïdes haploïdes par méiose.', 'Moyen'),
    (chap_id, 'Quel est l''effet d''une non-disjonction chromosomique en méiose ?', '["Des cellules normales","Des gamètes avec un chromosome en plus ou en moins, pouvant causer des trisomies comme la trisomie 21","Une polyploïdie","Un arrêt de la méiose"]'::jsonb, 'Des gamètes avec un chromosome en plus ou en moins, pouvant causer des trisomies comme la trisomie 21', 'La non-disjonction (échec de séparation chromosomique) produit des gamètes aneuploïdes ; la trisomie 21 en résulte souvent.', 'Moyen'),
    (chap_id, 'Pourquoi la méiose est-elle essentielle à la reproduction sexuée des organismes diploïdes ?', '["Elle augmente le nombre de chromosomes","Elle réduit la ploïdie de moitié, garantissant que la fécondation rétablit le nombre chromosomique diploïde normal","Elle empêche la variation génétique","Elle remplace la mitose"]'::jsonb, 'Elle réduit la ploïdie de moitié, garantissant que la fécondation rétablit le nombre chromosomique diploïde normal', 'Sans la méiose (2n→n), la fécondation (n+n) produirait un organisme avec le double de chromosomes à chaque génération.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Génétique : hérédité et lois de Mendel' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la première loi de Mendel (loi de ségrégation) ?', '["Les deux allèles d''un gène se retrouvent toujours ensemble dans le gamète","Les deux allèles d''un gène se séparent pendant la méiose, chaque gamète n''en portant qu''un seul","Les gènes sont transmis en blocs","Les allèles dominants masquent toujours les récessifs"]'::jsonb, 'Les deux allèles d''un gène se séparent pendant la méiose, chaque gamète n''en portant qu''un seul', 'La 1ère loi de Mendel (ségrégation allélique) découle directement de la méiose : chaque gamète reçoit un allèle par gène.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la deuxième loi de Mendel (loi d''assortiment indépendant) ?', '["Les gènes proches sur un chromosome sont toujours transmis ensemble","Les allèles de deux gènes situés sur des chromosomes différents se distribuent indépendamment lors de la méiose","Les gènes sont tous liés","La dominance est toujours complète"]'::jsonb, 'Les allèles de deux gènes situés sur des chromosomes différents se distribuent indépendamment lors de la méiose', 'La 2ème loi s''applique aux gènes non liés (chromosomes différents) ; les gènes liés ne la respectent pas.', 'Moyen'),
    (chap_id, 'Dans un croisement Aa × Aa, quelle est la proportion phénotypique attendue si A est dominant ?', '["1/4 dominant : 3/4 récessif","3/4 dominant : 1/4 récessif","1/2 dominant : 1/2 récessif","Tous dominants"]'::jsonb, '3/4 dominant : 1/4 récessif', 'Croisement hétérozygote : génotypes 1/4 AA + 2/4 Aa (phénotype dominant) + 1/4 aa (récessif) → 3:1.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un allèle récessif et comment s''exprime-t-il ?', '["Un allèle qui s''exprime toujours","Un allèle qui ne s''exprime phénotypiquement qu''à l''état homozygote (aa), masqué par l''allèle dominant à l''état hétérozygote","Un allèle dominant","Un allèle léthal"]'::jsonb, 'Un allèle qui ne s''exprime phénotypiquement qu''à l''état homozygote (aa), masqué par l''allèle dominant à l''état hétérozygote', 'La récessivité est définie par rapport au dominant : en présence de A, a n''est pas exprimé phénotypiquement.', 'Facile'),
    (chap_id, 'Qu''est-ce que la codominance et quel en est un exemple classique ?', '["Une dominance partielle où le phénotype est intermédiaire","L''expression simultanée et complète des deux allèles chez l''hétérozygote, comme les groupes sanguins AB","L''absence d''expression phénotypique","Une liaison génique"]'::jsonb, 'L''expression simultanée et complète des deux allèles chez l''hétérozygote, comme les groupes sanguins AB', 'En codominance (ex. groupe AB), les deux allèles s''expriment pleinement ; ce n''est pas une dominance incomplète.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la liaison génique (linkage) et son effet sur la 2ème loi de Mendel ?', '["Des gènes sur le même chromosome qui tendent à être transmis ensemble, violant la 2ème loi de Mendel","Des gènes sur des chromosomes différents","Un phénomène exclusivement végétal","Une mutation"]'::jsonb, 'Des gènes sur le même chromosome qui tendent à être transmis ensemble, violant la 2ème loi de Mendel', 'Les gènes liés ne s''assortiront pas indépendamment, sauf si des crossing-over sont suffisamment fréquents entre eux.', 'Moyen'),
    (chap_id, 'Comment les groupes sanguins ABO sont-ils déterminés génétiquement ?', '["Par un seul gène biallélique","Par un gène à 3 allèles (IA, IB, i) dont IA et IB sont codominants et i est récessif","Par deux gènes distincts","Par l''environnement uniquement"]'::jsonb, 'Par un gène à 3 allèles (IA, IB, i) dont IA et IB sont codominants et i est récessif', 'Le système ABO est un exemple classique d''allélisme multiple (3 allèles) avec codominance de IA et IB.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''hérédité liée au sexe (hérédité gonosomique) ?', '["Un mode de transmission identique chez les deux sexes","La transmission de gènes portés sur les chromosomes sexuels (X ou Y), avec des ratios différents selon le sexe","Une maladie génétique","L''hérédité maternelle uniquement"]'::jsonb, 'La transmission de gènes portés sur les chromosomes sexuels (X ou Y), avec des ratios différents selon le sexe', 'Les gènes liés au chromosome X s''expriment davantage chez les mâles (XY) n''ayant qu''un seul allèle X.', 'Moyen'),
    (chap_id, 'Quel est le résultat d''un croisement test (testcross) entre un individu de génotype inconnu et un individu homozygote récessif ?', '["Uniquement des individus dominants","Les proportions phénotypiques révèlent directement le génotype de l''individu inconnu","Tous les individus seront hétérozygotes","Le résultat ne donne aucune information"]'::jsonb, 'Les proportions phénotypiques révèlent directement le génotype de l''individu inconnu', 'Le testcross (croisement-test) est la méthode de Mendel pour déterminer si un phénotype dominant est homo- ou hétérozygote.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la pléiotropie en génétique ?', '["Un gène contrôlant un seul caractère","Un gène influençant plusieurs caractères phénotypiques différents","Plusieurs gènes contrôlant un seul caractère","Une mutation létale"]'::jsonb, 'Un gène influençant plusieurs caractères phénotypiques différents', 'Ex. : la drépanocytose (mutation de la β-globine) affecte les globules rouges, les os, le cœur, les reins simultanément.', 'Moyen'),
    (chap_id, 'Comment calcule-t-on la fréquence de recombinaison entre deux gènes liés ?', '["On ne peut pas la calculer","En divisant le nombre de descendants recombinants par le total de descendants × 100 (en centiMorgans)","En comparant les allèles dominants","Par la formule de Hardy-Weinberg"]'::jsonb, 'En divisant le nombre de descendants recombinants par le total de descendants × 100 (en centiMorgans)', 'La fréquence de recombinaison (= pourcentage de descendants recombinants) estime la distance génétique entre loci.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''épistasie en génétique ?', '["La dominance allélique","L''interaction entre deux gènes différents où l''un masque l''expression de l''autre","La codominance","Une mutation létale"]'::jsonb, 'L''interaction entre deux gènes différents où l''un masque l''expression de l''autre', 'L''épistasie (entre gènes) diffère de la dominance (entre allèles d''un même gène) : ex. gène A épisatique sur gène B.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Structure et fonction des molécules biologiques' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la structure de base d''un acide aminé ?', '["Un groupement carboxyle seul","Un carbone central (Cα) portant un groupement amine (-NH2), un carboxyle (-COOH), un hydrogène et une chaîne latérale (R)","Un acide gras et un alcool","Un nucléotide"]'::jsonb, 'Un carbone central (Cα) portant un groupement amine (-NH2), un carboxyle (-COOH), un hydrogène et une chaîne latérale (R)', 'Les 20 acides aminés standards diffèrent uniquement par leur chaîne latérale R qui détermine leurs propriétés.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une liaison peptidique et comment se forme-t-elle ?', '["Une liaison hydrogène entre protéines","Une liaison covalente entre le groupement carboxyle d''un acide aminé et le groupement amine du suivant, libérant de l''eau (condensation)","Une liaison ionique","Une liaison hydrophobe"]'::jsonb, 'Une liaison covalente entre le groupement carboxyle d''un acide aminé et le groupement amine du suivant, libérant de l''eau (condensation)', 'La liaison peptidique (-CO-NH-) unit les acides aminés en chaîne ; c''est une réaction de condensation (déshydratation).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la structure secondaire d''une protéine ?', '["La séquence en acides aminés","La conformation locale stabilisée par des liaisons hydrogène : hélice α et feuillet β","Les interactions à longue portée de la chaîne","L''assemblage de plusieurs chaînes peptidiques"]'::jsonb, 'La conformation locale stabilisée par des liaisons hydrogène : hélice α et feuillet β', 'La structure secondaire (hélice α, feuillet β plissé) résulte de liaisons H entre les groupements NH et C=O du squelette.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la dénaturation d''une protéine ?', '["La synthèse d''une protéine","La perte de la structure tridimensionnelle (et donc de la fonction) par rupture des liaisons non covalentes sous l''effet de la chaleur, du pH, etc.","La dégradation en acides aminés","La traduction de l''ARNm"]'::jsonb, 'La perte de la structure tridimensionnelle (et donc de la fonction) par rupture des liaisons non covalentes sous l''effet de la chaleur, du pH, etc.', 'La dénaturation (ex. cuisson d''un œuf) est souvent irréversible ; elle détruit l''activité enzymatique.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre un acide gras saturé et insaturé ?', '["Ils ont des formules différentes","Les acides gras saturés n''ont pas de double liaison C-C ; les insaturés en ont au moins une, les rendant plus fluides à basse température","Les saturés sont liquides et les insaturés solides","Les insaturés ont plus de carbones"]'::jsonb, 'Les acides gras saturés n''ont pas de double liaison C-C ; les insaturés en ont au moins une, les rendant plus fluides à basse température', 'Les doubles liaisons introduisent des coudes dans la chaîne carbonée, empêchant le tassement et abaissant le point de fusion.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''ATP et pourquoi est-il la "monnaie énergétique" de la cellule ?', '["Un acide aminé","L''adénosine triphosphate, molécule dont l''hydrolyse libère de l''énergie libre utilisable par toutes les réactions cellulaires","Un lipide","Un glucide"]'::jsonb, 'L''adénosine triphosphate, molécule dont l''hydrolyse libère de l''énergie libre utilisable par toutes les réactions cellulaires', 'L''ATP (adénosine-5''-triphosphate) libère ~7,3 kcal/mol lors de son hydrolyse ; c''est l''intermédiaire énergétique universel.', 'Facile'),
    (chap_id, 'Quelle est la différence entre un monosaccharide, un disaccharide et un polysaccharide ?', '["Ils ont des fonctions identiques","Les monosaccharides sont des sucres simples (glucose, fructose) ; les disaccharides sont deux sucres liés (saccharose) ; les polysaccharides sont des longues chaînes (amidon, cellulose)","Ils diffèrent par leur composition en acides aminés","Les polysaccharides sont des lipides"]'::jsonb, 'Les monosaccharides sont des sucres simples (glucose, fructose) ; les disaccharides sont deux sucres liés (saccharose) ; les polysaccharides sont des longues chaînes (amidon, cellulose)', 'Les glucides varient de simples (énergétiques) à complexes (énergétiques/structuraux selon leur structure).', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un nucléotide et quelle est sa structure ?', '["Un acide aminé","Une molécule composée d''un sucre pentose (ribose ou désoxyribose), d''un groupement phosphate et d''une base azotée","Un acide gras","Un polysaccharide"]'::jsonb, 'Une molécule composée d''un sucre pentose (ribose ou désoxyribose), d''un groupement phosphate et d''une base azotée', 'Les nucléotides sont les monomères de l''ADN et de l''ARN ; leur base azotée distingue les différents nucléotides.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre l''ADN et l''ARN en termes de structure ?', '["Ils sont identiques","L''ADN est double brin avec désoxyribose et thymine ; l''ARN est simple brin avec ribose et uracile","L''ARN est double brin","L''ADN contient de l''uracile"]'::jsonb, 'L''ADN est double brin avec désoxyribose et thymine ; l''ARN est simple brin avec ribose et uracile', 'ADN (double hélice, désoxyribose, A-T-G-C) vs ARN (simple brin, ribose, A-U-G-C) reflètent leurs fonctions distinctes.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une enzyme et comment catalyse-t-elle une réaction ?', '["Un substrat","Un biocatalyseur protéique abaissant l''énergie d''activation d''une réaction sans être consommé, grâce à son site actif spécifique","Un produit de réaction","Un lipide membranaire"]'::jsonb, 'Un biocatalyseur protéique abaissant l''énergie d''activation d''une réaction sans être consommé, grâce à son site actif spécifique', 'Les enzymes (biocatalyseurs) accélèrent les réactions sans modifier l''équilibre thermodynamique ni être consommées.', 'Facile'),
    (chap_id, 'Qu''est-ce que la spécificité enzymatique et comment s''explique-t-elle ?', '["Les enzymes catalysent toutes les réactions","Chaque enzyme ne catalyse qu''un type de réaction/substrat grâce à la complémentarité de forme et chimique entre site actif et substrat (modèle clé-serrure ou «induced fit»)","Les enzymes fonctionnent sans substrat","La spécificité enzymatique dépend du pH uniquement"]'::jsonb, 'Chaque enzyme ne catalyse qu''un type de réaction/substrat grâce à la complémentarité de forme et chimique entre site actif et substrat (modèle clé-serrure ou «induced fit»)', 'La spécificité enzymatique est la base de la régulation métabolique ; elle est déterminée par la structure tertiaire.', 'Moyen'),
    (chap_id, 'Comment le pH et la température affectent-ils l''activité enzymatique ?', '["Ils n''ont aucun effet","Chaque enzyme a un pH et une température optimaux ; au-delà des valeurs optimales, l''activité diminue et la dénaturation peut survenir","Les enzymes fonctionnent mieux à pH basique","La température n''affecte pas les enzymes"]'::jsonb, 'Chaque enzyme a un pH et une température optimaux ; au-delà des valeurs optimales, l''activité diminue et la dénaturation peut survenir', 'Les enzymes humaines ont généralement un optimum de ~37°C et pH 7,4 ; les enzymes digestives varient (pepsine pH 2).', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Métabolisme : photosynthèse et respiration cellulaire' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est l''équation globale de la photosynthèse ?', '["C6H12O6 + 6O2 → 6CO2 + 6H2O","6CO2 + 6H2O + lumière → C6H12O6 + 6O2","CO2 + H2O → sucre","6O2 + lumière → 6CO2"]'::jsonb, '6CO2 + 6H2O + lumière → C6H12O6 + 6O2', 'La photosynthèse convertit l''énergie lumineuse en énergie chimique (glucose) en fixant le CO2 et en libérant O2.', 'Facile'),
    (chap_id, 'Où se déroulent les réactions lumineuses (phase claire) de la photosynthèse ?', '["Dans la matrice du chloroplaste (stroma)","Dans les membranes des thylakoïdes du chloroplaste","Dans les mitochondries","Dans le cytoplasme"]'::jsonb, 'Dans les membranes des thylakoïdes du chloroplaste', 'Les thylakoïdes contiennent les photosystèmes I et II ; c''est là que se réalisent la photolyse de l''eau et la production d''ATP/NADPH.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le cycle de Calvin (phase sombre) de la photosynthèse ?', '["Les réactions de la phase claire","La fixation du CO2 en glucides en utilisant l''ATP et le NADPH produits par les réactions lumineuses, dans le stroma","La respiration cellulaire","La photolyse de l''eau"]'::jsonb, 'La fixation du CO2 en glucides en utilisant l''ATP et le NADPH produits par les réactions lumineuses, dans le stroma', 'Le cycle de Calvin (Calvin-Benson) fixe le CO2 via la RuBisCO et produit du G3P précurseur du glucose.', 'Moyen'),
    (chap_id, 'Quelle est l''équation globale de la respiration cellulaire aérobie ?', '["6CO2 + 6H2O → C6H12O6 + 6O2","C6H12O6 + 6O2 → 6CO2 + 6H2O + ATP","Glucose → acide lactique","Glucose + lumière → ATP"]'::jsonb, 'C6H12O6 + 6O2 → 6CO2 + 6H2O + ATP', 'La respiration aérobie est l''inverse de la photosynthèse ; elle dégrade le glucose pour produire de l''ATP.', 'Facile'),
    (chap_id, 'Quelles sont les trois étapes principales de la respiration cellulaire aérobie ?', '["Glycolyse uniquement","Glycolyse (cytoplasme), cycle de Krebs (matrice mitochondriale), chaîne respiratoire (membrane interne mitochondriale)","Photosynthèse, glycolyse, fermentation","Cycle de Calvin, glycolyse, ATP-synthase"]'::jsonb, 'Glycolyse (cytoplasme), cycle de Krebs (matrice mitochondriale), chaîne respiratoire (membrane interne mitochondriale)', 'La respiration aérobie produit ~36-38 ATP/glucose : 2 en glycolyse, 2 en cycle de Krebs, ~32-34 en chaîne respiratoire.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la fermentation et dans quelles conditions se produit-elle ?', '["La respiration aérobie","La production d''ATP en absence d''O2 (anaérobie), régénérant le NAD+ pour permettre la glycolyse de continuer","La photosynthèse","La dégradation des lipides"]'::jsonb, 'La production d''ATP en absence d''O2 (anaérobie), régénérant le NAD+ pour permettre la glycolyse de continuer', 'Fermentation lactique (muscles) ou alcoolique (levures) : ne produit que 2 ATP/glucose, mais fonctionne sans O2.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le coefficient respiratoire (CR) et que révèle-t-il ?', '["La quantité d''ATP produite","Le rapport CO2 produit / O2 consommé, indicateur du substrat oxydé (CR=1 glucides, ~0,7 lipides, ~0,8 protéines)","La quantité d''eau produite","Le taux de photosynthèse"]'::jsonb, 'Le rapport CO2 produit / O2 consommé, indicateur du substrat oxydé (CR=1 glucides, ~0,7 lipides, ~0,8 protéines)', 'Le CR permet de déterminer quelle molécule est préférentiellement oxydée lors de la respiration.', 'Moyen'),
    (chap_id, 'Quel est le rôle de l''ATP synthase dans la mitochondrie ?', '["Dégrader les protéines","Synthétiser l''ATP en utilisant le gradient de protons (H+) établi par la chaîne respiratoire (chimiosmose)","Transporter les électrons","Dégrader le glucose"]'::jsonb, 'Synthétiser l''ATP en utilisant le gradient de protons (H+) établi par la chaîne respiratoire (chimiosmose)', 'L''ATP synthase est une enzyme rotatrice ; le flux de protons à travers elle entraîne la phosphorylation de l''ADP en ATP.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre l''autotrophie et l''hétérotrophie ?', '["Aucune différence nutritionnelle","Les autotrophes synthétisent leur propre matière organique à partir de CO2 (photosynthèse) ; les hétérotrophes doivent consommer de la matière organique préformée","Les hétérotrophes font la photosynthèse","Les autotrophes ne respirent pas"]'::jsonb, 'Les autotrophes synthétisent leur propre matière organique à partir de CO2 (photosynthèse) ; les hétérotrophes doivent consommer de la matière organique préformée', 'Plantes et algues = autotrophes ; animaux et champignons = hétérotrophes. Tous respirent (si aérobies).', 'Facile'),
    (chap_id, 'Comment la concentration en CO2 affecte-t-elle le taux de photosynthèse ?', '["Elle n''a aucun effet","Jusqu''à une concentration optimale, une augmentation de CO2 augmente le taux de photosynthèse (facteur limitant)","Le CO2 inhibe la photosynthèse","Le CO2 n''est pas utilisé en photosynthèse"]'::jsonb, 'Jusqu''à une concentration optimale, une augmentation de CO2 augmente le taux de photosynthèse (facteur limitant)', 'La loi du minimum : la photosynthèse est limitée par le facteur le plus déficitaire (lumière, CO2, température).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le point de compensation photosynthétique ?', '["Le maximum de photosynthèse","L''intensité lumineuse à laquelle la photosynthèse brute égale la respiration, le bilan net de CO2 étant nul","L''absence totale de photosynthèse","La saturation en chlorophylle"]'::jsonb, 'L''intensité lumineuse à laquelle la photosynthèse brute égale la respiration, le bilan net de CO2 étant nul', 'En-dessous du point de compensation, la plante consomme plus de matière organique qu''elle n''en produit.', 'Moyen');
  END IF;
END $$;
