-- Supplement Histoire-Géographie (matiere_id=13) — NS3 et NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 13 AND titre = 'Les deux guerres mondiales et la recomposition du monde' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelles sont les principales causes de la Première Guerre mondiale (1914-1918) ?', '["Uniquement l''assassinat de Franz Ferdinand","Un faisceau de causes","Un conflit commercial uniquement","Une révolution socialiste"]'::jsonb, 'Un faisceau de causes', 'Le modèle MAIN (Militarisme, Alliances, Impérialisme, Nationalisme) explique l''embrasement rapide de l''Europe en 1914.', 'Moyen'),
    (chap_id, 'Quelles sont les conséquences du Traité de Versailles (1919) sur l''Allemagne et le monde ?', '["Des conditions modérées","Des conditions humiliantes (clause de","Un traité équitable","Un traité bénéfique pour l''Allemagne"]'::jsonb, 'Des conditions humiliantes (clause de', 'Keynes (1919) critiqua le Traité comme économiquement insoutenable ; Hitler en fera l''un de ses chevaux de bataille.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Shoah (Holocauste) et combien de victimes a-t-elle causées ?', '["Un événement mineur","Le génocide systématique des Juifs","Une guerre civile","Un bombardement isolé"]'::jsonb, 'Le génocide systématique des Juifs', 'La «Solution finale» (Wannsee, 1942) organisée par les SS a industrialisé le meurtre de masse à Auschwitz, Treblinka, etc.', 'Moyen'),
    (chap_id, 'Quelles sont les principales causes de la Deuxième Guerre mondiale ?', '["La Première Guerre mondiale seule","Le traité humiliant de Versailles","Un conflit territorial uniquement","Une révolution communiste mondiale"]'::jsonb, 'Le traité humiliant de Versailles', 'La chaîne causale WWI → Versailles → crise économique → nazisme → WWII illustre l''enchaînement des catastrophes du XXe siècle.', 'Moyen'),
    (chap_id, 'Quel est le rôle de la bombe atomique dans la fin de la Seconde Guerre mondiale ?', '["Elle n''a pas eu d''impact","Les bombes d''Hiroshima (6 août 1945) et","Elles ont été utilisées en Europe","Elles n''ont pas causé de victimes"]'::jsonb, 'Les bombes d''Hiroshima (6 août 1945) et', 'Hiroshima (~140 000 morts) et Nagasaki (~70 000 morts) : les deux seules utilisations en guerre de l''arme nucléaire à ce jour.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''ONU et pourquoi a-t-elle été créée en 1945 ?', '["Une organisation économique","Une organisation internationale créée","Une alliance militaire","Un tribunal international uniquement"]'::jsonb, 'Une organisation internationale créée', 'L''ONU (1945, 51 membres fondateurs dont Haïti) repose sur la Charte de San Francisco ; aujourd''hui 193 États membres.', 'Facile'),
    (chap_id, 'Qu''est-ce que la décolonisation et comment s''est-elle déroulée après 1945 ?', '["Un phénomène mineur","Le processus d''accession à","Un cadeau des puissances coloniales","Un processus uniquement africain"]'::jsonb, 'Le processus d''accession à', 'La décolonisation a été accélérée par la Charte de l''ONU (droit des peuples), les mouvements nationalistes et l''affaiblissement des métropoles.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Guerre froide et quels en ont été les principaux moments de crise ?', '["Un conflit armé direct","L''affrontement idéologique et","Un conflit exclusivement économique","Une alliance militaire"]'::jsonb, 'L''affrontement idéologique et', 'La Guerre froide a divisé le monde en blocs ; les pays du Tiers-Monde comme Haïti en ont subi les conséquences indirectes.', 'Moyen'),
    (chap_id, 'Quelle a été la relation entre Haïti et les États-Unis au XXe siècle, notamment l''occupation américaine ?', '["Relations inexistantes","L''occupation américaine d''Haïti","Une alliance militaire exclusive","Une relation purement commerciale"]'::jsonb, 'L''occupation américaine d''Haïti', 'L''occupation américaine (1915-1934) a désarmé l''armée haïtienne, pris le contrôle des finances et laissé des séquelles identitaires profondes.', 'Moyen'),
    (chap_id, 'Quel a été le règne des Duvalier et son impact sur Haïti ?', '["Une période de démocratie","Une dictature familiale (François","Une brève parenthèse militaire","Une période de prospérité"]'::jsonb, 'Une dictature familiale (François', 'Le duvaliérisme a paralysé le développement haïtien pendant 29 ans et causé une diaspora de cerveaux vers les USA, Canada, France.', 'Moyen'),
    (chap_id, 'Quelle est la signification de la révolution cubaine de 1959 pour les Caraïbes et l''Amérique latine ?', '["Un événement mineur","Le renversement de Batista par Castro a","Une révolution pro-américaine","Une révolution pacifique sans impact"]'::jsonb, 'Le renversement de Batista par Castro a', 'La révolution cubaine a polarisé les Caraïbes et conduit les USA à soutenir des dictateurs comme Duvalier pour éviter une «deuxième Cuba».', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Conférence de Bandung (1955) et le mouvement des Non-Alignés ?', '["Un sommet des grandes puissances","La conférence de 29 pays","Un traité militaire","Une organisation économique"]'::jsonb, 'La conférence de 29 pays', 'Bandung (1955) a fondé le Tiers-Monde politique ; les 5 principes de coexistence pacifique y ont été proclamés.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 13 AND titre = 'Mondialisation et enjeux géopolitiques contemporains' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la mondialisation et quelles en sont les dimensions principales ?', '["L''uniformisation culturelle","L''intensification des échanges","Un phénomène uniquement économique","La domination américaine"]'::jsonb, 'L''intensification des échanges', 'La mondialisation contemporaine (post-1989) s''appuie sur : conteneurisation, télécommunications, libéralisation financière.', 'Moyen'),
    (chap_id, 'Quel est le rôle des organisations économiques internationales (FMI, Banque mondiale, OMC) ?', '["Des organisations humanitaires","Des institutions de gouvernance","Des organisations militaires","Des organisations régionales uniquement"]'::jsonb, 'Des institutions de gouvernance', 'Ces institutions de Bretton Woods (1944) ont imposé des programmes d''ajustement structurel à Haïti dans les années 1990-2000.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géopolitique des ressources naturelles et comment structure-t-elle les relations internationales ?', '["Les ressources n''ont pas d''impact","Le contrôle des ressources (pétrole","Les ressources sont équitablement distribuées","La géopolitique concerne uniquement les frontières"]'::jsonb, 'Le contrôle des ressources (pétrole', 'Le pétrole (Moyen-Orient), les terres rares (Chine) et l''eau douce (aquifères partagés) sont des enjeux géopolitiques majeurs du XXIe s.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''émergence des pays BRICS et leur impact sur l''ordre mondial ?', '["Des pays en développement mineurs","L''essor du Brésil","Un groupe exclusivement asiatique","Un regroupement commercial de niche"]'::jsonb, 'L''essor du Brésil', 'La Chine (2ème PIB mondial) et l''Inde (le plus peuplé) changent le centre de gravité économique vers le Sud et l''Est.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le changement climatique comme enjeu géopolitique majeur du XXIe siècle ?', '["Un problème purement scientifique","Un enjeu qui menace la sécurité des","Un problème limité aux pôles","Un enjeu uniquement économique"]'::jsonb, 'Un enjeu qui menace la sécurité des', 'Haïti (<0,1% des émissions mondiales) est parmi les 10 pays les plus vulnérables au CC selon les indices ND-GAIN et GCRI.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Communauté des Caraïbes (CARICOM) et quel est son rôle pour Haïti ?', '["Une organisation militaire","Une organisation régionale","Une zone de libre-échange mondiale","Un organisme des Nations Unies"]'::jsonb, 'Une organisation régionale', 'Haïti est membre du CARICOM depuis 2002 ; les Caraïbes représentent un marché régional et un espace politique collectif.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la question de la migration internationale et ses enjeux pour Haïti ?', '["Un phénomène marginal","La diaspora haïtienne (~2 millions de","La migration ne concerne pas Haïti","Un phénomène uniquement illégal"]'::jsonb, 'La diaspora haïtienne (~2 millions de', 'Les transferts de la diaspora représentent ~20-30% du PIB haïtien ; ils surpassent l''aide internationale et les investissements directs étrangers.', 'Moyen'),
    (chap_id, 'Comment comprendre les relations haïtiano-dominicaines dans un contexte géopolitique régional ?', '["Des relations toujours hostiles","Des relations complexes sur une île","Des relations d''égalité totale","Des relations sans histoire"]'::jsonb, 'Des relations complexes sur une île', 'Le massacre de Parsley (1937, ~15 000 Haïtiens tués) et la décision de la Cour constitutionnelle dominicaine (2013) d''apatridie restent des tensions majeures.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la communauté internationale et l''aide au développement : le cas d''Haïti ?', '["L''aide résout tous les problèmes","L''aide internationale à Haïti","L''aide n''a aucun effet","Haïti ne reçoit pas d''aide internationale"]'::jsonb, 'L''aide internationale à Haïti', 'Le livre «Dead Aid» de Dambisa Moyo et les critiques post-séisme 2010 ont révélé les limites structurelles de l''aide en Haïti.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la gouvernance mondiale et ses défis actuels ?', '["Un gouvernement mondial unifié","L''ensemble des institutions","La domination d''un seul État","Un idéal irréalisable"]'::jsonb, 'L''ensemble des institutions', 'La COVID-19 et les COP climatiques ont mis en lumière les limites de la gouvernance mondiale face à des crises transnationales.', 'Moyen'),
    (chap_id, 'Comment la géographie physique d''Haïti influence-t-elle sa vulnérabilité aux catastrophes naturelles ?', '["Elle n''influence pas la vulnérabilité","Sa position dans la zone sismique des","Sa géographie est protectrice","Sa vulnérabilité est uniquement sociale"]'::jsonb, 'Sa position dans la zone sismique des', 'L''IVD (Indice de Vulnérabilité aux Désastres) d''Haïti est parmi les plus élevés du monde ; les séismes, cyclones et inondations s''additionnent.', 'Moyen'),
    (chap_id, 'Quel est le mouvement mondial des droits de l''homme depuis 1948 et ses avancées et limites ?', '["Un mouvement récent sans impact","La DUDH (1948) a établi des standards","Les droits de l''homme sont uniquement théoriques","Les droits sont uniquement civils et politiques"]'::jsonb, 'La DUDH (1948) a établi des standards', 'La CPI (1998), les tribunaux ad hoc (Rwanda, ex-Yougoslavie) représentent des avancées ; l''universalité des droits reste contestée.', 'Difficile');
  END IF;
END $$;
