-- Supplément Français NS3-NS4 (matiere_id=25) — +18 questions/chapitre

-- Chapitre 1 : Stylistique et rhétorique avancées NS3
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Stylistique et rhétorique avancées' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la "stylistique" comme discipline ?', '["L''étude des styles vestimentaires dans la littérature", "L''étude scientifique du style littéraire", "L''étude des figures de style uniquement", "L''étude de la grammaire normative"]'::jsonb, 'L''étude scientifique du style littéraire', 'La stylistique est la discipline qui étudie le style d''un texte de façon systématique : elle analyse les choix linguistiques (lexique, syntaxe, rythme, figures) et cherche à comprendre comment ils produisent des effets de sens. Elle est à la croisée de la linguistique et de l''analyse littéraire.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"ethos" dans la rhétorique classique ?', '["L''émotion provoquée chez l''auditeur", "L''image de soi que l''orateur projette", "L''argument logique et rationnel", "Le style littéraire utilisé par l''auteur"]'::jsonb, 'L''image de soi que l''orateur projette', 'La rhétorique aristotélicienne distingue trois moyens de persuasion : ethos (crédibilité de l''orateur, image qu''il projette), pathos (appel aux émotions du public) et logos (argument rationnel). L''ethos concerne l''autorité, la compétence et la vertu morale que l''orateur cherche à projeter.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "polyphonie" dans un texte littéraire (concept de Bakhtine) ?', '["Un texte écrit par plusieurs auteurs", "La coexistence de plusieurs voix", "Un texte qui utilise plusieurs langues", "Un texte avec plusieurs niveaux de narration"]'::jsonb, 'La coexistence de plusieurs voix', 'Mikhaïl Bakhtine a développé le concept de polyphonie romanesque : le roman (surtout chez Dostoïevski) donne voix à plusieurs consciences autonomes sans les soumettre à une vision unique de l''auteur. Chaque personnage a sa propre vision du monde. C''est l''opposé du monologisme où l''auteur impose sa perspective.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "syllepse de sens" (ou syllepse rhétorique) comme figure de style avancée ?', '["Une figure d''analogie entre deux éléments éloignés", "L''emploi d''un mot dans deux sens", "La répétition d''un même son dans une phrase", "L''accumulation de qualificatifs pour un même nom"]'::jsonb, 'L''emploi d''un mot dans deux sens', 'La syllepse de sens exploite l''ambiguïté d''un mot employé dans deux acceptions en même temps : "Ma pensée est noire" (noire = sombre moralement + couleur noire littéralement). C''est une figure d''ambivalence sémantique qui crée un jeu de sens et une profondeur d''interprétation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "prolepse" comme figure de narration ?', '["Une anticipation dans le récit", "Un retour en arrière dans le temps narratif", "Une pause descriptive qui arrête le cours de l''histoire", "Une ellipse qui supprime une période de l''histoire"]'::jsonb, 'Une anticipation dans le récit', 'La prolepse (ou anticipation, flash-forward) consiste à raconter ou mentionner à l''avance des événements futurs par rapport au moment où se situe le récit : "Plus tard, il comprendrait que ce jour avait tout changé." Son opposé est l''analepse (retour en arrière). Ces procédés temporels structurent la chronologie narrative.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"isotopie" en analyse sémantique d''un texte ?', '["La répétition d''un même mot dans un texte", "La récurrence de traits sémantiques", "La présence de synonymes dans un texte", "L''étude des temps verbaux dans un texte"]'::jsonb, 'La récurrence de traits sémantiques', 'L''isotopie (concept de Greimas) désigne la récurrence de sèmes (unités minimales de sens) qui assurent la cohérence d''un texte. Par exemple, dans un poème sur l''automne, les isotopies de la chute, du déclin et de la mélancolie se renforcent mutuellement et créent un réseau de sens cohérent.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "zeugme" comme figure de style ?', '["La répétition d''un mot en début de phrase", "La construction d''un verbe avec", "La comparaison entre deux objets très similaires", "L''utilisation de synonymes pour éviter les répétitions"]'::jsonb, 'La construction d''un verbe avec', 'Le zeugme (ou attelage) unit sous un même verbe des compléments de nature différente ou incompatible : "Il prit son chapeau et congé." (on prend un objet et une action). Cela crée un effet comique, poétique ou critique par le rapprochement inattendu. Prévert en use fréquemment.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "logos" dans la rhétorique aristotélicienne ?', '["L''appel aux émotions du public", "La crédibilité de l''orateur", "L''argument logique et rationnel qui", "Le style élaboré du discours"]'::jsonb, 'L''argument logique et rationnel qui', 'Le logos est le troisième moyen de persuasion chez Aristote (avec ethos et pathos). Il désigne la dimension logique et rationnelle de l''argumentation : les preuves, les syllogismes, les exemples, les raisonnements par induction ou déduction. Une argumentation efficace articule les trois dimensions.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "diégèse" et l''"extradiégèse" dans la narratologie ?', '["La diégèse est le style du narrateur ; l''extradiégèse est le style des personnages", "La diégèse est l''univers fictif de", "La diégèse est la partie descriptive du récit ; l''extradiégèse est la partie dialoguée", "La diégèse est le temps de la lecture ; l''extradiégèse est le temps de l''histoire"]'::jsonb, 'La diégèse est l''univers fictif de', 'La diégèse (terme de Genette) désigne l''univers fictif de l''histoire : les personnages, les lieux et le temps du récit. Un élément est "intradiégeétique" s''il appartient à cet univers. Un narrateur "extradiégétique" raconte de l''extérieur ; un narrateur "homodiégétique" fait partie de l''histoire qu''il raconte (ex. Meursault dans L''Étranger).', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "registre épique" et quels sont ses procédés caractéristiques ?', '["Un registre qui exprime la mélancolie par des métaphores délicates", "Un registre qui magnifie les actions", "Un registre qui cherche à provoquer le rire par des jeux de mots", "Un registre qui dénonce les vices de la société par l''ironie"]'::jsonb, 'Un registre qui magnifie les actions', 'Le registre épique exalte et magnifie : les héros accomplissent des exploits surhumains. Ses procédés : hyperboles ("des milliers de guerriers"), périphrases héroïques ("le maître des dieux"), rythme ample, vocabulaire de la grandeur et de la gloire. On le trouve dans les épopées (Iliade, Chanson de Roland) mais aussi dans les romans historiques et certains textes politiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"épanalepse" comme figure de style ?', '["La répétition d''un mot ou groupe de", "La reprise d''un mot à la fin d''une phrase pour commencer la phrase suivante", "L''accumulation de synonymes pour intensifier un effet", "La suppression d''un mot sous-entendu dans la phrase"]'::jsonb, 'La répétition d''un mot ou groupe de', 'L''épanalepse répète un terme en position encadrante (début et fin) : "La femme était là, souriante, indestructible, la femme." Cette structure cyclique crée un effet d''insistance et une mise en valeur du terme répété. Elle différe de l''anaphore (répétition en début de phrases successives) et de l''épiphore (répétition en fin).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "parataxe" et l''"hypotaxe" en stylistique ?', '["La parataxe est une figure de style ; l''hypotaxe est une faute de syntaxe", "La parataxe juxtapose des propositions", "La parataxe est utilisée en poésie ; l''hypotaxe dans la prose", "La parataxe et l''hypotaxe sont deux noms pour la même construction syntaxique"]'::jsonb, 'La parataxe juxtapose des propositions', 'La parataxe juxtapose sans lien explicite : "Il vint, il vit, il vainquit." Effet : rapidité, force, ambiguïté des liens logiques. L''hypotaxe hiérarchise par des subordonnées : "Parce qu''il vint voir la situation, il put la conquérir." Effet : clarté logique, complexité intellectuelle. La parataxe est liée à l''asyndète (suppression de conjonctions).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "métalepse" en narratologie ?', '["Une ellipse temporelle dans le récit", "Un franchissement des frontières entre", "Une comparaison entre deux récits différents", "La répétition d''un même épisode raconté deux fois"]'::jsonb, 'Un franchissement des frontières entre', 'La métalepse (Genette) est une transgression des frontières entre niveaux narratifs : le narrateur descend dans son histoire ("Pendant que Madame Bovary finit de dîner, nous allons voir...") ou les personnages en sortent (Woody Allen dans La Rose pourpre du Caire). Elle brise l''illusion fictionnelle et met en évidence la construction du récit.', 'Difficile'),
    (chap_id, 'Quel est le rôle de la "cadence" dans l''analyse stylistique d''un texte ?', '["La cadence désigne uniquement le rythme musical dans la poésie en vers", "La cadence désigne le rythme des phrases", "La cadence est uniquement l''étude des pauses dans un texte", "La cadence désigne la longueur totale du texte"]'::jsonb, 'La cadence désigne le rythme des phrases', 'La cadence est l''organisation rythmique de la phrase. Cadence mineure : fin avec un segment court, effet de rapidité ou de chute. Cadence majeure : fin longue et ample, effet de solennité et de conclusion. Cadence équilibrée : segments de même longueur, équilibre et harmonie. L''analyse de la cadence est essentielle dans l''étude du style oratoire et du rythme de la prose.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "chiasme" comme figure de style avancée ?', '["La répétition d''un mot en écho dans deux phrases successives", "La disposition en miroir d''éléments de", "L''opposition entre deux idées dans la même phrase", "L''accumulation de termes synonymes"]'::jsonb, 'La disposition en miroir d''éléments de', 'Le chiasme dispose les éléments en miroir : "Il faut manger pour vivre, et non vivre pour manger" (A-B-B-A). Il crée une symétrie inversée qui souligne une opposition ou renforce une idée par la structure même. Racine y recourt : "Je t''aimais inconstant : qu''aurais-je fait fidèle ?" (Andromaque).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"hypallage" comme figure de style ?', '["Une répétition intensificatrice", "Le transfert d''un qualificatif d''un", "Une question sans réponse attendue", "Une gradation descendante de termes"]'::jsonb, 'Le transfert d''un qualificatif d''un', 'L''hypallage attribue un qualificatif à un nom autre que celui auquel il se rapporte logiquement : "Il traversa les rues coupables de la ville" (ce sont les habitants qui sont coupables, pas les rues). "La fatigue heureuse du soir" (c''est le travailleur qui est heureux). Cette figure crée une vision synthétique et poétique du monde.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "modalisation" dans l''énonciation et à quoi sert-elle ?', '["L''utilisation des modes verbaux (subjonctif, conditionnel)", "L''expression de l''attitude du locuteur", "Le changement de registre de langue dans un texte", "L''organisation temporelle du discours"]'::jsonb, 'L''expression de l''attitude du locuteur', 'La modalisation marque la subjectivité de l''énonciateur envers son propos : modalisateurs de certitude (certainement, évidemment), de doute (peut-être, il semble que), d''appréciation (heureusement, malheureusement), guillemets de distance ironique. Elle révèle l''implication ou la prise de distance du locuteur par rapport à ce qu''il dit.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"anacoluthe" comme figure de style ou faute de style ?', '["Une rupture de construction syntaxique", "La répétition d''une même construction syntaxique dans plusieurs phrases successives", "L''omission volontaire d''un verbe dans une proposition", "L''inversion du sujet et du verbe à des fins stylistiques"]'::jsonb, 'Une rupture de construction syntaxique', 'L''anacoluthe est une rupture de construction : "Rentrant à la maison, la nuit était tombée" (le sujet grammatical change entre la participiale et la principale). Considérée comme faute en style courant, elle peut être délibérée pour mimer le désordre mental d''un personnage, la précipitation ou l''émotion. Céline l''utilise fréquemment dans son style fragmenté.', 'Difficile');
  END IF;
END $$;

-- Chapitre 2 : Littérature francophone : Caraïbe, Afrique et Antilles NS3
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Littérature francophone : Caraïbe, Afrique et Antilles' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui est l''auteur du "Cahier d''un retour au pays natal" (1939/1947), œuvre fondatrice de la Négritude ?', '["Léopold Sédar Senghor", "Frantz Fanon", "Aimé Césaire", "Édouard Glissant"]'::jsonb, 'Aimé Césaire', 'Aimé Césaire (1913-2008), poète et homme politique martiniquais, a écrit le Cahier d''un retour au pays natal, long poème fondateur de la Négritude. Il y affirme la fierté de l''identité noire et dénonce le colonialisme. Il est aussi l''auteur du Discours sur le colonialisme (1950) et de nombreuses pièces de théâtre.', 'Facile'),
    (chap_id, 'Qu''est-ce que la "Créolité" comme mouvement littéraire et culturel antillais ?', '["Un mouvement qui défend l''assimilation complète à la culture française", "Un mouvement qui affirme l''identité", "Un mouvement qui rejette l''écriture en français au profit du créole", "Un mouvement exclusivement politique sans dimension littéraire"]'::jsonb, 'Un mouvement qui affirme l''identité', 'La Créolité (manifeste d''Éloge de la créolité, 1989, par Chamoiseau, Confiant et Bernabé) succède à la Négritude. Elle affirme l''identité créole comme mosaïque culturelle unique. Les auteurs (Patrick Chamoiseau, Raphaël Confiant) écrivent en français mais intègrent la langue, les proverbes et la culture créoles dans leurs œuvres.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la théorie de la "Relation" développée par Édouard Glissant ?', '["Une théorie qui défend la pureté des cultures nationales", "Une philosophie de la diversité", "Une théorie linguistique sur les langues créoles", "Une théorie politique sur la décolonisation"]'::jsonb, 'Une philosophie de la diversité', 'Édouard Glissant (1928-2011, Martinique) développe une pensée de la "Relation" : les identités ne sont pas des essences fixes ("racine unique") mais se construisent dans la rencontre et le métissage ("rhizome"). Son concept de "Tout-Monde" célèbre la diversité culturelle comme richesse. Œuvres : Le Discours antillais, Poétique de la Relation.', 'Difficile'),
    (chap_id, 'Quel roman de Patrick Chamoiseau a remporté le Prix Goncourt en 1992 et explore l''enfance créole martiniquaise ?', '["Solibo Magnifique", "Texaco", "Chronique des sept misères", "Biblique des derniers gestes"]'::jsonb, 'Texaco', 'Texaco (Prix Goncourt, 1992) de Patrick Chamoiseau est un roman polyphonique sur la fondation d''un quartier précaire de Fort-de-France (Martinique) par une femme, Marie-Sophie Laborieux. Il mêle créole et français, oralité et écriture, pour reconstituer l''histoire de la Martinique depuis l''esclavage jusqu''au XXe siècle.', 'Moyen'),
    (chap_id, 'Qui est Léopold Sédar Senghor et quelle est sa contribution à la littérature francophone ?', '["Romancier haïtien du mouvement indigéniste", "Poète et homme d''État sénégalais", "Philosophe martiniquais théoricien de la Créolité", "Auteur camerounais du roman Une vie de boy"]'::jsonb, 'Poète et homme d''État sénégalais', 'Léopold Sédar Senghor (1906-2001) est le co-fondateur de la Négritude avec Aimé Césaire et Léon-Gontran Damas. Poète, il célèbre l''Afrique et les valeurs de civilisation africaine (Chants d''ombre, 1945 ; Hosties noires, 1948). Premier président du Sénégal (1960-1980), il est aussi le premier Africain élu à l''Académie française (1983).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la littérature "postcoloniale" et quels sont ses thèmes récurrents ?', '["La littérature écrite dans les colonies avant l''indépendance", "Une littérature qui explore les", "La littérature des colons européens décrivant les pays colonisés", "Une littérature exclusivement politique sans valeur esthétique"]'::jsonb, 'Une littérature qui explore les', 'La littérature postcoloniale émerge après les indépendances et traite des héritages complexes du colonialisme : la décolonisation identitaire, la quête de langues et de formes d''expression propres, l''hybridité culturelle, les traumatismes de l''esclavage et de l''exploitation. Elle interroge la relation avec la langue du colonisateur (Français, Anglais...).', 'Moyen'),
    (chap_id, 'Qui a écrit "Les Bouts de bois de Dieu" (1960), roman sur la grève des cheminots Dakar-Niger de 1947-1948 ?', '["Mongo Beti", "Cheikh Hamidou Kane", "Ousmane Sembène", "Ahmadou Kourouma"]'::jsonb, 'Ousmane Sembène', 'Ousmane Sembène (1923-2007, Sénégal) est l''auteur des Bouts de bois de Dieu (1960), roman sur la grande grève des cheminots du Dakar-Niger de 1947-1948, qui met en scène la résistance collective africaine au colonialisme français. Sembène est aussi un cinéaste majeur de l''Afrique noire (Mandabi, Ceddo, Moolaadé).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "Créolisation" comme processus culturel selon Glissant ?', '["Le mélange biologique entre personnes de différentes origines", "Le processus imprévisible par lequel", "L''imitation de la culture européenne par les peuples colonisés", "La création d''une langue pidgin pour la communication interculturelle"]'::jsonb, 'Le processus imprévisible par lequel', 'La créolisation chez Glissant est différente du simple métissage (mélange de deux éléments). C''est un processus ouvert, imprévisible, où les éléments s''interpénètrent pour créer du nouveau. L''imprévisibilité est essentielle : on ne peut pas prédire le résultat. C''est une pensée de la complexité culturelle qui s''oppose aux identités figées.', 'Difficile'),
    (chap_id, 'Quel roman d''Ahmadou Kourouma (1970) dénonce les dérives des régimes politiques africains post-indépendance ?', '["Les Soleils des indépendances", "En attendant le vote des bêtes sauvages", "Monnè, outrages et défis", "Allah n''est pas obligé"]'::jsonb, 'Les Soleils des indépendances', 'Les Soleils des indépendances (1970) d''Ahmadou Kourouma (Côte d''Ivoire) est un roman fondateur de la littérature africaine. À travers Fama, prince malinké dépossédé par l''indépendance, Kourouma dénonce les désillusions des indépendances africaines. La langue est révolutionnaire : le français est "malinkisé", intégrant la vision du monde malinké.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "littérature de la Shoah" ou "littérature de témoignage" et quels en sont les enjeux ?', '["La littérature qui nie la Shoah", "Une littérature qui témoigne des", "Une littérature historique objective sur la Seconde Guerre mondiale", "Une littérature exclusivement autobiographique sans valeur littéraire"]'::jsonb, 'Une littérature qui témoigne des', 'La littérature de témoignage sur la Shoah pose la question de l''écriture de l''extrême. Adorno disait : "Écrire un poème après Auschwitz est barbare." Auteurs : Elie Wiesel (La Nuit), Primo Levi (Si c''est un homme), Robert Antelme (L''Espèce humaine), Imre Kertész. L''enjeu est de transmettre la mémoire sans trahir les victimes.', 'Difficile'),
    (chap_id, 'Qui est Frantz Fanon et quelle est sa contribution à la pensée anticoloniale ?', '["Poète martiniquais fondateur de la Négritude", "Psychiatre et penseur martiniquais", "Romancier sénégalais du réalisme africain", "Philosophe guadeloupéen de la Créolité"]'::jsonb, 'Psychiatre et penseur martiniquais', 'Frantz Fanon (1925-1961) a analysé les effets psychologiques du colonialisme sur le colonisé (Peau noire, masques blancs, 1952) et défendu la légitimité de la lutte armée pour la décolonisation (Les Damnés de la Terre, 1961, préfacé par Sartre). Il a participé à la Révolution algérienne comme psychiatre à Blida.', 'Moyen'),
    (chap_id, 'Quel est l''apport linguistique de la littérature francophone africaine et antillaise à la langue française ?', '["Elle utilise le français standard sans innovation", "Elle enrichit le français par des", "Elle remplace le français par les langues locales", "Elle simplifie la langue française pour la rendre accessible"]'::jsonb, 'Elle enrichit le français par des', 'Les auteurs francophones ne se contentent pas d''écrire "en français" : ils le réinventent. Kourouma "malinkise" le français, Chamoiseau y intègre le créole, Sony Labou Tansi (Congo) créé un "français africain" baroque. Ces "français pluriels" témoignent d''une appropriation créatrice de la langue du colonisateur, transformée en outil d''expression identitaire.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le roman "L''Aventure ambiguë" (1961) de Cheikh Hamidou Kane explore comme thème central ?', '["La vie quotidienne dans un village sénégalais traditionnel", "Le déchirement entre tradition", "La résistance armée contre le colonialisme français au Sénégal", "Les inégalités économiques dans l''Afrique post-coloniale"]'::jsonb, 'Le déchirement entre tradition', 'L''Aventure ambiguë de Cheikh Hamidou Kane met en scène Samba Diallo, envoyé en France pour faire ses études tout en restant attaché à la tradition islamique peule. Le roman explore le conflit identitaire entre deux cultures inconciliables, et la question de si l''Afrique peut s''approprier les savoirs occidentaux sans se perdre.', 'Moyen'),
    (chap_id, 'Quel est le mouvement littéraire haïtien des années 1920-1940, contemporain de la Négritude, qui valorise la culture et l''identité haïtiennes face à l''occupation américaine ?', '["La Créolité", "Le Surréalisme haïtien", "L''Indigénisme haïtien", "Le Réalisme merveilleux"]'::jsonb, 'L''Indigénisme haïtien', 'L''Indigénisme haïtien (La Revue Indigène, 1927) est un mouvement culturel et littéraire qui, face à l''occupation américaine (1915-1934), affirme l''identité haïtienne en valorisant les cultures africaines, le vodou, la langue créole et le paysan haïtien. Auteurs : Jean Price-Mars (Ainsi parla l''Oncle), Jacques Roumain (Gouverneurs de la rosée).', 'Moyen'),
    (chap_id, 'Quel roman de Jacques Roumain (1944) est considéré comme le chef-d''œuvre de la littérature haïtienne ?', '["La Montagne ensorcelée", "Les Fantoches", "Gouverneurs de la rosée", "Bois d''ébène"]'::jsonb, 'Gouverneurs de la rosée', 'Gouverneurs de la rosée (1944) de Jacques Roumain est le chef-d''œuvre de la littérature haïtienne. Manuel, revenu de Cuba après des années de travail, cherche à réconcilier sa communauté divisée et à trouver de l''eau. Le roman célèbre la beauté de la langue créole, le courage du paysan haïtien et la solidarité collective face à la misère.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "réalisme merveilleux" dans la littérature caribéenne et latino-américaine ?', '["Un style réaliste qui décrit minutieusement la réalité sans aucun élément fantastique", "Une esthétique qui intègre", "Un mouvement qui rejette la réalité au profit du rêve et de l''inconscient", "Un style de narration qui amplifie délibérément la réalité par l''hyperbole"]'::jsonb, 'Une esthétique qui intègre', 'Le "réalisme merveilleux" (Alejo Carpentier) et le "réalisme magique" (García Márquez) intègrent le surnaturel dans le quotidien. Dans la tradition haïtienne, les esprits vodou, les zombies et les forces surnaturelles font partie de la réalité culturelle. Cette esthétique s''oppose au réalisme européen rationnel en proposant une vision du monde alternative.', 'Moyen'),
    (chap_id, 'Quelle est l''importance de la notion de "diaspora" dans la littérature francophone contemporaine ?', '["La diaspora est un thème mineur de la littérature francophone", "La diaspora produit une littérature de", "La diaspora désigne uniquement les auteurs africains vivant en France", "La diaspora est un concept purement sociologique sans intérêt littéraire"]'::jsonb, 'La diaspora produit une littérature de', 'La littérature de la diaspora (auteurs africains, antillais, haïtiens vivant en France, aux États-Unis...) explore le déracinement, l''hybridité culturelle, la nostalgie et la reformulation identitaire. Auteurs : Edwidge Danticat (Haïti/États-Unis), Léonora Miano (Cameroun/France), Gauz (Côte d''Ivoire/France). Elle questionne la notion même de "littérature nationale".', 'Difficile');
  END IF;
END $$;

-- Chapitre 3 : Sociolinguistique : langues, société et politique linguistique NS3
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Sociolinguistique : langues, société et politique linguistique' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la "diglossie" selon Charles Ferguson ?', '["La capacité de parler deux langues de façon équivalente", "La coexistence dans une société de deux", "La disparition progressive d''une langue dominée", "Le mélange de deux langues dans un même discours"]'::jsonb, 'La coexistence dans une société de deux', 'La diglossie (Ferguson, 1959) décrit la coexistence de deux variétés linguistiques dans une communauté : la variété haute (H) pour les registres formels (éducation, religion, officiel) et la variété basse (B) pour la communication quotidienne. En Haïti : le français = H et le créole haïtien = B, même si le créole est la langue maternelle de toute la population.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "bilinguisme" et en quoi diffère-t-il du "multilinguisme" ?', '["Ce sont des synonymes exacts", "Le bilinguisme est la maîtrise de deux", "Le bilinguisme est naturel et le multilinguisme est artificiel", "Le bilinguisme est individuel et le multilinguisme est uniquement collectif"]'::jsonb, 'Le bilinguisme est la maîtrise de deux', 'Le bilinguisme individuel est la capacité de communiquer dans deux langues (pas nécessairement au même niveau). Le multilinguisme désigne soit la maîtrise de plusieurs langues par un individu, soit la coexistence de plusieurs langues dans un pays (ex. Suisse : 4 langues officielles). Haïti est officiellement bilingue (français et créole haïtien).', 'Facile'),
    (chap_id, 'Qu''est-ce que la "politique linguistique" d''un État ?', '["Les lois grammaticales officielles d''une langue", "L''ensemble des choix et mesures qu''un", "La censure des œuvres littéraires en langue étrangère", "Les règles d''orthographe imposées par l''Académie"]'::jsonb, 'L''ensemble des choix et mesures qu''un', 'La politique linguistique est l''intervention consciente d''un État ou d''une institution sur les langues : choisir une ou plusieurs langues officielles, décider de la langue d''enseignement, créer une académie pour normer la langue, protéger les langues minoritaires ou au contraire les réprimer. En Haïti, la Constitution de 1987 a reconnu le créole comme langue officielle à côté du français.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "code-switching" (ou alternance codique) en sociolinguistique ?', '["Une erreur de grammaire commise par des locuteurs bilingues", "Le passage d''une langue à une autre (ou", "La traduction simultanée d''un discours", "Le remplacement progressif d''une langue par une autre dans une société"]'::jsonb, 'Le passage d''une langue à une autre (ou', 'L''alternance codique (code-switching) est une pratique normale des bilingues : ils passent d''une langue à l''autre selon le contexte, l''interlocuteur, le sujet ou pour exprimer des nuances que l''autre langue ne peut pas rendre. Ce n''est pas une faute mais une compétence communicative. En Haïti, il est courant d''alterner créole et français dans la même conversation.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "langue créole" du point de vue linguistique ?', '["Un dialecte simplifié d''une langue européenne", "Une langue complète", "Un argot utilisé par les populations défavorisées", "Un mélange non systématique de plusieurs langues sans grammaire propre"]'::jsonb, 'Une langue complète', 'Les langues créoles (haïtien, martiniquais, réunionnais...) sont des langues à part entière, avec leur propre phonologie, grammaire et lexique. Elles sont nées dans des situations de contact colonial forcé (traite négrière) où des personnes de langues différentes ont dû communiquer. Elles ne sont pas des patois ni des langues "impures" — cette vision est un préjugé colonial.', 'Moyen'),
    (chap_id, 'Quel est le statut officiel du créole haïtien selon la Constitution haïtienne de 1987 ?', '["Le créole n''a aucun statut officiel en Haïti", "Le créole est l''unique langue officielle d''Haïti", "Le créole haïtien et le français sont", "Le créole est reconnu comme patrimoine culturel mais pas comme langue officielle"]'::jsonb, 'Le créole haïtien et le français sont', 'La Constitution haïtienne de 1987 a reconnu officiellement le créole haïtien et le français comme langues officielles d''Haïti. Avant 1987, seul le français était officiel alors que moins de 10% de la population le maîtrisait. Le créole est la langue maternelle de toute la population haïtienne. Cette reconnaissance constitutionnelle est une avancée dans la valorisation de l''identité haïtienne.', 'Facile'),
    (chap_id, 'Qu''est-ce que le "purisme linguistique" et quels sont ses effets ?', '["La défense de l''authenticité et de la", "La promotion de l''apprentissage des langues étrangères", "La simplification délibérée d''une langue pour la rendre accessible", "L''étude scientifique des langues sans jugement de valeur"]'::jsonb, 'La défense de l''authenticité et de la', 'Le purisme linguistique cherche à protéger la "pureté" d''une langue contre les emprunts, les néologismes et les évolutions populaires. En France, l''Académie française et les lois Toubon visent à défendre le français contre les anglicismes. Le purisme peut devenir discriminatoire lorsqu''il stigmatise les locuteurs qui ne parlent pas la variété "standard" (discriminations de classe, raciales).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"aménagement linguistique" et quels exemples peut-on citer ?', '["La traduction des textes officiels", "L''ensemble des interventions planifiées", "La censure des langues étrangères dans les médias", "L''étude historique de l''évolution d''une langue"]'::jsonb, 'L''ensemble des interventions planifiées', 'L''aménagement linguistique comprend : le corpus planning (réforme de l''orthographe, création de néologismes, standardisation de la grammaire) et le status planning (décision sur le statut officiel, langue d''enseignement). Exemple haïtien : la standardisation de l''orthographe du créole (IPN, 1979) est un corpus planning ; sa reconnaissance constitutionnelle (1987) est un status planning.', 'Difficile'),
    (chap_id, 'Comment définit-on le "registre de langue" (ou niveau de langue) en sociolinguistique ?', '["La qualité grammaticale d''un texte", "La variation de la langue selon le", "L''accent régional d''un locuteur", "Le niveau d''alphabétisation d''une population"]'::jsonb, 'La variation de la langue selon le', 'Le registre de langue désigne les variations stylistiques adaptées à la situation de communication : registre familier (entre amis, informel : "t''as", "y a"), courant (contexte standard), soutenu ou littéraire (contexte formel, écrit soigné). La maîtrise des registres est un enjeu social et scolaire majeur, car les registres inférieurs sont souvent dévalorisés socialement.', 'Facile'),
    (chap_id, 'Qu''est-ce que la "glottophobie" comme forme de discrimination ?', '["La peur irrationnelle des langues étrangères", "La discrimination ou la stigmatisation", "L''interdiction légale de parler certaines langues", "La peur de prendre la parole en public"]'::jsonb, 'La discrimination ou la stigmatisation', 'Le concept de glottophobie (Philippe Blanchet) désigne la discrimination exercée en raison du parler : moquer un accent, refuser un emploi à cause d''une façon de s''exprimer, stigmatiser les créolophones ou les régionalistes. C''est une forme de discrimination aussi grave que le racisme ou le sexisme, mais souvent non reconnue légalement.', 'Moyen'),
    (chap_id, 'Quel est le rôle de l''"Académie française" dans la politique linguistique française ?', '["Elle gouverne directement la France", "Elle est chargée de définir et de", "Elle supervise l''enseignement du français dans les écoles", "Elle protège uniquement les droits d''auteur des écrivains français"]'::jsonb, 'Elle est chargée de définir et de', 'Fondée en 1635 par Richelieu, l''Académie française est chargée de la normalisation du français : rédaction du Dictionnaire de l''Académie (9e édition en cours), émission de recommandations sur le vocabulaire (déconseille les anglicismes), prise de position sur les réformes orthographiques. Ses décisions sont consultatives et souvent contestées par les linguistes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "variation dialectale" d''une langue ?', '["Les erreurs commises par des locuteurs non natifs", "Les différences systématiques de", "Les changements d''une langue à travers le temps", "La différence entre une langue orale et sa forme écrite"]'::jsonb, 'Les différences systématiques de', 'La variation dialectale désigne les différences géographiques au sein d''une même langue : le français du Québec, d''Haïti, de Belgique ou du Sénégal diffèrent du français de France par le lexique, la prononciation et parfois la syntaxe. Ces variétés ne sont pas des "mauvais français" mais des variétés régionales légitimes, chacune avec sa cohérence interne.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''"emprunt lexical" en linguistique et est-il un signe d''appauvrissement d''une langue ?', '["Oui, l''emprunt lexical appauvrit toujours la langue qui emprunte", "L''emprunt est l''adoption d''un mot d''une", "L''emprunt lexical est une faute de langue à corriger", "L''emprunt lexical n''existe que dans les langues créoles"]'::jsonb, 'L''emprunt est l''adoption d''un mot d''une', 'L''emprunt lexical est universel : le français a emprunté à l''arabe (algèbre, zéro), au latin (la majorité du vocabulaire), à l''anglais (week-end, football), à l''italien (opéra, piano). La résistance aux emprunts est souvent idéologique. Le créole haïtien a emprunté au français, aux langues africaines, à l''espagnol et à l''anglais, ce qui n''enlève rien à son originalité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "continuum créole" en linguistique et quel exemple peut-on citer ?', '["La disparition progressive du créole au profit du français", "Le spectre entre la variété créole la", "La transformation d''un créole en une langue standard", "Le mélange de deux créoles différents dans une même communauté"]'::jsonb, 'Le spectre entre la variété créole la', 'Le continuum créole décrit la variation entre les locuteurs : le basilecte est la variété la plus éloignée du français (parlé par les ruraux non scolarisés), l''acrolecte est la variété la plus proche du français standard (élites urbaines), et le mésolecte est la variété intermédiaire. En Haïti, ce continuum est fortement lié à la stratification sociale.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''"écolinguistique" ou "linguistique écologique" comme approche récente ?', '["L''étude des langues des peuples vivant en milieu naturel", "Une approche qui étudie la relation", "L''étude de l''impact de l''environnement sur l''évolution phonétique", "L''utilisation des langues pour promouvoir la protection de l''environnement"]'::jsonb, 'Une approche qui étudie la relation', 'L''écolinguistique examine les langues comme des espèces dans un écosystème : la mort d''une langue appauvrit la diversité cognitive et culturelle de l''humanité. Aujourd''hui, environ 7000 langues existent, mais la moitié est menacée de disparition d''ici la fin du siècle. La diversité linguistique est considérée comme un patrimoine de l''humanité au même titre que la biodiversité.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "norme prescriptive" et la "norme descriptive" en linguistique ?', '["Deux façons d''écrire la même chose", "La norme prescriptive dit comment on", "La norme prescriptive est scientifique ; la norme descriptive est subjective", "La norme prescriptive s''applique à l''écrit ; la norme descriptive à l''oral"]'::jsonb, 'La norme prescriptive dit comment on', 'La grammaire prescriptive (scolaire) fixe des règles et condamne les "fautes" (ex. "au niveau de" à la place de "en ce qui concerne"). La linguistique descriptive, au contraire, étudie les usages réels sans les hiérarchiser : ce que les gens disent EST la langue, même si ça s''écarte de la norme académique. Les linguistes (Ferdinand de Saussure, Émile Benveniste) sont des descriptivistes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le concept de "langue maternelle" et pourquoi est-il parfois critiqué ?', '["C''est la première langue apprise dans", "C''est la langue du pays de naissance, qui est toujours la première langue apprise", "C''est la langue nationale officielle du pays dans lequel on naît", "C''est uniquement une métaphore sans contenu linguistique précis"]'::jsonb, 'C''est la première langue apprise dans', 'La "langue maternelle" est ordinairement la première langue (L1) acquise par l''enfant dans son milieu familial. Mais le terme est critiqué : pour les populations colonisées qui ont dû apprendre la langue du colonisateur, la "langue maternelle scolaire" ne correspond pas à la langue de la maison. On lui préfère "langue première" ou "L1". En Haïti, L1 = créole mais L1 scolaire officielle = français.', 'Difficile');
  END IF;
END $$;

-- Chapitre 4 : Théorie et critique littéraires NS4
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Théorie et critique littéraires' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le "structuralisme" comme courant de la critique littéraire ?', '["Un courant qui analyse uniquement la structure externe des œuvres (nombre de chapitres, division en parties)", "Un courant qui cherche à identifier les", "Un courant qui analyse les structures sociales décrites dans les romans", "Un courant qui étudie l''architecture et l''organisation matérielle des textes manuscrits"]'::jsonb, 'Un courant qui cherche à identifier les', 'Le structuralisme littéraire (années 1960, Roland Barthes, Gérard Genette, A.-J. Greimas) s''inspire de Saussure pour analyser les textes comme des systèmes de signes. Il cherche les structures profondes du récit, les oppositions binaires, les grammaires narratives universelles. Il met en parenthèse l''auteur et le contexte pour se concentrer sur le texte comme objet autonome.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "mort de l''auteur" selon Roland Barthes (1968) ?', '["La mort biologique d''un auteur rend ses textes plus importants", "La thèse selon laquelle", "Un événement littéraire qui met fin à l''œuvre d''un auteur", "La disparition progressive des auteurs au profit des éditeurs"]'::jsonb, 'La thèse selon laquelle', '"La mort de l''auteur" (Barthes, 1968) et "La naissance du lecteur" qui lui correspond affirment que le sens d''un texte ne réside pas dans les intentions de son auteur (introuvables et non pertinentes) mais dans la réception du lecteur. Chaque lecture est une nouvelle naissance du texte. Cette thèse s''oppose à la critique biographique traditionnelle.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "déconstruction" comme méthode de lecture développée par Jacques Derrida ?', '["Une destruction des textes littéraires", "Une méthode qui montre que les textes", "Une méthode de lecture simplifiée pour les étudiants", "La méthode qui reconstruit la biographie d''un auteur à partir de ses textes"]'::jsonb, 'Une méthode qui montre que les textes', 'La déconstruction (Jacques Derrida, De la grammatologie, 1967) ne "détruit" pas les textes mais les "dé-construit" : elle montre comment tout texte, en voulant défendre une thèse, en mine les fondements. Elle traque les oppositions binaires (nature/culture, parole/écriture), les "traces" de ce que le texte réprime. C''est une lecture au second degré qui révèle les tensions internes.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "narratologie" comme discipline et quels en sont les fondateurs ?', '["L''histoire de la littérature narrative depuis l''Antiquité", "La théorie et l''analyse systématique", "L''étude des narrateurs dans les romans du XIXe siècle uniquement", "La classification des genres littéraires narratifs"]'::jsonb, 'La théorie et l''analyse systématique', 'La narratologie (Figures III de Genette, 1972) est la science du récit. Elle analyse la narration selon les catégories de : temps (ordre, durée, fréquence), mode (distance, focalisation) et voix (qui raconte, à quel niveau diégétique). Elle a fourni un vocabulaire précis (prolepse, analepse, focalisation, diégèse, homodiégèse) devenu central dans l''analyse littéraire.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "critique féministe" en littérature et quels sont ses objectifs ?', '["Une critique qui analyse uniquement les œuvres écrites par des femmes", "Une approche qui examine la", "Une critique qui rejette toute littérature masculine", "Une approche uniquement sociologique sans dimension esthétique"]'::jsonb, 'Une approche qui examine la', 'La critique féministe (Simone de Beauvoir, Hélène Cixous, Luce Irigaray) analyse : la représentation des femmes dans les textes d''hommes (souvent stéréotypée), la minorisation des autrices dans le canon littéraire, la possibilité d''une "écriture féminine" spécifique (Cixous), et le caractère masculin supposément neutre de la critique traditionnelle.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "critique marxiste" ou "sociocritique" en littérature ?', '["Une critique qui cherche des idées marxistes dans les textes littéraires", "Une approche qui analyse les textes", "Une critique qui juge les œuvres selon leur utilité politique pour le prolétariat", "Une méthode d''analyse uniquement applicable aux romans réalistes du XIXe siècle"]'::jsonb, 'Une approche qui analyse les textes', 'La sociocritique (Lukács, Goldmann, Pierre Macherey) examine la littérature comme produit social : comment les textes reflètent, reproduisent ou critiquent les structures sociales et idéologiques de leur époque. Goldmann développe le concept de "vision du monde" qui imprègne les œuvres. Bourdieu analyse le "champ littéraire" comme espace social de luttes de pouvoir.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''"intertextualité" comme concept théorique (Kristeva/Barthes) ?', '["La présence de plusieurs auteurs dans un même texte", "Le fait que tout texte est un tissu de", "La comparaison de plusieurs textes du même auteur", "Les notes de bas de page qui renvoient à d''autres textes"]'::jsonb, 'Le fait que tout texte est un tissu de', 'L''intertextualité (Julia Kristeva, 1967, reprenant Bakhtine) affirme que tout texte est une "mosaïque de citations" : il absorbe et transforme d''autres textes. Genette la systématise dans Palimpsestes (1982) : citation, allusion, plagiat, parodie, pastiche, hypertextualité. Comprendre un texte nécessite de connaître les textes qu''il cite ou transforme.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "réception" d''une œuvre littéraire et l''"esthétique de la réception" (Hans Robert Jauss) ?', '["L''accueil financier d''un livre lors de sa publication", "La théorie selon laquelle le sens d''une", "L''étude des critiques journalistiques d''un livre", "La façon dont un auteur reçoit les influences de ses prédécesseurs"]'::jsonb, 'La théorie selon laquelle le sens d''une', 'L''esthétique de la réception (Jauss, École de Constance, années 1960) s''intéresse à l''histoire de la réception des œuvres : comment ont-elles été lues à différentes époques ? L''"horizon d''attente" est le système de références et d''attentes que le public apporte à la lecture. Quand une œuvre rompt avec cet horizon (Madame Bovary, 1857), elle crée un "choc esthétique".', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "canon littéraire" et pourquoi est-il contesté ?', '["La liste officielle des livres publiés dans un pays", "L''ensemble des œuvres considérées comme", "Les règles de composition des textes littéraires", "Les récompenses littéraires qui consacrent les meilleurs auteurs"]'::jsonb, 'L''ensemble des œuvres considérées comme', 'Le canon littéraire (en France : les "classiques" des programmes scolaires) est contesté pour son caractère idéologique : il reflète les choix d''une élite blanche, masculine et européenne. Les débats contemporains sur la "décanonisation" (inclure des autrices, des auteurs colonisés) questionnent qui décide de ce qui mérite d''être transmis et selon quels critères.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "psychocritique" comme méthode d''analyse littéraire (Charles Mauron) ?', '["L''étude des états psychologiques des personnages dans les romans", "Une méthode qui superpose les textes", "L''application directe de la psychanalyse freudienne à l''auteur à partir de sa biographie", "L''étude des effets psychologiques de la lecture sur les lecteurs"]'::jsonb, 'Une méthode qui superpose les textes', 'La psychocritique (Charles Mauron, 1963) superpose les textes d''un auteur pour faire apparaître des "réseaux de métaphores obsédants" qui révèlent son "mythe personnel" : un scénario fantasmatique inconscient. Elle se distingue de la biographie en restant dans le texte. Appliquée à Baudelaire, elle révèle l''obsession de la chute et de l''élévation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "pragmatique littéraire" ?', '["L''étude des aspects pratiques de la production et de la distribution des livres", "L''analyse de la littérature comme acte", "L''étude des effets économiques de la littérature", "L''analyse de l''utilité sociale de la littérature"]'::jsonb, 'L''analyse de la littérature comme acte', 'La pragmatique appliquée à la littérature (inspirée de Austin et Searle) analyse les textes comme actes de langage : la littérature fait des choses (elle crée des mondes fictifs, engage, séduit, provoque). Le "contrat de lecture" est le pacte implicite entre auteur et lecteur sur le régime de vérité du texte (autobiographie vs fiction, documentaire vs roman).', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "pacte autobiographique" selon Philippe Lejeune ?', '["Le contrat entre l''auteur et son éditeur pour la publication d''une biographie", "L''engagement implicite de l''auteur", "Les règles stylistiques propres au genre autobiographique", "La promesse de l''autobiographe de ne rien cacher de sa vie"]'::jsonb, 'L''engagement implicite de l''auteur', 'Le pacte autobiographique (Philippe Lejeune, 1975) définit l''autobiographie comme un genre basé sur une triple identité : auteur = narrateur = personnage principal. Ce pacte engage l''auteur à la vérité de sa vie. Il se distingue du roman autobiographique (roman à la première personne) par cette identité clairement affichée et par le "nom propre" partagé entre couverture et personnage.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "théorie queer" en études littéraires ?', '["Une théorie sur la sexualité dans la littérature érotique", "Un courant qui déconstruit les", "Une théorie qui défend la représentation des personnes LGBTQ+ dans la littérature", "Un mouvement exclusivement américain sans pertinence pour la littérature française"]'::jsonb, 'Un courant qui déconstruit les', 'La théorie queer (Judith Butler, Gender Trouble, 1990) déconstruit les catégories "naturelles" de genre et de sexualité : elles sont des constructions performatives et non des données biologiques. Appliquée à la littérature, elle révèle comment les textes construisent et renforcent des normes de genre, ou comment certains textes les subvertissent. Lire des textes classiques avec une lecture queer révèle des sens cachés.', 'Difficile'),
    (chap_id, 'Comment définit-on le "genre littéraire" et quelles sont ses fonctions ?', '["Une classification rigide des œuvres qui détermine leur valeur", "Un système de conventions et d''attentes", "La distinction entre textes écrits par des hommes et des femmes", "La division entre textes anciens et modernes"]'::jsonb, 'Un système de conventions et d''attentes', 'Le genre littéraire (roman, poésie, théâtre, essai, conte...) est un contrat implicite entre auteur et lecteur : il crée des attentes (un roman policier doit avoir une enquête, un sonnet 14 vers) que l''auteur peut respecter ou transgresser. Les genres ne sont pas fixes : ils évoluent historiquement, se mélangent et se renouvellent. Le roman est le genre le plus plastique de la modernité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la critique "postcoloniale" comme approche théorique (Said, Spivak, Bhabha) ?', '["Une critique qui célèbre les littératures coloniales européennes", "Un courant qui examine les", "Une critique uniquement réservée aux auteurs des anciennes colonies", "Une approche purement politique sans dimension littéraire"]'::jsonb, 'Un courant qui examine les', 'La critique postcoloniale (Edward Said, Orientalisme, 1978 ; Gayatri Spivak, "Les subalternes peuvent-elles parler ?" ; Homi Bhabha, Les Lieux de la culture) déconstruit les représentations que l''Occident a construites des peuples colonisés. Said montre comment la littérature et le discours savant européen ont construit un "Orient" imaginaire servant à justifier la domination coloniale.', 'Difficile');
  END IF;
END $$;

-- Chapitre 5 : Dissertation et commentaire composé avancés NS4
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Dissertation et commentaire composé avancés' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le "commentaire composé" et en quoi diffère-t-il de l''explication linéaire ?', '["Ce sont deux noms pour la même méthode", "Le commentaire composé analyse le texte", "L''explication linéaire va du début à la fin ; le commentaire composé n''analyse que la fin du texte", "Le commentaire composé est réservé aux textes poétiques ; l''explication linéaire aux textes narratifs"]'::jsonb, 'Le commentaire composé analyse le texte', 'Le commentaire composé (ou analyse littéraire) organise l''étude du texte en axes thématiques (ex. : l''écriture de l''absurde, le portrait satirique) plutôt que de le suivre linéairement. Chaque partie développe un aspect en illustrant à différents endroits du texte. L''explication linéaire va du début à la fin, analysant chaque élément dans l''ordre du texte.', 'Moyen'),
    (chap_id, 'Comment formuler les "axes de lecture" d''un commentaire composé ?', '["En résumant les différentes parties du texte", "En dégageant des problèmes ou aspects", "En énumérant toutes les figures de style du texte", "En suivant l''ordre chronologique des idées dans le texte"]'::jsonb, 'En dégageant des problèmes ou aspects', 'Les axes de lecture sont les grandes parties du commentaire composé, chacune développant une dimension du texte. Ils doivent être : distincts (pas de chevauchement), complémentaires (chacun apporte quelque chose), et liés à la problématique. Un bon intitulé d''axe est à la fois analytique (dit quelque chose sur le texte) et annonce les procédés qui seront étudiés.', 'Difficile'),
    (chap_id, 'Quelle est la différence entre la "thèse" et la "problématique" dans une dissertation littéraire avancée ?', '["Elles sont identiques", "La problématique est la question", "La problématique est au début ; la thèse est à la fin", "La problématique est pour la dissertation ; la thèse est pour le commentaire composé"]'::jsonb, 'La problématique est la question', 'Dans une dissertation analytique (plan en thèse/antithèse/synthèse ou plan thématique), la problématique ouvre la question ("En quoi la littérature est-elle engagée ?") et la thèse est la position défendue ("La littérature est fondamentalement engagée"). Dans le plan dialectique, on présente d''abord la thèse, puis l''antithèse, avant de les dépasser en synthèse.', 'Moyen'),
    (chap_id, 'Quel est le "plan analytique" d''une dissertation par opposition au plan dialectique ?', '["Un plan qui analyse uniquement des textes littéraires", "Un plan qui démontre une thèse sans la", "Un plan qui suit l''ordre chronologique des arguments", "Un plan uniquement pour les dissertations philosophiques"]'::jsonb, 'Un plan qui démontre une thèse sans la', 'Le plan analytique ne débat pas d''une thèse vs une antithèse : il démontre une thèse en développant progressivement ses différentes dimensions. Exemple : "La littérature est une arme politique" → I. Elle dénonce (exemples) → II. Elle mobilise (exemples) → III. Elle transforme les consciences (exemples). Chaque partie approfondit sans contredire la précédente.', 'Difficile'),
    (chap_id, 'Comment citer un texte littéraire dans un commentaire ou une dissertation sans paraphraser ?', '["En résumant longuement l''extrait cité", "En citant un segment précis entre", "En reproduisant des paragraphes entiers du texte", "En évitant de citer le texte pour éviter la paraphrase"]'::jsonb, 'En citant un segment précis entre', 'Une citation efficace est courte, précise et intégrée : "Quand Baudelaire écrit ''spleen'', il désigne... " L''analyse suit immédiatement : "Ce terme anglais... révèle l''incapacité du sujet lyrique à...". Une citation non analysée ne prouve rien. La règle : Citer → Nommer le procédé → Analyser l''effet → Lier à l''argument.', 'Moyen'),
    (chap_id, 'Comment rédiger une "ouverture" efficace en conclusion d''une dissertation ?', '["En résumant à nouveau le plan de la dissertation", "En proposant une question ou une", "En citant longuement un auteur", "En admettant que la problématique reste sans réponse"]'::jsonb, 'En proposant une question ou une', 'L''ouverture de conclusion doit aller au-delà du sujet traité, pas en le répétant. Elle propose un prolongement : une autre discipline (philosophie, psychologie), une autre période historique, une autre œuvre ou un autre auteur. Elle ne doit pas introduire un nouveau sujet entier mais ouvrir sur une réflexion possible. Elle doit être courte (2-3 lignes max).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "distanciation critique" dans une dissertation littéraire de niveau avancé ?', '["L''absence totale de subjectivité dans l''analyse", "La capacité à prendre du recul par", "Le fait de ne jamais utiliser la première personne dans sa rédaction", "La référence constante à des théoriciens et critiques littéraires"]'::jsonb, 'La capacité à prendre du recul par', 'La distanciation critique, au niveau avancé, consiste à problématiser ce que le texte semble dire à première vue, à identifier ses tensions internes, à évaluer différentes interprétations possibles et à justifier ses choix interprétatifs. Elle s''oppose à la lecture naïve et à la paraphrase. Elle implique de mobiliser des outils théoriques (narratologie, stylistique, intertextualité).', 'Difficile'),
    (chap_id, 'Quelle est la règle du "micro-argument" dans la rédaction d''un paragraphe de développement avancé ?', '["Un paragraphe ne doit contenir qu''une seule phrase", "Chaque paragraphe développe une idée", "Un paragraphe doit toujours se terminer par une citation", "Un paragraphe ne doit pas dépasser 5 lignes"]'::jsonb, 'Chaque paragraphe développe une idée', 'Dans une dissertation ou un commentaire avancé, chaque paragraphe = une idée. La progression interne : (1) énoncer clairement l''argument en début de paragraphe, (2) illustrer précisément (citation textuelle ou exemple), (3) analyser le lien entre l''illustration et l''argument, (4) formuler une mini-conclusion reliant ce paragraphe à l''axe général. Cette structure évite le délayage et la digression.', 'Difficile'),
    (chap_id, 'Comment éviter le défaut de la "liste d''exemples" dans une dissertation de niveau avancé ?', '["En n''utilisant qu''un seul exemple par partie", "En analysant chaque exemple plutôt que", "En évitant complètement les exemples et en restant dans l''abstraction", "En utilisant uniquement des citations d''auteurs célèbres"]'::jsonb, 'En analysant chaque exemple plutôt que', 'Le défaut de la "liste d''exemples" consiste à accumuler des références (Zola montre X, Hugo montre Y, Flaubert montre Z) sans analyser leur pertinence ni les articuler à l''argument. Au niveau avancé, un exemple développé, contextualisé et analysé est bien plus convaincant que dix exemples cités superficiellement. La qualité prime sur la quantité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"articulation logique" du développement dans une dissertation et comment l''assurer ?', '["L''utilisation de connecteurs logiques comme ''premièrement, deuxièmement''", "La progression du raisonnement qui fait", "Le fait que les parties aient la même longueur", "La présence de titres de parties bien formulés"]'::jsonb, 'La progression du raisonnement qui fait', 'Une dissertation bien articulée n''est pas trois thèses indépendantes mais un raisonnement progressif : la partie 2 s''appuie sur la partie 1 et la nuance, et la partie 3 synthétise ou dépasse. Les transitions doivent montrer cette progression ("Si la littérature dénonce, nous avons vu que... Cependant, elle va plus loin en..."). Sans articulation, le développement ressemble à un catalogue.', 'Difficile'),
    (chap_id, 'Comment analyser le "style" d''un auteur dans un commentaire ou une dissertation avancée ?', '["En identifiant le genre littéraire et la période historique de l''œuvre", "En examinant les choix lexicaux (niveau", "En résumant la biographie de l''auteur", "En comptant le nombre de pages et de chapitres de l''œuvre"]'::jsonb, 'En examinant les choix lexicaux (niveau', 'L''analyse stylistique avancée examine le style à plusieurs niveaux : lexical (vocabulaire soutenu/familier, champs lexicaux dominants), syntaxique (phrases longues/courtes, coordination/subordination), rhythmique (cadence des phrases, pauses, ponctuation) et rhétorique (figures de style et leurs effets). L''objectif est toujours de montrer comment ces choix de style créent du sens et s''articulent à la thèse de l''auteur.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une "interprétation plurielle" dans l''analyse littéraire avancée ?', '["Une analyse où plusieurs personnes donnent leur avis", "La reconnaissance que les grands textes", "Une méthode qui applique plusieurs théories critiques différentes au même texte", "Une dissertation rédigée en plusieurs parties de longueurs différentes"]'::jsonb, 'La reconnaissance que les grands textes', 'Au niveau avancé, la lecture est polysémique : les grands textes résistent à une interprétation unique. La dissertation avancée montre comment un texte est travaillé par des tensions (tragique/comique, espoir/désespoir), comment il peut être lu selon différentes grilles (historique, psychanalytique, féministe) et pourquoi cette pluralité des lectures est une marque de sa littérarité.', 'Difficile'),
    (chap_id, 'Comment "contextualiser" un texte dans une analyse littéraire sans tomber dans le "hors-texte" ?', '["Ne jamais mentionner l''histoire ou la biographie de l''auteur", "Mobiliser le contexte (historique", "Développer longuement la biographie de l''auteur avant d''analyser le texte", "Faire un cours d''histoire sur l''époque de l''œuvre analysée"]'::jsonb, 'Mobiliser le contexte (historique', 'La contextualisation doit être au service de l''analyse textuelle, pas autonome. On mentionne le contexte pour expliquer un choix de l''auteur : "Rédigé sous la censure impériale, Hugo utilise l''allégorie pour...". Le "hors-texte" est le défaut inverse : développer longuement le contexte sans revenir aux procédés du texte. La règle : contexte → texte, jamais texte → prétexte au contexte.', 'Difficile'),
    (chap_id, 'Quel est le rôle de la "problématique originale" dans une dissertation de niveau avancé ?', '["Une problématique originale est celle que personne n''a jamais formulée", "Une problématique originale interroge", "Une problématique originale doit être la plus simple possible", "Une problématique originale cite toujours un théoricien littéraire"]'::jsonb, 'Une problématique originale interroge', 'Au niveau avancé, la problématique ne doit pas reformuler banalement le sujet mais révéler un enjeu moins visible, une tension ou un paradoxe qui rend la question plus intéressante. Par exemple, pour "La littérature est-elle engagée ?", une problématique originale pourrait être : "En quoi la forme littéraire est-elle elle-même une forme d''engagement, indépendamment du contenu ?" Cela ouvre des analyses inattendues.', 'Difficile'),
    (chap_id, 'Comment construire un "développement non prévisible" dans une dissertation avancée ?', '["En choisissant des exemples rares et peu connus", "En formulant des idées qui ne sont pas", "En changeant la structure habituelle de la dissertation", "En utilisant un vocabulaire très technique et spécialisé"]'::jsonb, 'En formulant des idées qui ne sont pas', 'Un développement avancé évite les "premières idées" (les plus prévisibles) et cherche des angles d''attaque moins attendus : questionner les présupposés du sujet, mobiliser une théorie critique, renverser la perspective habituelle. La valeur d''une dissertation avancée tient à la profondeur de la pensée et à l''originalité des analyses, pas à l''accumulation d''exemples connus.', 'Difficile');
  END IF;
END $$;
