-- Supplément Français NS1-NS2 (matiere_id=25) — +16 questions/chapitre pour atteindre 20 minimum

-- Chapitre 1 : Grammaire française : morphologie et syntaxe NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Grammaire française : morphologie et syntaxe' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la fonction grammaticale du groupe nominal en italique dans : "Le professeur corrige les copies" ?', '["Sujet", "Complément d''objet direct (COD)", "Complément d''objet indirect (COI)", "Attribut du sujet"]'::jsonb, 'Complément d''objet direct (COD)', '"Les copies" est le COD du verbe "corrige" : il répond à la question "corrige quoi ?". Le COD se construit directement sans préposition, contrairement au COI.', 'Facile'),
    (chap_id, 'Quelle classe grammaticale désigne les mots qui remplacent un nom ou un groupe nominal ?', '["Les adjectifs", "Les pronoms", "Les adverbes", "Les conjonctions"]'::jsonb, 'Les pronoms', 'Les pronoms remplacent un nom ou un groupe nominal pour éviter les répétitions. Il en existe plusieurs types : pronoms personnels (je, il), démonstratifs (ce, celui), possessifs (le mien), relatifs (qui, que), interrogatifs (qui, que) et indéfinis (on, tout).', 'Facile'),
    (chap_id, 'Dans la phrase "Il travaille sérieusement", à quelle classe grammaticale appartient "sérieusement" ?', '["Adjectif qualificatif", "Nom commun", "Adverbe", "Préposition"]'::jsonb, 'Adverbe', '"Sérieusement" est un adverbe de manière formé à partir de l''adjectif "sérieux". Il modifie le verbe "travaille" et est invariable. Les adverbes en -ment se forment généralement sur le féminin de l''adjectif + -ment.', 'Facile'),
    (chap_id, 'Qu''est-ce que le "sujet" d''un verbe ?', '["Le mot qui suit directement le verbe", "Le groupe nominal ou pronominal dont le verbe indique l''action ou l''état, et avec lequel il s''accorde", "Le complément qui répond à la question ''à qui ?''", "Le mot qui qualifie le verbe"]'::jsonb, 'Le groupe nominal ou pronominal dont le verbe indique l''action ou l''état, et avec lequel il s''accorde', 'Le sujet est l''élément essentiel de la phrase avec lequel le verbe s''accorde. On le trouve en posant la question "Qui est-ce qui + verbe ?" ou "Qu''est-ce qui + verbe ?". Il peut être un nom propre, un groupe nominal ou un pronom.', 'Facile'),
    (chap_id, 'Dans "Les élèves que j''enseigne sont brillants", quelle est la fonction du pronom relatif "que" ?', '["Sujet de la proposition relative", "COD du verbe ''enseigner'' dans la proposition relative", "Attribut du sujet dans la proposition principale", "Complément circonstanciel"]'::jsonb, 'COD du verbe ''enseigner'' dans la proposition relative', 'Dans "que j''enseigne", "que" est le pronom relatif COD du verbe "enseigner" (j''enseigne qui ? → que les élèves). Le pronom relatif "que" a toujours une fonction de COD dans la relative, contrairement à "qui" qui est sujet.', 'Moyen'),
    (chap_id, 'Comment s''accorde le participe passé employé avec l''auxiliaire "avoir" ?', '["Il s''accorde toujours avec le sujet", "Il s''accorde avec le COD quand celui-ci est placé avant le verbe", "Il est toujours invariable", "Il s''accorde avec le COI"]'::jsonb, 'Il s''accorde avec le COD quand celui-ci est placé avant le verbe', 'Avec l''auxiliaire "avoir", le participe passé s''accorde en genre et en nombre avec le COD si celui-ci est placé avant le verbe : "Les livres que j''ai lus" (lus = masc. plur. car "que" reprend "livres"). Si le COD est après, pas d''accord : "J''ai lu des livres."', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "phrase complexe" en grammaire française ?', '["Une phrase avec beaucoup de mots", "Une phrase contenant au moins deux propositions liées par un lien de subordination ou de coordination", "Une phrase sans verbe", "Une phrase avec un verbe à un temps composé"]'::jsonb, 'Une phrase contenant au moins deux propositions liées par un lien de subordination ou de coordination', 'La phrase complexe comporte au moins deux propositions : une principale et une (ou plusieurs) subordonnée(s), liées par une conjonction de subordination (que, quand, si...) ou de coordination (mais, ou, et, donc, or, ni, car), ou par un pronom relatif.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre un complément circonstanciel supprimable et un complément essentiel ?', '["Les compléments circonstanciels sont toujours des adverbes ; les compléments essentiels sont toujours des noms", "Le complément circonstanciel est supprimable et déplaçable ; le complément essentiel (COD, COI) ne peut généralement pas être supprimé sans changer le sens fondamental de la phrase", "Il n''y a pas de différence", "Les compléments essentiels se placent toujours devant le verbe"]'::jsonb, 'Le complément circonstanciel est supprimable et déplaçable ; le complément essentiel (COD, COI) ne peut généralement pas être supprimé sans changer le sens fondamental de la phrase', 'Le CC (de temps, lieu, manière) est supprimable : "Il travaille le matin" → "Il travaille" reste grammatical. Le COD/COI est essentiel : "Il mange une pomme" → "Il mange" change de sens (verbe absolu vs transitif), et "Il pense à son avenir" → "Il pense" perd son complément nécessaire.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "voix passive" en français et comment la forme-t-on ?', '["Une phrase où le sujet est inconnu", "Une construction où le sujet subit l''action : auxiliaire ''être'' au temps voulu + participe passé du verbe, accord avec le sujet", "Une phrase négative", "Une phrase interrogative indirecte"]'::jsonb, 'Une construction où le sujet subit l''action : auxiliaire ''être'' au temps voulu + participe passé du verbe, accord avec le sujet', 'La voix passive se forme avec l''auxiliaire "être" conjugué au temps voulu + le participe passé accordé avec le sujet : "Le roman est écrit par l''auteur." Le sujet de la passive correspond au COD de l''active, et le complément d''agent (par...) correspond au sujet de l''active.', 'Moyen'),
    (chap_id, 'Quelle est la règle d''accord de l''adjectif qualificatif en français ?', '["Il s''accorde uniquement en genre avec le nom", "Il s''accorde en genre et en nombre avec le nom ou le pronom auquel il se rapporte", "Il est toujours invariable", "Il s''accorde avec le verbe de la phrase"]'::jsonb, 'Il s''accorde en genre et en nombre avec le nom ou le pronom auquel il se rapporte', 'L''adjectif qualificatif s''accorde en genre (masculin/féminin) et en nombre (singulier/pluriel) avec le nom ou pronom qu''il qualifie : "une belle maison" (fém. sg.), "de beaux arbres" (masc. pl.). Cette règle d''accord est fondamentale en grammaire française.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une "proposition subordonnée relative" ?', '["Une proposition qui suit toujours la principale", "Une proposition introduite par un pronom relatif (qui, que, dont, où...) qui complète un antécédent dans la principale", "Une proposition introduite par ''que'' exprimant un souhait", "Une proposition qui exprime une condition"]'::jsonb, 'Une proposition introduite par un pronom relatif (qui, que, dont, où...) qui complète un antécédent dans la principale', 'La proposition subordonnée relative est introduite par un pronom relatif (qui, que, quoi, dont, où, lequel...) et complète un nom ou pronom antécédent dans la principale : "Le livre que tu m''as prêté est passionnant." La relative joue le rôle d''un adjectif qualificatif.', 'Moyen'),
    (chap_id, 'Comment distingue-t-on "leur" pronom personnel de "leur" adjectif possessif ?', '["Ils sont identiques et interchangeables", "''Leur'' pronom est invariable et représente des personnes ; ''leurs'' adjectif possessif s''accorde en nombre avec le nom qu''il détermine", "''Leur'' pronom s''accorde toujours ; ''leur'' adjectif est invariable", "Il n''y a pas de ''leur'' adjectif possessif en français"]'::jsonb, '"Leur" pronom est invariable et représente des personnes ; "leurs" adjectif possessif s''accorde en nombre avec le nom qu''il détermine', '"Leur" COI/pronom est invariable : "Je leur parle" (= à eux/elles). "Leur/leurs" adjectif possessif varie en nombre selon le nom possédé : "leur livre" (un livre) vs "leurs livres" (plusieurs livres). Test : remplacer par "lui" → COI ; par "son/ses" → adjectif.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "discours indirect" et comment transforme-t-on le discours direct en indirect ?', '["Le discours rapporté sans guillemets, introduit par une conjonction (que, si...) avec changement de pronoms et souvent de temps verbaux", "Le discours rapporté en gardant exactement les mêmes mots avec des guillemets", "Un discours public ou politique", "Une citation littérale d''un auteur"]'::jsonb, 'Le discours rapporté sans guillemets, introduit par une conjonction (que, si...) avec changement de pronoms et souvent de temps verbaux', 'Le discours indirect rapporte les paroles sans guillemets, introduit par "que/si" : "Il dit qu''il viendra." Les pronoms changent (je→il), les temps reculent (présent→imparfait si verbe intro au passé), et certains adverbes changent (maintenant→alors, ici→là). C''est opposé au discours direct qui cite mot pour mot.', 'Difficile'),
    (chap_id, 'Quelle est la fonction de l''attribut du sujet ?', '["Il complète directement le verbe d''action", "Il qualifie ou caractérise le sujet par l''intermédiaire d''un verbe d''état (être, paraître, sembler, devenir...)", "Il indique la circonstance de l''action", "Il est toujours un adverbe"]'::jsonb, 'Il qualifie ou caractérise le sujet par l''intermédiaire d''un verbe d''état (être, paraître, sembler, devenir...)', 'L''attribut du sujet se construit avec un verbe d''état (copule) et caractérise le sujet : "Elle est brillante." L''attribut s''accorde avec le sujet. Il se distingue du COD par son lien avec le sujet via le verbe d''état, et par le fait qu''on ne peut le pronominaliser par "le/la/les" mais par "le" invariable.', 'Moyen'),
    (chap_id, 'Quel mode verbal exprime une action éventuelle, souhaitée ou subordonnée à un sentiment ou un jugement ?', '["L''indicatif", "L''impératif", "Le subjonctif", "L''infinitif"]'::jsonb, 'Le subjonctif', 'Le subjonctif exprime l''incertitude, le souhait, le doute, la nécessité, les émotions : "Il faut que tu viennes", "Je souhaite qu''il réussisse". Il est souvent requis après certaines conjonctions (bien que, pour que, à moins que) ou verbes (vouloir que, craindre que).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "morphème" en linguistique et en grammaire française ?', '["Un mot complet isolé", "La plus petite unité de sens d''une langue : radical, préfixe, suffixe, désinence", "Une syllabe d''un mot", "Un groupe de mots formant une expression"]'::jsonb, 'La plus petite unité de sens d''une langue : radical, préfixe, suffixe, désinence', 'Un morphème est la plus petite unité linguistique porteuse de sens. En français : le radical (sens de base), les préfixes (avant le radical : re-, dé-, in-), les suffixes (après : -tion, -eur, -ment) et les désinences verbales (-ons, -ez, -ait) sont des morphèmes. Morphologie = étude des morphèmes.', 'Difficile');
  END IF;
END $$;

-- Chapitre 2 : Lecture et analyse de textes : méthodologie NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Lecture et analyse de textes : méthodologie' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une "lecture analytique" d''un texte ?', '["Une lecture rapide pour en comprendre l''essentiel", "Une lecture attentive qui identifie et interprète les procédés stylistiques, les thèmes et la signification profonde d''un texte", "Une lecture à voix haute pour la classe", "Une lecture qui résume le texte en moins de mots"]'::jsonb, 'Une lecture attentive qui identifie et interprète les procédés stylistiques, les thèmes et la signification profonde d''un texte', 'La lecture analytique (ou explication de texte) est une méthode qui consiste à lire attentivement un extrait pour identifier ses caractéristiques formelles (style, figures de rhétorique, structure), ses thèmes et ses significations. Elle va au-delà du résumé pour interpréter le sens.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une "figure de style" dans un texte littéraire ?', '["Une illustration graphique dans le texte", "Un procédé d''écriture particulier qui modifie l''expression ordinaire pour produire un effet (métaphore, comparaison, anaphore...)", "Un paragraphe de transition entre deux idées", "Un personnage secondaire de récit"]'::jsonb, 'Un procédé d''écriture particulier qui modifie l''expression ordinaire pour produire un effet (métaphore, comparaison, anaphore...)', 'Les figures de style sont des procédés rhétoriques qui embellissent, renforcent ou surprennent : la métaphore (comparaison implicite), la comparaison (avec "comme"), l''hyperbole (exagération), l''anaphore (répétition en début de phrase), la personnification (donner des traits humains à un objet), etc.', 'Facile'),
    (chap_id, 'Qu''est-ce que la "métaphore" et en quoi diffère-t-elle de la comparaison ?', '["Elles sont identiques", "La métaphore identifie implicitement deux éléments sans outil comparatif ; la comparaison les rapproche explicitement avec ''comme'', ''tel'', ''ainsi que''", "La métaphore n''utilise que des animaux ; la comparaison utilise des personnes", "La métaphore est réservée à la poésie ; la comparaison à la prose"]'::jsonb, 'La métaphore identifie implicitement deux éléments sans outil comparatif ; la comparaison les rapproche explicitement avec ''comme'', ''tel'', ''ainsi que''', '"Sa voix est de l''or" (métaphore) vs "Sa voix est comme de l''or" (comparaison). La métaphore crée une image plus forte car elle fusionne les deux réalités, tandis que la comparaison maintient la distance entre elles.', 'Moyen'),
    (chap_id, 'Comment identifier le "thème principal" d''un texte ?', '["En cherchant le mot qui revient le plus souvent", "En identifiant le sujet central dont traite le texte, qui unifie toutes ses parties et que l''on peut formuler en un mot ou groupe nominal", "En lisant uniquement le début et la fin du texte", "En comptant le nombre de personnages"]'::jsonb, 'En identifiant le sujet central dont traite le texte, qui unifie toutes ses parties et que l''on peut formuler en un mot ou groupe nominal', 'Le thème principal est l''idée centrale qui unifie l''ensemble du texte, formulée en un nom abstrait (l''amour, la liberté, la mort, le temps). On l''identifie en cherchant le sujet récurrent de toutes les parties du texte. Il se distingue de la thèse (dans un texte argumentatif) qui est la position défendue sur ce thème.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "registre" d''un texte (aussi appelé tonalité) ?', '["Le niveau de langue utilisé (familier, courant, soutenu)", "L''ensemble des effets produits par le texte sur le lecteur, liés aux émotions visées : registre lyrique, épique, tragique, comique, ironique...", "La longueur des phrases du texte", "Le type de narrateur utilisé"]'::jsonb, 'L''ensemble des effets produits par le texte sur le lecteur, liés aux émotions visées : registre lyrique, épique, tragique, comique, ironique...', 'Le registre (ou tonalité) est l''effet dominant que l''auteur cherche à produire sur le lecteur. Le registre lyrique exprime des émotions personnelles ; épique magnifie des actions héroïques ; tragique explore la fatalité et la mort ; comique provoque le rire ; ironique dit le contraire de ce qu''on pense pour critiquer.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"anaphore" comme figure de style ?', '["La répétition d''un mot ou d''un groupe de mots au début de phrases ou de propositions successives", "Une comparaison entre deux réalités très différentes", "Une question posée sans attendre de réponse", "Une exagération délibérée pour produire un effet"]'::jsonb, 'La répétition d''un mot ou d''un groupe de mots au début de phrases ou de propositions successives', 'L''anaphore est la répétition d''un même mot ou expression en tête de phrases successives : "Je me souviens de ta voix, je me souviens de ton sourire, je me souviens de ta présence..." Cette répétition crée un rythme, renforce l''emphase et produit un effet incantatoire ou oratoire.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"hyperbole" comme figure de style ?', '["Une atténuation délibérée de la réalité", "Une exagération délibérée pour accentuer un effet ou une idée", "Une comparaison avec un élément très petit", "Un retour en arrière dans la narration"]'::jsonb, 'Une exagération délibérée pour accentuer un effet ou une idée', 'L''hyperbole est une exagération volontaire : "Je t''ai dit mille fois de ranger ta chambre !", "Il pleurait un fleuve de larmes." Elle vise à accentuer l''intensité d''un sentiment, d''une action ou d''une réalité. Son contraire est la litote (atténuation) : "Ce n''est pas mal" pour dire "c''est très bien".', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un "champ lexical" dans l''analyse d''un texte ?', '["Le vocabulaire difficile d''un texte", "L''ensemble des mots appartenant à un même domaine thématique dans un texte", "Les mots de liaison entre les paragraphes", "Le registre de langue utilisé par l''auteur"]'::jsonb, 'L''ensemble des mots appartenant à un même domaine thématique dans un texte', 'Le champ lexical est l''ensemble des mots (noms, verbes, adjectifs, expressions) qui se rapportent à un même thème dans un texte. Exemple : champ lexical de la mer = vague, horizon, sel, tempête, naviguer, marin, côte... Identifier les champs lexicaux dominants révèle les thèmes principaux du texte.', 'Facile'),
    (chap_id, 'Comment repère-t-on l''"ironie" dans un texte littéraire ?', '["Par la présence de points d''exclamation", "Quand l''auteur dit le contraire de ce qu''il pense, souvent pour critiquer, et que le contexte permet de comprendre la vraie intention", "Par l''utilisation du vocabulaire mélioratif", "Uniquement dans les textes comiques"]'::jsonb, 'Quand l''auteur dit le contraire de ce qu''il pense, souvent pour critiquer, et que le contexte permet de comprendre la vraie intention', 'L''ironie consiste à dire le contraire de ce que l''on pense, en comptant sur le lecteur pour comprendre la distorsion : louer pour critiquer, minimiser pour dénoncer. Le contexte, le ton et les indices textuels permettent de déceler l''ironie. C''est un procédé fréquent dans la satire et l''essai critique.', 'Moyen'),
    (chap_id, 'Quelle est la structure d''une explication de texte en français ?', '["Introduction - Résumé - Conclusion", "Introduction (présentation + problématique + plan) - Développement (analyse des procédés liés à la problématique) - Conclusion (bilan + ouverture)", "Résumé - Analyse stylistique - Biographie de l''auteur", "Thèse - Antithèse - Synthèse uniquement pour les textes argumentatifs"]'::jsonb, 'Introduction (présentation + problématique + plan) - Développement (analyse des procédés liés à la problématique) - Conclusion (bilan + ouverture)', 'L''explication de texte suit une structure : Introduction (situer le texte, formuler la problématique : en quoi ce texte est-il remarquable ? + annoncer le plan) ; Développement (axes d''analyse avec procédés + interprétations) ; Conclusion (bilan répondant à la problématique + ouverture).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "personnification" comme figure de style ?', '["Donner un nom propre à un personnage fictif", "Attribuer des caractéristiques, des sentiments ou des actions humaines à un animal, un objet ou une idée abstraite", "Décrire une personne en détail", "Utiliser un pronom personnel à la première personne"]'::jsonb, 'Attribuer des caractéristiques, des sentiments ou des actions humaines à un animal, un objet ou une idée abstraite', 'La personnification prête des traits, des sentiments ou des actions humaines à ce qui n''est pas humain : "La mer en colère grondait", "Le temps fuyait", "La mort l''attendait au coin de la rue." C''est une forme de métaphore qui anime le monde inanimé.', 'Facile'),
    (chap_id, 'Comment analyser le "point de vue" d''un narrateur dans un récit ?', '["En cherchant si l''auteur apparaît physiquement dans le texte", "En identifiant qui voit et qui sait dans le récit : narrateur omniscient (tout sait), interne (vision d''un personnage), externe (observation sans accès aux pensées)", "En comptant le nombre de fois que le narrateur utilise ''je''", "En lisant uniquement les dialogues"]'::jsonb, 'En identifiant qui voit et qui sait dans le récit : narrateur omniscient (tout sait), interne (vision d''un personnage), externe (observation sans accès aux pensées)', 'La focalisation (point de vue narratif) se détermine par la question "Qui perçoit ?" : focalisation zéro (narrateur omniscient sait tout), interne (récit depuis la perspective d''un personnage), externe (narrateur observe de l''extérieur sans connaître les pensées). Ce choix conditionne la relation du lecteur aux personnages.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''"ellipse" dans un récit ?', '["Une phrase trop longue", "Une omission narrative : le narrateur saute une période de temps sans la raconter", "Un personnage muet dans le récit", "Une répétition inutile dans le texte"]'::jsonb, 'Une omission narrative : le narrateur saute une période de temps sans la raconter', 'L''ellipse est une omission temporelle dans le récit : le narrateur passe sous silence une période plus ou moins longue ("Cinq ans plus tard..."). Contrairement à la scène (temps du récit = temps de l''histoire), l''ellipse accélère le rythme narratif en supprimant des événements jugés peu importants.', 'Difficile'),
    (chap_id, 'Comment reconnaître un texte "argumentatif" d''un texte "narratif" ?', '["Par la présence de personnages", "Le texte argumentatif défend une thèse avec des arguments et des exemples ; le texte narratif raconte une histoire avec des personnages, des actions et une chronologie", "Par la longueur du texte", "Par l''absence de temps verbaux au passé"]'::jsonb, 'Le texte argumentatif défend une thèse avec des arguments et des exemples ; le texte narratif raconte une histoire avec des personnages, des actions et une chronologie', 'Le texte argumentatif vise à convaincre : il présente une thèse, des arguments logiques, des exemples. Le texte narratif raconte des événements selon une chronologie avec des personnages. D''autres types : descriptif (peindre une réalité), injonctif (donner des ordres), explicatif (faire comprendre).', 'Facile'),
    (chap_id, 'Qu''est-ce que l''"oxymore" comme figure de style ?', '["Une comparaison entre deux réalités très proches", "L''association de deux termes contradictoires ou opposés dans une même expression", "La répétition d''un son consonantique dans une phrase", "Une énumération de qualités opposées"]'::jsonb, 'L''association de deux termes contradictoires ou opposés dans une même expression', 'L''oxymore (ou alliance de mots) rapproche deux termes contradictoires : "une obscure clarté", "un silence éloquent", "une douce violence". Cette figure crée une tension paradoxale qui force le lecteur à réfléchir sur la complexité du réel. Victor Hugo en est un maître : "Cette obscure clarté qui tombe des étoiles".', 'Moyen'),
    (chap_id, 'Quelle question fondamentale guide l''analyse d''un texte littéraire lors d''une explication de texte ?', '["Quel est le résumé du texte ?", "La problématique : en quoi ce texte est-il remarquable ? Quel est l''enjeu littéraire de cet extrait ?", "Qui est l''auteur du texte ?", "Combien de figures de style y a-t-il dans le texte ?"]'::jsonb, 'La problématique : en quoi ce texte est-il remarquable ? Quel est l''enjeu littéraire de cet extrait ?', 'La problématique est la question centrale qui oriente toute l''analyse : elle interroge l''intérêt et la particularité du texte. Elle dépasse la simple description pour questionner les intentions de l''auteur, les effets produits sur le lecteur et les enjeux littéraires, culturels ou philosophiques de l''extrait.', 'Difficile');
  END IF;
END $$;

-- Chapitre 3 : Expression écrite : disserter et rédiger NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Expression écrite : disserter et rédiger' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la structure classique d''une dissertation littéraire ?', '["Résumé - Analyse - Biographie de l''auteur", "Introduction - Développement en plusieurs parties - Conclusion", "Thèse uniquement - Exemples - Fin", "Introduction - Exemples - Résumé"]'::jsonb, 'Introduction - Développement en plusieurs parties - Conclusion', 'La dissertation suit une structure tripartite : Introduction (accroche + présentation du sujet + problématique + annonce du plan), Développement (2 ou 3 parties avec arguments et exemples, transitions entre parties), Conclusion (bilan répondant à la problématique + ouverture sur une perspective plus large).', 'Facile'),
    (chap_id, 'Qu''est-ce que la "problématique" dans une dissertation ?', '["La liste des exemples qu''on va utiliser", "La question centrale à laquelle la dissertation va répondre, reformulant le sujet sous forme interrogative avec un enjeu intellectuel", "Le résumé du sujet donné", "Le plan détaillé de la dissertation"]'::jsonb, 'La question centrale à laquelle la dissertation va répondre, reformulant le sujet sous forme interrogative avec un enjeu intellectuel', 'La problématique est la question directrice de la dissertation, formulée à partir du sujet. Elle doit être ouverte (pas de réponse par oui/non), pertinente (cerner l''enjeu réel du sujet) et orientée (permettre une réflexion argumentée). Elle naît de l''analyse des termes du sujet.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"accroche" en début d''introduction d''une dissertation ?', '["La définition de tous les termes du sujet", "Une entrée en matière qui captive le lecteur : citation, anecdote, fait marquant, paradoxe, lié au sujet", "La formulation immédiate de la thèse", "Un résumé du plan de la dissertation"]'::jsonb, 'Une entrée en matière qui captive le lecteur : citation, anecdote, fait marquant, paradoxe, lié au sujet', 'L''accroche est la phrase ou le court paragraphe d''ouverture qui attire l''attention du lecteur avant d''arriver au sujet. Elle doit être en lien avec le thème traité mais partir d''un angle différent. Elle peut être une citation d''auteur, un fait d''actualité, une anecdote historique ou un paradoxe frappant.', 'Facile'),
    (chap_id, 'Comment rédiger une "transition" entre deux parties d''une dissertation ?', '["En commençant simplement la nouvelle partie sans transition", "En formulant un bilan de la partie précédente, en montrant sa limite, et en annonçant la partie suivante comme réponse à cette limite", "En répétant la problématique au début de chaque partie", "En ajoutant des citations entre les parties"]'::jsonb, 'En formulant un bilan de la partie précédente, en montrant sa limite, et en annonçant la partie suivante comme réponse à cette limite', 'Une transition efficace comporte trois éléments : (1) un mini-bilan de la partie précédente, (2) la mise en évidence de sa limite ou insuffisance (mais..., cependant...), (3) l''annonce de la partie suivante comme approfondissement ou nuance. Elle assure la cohérence logique du développement.', 'Moyen'),
    (chap_id, 'Quel est le rôle de l''introduction dans une dissertation ?', '["Présenter tous les arguments de la dissertation", "Présenter le sujet, montrer son intérêt, formuler la problématique et annoncer le plan", "Donner la réponse définitive à la question posée", "Résumer les conclusions de la dissertation"]'::jsonb, 'Présenter le sujet, montrer son intérêt, formuler la problématique et annoncer le plan', 'L''introduction remplit quatre fonctions essentielles : (1) amener le sujet (accroche générale), (2) poser le sujet (reformuler et définir les termes), (3) problématiser (formuler la question centrale), (4) annoncer le plan (présenter les grandes parties sans les détailler). Elle doit être en un seul paragraphe ou deux.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "argument" dans un développement de dissertation ?', '["Un exemple tiré d''un roman ou d''un film", "Une raison logique et générale qui soutient la thèse, pouvant se formuler sans exemple précis", "Une citation d''auteur", "Un fait historique précis"]'::jsonb, 'Une raison logique et générale qui soutenir la thèse, pouvant se formuler sans exemple précis', 'L''argument est la raison générale et logique qui soutient la thèse. Il se formule de façon abstraite : "La littérature permet de développer l''empathie." Il précède toujours l''exemple concret qui l''illustre. Un bon argument tient par lui-même, sans avoir besoin de l''exemple pour être compris.', 'Moyen'),
    (chap_id, 'Quel est le rôle de la conclusion dans une dissertation ?', '["Répéter l''introduction mot pour mot", "Faire le bilan de la réflexion en répondant à la problématique, puis ouvrir sur une perspective plus large", "Introduire de nouveaux arguments non développés dans le corps", "Donner son opinion personnelle sur le sujet"]'::jsonb, 'Faire le bilan de la réflexion en répondant à la problématique, puis ouvrir sur une perspective plus large', 'La conclusion remplit deux fonctions : (1) le bilan synthétique du développement (répondre clairement à la problématique en résumant le cheminement intellectuel), et (2) l''ouverture (une question ou perspective nouvelle qui prolonge la réflexion au-delà du sujet traité). Elle doit être en un seul paragraphe.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "plan dialectique" (thèse-antithèse-synthèse) ?', '["Un plan avec trois parties identiques", "Un plan où l''on défend d''abord une position, puis la position contraire, avant de les dépasser dans une synthèse nuancée", "Un plan uniquement pour les dissertations philosophiques", "Un plan avec deux parties opposées sans synthèse"]'::jsonb, 'Un plan où l''on défend d''abord une position, puis la position contraire, avant de les dépasser dans une synthèse nuancée', 'Le plan dialectique suit une progression : Thèse (première position sur le sujet) → Antithèse (position contraire qui nuance la thèse) → Synthèse (dépassement des deux positions précédentes, position plus nuancée). Il convient aux sujets qui demandent de peser le pour et le contre avant d''arriver à une position élaborée.', 'Difficile'),
    (chap_id, 'Comment illustrer un argument avec un exemple dans une dissertation ?', '["En citant n''importe quel livre ou film connu", "En choisissant un exemple précis et pertinent (œuvre littéraire, événement historique, fait réel), en le présentant et en l''analysant pour montrer comment il illustre l''argument", "En résumant longuement une œuvre entière", "En donnant plusieurs exemples sans les analyser"]'::jsonb, 'En choisissant un exemple précis et pertinent (œuvre littéraire, événement historique, fait réel), en le présentant et en l''analysant pour montrer comment il illustre l''argument', 'L''exemple doit être précis (titre, auteur, époque), pertinent (vraiment lié à l''argument) et analysé (montrer explicitement le lien entre l''exemple et l''argument). Un exemple bien choisi mais mal analysé ne prouve rien. La formule est : Argument → Exemple → Analyse du lien → Mini-conclusion.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "cohérence" dans un texte rédigé ?', '["La longueur appropriée du texte", "La logique et la progression des idées, chaque phrase découlant naturellement de la précédente, et chaque paragraphe s''enchaînant logiquement", "L''absence de fautes d''orthographe", "L''utilisation de citations littéraires"]'::jsonb, 'La logique et la progression des idées, chaque phrase découlant naturellement de la précédente, et chaque paragraphe s''enchaînant logiquement', 'La cohérence textuelle se manifeste à plusieurs niveaux : la cohérence thématique (unité du sujet), la cohérence sémantique (pas de contradictions), la cohérence syntaxique (connecteurs logiques) et la cohérence énonciative (point de vue stable). Un texte cohérent guide le lecteur dans la progression des idées.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre une "paraphrase" et une véritable "analyse" dans une dissertation ?', '["Il n''y a aucune différence", "La paraphrase reformule le texte sans l''expliquer ni l''interpréter ; l''analyse va au-delà en dégageant le sens, les enjeux et les procédés", "La paraphrase est réservée aux textes difficiles ; l''analyse aux textes simples", "La paraphrase est plus longue que l''analyse"]'::jsonb, 'La paraphrase reformule le texte sans l''expliquer ni l''interpréter ; l''analyse va au-delà en dégageant le sens, les enjeux et les procédés', 'La paraphrase est un défaut majeur en dissertation : elle se contente de "re-dire" le texte en d''autres mots. L''analyse, au contraire, interprète, questionne, problématise : elle explique POURQUOI et COMMENT un texte fonctionne, quels effets il produit et en quoi il répond à la problématique.', 'Difficile'),
    (chap_id, 'Comment formuler une "phrase de conclusion de paragraphe" efficace ?', '["En répétant le sujet de la dissertation", "En récapitulant l''argument développé dans ce paragraphe et en montrant son lien avec la problématique ou l''axe de la partie", "En introduisant un nouveau sujet pour le paragraphe suivant", "En donnant un exemple supplémentaire"]'::jsonb, 'En récapitulant l''argument développé dans ce paragraphe et en montrant son lien avec la problématique ou l''axe de la partie', 'La phrase de conclusion de paragraphe (ou "phrase-bilan") récapitule en une phrase l''argument et l''exemple du paragraphe, puis établit le lien avec le titre de la partie ou la problématique générale. Elle sert de "porte de sortie" du paragraphe et prépare la transition vers le suivant.', 'Difficile'),
    (chap_id, 'Quel est le rôle des "connecteurs logiques" dans une dissertation ?', '["Ils servent uniquement à commencer chaque paragraphe", "Ils organisent la progression logique des idées en indiquant les relations entre elles : addition, opposition, cause, conséquence, concession", "Ils remplacent les citations d''auteurs", "Ils servent uniquement dans les introductions"]'::jsonb, 'Ils organisent la progression logique des idées en indiquant les relations entre elles : addition, opposition, cause, conséquence, concession', 'Les connecteurs logiques (de plus, cependant, en effet, par conséquent, néanmoins, certes, or, ainsi...) sont essentiels dans une dissertation : ils balisent le raisonnement, indiquent les relations entre les idées et guident le lecteur dans la progression de l''argumentation. Leur emploi varié et précis est signe de maîtrise de l''expression écrite.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "reformulation du sujet" dans l''introduction d''une dissertation ?', '["Copier exactement le sujet donné", "Redire le sujet en d''autres mots pour montrer qu''on l''a compris, en définissant les termes clés et en délimitant le champ de la réflexion", "Choisir un autre sujet plus facile", "Résumer ce qu''on va dire dans le développement"]'::jsonb, 'Redire le sujet en d''autres mots pour montrer qu''on l''a compris, en définissant les termes clés et en délimitant le champ de la réflexion', 'Reformuler le sujet dans l''introduction montre qu''on a compris sa portée. Elle implique de définir les termes clés (par exemple "littérature", "liberté", "engagement"), de délimiter le champ (quelle période ? quelle forme littéraire ?), et de montrer l''enjeu de la question posée avant de formuler la problématique.', 'Moyen'),
    (chap_id, 'Dans une rédaction, qu''est-ce qu''un "paragraphe développé" (PEEL ou méthode équivalente) ?', '["Un paragraphe d''au moins 10 lignes", "Un paragraphe structuré : Point (argument) - Explication - Exemple - Lien (avec la problématique ou la partie)", "Un paragraphe avec plusieurs citations d''auteurs", "Un paragraphe sans introduction ni conclusion"]'::jsonb, 'Un paragraphe structuré : Point (argument) - Explication - Exemple - Lien (avec la problématique ou la partie)', 'La méthode PEEL (Point-Evidence-Explanation-Link) ou son équivalent français est une structure pour rédiger un paragraphe de développement : on énonce l''argument (Point), on l''explique (Explanation), on l''illustre d''un exemple précis (Evidence), et on établit le lien avec la thèse ou problématique (Link).', 'Moyen'),
    (chap_id, 'Pourquoi faut-il éviter le "je" dans une dissertation académique ?', '["Parce que le ''je'' est grammaticalement incorrect", "Parce que la dissertation exige un positionnement objectif et distancié, où l''argument doit convaincre par sa logique et non par l''autorité de l''énonciateur", "Parce que les correcteurs ne comprennent pas le ''je''", "Parce que c''est une règle arbitraire sans raison logique"]'::jsonb, 'Parce que la dissertation exige un positionnement objectif et distancié, où l''argument doit convaincre par sa logique et non par l''autorité de l''énonciateur', 'La dissertation académique vise à une argumentation impersonnelle et universalisable. L''usage du "je" donne l''impression d''une opinion subjective. On préfère des formulations impersonnelles ("On peut affirmer que...", "Il semble que...", "Nous verrons que...") qui confèrent objectivité et distance critique à la réflexion.', 'Difficile');
  END IF;
END $$;

-- Chapitre 4 : Littérature française : du Moyen Âge au 18e siècle NS2
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Littérature française : du Moyen Âge au 18e siècle' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le mouvement littéraire caractéristique de la fin du XVIe et du début du XVIIe siècle, marqué par l''abondance ornementale et le mouvement ?', '["Le classicisme", "Le romantisme", "Le baroque", "L''humanisme"]'::jsonb, 'Le baroque', 'Le baroque (fin XVIe – début XVIIe siècle) se caractérise par l''exubérance formelle, le mouvement, l''irrégularité, le trompe-l''œil et les métamorphoses. En littérature : Agrippa d''Aubigné (Les Tragiques), Théophile de Viau. Le baroque s''oppose au classicisme qui lui succède.', 'Moyen'),
    (chap_id, 'Quel mouvement littéraire du XVIIe siècle prône la raison, l''ordre, la clarté et l''imitation des Anciens ?', '["Le baroque", "Le romantisme", "Le classicisme", "Le symbolisme"]'::jsonb, 'Le classicisme', 'Le classicisme (XVIIe siècle, notamment sous Louis XIV) prône la raison, la mesure, l''ordre, la clarté et l''imitation des Anciens (Grecs et Latins). Ses règles : vraisemblance, bienséance, unités du théâtre (temps, lieu, action). Auteurs : Molière, Racine, Corneille, La Fontaine, Boileau.', 'Facile'),
    (chap_id, 'Qui a écrit "Les Fables" au XVIIe siècle, courts récits poétiques mettant souvent en scène des animaux pour illustrer une morale ?', '["Jean Racine", "Jean de La Fontaine", "Molière", "Pierre Corneille"]'::jsonb, 'Jean de La Fontaine', 'Jean de La Fontaine (1621-1695) a écrit les célèbres Fables (1668-1694), publiées en 12 livres, inspirées d''Ésope et de Phèdre. Ces courts récits poétiques mettent en scène des animaux personnifiés pour illustrer des vérités morales avec humour et finesse. "La Cigale et la Fourmi" est la plus connue.', 'Facile'),
    (chap_id, 'Quelle est la règle des "trois unités" dans le théâtre classique français du XVIIe siècle ?', '["Unité de style, de personnages et de décors", "Unité de temps (24h), de lieu (un seul endroit), d''action (une intrigue principale)", "Unité de langue, de ton et de morale", "Unité d''auteur, d''époque et de genre"]'::jsonb, 'Unité de temps (24h), de lieu (un seul endroit), d''action (une intrigue principale)', 'Les trois unités du théâtre classique (codifiées par Boileau dans L''Art poétique) exigent : unité de temps (l''action doit se dérouler en 24h maximum), unité de lieu (un seul décor), unité d''action (une seule intrigue principale, sans sous-intrigues indépendantes). Ces règles visent la vraisemblance et la concentration dramatique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''"Humanisme" de la Renaissance (XVIe siècle) en littérature française ?', '["Un mouvement qui rejette l''Antiquité au profit de la modernité", "Un mouvement qui place l''être humain au centre de la réflexion, valorise les textes antiques et grecs, et prône l''éducation et la liberté de pensée", "Un mouvement exclusivement religieux", "Un mouvement qui s''oppose à toute forme d''art"]'::jsonb, 'Un mouvement qui place l''être humain au centre de la réflexion, valorise les textes antiques et grecs, et prône l''éducation et la liberté de pensée', 'L''Humanisme de la Renaissance (XVIe siècle) redécouvre les textes grecs et latins, place l''homme au centre (vs le Moyen Âge théocentrique), valorise l''éducation, la raison et la liberté de conscience. Auteurs : Rabelais (Gargantua, Pantagruel), Montaigne (Essais), Ronsard (Sonnets pour Hélène).', 'Moyen'),
    (chap_id, 'Quel philosophe et écrivain du XVIIIe siècle a écrit "Candide" (1759), conte philosophique critiquant l''optimisme de Leibniz ?', '["Jean-Jacques Rousseau", "Denis Diderot", "Voltaire (François-Marie Arouet)", "Montesquieu"]'::jsonb, 'Voltaire (François-Marie Arouet)', 'Voltaire (1694-1778) a écrit Candide ou l''Optimisme (1759), conte philosophique satirique qui critique la théorie de Leibniz selon laquelle "tout est pour le mieux dans le meilleur des mondes possibles". À travers les mésaventures de Candide, Voltaire dénonce les guerres, l''intolérance religieuse et l''esclavage.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les "Lumières" (XVIIIe siècle) en France ?', '["Un mouvement artistique centré sur la peinture lumineuse", "Un mouvement philosophique qui défend la raison, la liberté, la tolérance et le progrès contre l''obscurantisme et le fanatisme", "Un mouvement religieux mystique", "Un courant littéraire privilégiant les descriptions de la nature"]'::jsonb, 'Un mouvement philosophique qui défend la raison, la liberté, la tolérance et le progrès contre l''obscurantisme et le fanatisme', 'Les Lumières (Aufklärung) sont un mouvement philosophique du XVIIIe siècle qui utilise la raison pour combattre les préjugés, l''intolérance religieuse et les abus du pouvoir. Ses figures : Voltaire, Rousseau, Diderot, Montesquieu. L''Encyclopédie (1751-1772) en est l''œuvre emblématique.', 'Facile'),
    (chap_id, 'Quel philosophe du XVIIIe siècle a écrit "Du Contrat Social" (1762) et développé la théorie de la souveraineté populaire ?', '["Voltaire", "Diderot", "Montesquieu", "Jean-Jacques Rousseau"]'::jsonb, 'Jean-Jacques Rousseau', 'Jean-Jacques Rousseau (1712-1778) a écrit Du Contrat Social (1762), où il développe la théorie selon laquelle la légitimité du pouvoir politique vient du peuple (volonté générale). Il a influencé la Révolution française et les démocraties modernes. Il est aussi l''auteur des Confessions et d''Émile.', 'Moyen'),
    (chap_id, 'Quel est le genre littéraire dominant du Moyen Âge qui raconte les aventures de chevaliers en quête de gloire ou d''amour courtois ?', '["La fable", "L''épopée antique", "Le roman courtois (ou roman de chevalerie)", "La tragédie classique"]'::jsonb, 'Le roman courtois (ou roman de chevalerie)', 'Le roman courtois (XIIe-XIIIe siècles) met en scène des chevaliers (Lancelot, Perceval, Tristan) en quête d''idéaux chevaleresques et d''amour courtois. Chrétien de Troyes est le maître du genre : Yvain ou le Chevalier au lion, Lancelot. La Chanson de Roland (XIe s.) relève plutôt de l''épopée.', 'Moyen'),
    (chap_id, 'Quelle pièce de Molière (1622-1673) critique l''hypocrisie religieuse et le faux dévot ?', '["L''Avare", "Le Misanthrope", "Tartuffe ou l''Imposteur", "Dom Juan"]'::jsonb, 'Tartuffe ou l''Imposteur', 'Tartuffe ou l''Imposteur (1664, créé en version intégrale en 1669) est la comédie de Molière qui dénonce l''hypocrisie religieuse à travers le personnage de Tartuffe, faux dévot qui manipule la famille d''Orgon. La pièce fut censurée par l''Église avant d''être finalement jouée.', 'Moyen'),
    (chap_id, 'Quel est le "genre épistolaire" en littérature française et quelle œuvre du XVIIIe siècle en est un chef-d''œuvre ?', '["Le genre dramatique ; le Cid de Corneille", "Le genre des textes écrits sous forme de lettres ; Les Liaisons dangereuses de Choderlos de Laclos (1782)", "Le genre des mémoires autobiographiques ; Les Confessions de Rousseau", "Le genre des textes philosophiques ; l''Encyclopédie de Diderot"]'::jsonb, 'Le genre des textes écrits sous forme de lettres ; Les Liaisons dangereuses de Choderlos de Laclos (1782)', 'Le roman épistolaire est un récit composé de lettres échangées entre personnages. Les Liaisons dangereuses (1782) de Laclos est un chef-d''œuvre du genre : deux libertins (Valmont et Merteuil) s''écrivent pour planifier leurs conquêtes amoureuses. D''autres exemples : La Nouvelle Héloïse de Rousseau, Lettres persanes de Montesquieu.', 'Difficile'),
    (chap_id, 'Quel poète de la Pléiade du XVIe siècle est l''auteur des "Sonnets pour Hélène" et a popularisé le sonnet en France ?', '["François Villon", "Joachim du Bellay", "Pierre de Ronsard", "Agrippa d''Aubigné"]'::jsonb, 'Pierre de Ronsard', 'Pierre de Ronsard (1524-1585), "Prince des poètes", a popularisé le sonnet en France (Amours, Sonnets pour Hélène). Avec du Bellay (Défense et illustration de la langue française), il fonde la Pléiade, groupe de poètes qui veulent enrichir la langue française sur le modèle des langues antiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "bienséance" dans le théâtre classique français du XVIIe siècle ?', '["La règle selon laquelle le spectacle dure au maximum 2 heures", "La règle selon laquelle certaines scènes violentes ou choquantes ne peuvent être représentées sur scène et doivent être racontées off-stage", "La règle exigeant que tous les personnages soient de rang noble", "La règle interdisant les personnages féminins sur scène"]'::jsonb, 'La règle selon laquelle certaines scènes violentes ou choquantes ne peuvent être représentées sur scène et doivent être racontées off-stage', 'La bienséance (une des règles du classicisme) interdit de représenter sur scène les actions violentes, indécentes ou grossières qui heurteraient le public : meurtres, batailles, actes sexuels. Ces événements se passent "en coulisses" et sont racontés par un personnage. Œdipe se crève les yeux dans les coulisses, pas devant le public.', 'Difficile'),
    (chap_id, 'Quelle est la thèse philosophique principale développée par Montaigne dans ses "Essais" (1580-1588) ?', '["La supériorité de la civilisation européenne sur toutes les autres", "Le scepticisme et la connaissance de soi : ''Que sais-je ?'', avec l''idée que la sagesse consiste à accepter l''incertitude et à se connaître soi-même", "La nécessité d''obéir aux autorités religieuses", "La séparation absolue de la philosophie et de la religion"]'::jsonb, 'Le scepticisme et la connaissance de soi : ''Que sais-je ?'', avec l''idée que la sagesse consiste à accepter l''incertitude et à se connaître soi-même', 'Montaigne (1533-1592) dans les Essais développe un scepticisme humaniste : sa devise "Que sais-je ?" exprime le doute comme sagesse. Il tourne son regard vers lui-même ("Chaque homme porte la forme entière de l''humaine condition") et prône la tolérance face aux guerres de religion. Il invente le genre de l''essai.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "tragédie classique" au XVIIe siècle en France et quels en sont les thèmes principaux ?', '["Une pièce comique se terminant par un mariage", "Un genre dramatique représentant la chute inéluctable d''un héros de rang élevé, aux prises avec des passions dévastatrices ou le destin", "Un texte philosophique en prose sur la mort", "Un récit épique en vers sur des batailles"]'::jsonb, 'Un genre dramatique représentant la chute inéluctable d''un héros de rang élevé, aux prises avec des passions dévastatrices ou le destin', 'La tragédie classique (Racine, Corneille) met en scène des personnages de rang élevé (rois, princes) déchirés entre raison et passion, liberté et destin. Elle se termine par la mort ou la ruine. Exemples : Phèdre (Racine), Le Cid (Corneille). Elle vise à provoquer catharsis (purification des passions) chez le spectateur.', 'Moyen'),
    (chap_id, 'Quelle invention du XVe siècle a révolutionné la diffusion de la littérature et favorisé l''Humanisme et la Renaissance ?', '["La presse à imprimer à caractères mobiles de Gutenberg (vers 1450)", "L''invention du papier en Europe", "La création des premières bibliothèques universitaires", "L''introduction de l''alphabet latin dans les langues vernaculaires"]'::jsonb, 'La presse à imprimer à caractères mobiles de Gutenberg (vers 1450)', 'La presse à imprimer de Gutenberg (vers 1450) a révolutionné la diffusion des textes : la Bible, les textes antiques et les œuvres humanistes ont pu être reproduits en grande quantité à faible coût. Cela a favorisé l''Humanisme, la Réforme protestante et la diffusion des Lumières au XVIIIe siècle.', 'Moyen');
  END IF;
END $$;

-- Chapitre 5 : Littérature française : 19e et 20e siècles NS2
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 25 AND titre = 'Littérature française : 19e et 20e siècles' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel mouvement littéraire du XIXe siècle réagit contre la raison des Lumières et valorise les sentiments, la nature et le moi ?', '["Le réalisme", "Le symbolisme", "Le romantisme", "Le naturalisme"]'::jsonb, 'Le romantisme', 'Le romantisme (début XIXe siècle) est une réaction contre la raison froide des Lumières. Il exalte les émotions, la nature sauvage, le "mal du siècle" (mélancolie), l''histoire nationale et le génie individuel. Auteurs : Victor Hugo, Lamartine, Musset, Vigny, Chateaubriand.', 'Facile'),
    (chap_id, 'Quel roman de Victor Hugo (1862) dénonce les injustices sociales à travers les aventures de Jean Valjean et du policier Javert ?', '["Notre-Dame de Paris", "Les Misérables", "Le Dernier Jour d''un condamné", "L''Homme qui rit"]'::jsonb, 'Les Misérables', 'Les Misérables (1862) de Victor Hugo est un roman-fleuve qui dénonce la misère sociale, l''injustice du système pénal et la rédemption possible de l''homme. Jean Valjean, ancien forçat, cherche sa rédemption face au policier Javert. L''œuvre incarne l''engagement social de Hugo pour les opprimés.', 'Facile'),
    (chap_id, 'Quel mouvement littéraire du XIXe siècle cherche à représenter la réalité sociale avec objectivité et exactitude, s''opposant à l''idéalisation romantique ?', '["Le romantisme", "Le symbolisme", "Le réalisme", "Le surréalisme"]'::jsonb, 'Le réalisme', 'Le réalisme (milieu XIXe siècle) vise à décrire la réalité sociale telle qu''elle est, sans idéalisation. Auteurs : Balzac (La Comédie humaine), Stendhal (Le Rouge et le Noir), Flaubert (Madame Bovary). Le naturalisme (Zola) en est un prolongement scientifique, influencé par les théories de Darwin et Claude Bernard.', 'Facile'),
    (chap_id, 'Quelle œuvre d''Émile Zola (1885) décrit la vie des mineurs du nord de la France et constitue le 13e volume des Rougon-Macquart ?', '["L''Assommoir", "Nana", "Germinal", "Au Bonheur des Dames"]'::jsonb, 'Germinal', 'Germinal (1885) de Zola raconte la grève des mineurs de la mine de Voreux dans le Nord de la France. C''est l''un des plus grands romans sociaux français. Il fait partie du cycle des Rougon-Macquart, 20 romans décrivant scientifiquement une famille sous le Second Empire, influencés par le naturalisme.', 'Moyen'),
    (chap_id, 'Quel est le mouvement littéraire du début du XXe siècle qui explore l''inconscient, les rêves et libère l''écriture des contraintes rationnelles ?', '["Le réalisme", "Le naturalisme", "Le surréalisme", "L''existentialisme"]'::jsonb, 'Le surréalisme', 'Le surréalisme (1924, Manifeste d''André Breton) s''inspire des théories de Freud sur l''inconscient. Il libère l''écriture et l''art des contraintes rationnelles par l''écriture automatique, les rêves et le hasard. Auteurs : Breton (Nadja), Aragon, Éluard, Desnos. En peinture : Dalí, Magritte.', 'Moyen'),
    (chap_id, 'Quel philosophe et romancier français du XXe siècle est le représentant majeur de l''existentialisme et auteur de "L''Être et le Néant" et "La Nausée" ?', '["Albert Camus", "Simone de Beauvoir", "Jean-Paul Sartre", "André Malraux"]'::jsonb, 'Jean-Paul Sartre', 'Jean-Paul Sartre (1905-1980) est le philosophe de l''existentialisme : "L''existence précède l''essence" (l''homme se définit par ses actes, pas par une nature préétablie). Œuvres : L''Être et le Néant (essai), La Nausée (roman), Huis clos (théâtre). Il a refusé le Prix Nobel de littérature en 1964.', 'Moyen'),
    (chap_id, 'Quel roman d''Albert Camus (1942) met en scène Meursault, un homme qui tue un Arabe sans émotion apparente, illustrant l''absurde ?', '["La Chute", "L''Étranger", "La Peste", "Le Mythe de Sisyphe"]'::jsonb, 'L''Étranger', 'L''Étranger (1942) d''Albert Camus présente Meursault, personnage "étranger" à sa propre vie et aux conventions sociales, qui tue un Arabe sur une plage et sera condamné davantage pour son indifférence lors de la mort de sa mère que pour le meurtre. C''est une illustration de la philosophie de l''absurde de Camus.', 'Moyen'),
    (chap_id, 'Quel mouvement poétique de la fin du XIXe siècle cherche à suggérer plutôt qu''à décrire, en utilisant la musicalité des mots ?', '["Le Parnasse", "Le réalisme", "Le symbolisme", "Le Dadaïsme"]'::jsonb, 'Le symbolisme', 'Le symbolisme (fin XIXe siècle) réagit contre le réalisme et le Parnasse. Il cherche à suggérer les émotions et les états d''âme par la musicalité des mots et les symboles plutôt que par la description directe. Auteurs : Mallarmé, Verlaine (Art poétique : "De la musique avant toute chose"), Rimbaud.', 'Moyen'),
    (chap_id, 'Quel est l''apport de Gustave Flaubert à la technique romanesque avec "Madame Bovary" (1857) ?', '["Il a introduit le roman-fleuve en France", "Il a révolutionné la technique narrative avec le style indirect libre et une recherche du ''mot juste''", "Il a créé le roman naturaliste fondé sur des enquêtes scientifiques", "Il a introduit le monologue intérieur dans le roman français"]'::jsonb, 'Il a révolutionné la technique narrative avec le style indirect libre et une recherche du ''mot juste''', 'Flaubert a révolutionné le roman avec Madame Bovary : il perfectionne le style indirect libre (pensées du personnage intégrées au récit à la 3e personne), traque le "mot juste" (réécriture obsessionnelle), et efface l''auteur derrière ses personnages. Ces innovations ont profondément influencé le roman moderne.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "Nouveau Roman" français des années 1950-1960 ?', '["Un genre de romans d''aventures populaires", "Un mouvement littéraire qui remet en cause les conventions du roman traditionnel (intrigue, personnages, chronologie) pour explorer de nouvelles formes narratives", "Un ensemble de romans autobiographiques de l''après-guerre", "Un mouvement qui cherche à rendre le roman plus accessible au grand public"]'::jsonb, 'Un mouvement littéraire qui remet en cause les conventions du roman traditionnel (intrigue, personnages, chronologie) pour explorer de nouvelles formes narratives', 'Le Nouveau Roman (Alain Robbe-Grillet, Nathalie Sarraute, Marguerite Duras, Claude Simon) conteste les conventions romanesques : pas d''intrigue linéaire, personnages sans psychologie traditionnelle, descriptions minutieuses des objets, temps fragmenté. Exemple : La Jalousie de Robbe-Grillet. Il reflète une vision du monde moderne sans sens prédéterminé.', 'Difficile'),
    (chap_id, 'Quel poète français du XIXe siècle est l''auteur des "Fleurs du Mal" (1857), condamné pour immoralité ?', '["Paul Verlaine", "Arthur Rimbaud", "Charles Baudelaire", "Stéphane Mallarmé"]'::jsonb, 'Charles Baudelaire', 'Charles Baudelaire (1821-1867) a publié Les Fleurs du Mal (1857), recueil poétique condamné pour immoralité (6 pièces censurées). Il explore la beauté dans le vice, la mélancolie ("spleen"), l''idéal et le mal. Baudelaire est le pont entre le romantisme et le symbolisme, inventeur de la "modernité" poétique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "poésie engagée" au XXe siècle et qui en sont les représentants français ?', '["Une poésie qui célèbre la nature et les saisons", "Une poésie qui met la littérature au service d''une cause politique, sociale ou humaniste", "Une poésie exclusivement religieuse", "Une poésie qui respecte strictement les formes fixes comme le sonnet"]'::jsonb, 'Une poésie qui met la littérature au service d''une cause politique, sociale ou humaniste', 'La poésie engagée met l''écriture au service d''une lutte : Aragon et Éluard pendant la Résistance, Aimé Césaire (Cahier d''un retour au pays natal) contre le colonialisme, Senghor pour la Négritude. L''engagement en littérature est aussi défendu par Sartre : "Qu''est-ce que la littérature ?" (1947).', 'Moyen'),
    (chap_id, 'Quel est le thème central du roman "La Condition humaine" (1933) d''André Malraux ?', '["L''aventure exotique en Asie sans enjeux politiques", "La révolution chinoise de 1927 comme mise en scène de la question du sens de l''existence humaine face à la mort et à l''histoire", "Un roman autobiographique sur la vie de Malraux en Indochine", "La critique de la politique coloniale française en Asie"]'::jsonb, 'La révolution chinoise de 1927 comme mise en scène de la question du sens de l''existence humaine face à la mort et à l''histoire', 'La Condition humaine (Prix Goncourt, 1933) de Malraux se déroule lors de l''insurrection communiste de Shanghai (1927). À travers des révolutionnaires condamnés à mort, Malraux explore la "condition humaine" : la solitude, la fraternité face à la mort, le rapport entre action politique et recherche du sens de l''existence.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "Négritude" comme mouvement littéraire du XXe siècle ?', '["Un mouvement qui défend la suprématie culturelle africaine", "Un mouvement culturel et littéraire né dans les années 1930, affirmant la valeur et la fierté des cultures noires face au colonialisme et à l''assimilation", "Un mouvement exclusivement haïtien de revalorisation de la culture créole", "Un mouvement politique panafricaniste sans dimension littéraire"]'::jsonb, 'Un mouvement culturel et littéraire né dans les années 1930, affirmant la valeur et la fierté des cultures noires face au colonialisme et à l''assimilation', 'La Négritude est fondée dans les années 1930 à Paris par Aimé Césaire (Martinique), Léopold Sédar Senghor (Sénégal) et Léon-Gontran Damas (Guyane). Elle affirme la fierté de l''identité noire, critique le colonialisme et valorise les cultures africaines. Elle a influencé l''indigénisme haïtien et les mouvements de décolonisation.', 'Moyen'),
    (chap_id, 'Quel roman de Marcel Proust (7 volumes, 1913-1927) explore la mémoire involontaire et le temps perdu à travers la vie de son narrateur dans la société bourgeoise et aristocratique française ?', '["À la recherche du temps perdu", "Les Faux-Monnayeurs", "Le Grand Meaulnes", "Jean-Christophe"]'::jsonb, 'À la recherche du temps perdu', 'À la recherche du temps perdu (1913-1927) de Marcel Proust est l''une des plus grandes œuvres de la littérature mondiale. En 7 volumes (dont Du côté de chez Swann), le narrateur explore la mémoire involontaire (la madeleine trempée dans le thé) et reconstruit le temps perdu pour donner un sens à son existence.', 'Moyen'),
    (chap_id, 'Quel courant littéraire du XXe siècle, né au lendemain de la Première Guerre mondiale, refuse toute logique et toute esthétique pour détruire les valeurs de la société bourgeoise ?', '["Le surréalisme", "Le dadaïsme", "L''existentialisme", "Le naturalisme"]'::jsonb, 'Le dadaïsme', 'Le dadaïsme (1916, Zurich, Tristan Tzara) est un mouvement de révolte totale née du traumatisme de la Première Guerre mondiale. Il refuse toute logique, toute esthétique et toute morale "bourgeoise", prônant le nonsense, le hasard et la destruction des conventions. Il a préparé le terrain pour le surréalisme.', 'Difficile');
  END IF;
END $$;
