-- Supplement Biologie (matiere_id=11) — NS3 et NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'ADN, réplication et expression génétique' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui a déterminé la structure en double hélice de l''ADN et en quelle année ?', '["Mendel en 1865","Watson et Crick en 1953, s''appuyant sur les données de Franklin","Pasteur en 1870","Lamarck en 1809"]'::jsonb, 'Watson et Crick en 1953, s''appuyant sur les données de Franklin', 'Watson, Crick et Franklin (données de diffraction X) ont établi le modèle de la double hélice antiparallèle de l''ADN.', 'Facile'),
    (chap_id, 'Qu''est-ce que la complémentarité des bases azotées dans l''ADN ?', '["Toutes les bases s''apparient avec toutes","Adénine (A) s''apparie avec Thymine (T) par 2 liaisons H ; Guanine (G) avec Cytosine (C) par 3 liaisons H","A-G et T-C s''apparient","Les bases ne s''apparient pas"]'::jsonb, 'Adénine (A) s''apparie avec Thymine (T) par 2 liaisons H ; Guanine (G) avec Cytosine (C) par 3 liaisons H', 'La règle de Chargaff (%A=%T, %G=%C) découle de l''appariement spécifique ; la paire G-C est plus stable (3 liaisons H).', 'Facile'),
    (chap_id, 'Qu''est-ce que la réplication semi-conservative de l''ADN ?', '["Chaque brin parental est dégradé","Chaque brin parental sert de matrice pour un nouveau brin complémentaire, donnant 2 molécules filles hybrides (1 brin parental + 1 nouveau)","Les deux brins sont reconstruits entièrement","La réplication est conservative (les deux brins parentaux restent ensemble)"]'::jsonb, 'Chaque brin parental sert de matrice pour un nouveau brin complémentaire, donnant 2 molécules filles hybrides (1 brin parental + 1 nouveau)', 'Meselson et Stahl (1958) ont confirmé la réplication semi-conservative par l''expérience aux isotopes N14/N15.', 'Moyen'),
    (chap_id, 'Quel est le rôle de l''ADN polymérase dans la réplication ?', '["Couper l''ADN","Synthétiser le nouveau brin d''ADN en lisant le brin matrice dans le sens 3''→5'' et en ajoutant des nucléotides en 5''→3''","Dérouler la double hélice","Lier les fragments d''Okazaki"]'::jsonb, 'Synthétiser le nouveau brin d''ADN en lisant le brin matrice dans le sens 3''→5'' et en ajoutant des nucléotides en 5''→3''', 'L''ADN polymérase ne peut synthétiser que dans le sens 5''→3'' ; d''où la différence entre brin continu et brin discontinu.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la transcription et où se déroule-t-elle dans une cellule eucaryote ?', '["La synthèse d''une protéine","La synthèse d''un ARNm à partir d''un brin d''ADN matrice par l''ARN polymérase, dans le noyau","La réplication de l''ADN","La traduction de l''ARNm"]'::jsonb, 'La synthèse d''un ARNm à partir d''un brin d''ADN matrice par l''ARN polymérase, dans le noyau', 'La transcription (ADN→ARNm) se déroule dans le noyau chez les eucaryotes ; l''ARNm est ensuite exporté dans le cytoplasme.', 'Facile'),
    (chap_id, 'Qu''est-ce que la traduction et où se déroule-t-elle ?', '["La transcription de l''ADN","La synthèse d''une chaîne polypeptidique à partir du code de l''ARNm, au niveau des ribosomes dans le cytoplasme","La réplication de l''ARN","La dégradation des protéines"]'::jsonb, 'La synthèse d''une chaîne polypeptidique à partir du code de l''ARNm, au niveau des ribosomes dans le cytoplasme', 'La traduction (ARNm→protéine) requiert l''ARNm, les ARNt, les ribosomes et l''ARNr (rRNA dans les ribosomes).', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un codon et comment code-t-il pour un acide aminé ?', '["Un nucléotide unique","Une séquence de 3 nucléotides de l''ARNm qui spécifie un acide aminé particulier ou un signal stop","Une protéine","Un intron"]'::jsonb, 'Une séquence de 3 nucléotides de l''ARNm qui spécifie un acide aminé particulier ou un signal stop', 'Le code génétique est triplet (64 codons pour 20 AA + 3 stop) : il est universel, redondant et sans chevauchement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le traitement (maturation) de l''ARNm chez les eucaryotes ?', '["L''ARNm est directement traduit sans modification","La coiffe 5'', la queue poly-A 3'' et l''épissage des introns (retrait) pour ne garder que les exons","L''ARNm est dégradé immédiatement","L''ARN polymérase modifie l''ARNm"]'::jsonb, 'La coiffe 5'', la queue poly-A 3'' et l''épissage des introns (retrait) pour ne garder que les exons', 'Le pré-ARNm eucaryote est matured dans le noyau : coiffe 5''-méthylguanosine, poly-A 3'', épissage (splicing) des introns.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''épissage alternatif et quelle est son importance ?', '["Un type de mutation","La possibilité d''inclure ou d''exclure différents exons lors de l''épissage, produisant plusieurs protéines à partir d''un seul gène","Un mécanisme de réplication","Un processus de dégradation de l''ARN"]'::jsonb, 'La possibilité d''inclure ou d''exclure différents exons lors de l''épissage, produisant plusieurs protéines à partir d''un seul gène', 'L''épissage alternatif explique pourquoi ~20 000 gènes humains produisent plus de 100 000 protéines différentes.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une mutation ponctuelle et quels en sont les types ?', '["Le remplacement d''un chromosome entier","Un changement d''un seul nucléotide dans la séquence d''ADN : substitution (transition/transversion), insertion ou délétion","Une mutation chromosomique","Une polyploïdie"]'::jsonb, 'Un changement d''un seul nucléotide dans la séquence d''ADN : substitution (transition/transversion), insertion ou délétion', 'Les mutations ponctuelles peuvent être silencieuses, faux-sens, non-sens ou de décalage du cadre de lecture (frameshift).', 'Moyen'),
    (chap_id, 'Quel est le rôle de l''ARN de transfert (ARNt) dans la traduction ?', '["Il code pour les protéines","Il transporte un acide aminé spécifique vers le ribosome et reconnaît le codon de l''ARNm via son anticodon complémentaire","Il sert de matrice pour l''ARNm","Il dégrade les protéines"]'::jsonb, 'Il transporte un acide aminé spécifique vers le ribosome et reconnaît le codon de l''ARNm via son anticodon complémentaire', 'L''ARNt est la molécule adaptatrice entre le code nucléique (triplets ARNm) et la séquence protéique (acides aminés).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''opéron lac chez E. coli et son intérêt pour comprendre la régulation des gènes ?', '["Un gène unique","Un ensemble de gènes structuraux sous contrôle d''un promoteur commun, régulés par un répresseur et un inducteur (lactose), modèle de la régulation génique procaryote","Un mécanisme de recombinaison","Un plasmide"]'::jsonb, 'Un ensemble de gènes structuraux sous contrôle d''un promoteur commun, régulés par un répresseur et un inducteur (lactose), modèle de la régulation génique procaryote', 'Le modèle de Jacob et Monod (1961, Nobel 1965) sur l''opéron lactose a révolutionné la compréhension de la régulation génique.', 'Moyen'),
    (chap_id, 'Quel est le rôle de la télomérase dans les cellules eucaryotes ?', '["Initier la réplication","Allonger les télomères qui raccourcissent à chaque réplication, maintenant l''intégrité chromosomique dans les cellules germinales et les cellules souches","Réparer les cassures double brin","Épissage des introns"]'::jsonb, 'Allonger les télomères qui raccourcissent à chaque réplication, maintenant l''intégrité chromosomique dans les cellules germinales et les cellules souches', 'Sans télomérase, les cellules somatiques vieillissent (sénescence) ; la télomérase active est un marqueur de certains cancers.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Évolution et classification du vivant' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la théorie de l''évolution par la sélection naturelle proposée par Darwin ?', '["Les espèces sont immuables","Les individus les mieux adaptés à leur environnement survivent préférentiellement et se reproduisent davantage, transmettant leurs caractères avantageux","L''évolution est dirigée vers la complexité","Les caractères acquis sont héréditaires"]'::jsonb, 'Les individus les mieux adaptés à leur environnement survivent préférentiellement et se reproduisent davantage, transmettant leurs caractères avantageux', 'Darwin (1859) : variation + hérédité + sélection naturelle = évolution. L''adaptation est graduelle et sans direction fixée.', 'Facile'),
    (chap_id, 'Quelle est la différence entre l''évolution de Lamarck et celle de Darwin ?', '["Elles sont identiques","Lamarck proposait l''hérédité des caractères acquis et une volonté interne ; Darwin proposait la variation héréditaire aléatoire et la sélection naturelle","Darwin est antérieur à Lamarck","Lamarck n''a pas théorisé l''évolution"]'::jsonb, 'Lamarck proposait l''hérédité des caractères acquis et une volonté interne ; Darwin proposait la variation héréditaire aléatoire et la sélection naturelle', 'La théorie de Lamarck (girafe allongeant le cou) est réfutée ; celle de Darwin est confirmée par la génétique moderne.', 'Facile'),
    (chap_id, 'Qu''est-ce que la dérive génétique et comment diffère-t-elle de la sélection naturelle ?', '["Elles sont identiques","La dérive génétique est une variation aléatoire des fréquences alléliques (non due à l''adaptation) ; elle est plus forte dans les petites populations","La dérive génétique augmente toujours l''adaptation","La sélection naturelle est aléatoire"]'::jsonb, 'La dérive génétique est une variation aléatoire des fréquences alléliques (non due à l''adaptation) ; elle est plus forte dans les petites populations', 'La dérive génétique (effet stochastique) peut fixer des allèles neutres ou même délétères dans les petites populations.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la spéciation allopatrique et quand se produit-elle ?', '["La spéciation par compétition directe","La formation d''une nouvelle espèce suite à l''isolement géographique de populations d''une même espèce (flux génique interrompu, divergence)","La spéciation en sympatrie","La spéciation par polyploïdie uniquement"]'::jsonb, 'La formation d''une nouvelle espèce suite à l''isolement géographique de populations d''une même espèce (flux génique interrompu, divergence)', 'L''isolement géographique (chaîne de montagnes, bras de mer) permet à des populations de diverger génétiquement jusqu''à l''isolement reproducteur.', 'Moyen'),
    (chap_id, 'Quelles sont les preuves moléculaires de l''évolution commune ?', '["L''absence de similitudes","La comparaison des séquences d''ADN/protéines montrant que des espèces apparentées partagent davantage de séquences communes","La différence de taille entre espèces","L''absence de fossiles"]'::jsonb, 'La comparaison des séquences d''ADN/protéines montrant que des espèces apparentées partagent davantage de séquences communes', 'La phylogénétique moléculaire utilise les homologies de séquences (ADNr 16S, cytochrome c) pour établir les liens évolutifs.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la classification phylogénétique (cladistique) ?', '["Classer les organismes par ressemblance morphologique","Regrouper les organismes selon leur histoire évolutive commune (ancêtre partagé), basée sur les synapomorphies (caractères dérivés partagés)","Classer par habitat","Classer par taille"]'::jsonb, 'Regrouper les organismes selon leur histoire évolutive commune (ancêtre partagé), basée sur les synapomorphies (caractères dérivés partagés)', 'La cladistique (Hennig, 1950) cherche des groupes monophylétiques (clades) ; elle a remplacé la classification purement morphologique.', 'Moyen'),
    (chap_id, 'Quel est le principe de la théorie synthétique de l''évolution (néo-darwinisme) ?', '["La sélection naturelle seule explique tout","La synthèse de la sélection naturelle (Darwin) et de la génétique mendélienne et des populations, intégrant mutations, dérive, flux génique et sélection comme forces évolutives","L''évolution est uniquement moléculaire","Les espèces n''évoluent pas"]'::jsonb, 'La synthèse de la sélection naturelle (Darwin) et de la génétique mendélienne et des populations, intégrant mutations, dérive, flux génique et sélection comme forces évolutives', 'La théorie synthétique (années 1930-1940) unifie Darwin, Mendel, la génétique des populations (Hardy-Weinberg).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un organe homologue et comment diffère-t-il d''un organe analogue ?', '["Ils sont identiques","Les organes homologues ont une même origine embryonnaire mais des fonctions différentes (bras humain/aile de chauve-souris) ; les analogues ont des fonctions similaires mais des origines différentes (aile d''oiseau/insecte)","Les analogues ont la même origine","Les homologues ont des fonctions identiques"]'::jsonb, 'Les organes homologues ont une même origine embryonnaire mais des fonctions différentes (bras humain/aile de chauve-souris) ; les analogues ont des fonctions similaires mais des origines différentes (aile d''oiseau/insecte)', 'Les homologues révèlent un ancêtre commun (évolution divergente) ; les analogues montrent l''évolution convergente.', 'Moyen'),
    (chap_id, 'Quelle est la signification de la nomenclature binominale de Linné ?', '["Un nom unique pour chaque individu","Chaque espèce est nommée par deux mots latins : le genre (majuscule) et l''épithète spécifique (minuscule), ex. Homo sapiens","Une classification en 3 règnes","Un système de classification numérique"]'::jsonb, 'Chaque espèce est nommée par deux mots latins : le genre (majuscule) et l''épithète spécifique (minuscule), ex. Homo sapiens', 'La nomenclature binominale (Linné, 1753) est universelle et en italique : Homo sapiens, Canis lupus, etc.', 'Facile'),
    (chap_id, 'Qu''est-ce que la coévolution et quel en est un exemple classique ?', '["L''évolution indépendante de deux espèces","L''évolution mutuelle de deux espèces interagissant, chaque changement de l''une exerçant une pression sélective sur l''autre (ex. fleur et pollinisateur)","L''évolution uniquement parasitaire","La convergence évolutive"]'::jsonb, 'L''évolution mutuelle de deux espèces interagissant, chaque changement de l''une exerçant une pression sélective sur l''autre (ex. fleur et pollinisateur)', 'Coévolution : orchidées de Madagascar et Xanthopan morganii (Darwin l''avait prédit avant sa découverte).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''endosymbiose et comment explique-t-elle l''origine des mitochondries et des chloroplastes ?', '["Une théorie réfutée","La théorie selon laquelle des bactéries ont été englouties par des cellules hôtes sans être digérées, devenant des organites (Lynn Margulis)","Une forme de parasitisme","Un mécanisme de division cellulaire"]'::jsonb, 'La théorie selon laquelle des bactéries ont été englouties par des cellules hôtes sans être digérées, devenant des organites (Lynn Margulis)', 'La théorie endosymbiotique est confirmée par l''ADN circulaire des mitochondries/chloroplastes et leurs propres ribosomes 70S.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la sélection sexuelle et comment diffère-t-elle de la sélection naturelle de survie ?', '["Elles sont identiques","La sélection sexuelle favorise les traits améliorant le succès reproducteur (séduction des partenaires ou compétition entre mâles) même s''ils réduisent la survie","La sélection sexuelle est purement aléatoire","Elle n''existe que chez les insectes"]'::jsonb, 'La sélection sexuelle favorise les traits améliorant le succès reproducteur (séduction des partenaires ou compétition entre mâles) même s''ils réduisent la survie', 'La queue du paon (handicap de survie mais avantage reproducteur) illustre la sélection sexuelle inter-sexuelle.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Écologie et dynamique des écosystèmes' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''un écosystème et quels en sont les composants principaux ?', '["Uniquement les organismes vivants","L''ensemble formé par une communauté d''organismes vivants (biocénose) et leur milieu physique (biotope), interconnectés par des flux d''énergie et de matière","Un groupe d''espèces de même genre","Un habitat forestier uniquement"]'::jsonb, 'L''ensemble formé par une communauté d''organismes vivants (biocénose) et leur milieu physique (biotope), interconnectés par des flux d''énergie et de matière', 'Un écosystème intègre les facteurs abiotiques (T°, lumière, sol) et biotiques (prédation, compétition, symbiose).', 'Facile'),
    (chap_id, 'Qu''est-ce que la chaîne alimentaire et le réseau trophique ?', '["Des séquences de décomposeurs","La chaîne alimentaire montre les relations proie-prédateur en séquence linéaire ; le réseau trophique représente toutes les interactions alimentaires complexes d''un écosystème","Des relations symbiotiques uniquement","Des cycles biogéochimiques"]'::jsonb, 'La chaîne alimentaire montre les relations proie-prédateur en séquence linéaire ; le réseau trophique représente toutes les interactions alimentaires complexes d''un écosystème', 'Le réseau trophique réel est beaucoup plus complexe qu''une chaîne simple ; les espèces ont souvent plusieurs proies et prédateurs.', 'Facile'),
    (chap_id, 'Qu''est-ce que le flux d''énergie dans un écosystème et la règle des 10% ?', '["L''énergie est recyclée indéfiniment","L''énergie circule à sens unique (non cyclique) ; environ 10% de l''énergie d''un niveau trophique est transférée au niveau suivant","Toute l''énergie est transférée","L''énergie augmente à chaque niveau trophique"]'::jsonb, 'L''énergie circule à sens unique (non cyclique) ; environ 10% de l''énergie d''un niveau trophique est transférée au niveau suivant', 'La règle des 10% (Lindeman) explique pourquoi les pyramides de biomasse s''amenuisent vers les prédateurs supérieurs.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le cycle du carbone et son importance pour le climat ?', '["Un cycle mineur","Le mouvement du carbone entre atmosphère (CO2), organismes (photosynthèse/respiration), océans et sédiments (fossiles) ; sa perturbation par les combustibles fossiles cause le changement climatique","Un cycle uniquement terrestre","Un processus sans lien avec le vivant"]'::jsonb, 'Le mouvement du carbone entre atmosphère (CO2), organismes (photosynthèse/respiration), océans et sédiments (fossiles) ; sa perturbation par les combustibles fossiles cause le changement climatique', 'L''excès de CO2 atmosphérique (combustion fossile) amplifie l''effet de serre et perturbe le cycle du carbone naturel.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la succession écologique et quels en sont les types ?', '["Un phénomène de migration","Le remplacement progressif de communautés dans un habitat au fil du temps : primaire (substrat nu) ou secondaire (après perturbation d''un écosystème existant)","Une extinction d''espèces","Un cycle saisonnier"]'::jsonb, 'Le remplacement progressif de communautés dans un habitat au fil du temps : primaire (substrat nu) ou secondaire (après perturbation d''un écosystème existant)', 'La succession aboutit à une communauté climacique (stable) ; ex. lagon comblé → marais → forêt.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la biodiversité et comment la mesure-t-on ?', '["Le nombre total d''espèces","La variété du vivant à l''échelle des gènes (diversité génétique), des espèces (richesse spécifique) et des écosystèmes ; mesurée par des indices comme Shannon ou Simpson","La biomasse totale","Le nombre d''individus"]'::jsonb, 'La variété du vivant à l''échelle des gènes (diversité génétique), des espèces (richesse spécifique) et des écosystèmes ; mesurée par des indices comme Shannon ou Simpson', 'La biodiversité (alpha, beta, gamma) est le résultat de milliards d''années d''évolution ; elle fournit des services écosystémiques.', 'Moyen'),
    (chap_id, 'Quelles sont les principales causes actuelles de l''érosion de la biodiversité ?', '["Uniquement la pollution","La destruction et fragmentation des habitats, la surexploitation, les espèces invasives, la pollution et le changement climatique (acronyme HIPPO)","Uniquement le changement climatique","L''introduction d''espèces sauvages"]'::jsonb, 'La destruction et fragmentation des habitats, la surexploitation, les espèces invasives, la pollution et le changement climatique (acronyme HIPPO)', 'Le taux d''extinction actuel est estimé 1000× supérieur au taux de fond naturel ; nous vivons la 6ème extinction de masse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la niche écologique d''une espèce ?', '["Son habitat géographique","L''ensemble des rôles fonctionnels et des ressources utilisées par une espèce dans son écosystème (ce qu''elle mange, comment elle est mangée, ses interactions biogéochimiques)","Son nom scientifique","Sa taille de population"]'::jsonb, 'L''ensemble des rôles fonctionnels et des ressources utilisées par une espèce dans son écosystème (ce qu''elle mange, comment elle est mangée, ses interactions biogéochimiques)', 'Hutchinson définit la niche en n dimensions ; deux espèces occupant la même niche entrent en compétition exclusive.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe d''exclusion compétitive de Gause ?', '["Les espèces coexistent toujours","Deux espèces occupant exactement la même niche écologique ne peuvent coexister indéfiniment ; l''une exclut l''autre","Les espèces se partagent toujours les ressources","La compétition est rare en nature"]'::jsonb, 'Deux espèces occupant exactement la même niche écologique ne peuvent coexister indéfiniment ; l''une exclut l''autre', 'Le principe de Gause (1934) explique la diversification des niches et la divergence des caractères entre espèces sympatriques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le changement climatique et ses effets sur les écosystèmes haïtiens ?', '["Un phénomène naturel sans importance","Le réchauffement global causé principalement par les émissions de GES humaines, aggravant la déforestation haïtienne, les cyclones, les sécheresses et la perte de biodiversité marine","Un phénomène limité aux pôles","Un problème exclusivement industriel"]'::jsonb, 'Le réchauffement global causé principalement par les émissions de GES humaines, aggravant la déforestation haïtienne, les cyclones, les sécheresses et la perte de biodiversité marine', 'Haïti est parmi les pays les plus vulnérables au CC : déforestation (couverture forestière ~2%), érosion des sols, blanchissement corallien.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la biorestauration et comment peut-elle aider des écosystèmes dégradés ?', '["La destruction des écosystèmes","L''utilisation d''organismes vivants (plantes, bactéries, champignons) pour dégrader des polluants ou restaurer des écosystèmes endommagés","Un processus uniquement chimique","Une technique agricole uniquement"]'::jsonb, 'L''utilisation d''organismes vivants (plantes, bactéries, champignons) pour dégrader des polluants ou restaurer des écosystèmes endommagés', 'La biorestauration (phytoremédiation, biorémédiation bactérienne) est une alternative économique aux méthodes physico-chimiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la biologie de la conservation et ses outils principaux ?', '["La gestion des fermes","La discipline scientifique visant à préserver la biodiversité en combinant écologie, génétique des populations, sociologie et politique pour informer les décisions de conservation","La biologie moléculaire uniquement","L''agriculture intensive"]'::jsonb, 'La discipline scientifique visant à préserver la biodiversité en combinant écologie, génétique des populations, sociologie et politique pour informer les décisions de conservation', 'La biologie de la conservation utilise : corridors écologiques, programmes d''élevage ex situ, banques de gènes, aires protégées.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 11 AND titre = 'Biotechnologies et applications de la biologie' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la PCR (réaction en chaîne par polymérase) et à quoi sert-elle ?', '["Une technique de séquençage","Une technique d''amplification in vitro d''une séquence d''ADN spécifique permettant d''en obtenir des millions de copies en quelques heures","Une technique de chromatographie","Une méthode d''électrophorèse"]'::jsonb, 'Une technique d''amplification in vitro d''une séquence d''ADN spécifique permettant d''en obtenir des millions de copies en quelques heures', 'La PCR (Mullis, 1983, Nobel 1993) utilise Taq polymérase, amorces et cycles thermiques (dénaturation, hybridation, élongation).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la technologie CRISPR-Cas9 et ses applications ?', '["Un type de PCR","Un système d''édition génomique précis permettant de couper l''ADN à un endroit spécifique et d''y ajouter, supprimer ou modifier des séquences","Une technique de séquençage","Un outil de clonage classique"]'::jsonb, 'Un système d''édition génomique précis permettant de couper l''ADN à un endroit spécifique et d''y ajouter, supprimer ou modifier des séquences', 'CRISPR-Cas9 (Doudna & Charpentier, Nobel 2020) révolutionne la médecine, l''agriculture et la recherche fondamentale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le clonage moléculaire et ses étapes principales ?', '["La reproduction asexuée d''un animal","L''insertion d''un fragment d''ADN dans un vecteur (plasmide), transformation d''une bactérie hôte, et production de nombreuses copies du gène d''intérêt","Une technique de PCR","Le séquençage de génome"]'::jsonb, 'L''insertion d''un fragment d''ADN dans un vecteur (plasmide), transformation d''une bactérie hôte, et production de nombreuses copies du gène d''intérêt', 'Le clonage moléculaire (gènes recombinants) a permis de produire l''insuline humaine par des bactéries dès 1982.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les organismes génétiquement modifiés (OGM) et leurs controverses ?', '["Des mutants naturels","Des organismes dont le génome a été modifié par biotechnologie pour exprimer de nouveaux caractères, au cœur de débats sur la biosécurité, l''éthique et la brevetabilité du vivant","Des organismes clonés","Des hybrides naturels"]'::jsonb, 'Des organismes dont le génome a été modifié par biotechnologie pour exprimer de nouveaux caractères, au cœur de débats sur la biosécurité, l''éthique et la brevetabilité du vivant', 'OGM : maïs Bt (résistant aux insectes), riz doré (vitamine A) ; controverses : effets sur biodiversité, monopoles semenciers.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la thérapie génique et quels sont ses principes ?', '["La chirurgie traditionnelle","L''introduction d''une version fonctionnelle d''un gène défectueux dans les cellules d''un patient pour traiter une maladie génétique","La chimiothérapie","La greffe d''organes"]'::jsonb, 'L''introduction d''une version fonctionnelle d''un gène défectueux dans les cellules d''un patient pour traiter une maladie génétique', 'La thérapie génique (ex. Luxturna pour la rétinite pigmentaire, Zolgensma pour SMA) utilise des vecteurs viraux (AAV).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la médecine personnalisée et comment la génomique y contribue-t-elle ?', '["La médecine traditionnelle","L''adaptation des traitements médicaux aux caractéristiques génétiques individuelles du patient, permettant des thérapies plus efficaces avec moins d''effets secondaires","La médecine homéopathique","La médecine préventive classique"]'::jsonb, 'L''adaptation des traitements médicaux aux caractéristiques génétiques individuelles du patient, permettant des thérapies plus efficaces avec moins d''effets secondaires', 'La pharmacogénomique identifie les variants génétiques influençant la réponse aux médicaments (métabolisme, cibles).', 'Moyen'),
    (chap_id, 'Qu''est-ce que les cellules souches et leurs types principaux ?', '["Des cellules différenciées","Des cellules indifférenciées capables de s''auto-renouveler et de se différencier : totipotentes (embryon précoce), pluripotentes (blastocyste), multipotentes (adultes)","Des cellules cancéreuses","Des cellules reproductrices"]'::jsonb, 'Des cellules indifférenciées capables de s''auto-renouveler et de se différencier : totipotentes (embryon précoce), pluripotentes (blastocyste), multipotentes (adultes)', 'Les cellules souches iPSC (Yamanaka, Nobel 2012) sont créées en reprogrammant des cellules adultes différenciées.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la bioinformatique et quel est son rôle en biologie moderne ?', '["La biologie des insectes","L''utilisation de l''informatique et des mathématiques pour analyser et interpréter les données biologiques (génomes, protéomes), essentielle à l''ère du séquençage haut débit","La biotechnologie agricole","La biologie marine informatisée"]'::jsonb, 'L''utilisation de l''informatique et des mathématiques pour analyser et interpréter les données biologiques (génomes, protéomes), essentielle à l''ère du séquençage haut débit', 'La bioinformatique (BLAST, phylogénomique, prédiction de structure AlphaFold) est indispensable à la biologie moderne.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le Projet Génome Humain et ses résultats principaux ?', '["Un projet d''agriculture","Le projet international (1990-2003) qui a séquencé les ~3 milliards de paires de bases du génome humain, révélant ~20 000 gènes et ouvrant l''ère de la génomique","Un projet uniquement américain","Un projet de clonage humain"]'::jsonb, 'Le projet international (1990-2003) qui a séquencé les ~3 milliards de paires de bases du génome humain, révélant ~20 000 gènes et ouvrant l''ère de la génomique', 'Le PGH a révélé que ~1,5% du génome code pour des protéines et que >95% était considéré «ADN non codant» (maintenant partiellement fonctionnel).', 'Moyen'),
    (chap_id, 'Quelles sont les applications de la biologie en agroalimentaire et en médecine en Haïti ?', '["Aucune application locale","Les biotechnologies peuvent améliorer les cultures haïtiennes résistantes à la sécheresse, produire des vaccins locaux, développer des biomédicaments et renforcer la sécurité alimentaire","Uniquement des applications ornementales","Les biotechnologies sont inaccessibles aux pays en développement"]'::jsonb, 'Les biotechnologies peuvent améliorer les cultures haïtiennes résistantes à la sécheresse, produire des vaccins locaux, développer des biomédicaments et renforcer la sécurité alimentaire', 'Haïti peut bénéficier des biotechnologies : sélection variétale, biofortification, diagnostics moléculaires adaptés au climat tropical.', 'Moyen');
  END IF;
END $$;
