-- Supplement Mathématiques NS3-NS4 (matiere_id=27)
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 27 AND titre = 'Analyse avancée : limites, séries et équations différentielles' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Que vaut lim(x→+∞) (3x² + 2x) / x² ?', '["0","2","3","∞"]'::jsonb, '3', 'En divisant par x² : (3 + 2/x) → 3 quand x → +∞.', 'Moyen'),
    (chap_id, 'Quelle est la forme indéterminée de lim(x→0) x/x ?', '["0/0","∞/∞","0×∞","∞-∞"]'::jsonb, '0/0', '0/0 est une forme indéterminée qui nécessite une analyse plus approfondie (factorisation ou L''Hôpital).', 'Moyen'),
    (chap_id, 'Quel test détermine la convergence d''une série en comparant avec une série géométrique ?', '["Test de la divergence","Test de d''Alembert (ratio)","Test de Cauchy","Test de comparaison"]'::jsonb, 'Test de d''Alembert (ratio)', 'Le test de d''Alembert compare lim|aₙ₊₁/aₙ| à 1 pour déterminer la convergence.', 'Difficile'),
    (chap_id, 'Quelle est la somme de la série géométrique convergente Σ(r^n) pour |r| < 1 ?', '["1/(1+r)","1/(1-r)","r/(1-r)","1/r"]'::jsonb, '1/(1-r)', 'La série Σrⁿ (n=0 à ∞) converge vers 1/(1-r) si |r| < 1.', 'Difficile'),
    (chap_id, 'Quelle est la solution générale de l''équation différentielle y'' = ky (k constante) ?', '["y = kx + C","y = Ce^(kx)","y = Cx + ke^x","y = C sin(kx)"]'::jsonb, 'y = Ce^(kx)', 'y'' = ky a pour solution générale y = Ce^(kx), car (Ce^(kx))'' = kCe^(kx) = ky.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un développement de Taylor d''une fonction f en a ?', '["La valeur de f en a","L''approximation de f par une série de polynômes dérivés en a","La dérivée de f en a","La primitive de f"]'::jsonb, 'L''approximation de f par une série de polynômes dérivés en a', 'Le développement de Taylor exprime f(x) = Σ f⁽ⁿ⁾(a)/n! × (x-a)ⁿ au voisinage de a.', 'Difficile'),
    (chap_id, 'Que représente la continuité d''une fonction en un point a ?', '["f''(a) existe","lim(x→a) f(x) = f(a)","f(a) = 0","f est dérivable en a"]'::jsonb, 'lim(x→a) f(x) = f(a)', 'f est continue en a si la limite en a existe et coïncide avec la valeur de f en a.', 'Moyen'),
    (chap_id, 'Quel est le développement limité de eˣ au premier ordre en 0 ?', '["1 + x","1 - x","x","e + x"]'::jsonb, '1 + x', 'eˣ ≈ 1 + x au voisinage de 0 (terme constant + terme linéaire du développement de Taylor).', 'Moyen'),
    (chap_id, 'Une série est absolument convergente si ?', '["Σaₙ converge","Σ|aₙ| converge","aₙ → 0","La série alterne"]'::jsonb, 'Σ|aₙ| converge', 'La convergence absolue (Σ|aₙ| converge) implique la convergence simple.', 'Difficile'),
    (chap_id, 'Que signifie la dérivabilité d''une fonction en un point a ?', '["f est continue en a","La limite du taux de variation en a existe et est finie","f(a) = 0","f est monotone au voisinage de a"]'::jsonb, 'La limite du taux de variation en a existe et est finie', 'f est dérivable en a si lim(h→0) [f(a+h)-f(a)]/h existe ; cette limite est f''(a).', 'Moyen'),
    (chap_id, 'Quelle condition est nécessaire (mais pas suffisante) pour la convergence d''une série Σaₙ ?', '["aₙ → 0","aₙ > 0","Σaₙ diverge","aₙ est décroissante"]'::jsonb, 'aₙ → 0', 'Si aₙ ne tend pas vers 0, la série diverge ; mais aₙ → 0 ne garantit pas la convergence.', 'Difficile'),
    (chap_id, 'Quelle est la formule de la règle de L''Hôpital pour les formes indéterminées 0/0 ?', '["lim f/g = lim f''/g","lim f/g = lim f''/g''","lim f/g = lim f × g''","lim f/g = (lim f)/(lim g)"]'::jsonb, 'lim f/g = lim f''/g''', 'La règle de L''Hôpital : si f/g → 0/0 ou ∞/∞, alors lim f/g = lim f''/g'' sous conditions.', 'Difficile'),
    (chap_id, 'Quel type d''équation différentielle est dy/dx + P(x)y = Q(x) ?', '["Équation du 2ème ordre","Équation linéaire du 1er ordre","Équation homogène","Équation de Bernoulli"]'::jsonb, 'Équation linéaire du 1er ordre', 'dy/dx + P(x)y = Q(x) est une équation différentielle linéaire du premier ordre à coefficients variables.', 'Difficile'),
    (chap_id, 'Quelle est la règle pour dériver ln(f(x)) ?', '["1/f(x)","f''(x)/f(x)","f(x)/f''(x)","ln(f''(x))"]'::jsonb, 'f''(x)/f(x)', '(ln f(x))'' = f''(x)/f(x) par la règle de la chaîne appliquée à la dérivée de ln.', 'Moyen'),
    (chap_id, 'Que vaut ∫₋₁¹ x dx ?', '["2","1","0","-1"]'::jsonb, '0', '[x²/2]₋₁¹ = 1/2 - 1/2 = 0. Résultat cohérent car f(x)=x est impaire et l''intervalle est symétrique.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 27 AND titre = 'Algèbre linéaire et matrices' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une matrice carrée ?', '["Une matrice avec une seule colonne","Une matrice ayant autant de lignes que de colonnes","Une matrice de dimension 2×3","Une matrice diagonale"]'::jsonb, 'Une matrice ayant autant de lignes que de colonnes', 'Une matrice n×n est dite carrée d''ordre n.', 'Facile'),
    (chap_id, 'Quel est le déterminant de la matrice 2×2 [[a,b],[c,d]] ?', '["ac + bd","ad - bc","ab - cd","a + d"]'::jsonb, 'ad - bc', 'det([[a,b],[c,d]]) = ad - bc. C''est la formule du déterminant 2×2.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un espace vectoriel ?', '["Un ensemble de vecteurs géométriques","Un ensemble muni de l''addition et de la multiplication scalaire satisfaisant 8 axiomes","Un graphe","Une matrice diagonale"]'::jsonb, 'Un ensemble muni de l''addition et de la multiplication scalaire satisfaisant 8 axiomes', 'Un espace vectoriel est une structure algébrique fondamentale en algèbre linéaire.', 'Difficile'),
    (chap_id, 'Quelle propriété un ensemble de vecteurs doit-il satisfaire pour être une base ?', '["Être orthogonal","Être libre (linéairement indépendant) et générateur","Avoir un déterminant non nul","Être de norme 1"]'::jsonb, 'Être libre (linéairement indépendant) et générateur', 'Une base est un système générateur minimalement libre (ou libre maximalement générateur).', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une valeur propre d''une matrice A ?', '["Le déterminant de A","Un scalaire λ tel que Av = λv pour un vecteur non nul v","La trace de A","Un coefficient de A"]'::jsonb, 'Un scalaire λ tel que Av = λv pour un vecteur non nul v', 'Les valeurs propres sont les solutions de det(A - λI) = 0, l''équation caractéristique.', 'Difficile'),
    (chap_id, 'Comment multiplier deux matrices A(m×n) et B(n×p) ?', '["Élément par élément","Chaque élément (AB)ᵢⱼ = somme des produits de la ligne i de A par la colonne j de B","Addition terme à terme","Transposer B puis multiplier"]'::jsonb, 'Chaque élément (AB)ᵢⱼ = somme des produits de la ligne i de A par la colonne j de B', 'La multiplication matricielle est une combinaison de produits scalaires entre lignes et colonnes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la transposée d''une matrice A ?', '["La matrice inverse","La matrice obtenue en échangeant lignes et colonnes de A","Le déterminant","La trace"]'::jsonb, 'La matrice obtenue en échangeant lignes et colonnes de A', 'La transposée Aᵀ a (Aᵀ)ᵢⱼ = Aⱼᵢ : les lignes deviennent des colonnes.', 'Facile'),
    (chap_id, 'Quel est le rang d''une matrice ?', '["Le nombre de lignes","Le nombre de colonnes de la matrice réduite","La dimension de l''espace image de l''application linéaire associée","Le déterminant"]'::jsonb, 'La dimension de l''espace image de l''application linéaire associée', 'Le rang est le nombre de colonnes (ou lignes) linéairement indépendantes.', 'Difficile'),
    (chap_id, 'Quelle est la condition pour qu''une matrice carrée soit inversible ?', '["Sa trace est non nulle","Son déterminant est non nul","Elle est symétrique","Elle est diagonale"]'::jsonb, 'Son déterminant est non nul', 'A est inversible ⟺ det(A) ≠ 0 ⟺ les colonnes (ou lignes) sont linéairement indépendantes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la diagonalisation d''une matrice ?', '["La rendre triangulaire","L''écrire sous la forme PDP⁻¹ où D est diagonale","Calculer son déterminant","Trouver sa transposée"]'::jsonb, 'L''écrire sous la forme PDP⁻¹ où D est diagonale', 'Une matrice diagonalisable peut s''écrire A = PDP⁻¹ où les colonnes de P sont les vecteurs propres.', 'Difficile'),
    (chap_id, 'Quelle est la trace d''une matrice A ?', '["Le produit de ses éléments diagonaux","La somme de ses éléments diagonaux","Le déterminant","La somme de tous ses éléments"]'::jsonb, 'La somme de ses éléments diagonaux', 'tr(A) = Σaᵢᵢ. La trace est aussi égale à la somme des valeurs propres.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une application linéaire ?', '["Une fonction affine","Une application f: E→F telle que f(αu + βv) = αf(u) + βf(v)","Une matrice carrée","Un isomorphisme"]'::jsonb, 'Une application f: E→F telle que f(αu + βv) = αf(u) + βf(v)', 'L''application linéaire préserve les opérations vectorielles (additivité et homogénéité).', 'Difficile'),
    (chap_id, 'Quel outil résout un système linéaire Ax = b par réductions ?', '["La méthode de Newton","L''élimination de Gauss-Jordan","La méthode des éléments finis","La décomposition QR"]'::jsonb, 'L''élimination de Gauss-Jordan', 'L''élimination de Gauss-Jordan transforme la matrice augmentée [A|b] en forme échelonnée réduite.', 'Moyen'),
    (chap_id, 'Pour deux vecteurs u et v, qu''est-ce que leur produit vectoriel u × v donne ?', '["Un scalaire","Un vecteur perpendiculaire au plan formé par u et v","La somme des composantes","La projection de u sur v"]'::jsonb, 'Un vecteur perpendiculaire au plan formé par u et v', 'Le produit vectoriel est défini en ℝ³ et donne un vecteur orthogonal aux deux vecteurs.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''orthonormalisation de Gram-Schmidt ?', '["Une factorisation de matrices","Un procédé pour construire une base orthonormale à partir d''une base quelconque","Un algorithme de tri","Une méthode de résolution d''équations différentielles"]'::jsonb, 'Un procédé pour construire une base orthonormale à partir d''une base quelconque', 'Gram-Schmidt transforme iterativement une base en une base orthonormale par projections et normalisations.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 27 AND titre = 'Probabilités et statistiques avancées' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la formule de la probabilité conditionnelle P(A|B) ?', '["P(A) + P(B)","P(A ∩ B) / P(B)","P(A) × P(B)","P(A ∪ B) - P(B)"]'::jsonb, 'P(A ∩ B) / P(B)', 'P(A|B) = P(A ∩ B) / P(B), avec P(B) > 0. C''est la définition de la probabilité conditionnelle.', 'Moyen'),
    (chap_id, 'Quel théorème permet de "inverser" les probabilités conditionnelles ?', '["Théorème de Pythagore","Théorème de Bayes","Théorème central limite","Loi des grands nombres"]'::jsonb, 'Théorème de Bayes', 'Bayes : P(B|A) = P(A|B)P(B)/P(A), fondement des statistiques bayésiennes.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une variable aléatoire normale (gaussienne) ?', '["Une variable ne prenant que des valeurs entières","Une variable avec une distribution en cloche symétrique","Une variable uniforme","Une variable de Poisson"]'::jsonb, 'Une variable avec une distribution en cloche symétrique', 'La loi normale N(μ,σ²) est caractérisée par sa moyenne μ et son écart-type σ, en forme de cloche.', 'Moyen'),
    (chap_id, 'Que dit le théorème central limite ?', '["La somme de variables aléatoires indépendantes tend vers une loi normale","Les probabilités convergent vers 1","La moyenne empirique est toujours normale","Les variables indépendantes sont non corrélées"]'::jsonb, 'La somme de variables aléatoires indépendantes tend vers une loi normale', 'Pour n grand, la moyenne de n v.a.i.i.d. suit approximativement une loi normale, quel que soit la distribution initiale.', 'Difficile'),
    (chap_id, 'Quelle mesure statistique est robuste aux valeurs extrêmes (outliers) ?', '["La moyenne","La médiane","L''écart-type","La variance"]'::jsonb, 'La médiane', 'La médiane n''est pas influencée par les valeurs extrêmes, contrairement à la moyenne.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un intervalle de confiance à 95% ?', '["Un intervalle contenant 95% des données","Un intervalle qui capture le paramètre vrai dans 95% des échantillons","Un intervalle de probabilité 0.95","Une borne d''erreur"]'::jsonb, 'Un intervalle qui capture le paramètre vrai dans 95% des échantillons', 'Un IC à 95% signifie que 95% des intervalles construits de cette façon contiennent le vrai paramètre.', 'Difficile'),
    (chap_id, 'Quelle est la variance d''une variable aléatoire X ?', '["E[X]","E[X²] - (E[X])²","E[X] × P(X)","(E[X])²"]'::jsonb, 'E[X²] - (E[X])²', 'Var(X) = E[X²] - μ² par la formule de Koenig-Huygens, où μ = E[X].', 'Difficile'),
    (chap_id, 'Qu''est-ce que la corrélation entre deux variables X et Y ?', '["Leur somme","Une mesure normalisée de leur dépendance linéaire, entre -1 et 1","Leur différence de variance","La covariance brute"]'::jsonb, 'Une mesure normalisée de leur dépendance linéaire, entre -1 et 1', 'ρ(X,Y) = Cov(X,Y)/(σₓσ_y) est le coefficient de corrélation de Pearson.', 'Difficile'),
    (chap_id, 'Quel test statistique compare les moyennes de deux groupes indépendants ?', '["Test du chi-carré","Test t de Student","Test de Fisher","Test de Kolmogorov-Smirnov"]'::jsonb, 'Test t de Student', 'Le test t de Student compare les moyennes de deux groupes en tenant compte de leur variance.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une loi de Poisson ?', '["Une distribution continue symétrique","La distribution du nombre d''événements dans un intervalle de temps fixé","Une loi normale centrée","Une loi uniforme sur [0,1]"]'::jsonb, 'La distribution du nombre d''événements dans un intervalle de temps fixé', 'La loi de Poisson P(λ) modélise des événements rares et indépendants (λ = taux d''occurrence).', 'Moyen'),
    (chap_id, 'Quelle est la relation entre variance et écart-type ?', '["σ = Var(X)","σ = √Var(X)","Var(X) = σ","σ = Var(X)²"]'::jsonb, 'σ = √Var(X)', 'L''écart-type σ est la racine carrée de la variance, et a la même unité que X.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une p-valeur en test d''hypothèse ?', '["La probabilité que H₀ soit vraie","La probabilité d''observer un résultat aussi extrême si H₀ est vraie","La puissance du test","L''erreur de type I"]'::jsonb, 'La probabilité d''observer un résultat aussi extrême si H₀ est vraie', 'Une p-valeur < 0.05 conduit souvent à rejeter H₀, mais ne prouve pas que H₁ est vraie.', 'Difficile'),
    (chap_id, 'Quelle loi modélise le nombre de succès dans n essais indépendants avec probabilité p ?', '["Poisson","Normale","Binomiale","Géométrique"]'::jsonb, 'Binomiale', 'X ~ B(n,p) : X suit une loi binomiale avec P(X=k) = C(n,k) × pᵏ × (1-p)ⁿ⁻ᵏ.', 'Moyen');
  END IF;
END $$;
