-- Supplement Histoire-Géographie (matiere_id=13) — NS3 et NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 13 AND titre = 'Les deux guerres mondiales et la recomposition du monde' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelles sont les principales causes de la Première Guerre mondiale (1914-1918) ?', '["Uniquement l''assassinat de Franz Ferdinand","Un faisceau de causes : impérialisme, nationalisme, militarisme, systèmes d''alliances rigides (Triple Entente vs Triple Alliance), déclenchées par l''assassinat de Franz Ferdinand à Sarajevo","Un conflit commercial uniquement","Une révolution socialiste"]'::jsonb, 'Un faisceau de causes : impérialisme, nationalisme, militarisme, systèmes d''alliances rigides (Triple Entente vs Triple Alliance), déclenchées par l''assassinat de Franz Ferdinand à Sarajevo', 'Le modèle MAIN (Militarisme, Alliances, Impérialisme, Nationalisme) explique l''embrasement rapide de l''Europe en 1914.', 'Moyen'),
    (chap_id, 'Quelles sont les conséquences du Traité de Versailles (1919) sur l''Allemagne et le monde ?', '["Des conditions modérées","Des conditions humiliantes (clause de culpabilité, reparations de 132 milliards de marks-or, pertes territoriales) qui ont contribué à l''instabilité de la République de Weimar et à la montée du nazisme","Un traité équitable","Un traité bénéfique pour l''Allemagne"]'::jsonb, 'Des conditions humiliantes (clause de culpabilité, reparations de 132 milliards de marks-or, pertes territoriales) qui ont contribué à l''instabilité de la République de Weimar et à la montée du nazisme', 'Keynes (1919) critiqua le Traité comme économiquement insoutenable ; Hitler en fera l''un de ses chevaux de bataille.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Shoah (Holocauste) et combien de victimes a-t-elle causées ?', '["Un événement mineur","Le génocide systématique des Juifs d''Europe par les nazis, faisant environ 6 millions de victimes (60% des Juifs européens), dans des camps d''extermination","Une guerre civile","Un bombardement isolé"]'::jsonb, 'Le génocide systématique des Juifs d''Europe par les nazis, faisant environ 6 millions de victimes (60% des Juifs européens), dans des camps d''extermination', 'La «Solution finale» (Wannsee, 1942) organisée par les SS a industrialisé le meurtre de masse à Auschwitz, Treblinka, etc.', 'Moyen'),
    (chap_id, 'Quelles sont les principales causes de la Deuxième Guerre mondiale ?', '["La Première Guerre mondiale seule","Le traité humiliant de Versailles, la Grande Dépression (1929), la montée des fascismes (Hitler, Mussolini), la politique d''apaisement d''Appeasement et l''invasion de la Pologne (1939)","Un conflit territorial uniquement","Une révolution communiste mondiale"]'::jsonb, 'Le traité humiliant de Versailles, la Grande Dépression (1929), la montée des fascismes (Hitler, Mussolini), la politique d''apaisement d''Appeasement et l''invasion de la Pologne (1939)', 'La chaîne causale WWI → Versailles → crise économique → nazisme → WWII illustre l''enchaînement des catastrophes du XXe siècle.', 'Moyen'),
    (chap_id, 'Quel est le rôle de la bombe atomique dans la fin de la Seconde Guerre mondiale ?', '["Elle n''a pas eu d''impact","Les bombes d''Hiroshima (6 août 1945) et Nagasaki (9 août 1945) ont provoqué la capitulation du Japon, introduisant l''ère nucléaire et soulevant des questions éthiques permanentes sur l''usage des armes de destruction massive","Elles ont été utilisées en Europe","Elles n''ont pas causé de victimes"]'::jsonb, 'Les bombes d''Hiroshima (6 août 1945) et Nagasaki (9 août 1945) ont provoqué la capitulation du Japon, introduisant l''ère nucléaire et soulevant des questions éthiques permanentes sur l''usage des armes de destruction massive', 'Hiroshima (~140 000 morts) et Nagasaki (~70 000 morts) : les deux seules utilisations en guerre de l''arme nucléaire à ce jour.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''ONU et pourquoi a-t-elle été créée en 1945 ?', '["Une organisation économique","Une organisation internationale créée après la WWII pour maintenir la paix, prévenir un nouveau génocide et favoriser la coopération internationale, succédant à la Société des Nations","Une alliance militaire","Un tribunal international uniquement"]'::jsonb, 'Une organisation internationale créée après la WWII pour maintenir la paix, prévenir un nouveau génocide et favoriser la coopération internationale, succédant à la Société des Nations', 'L''ONU (1945, 51 membres fondateurs dont Haïti) repose sur la Charte de San Francisco ; aujourd''hui 193 États membres.', 'Facile'),
    (chap_id, 'Qu''est-ce que la décolonisation et comment s''est-elle déroulée après 1945 ?', '["Un phénomène mineur","Le processus d''accession à l''indépendance des colonies asiatiques et africaines (1945-1975), parfois négocié (Inde 1947), parfois violent (Algérie, Angola), soulevant des questions d''identité et de développement","Un cadeau des puissances coloniales","Un processus uniquement africain"]'::jsonb, 'Le processus d''accession à l''indépendance des colonies asiatiques et africaines (1945-1975), parfois négocié (Inde 1947), parfois violent (Algérie, Angola), soulevant des questions d''identité et de développement', 'La décolonisation a été accélérée par la Charte de l''ONU (droit des peuples), les mouvements nationalistes et l''affaiblissement des métropoles.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Guerre froide et quels en ont été les principaux moments de crise ?', '["Un conflit armé direct","L''affrontement idéologique et géopolitique entre les États-Unis (bloc occidental libéral) et l''URSS (bloc communiste) de 1947 à 1991, avec des crises majeures : Berlin (1961), Cuba (1962), Vietnam (1965-75)","Un conflit exclusivement économique","Une alliance militaire"]'::jsonb, 'L''affrontement idéologique et géopolitique entre les États-Unis (bloc occidental libéral) et l''URSS (bloc communiste) de 1947 à 1991, avec des crises majeures : Berlin (1961), Cuba (1962), Vietnam (1965-75)', 'La Guerre froide a divisé le monde en blocs ; les pays du Tiers-Monde comme Haïti en ont subi les conséquences indirectes.', 'Moyen'),
    (chap_id, 'Quelle a été la relation entre Haïti et les États-Unis au XXe siècle, notamment l''occupation américaine ?', '["Relations inexistantes","L''occupation américaine d''Haïti (1915-1934) a modernisé certaines infrastructures mais aussi humilié la souveraineté haïtienne, et les interventions constantes ont influencé la politique haïtienne tout au long du XXe siècle","Une alliance militaire exclusive","Une relation purement commerciale"]'::jsonb, 'L''occupation américaine d''Haïti (1915-1934) a modernisé certaines infrastructures mais aussi humilié la souveraineté haïtienne, et les interventions constantes ont influencé la politique haïtienne tout au long du XXe siècle', 'L''occupation américaine (1915-1934) a désarmé l''armée haïtienne, pris le contrôle des finances et laissé des séquelles identitaires profondes.', 'Moyen'),
    (chap_id, 'Quel a été le règne des Duvalier et son impact sur Haïti ?', '["Une période de démocratie","Une dictature familiale (François Duvalier «Papa Doc» 1957-1971, puis Jean-Claude «Baby Doc» 1971-1986) caractérisée par la terreur des Tontons Macoutes, la répression, la corruption et une émigration massive","Une brève parenthèse militaire","Une période de prospérité"]'::jsonb, 'Une dictature familiale (François Duvalier «Papa Doc» 1957-1971, puis Jean-Claude «Baby Doc» 1971-1986) caractérisée par la terreur des Tontons Macoutes, la répression, la corruption et une émigration massive', 'Le duvaliérisme a paralysé le développement haïtien pendant 29 ans et causé une diaspora de cerveaux vers les USA, Canada, France.', 'Moyen'),
    (chap_id, 'Quelle est la signification de la révolution cubaine de 1959 pour les Caraïbes et l''Amérique latine ?', '["Un événement mineur","Le renversement de Batista par Castro a instauré le premier régime communiste des Amériques, provoquant la crise de Cuba (1962), exacerbant les tensions de la Guerre froide dans les Caraïbes et inspirant des guérillas en Amérique latine","Une révolution pro-américaine","Une révolution pacifique sans impact"]'::jsonb, 'Le renversement de Batista par Castro a instauré le premier régime communiste des Amériques, provoquant la crise de Cuba (1962), exacerbant les tensions de la Guerre froide dans les Caraïbes et inspirant des guérillas en Amérique latine', 'La révolution cubaine a polarisé les Caraïbes et conduit les USA à soutenir des dictateurs comme Duvalier pour éviter une «deuxième Cuba».', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Conférence de Bandung (1955) et le mouvement des Non-Alignés ?', '["Un sommet des grandes puissances","La conférence de 29 pays afro-asiatiques déclarant leur refus de s''aligner sur les deux blocs (USA/URSS), cherchant une «troisième voie» ; mouvement fondé sur la souveraineté, l''anti-colonialisme et la solidarité Sud-Sud","Un traité militaire","Une organisation économique"]'::jsonb, 'La conférence de 29 pays afro-asiatiques déclarant leur refus de s''aligner sur les deux blocs (USA/URSS), cherchant une «troisième voie» ; mouvement fondé sur la souveraineté, l''anti-colonialisme et la solidarité Sud-Sud', 'Bandung (1955) a fondé le Tiers-Monde politique ; les 5 principes de coexistence pacifique y ont été proclamés.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 13 AND titre = 'Mondialisation et enjeux géopolitiques contemporains' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la mondialisation et quelles en sont les dimensions principales ?', '["L''uniformisation culturelle","L''intensification des échanges économiques (commerce, investissements, chaînes de valeur), des flux d''informations et des migrations humaines à l''échelle planétaire, avec des effets inégaux selon les régions","Un phénomène uniquement économique","La domination américaine"]'::jsonb, 'L''intensification des échanges économiques (commerce, investissements, chaînes de valeur), des flux d''informations et des migrations humaines à l''échelle planétaire, avec des effets inégaux selon les régions', 'La mondialisation contemporaine (post-1989) s''appuie sur : conteneurisation, télécommunications, libéralisation financière.', 'Moyen'),
    (chap_id, 'Quel est le rôle des organisations économiques internationales (FMI, Banque mondiale, OMC) ?', '["Des organisations humanitaires","Des institutions de gouvernance économique mondiale : le FMI gère les crises financières, la Banque mondiale finance le développement, l''OMC régule le commerce international","Des organisations militaires","Des organisations régionales uniquement"]'::jsonb, 'Des institutions de gouvernance économique mondiale : le FMI gère les crises financières, la Banque mondiale finance le développement, l''OMC régule le commerce international', 'Ces institutions de Bretton Woods (1944) ont imposé des programmes d''ajustement structurel à Haïti dans les années 1990-2000.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géopolitique des ressources naturelles et comment structure-t-elle les relations internationales ?', '["Les ressources n''ont pas d''impact","Le contrôle des ressources (pétrole, eau, terres rares) structure les alliances, les conflits et les inégalités mondiales ; les pays producteurs subissent souvent la «malédiction des ressources»","Les ressources sont équitablement distribuées","La géopolitique concerne uniquement les frontières"]'::jsonb, 'Le contrôle des ressources (pétrole, eau, terres rares) structure les alliances, les conflits et les inégalités mondiales ; les pays producteurs subissent souvent la «malédiction des ressources»', 'Le pétrole (Moyen-Orient), les terres rares (Chine) et l''eau douce (aquifères partagés) sont des enjeux géopolitiques majeurs du XXIe s.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''émergence des pays BRICS et leur impact sur l''ordre mondial ?', '["Des pays en développement mineurs","L''essor du Brésil, de la Russie, de l''Inde, de la Chine et de l''Afrique du Sud (BRICS) qui contestent l''hégémonie occidentale, proposent des alternatives aux institutions de Bretton Woods et redessinent les équilibres géopolitiques","Un groupe exclusivement asiatique","Un regroupement commercial de niche"]'::jsonb, 'L''essor du Brésil, de la Russie, de l''Inde, de la Chine et de l''Afrique du Sud (BRICS) qui contestent l''hégémonie occidentale, proposent des alternatives aux institutions de Bretton Woods et redessinent les équilibres géopolitiques', 'La Chine (2ème PIB mondial) et l''Inde (le plus peuplé) changent le centre de gravité économique vers le Sud et l''Est.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le changement climatique comme enjeu géopolitique majeur du XXIe siècle ?', '["Un problème purement scientifique","Un enjeu qui menace la sécurité des États (migrations climatiques, conflits pour l''eau), recompose les alliances et oppose pays industrialisés (émetteurs historiques) et pays vulnérables (dont Haïti) sur la question de la responsabilité et de l''aide","Un problème limité aux pôles","Un enjeu uniquement économique"]'::jsonb, 'Un enjeu qui menace la sécurité des États (migrations climatiques, conflits pour l''eau), recompose les alliances et oppose pays industrialisés (émetteurs historiques) et pays vulnérables (dont Haïti) sur la question de la responsabilité et de l''aide', 'Haïti (<0,1% des émissions mondiales) est parmi les 10 pays les plus vulnérables au CC selon les indices ND-GAIN et GCRI.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Communauté des Caraïbes (CARICOM) et quel est son rôle pour Haïti ?', '["Une organisation militaire","Une organisation régionale d''intégration économique et politique des Caraïbes, dont Haïti est membre ; elle promeut le commerce intrazone, la libre circulation et la coordination des politiques","Une zone de libre-échange mondiale","Un organisme des Nations Unies"]'::jsonb, 'Une organisation régionale d''intégration économique et politique des Caraïbes, dont Haïti est membre ; elle promeut le commerce intrazone, la libre circulation et la coordination des politiques', 'Haïti est membre du CARICOM depuis 2002 ; les Caraïbes représentent un marché régional et un espace politique collectif.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la question de la migration internationale et ses enjeux pour Haïti ?', '["Un phénomène marginal","La diaspora haïtienne (~2 millions de personnes aux USA, Canada, France, RD, Bahamas) représente un apport économique vital (transferts ~>3 milliards $/an) mais aussi un drain des cerveaux","La migration ne concerne pas Haïti","Un phénomène uniquement illégal"]'::jsonb, 'La diaspora haïtienne (~2 millions de personnes aux USA, Canada, France, RD, Bahamas) représente un apport économique vital (transferts ~>3 milliards $/an) mais aussi un drain des cerveaux', 'Les transferts de la diaspora représentent ~20-30% du PIB haïtien ; ils surpassent l''aide internationale et les investissements directs étrangers.', 'Moyen'),
    (chap_id, 'Comment comprendre les relations haïtiano-dominicaines dans un contexte géopolitique régional ?', '["Des relations toujours hostiles","Des relations complexes sur une île partagée : interdépendance économique (commerce, main-d''œuvre), tensions historiques (massacre de 1937, Trujillo) et enjeux actuels de migration et d''apatridie","Des relations d''égalité totale","Des relations sans histoire"]'::jsonb, 'Des relations complexes sur une île partagée : interdépendance économique (commerce, main-d''œuvre), tensions historiques (massacre de 1937, Trujillo) et enjeux actuels de migration et d''apatridie', 'Le massacre de Parsley (1937, ~15 000 Haïtiens tués) et la décision de la Cour constitutionnelle dominicaine (2013) d''apatridie restent des tensions majeures.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la communauté internationale et l''aide au développement : le cas d''Haïti ?', '["L''aide résout tous les problèmes","L''aide internationale à Haïti (~500M$/an avant 2010) a souvent renforcé la dépendance, contourné l''État haïtien et profité aux ONG étrangères plus qu''aux institutions locales, un phénomène critiqué comme «business humanitaire»","L''aide n''a aucun effet","Haïti ne reçoit pas d''aide internationale"]'::jsonb, 'L''aide internationale à Haïti (~500M$/an avant 2010) a souvent renforcé la dépendance, contourné l''État haïtien et profité aux ONG étrangères plus qu''aux institutions locales, un phénomène critiqué comme «business humanitaire»', 'Le livre «Dead Aid» de Dambisa Moyo et les critiques post-séisme 2010 ont révélé les limites structurelles de l''aide en Haïti.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la gouvernance mondiale et ses défis actuels ?', '["Un gouvernement mondial unifié","L''ensemble des institutions, règles et processus par lesquels la communauté internationale gère les problèmes collectifs (changement climatique, pandémies, cyberguerre) en l''absence d''un gouvernement mondial","La domination d''un seul État","Un idéal irréalisable"]'::jsonb, 'L''ensemble des institutions, règles et processus par lesquels la communauté internationale gère les problèmes collectifs (changement climatique, pandémies, cyberguerre) en l''absence d''un gouvernement mondial', 'La COVID-19 et les COP climatiques ont mis en lumière les limites de la gouvernance mondiale face à des crises transnationales.', 'Moyen'),
    (chap_id, 'Comment la géographie physique d''Haïti influence-t-elle sa vulnérabilité aux catastrophes naturelles ?', '["Elle n''influence pas la vulnérabilité","Sa position dans la zone sismique des Caraïbes, son relief montagneux accidenté, sa déforestation avancée et sa géographie côtière exposée aux cyclones se combinent pour en faire l''un des pays les plus vulnérables du monde","Sa géographie est protectrice","Sa vulnérabilité est uniquement sociale"]'::jsonb, 'Sa position dans la zone sismique des Caraïbes, son relief montagneux accidenté, sa déforestation avancée et sa géographie côtière exposée aux cyclones se combinent pour en faire l''un des pays les plus vulnérables du monde', 'L''IVD (Indice de Vulnérabilité aux Désastres) d''Haïti est parmi les plus élevés du monde ; les séismes, cyclones et inondations s''additionnent.', 'Moyen'),
    (chap_id, 'Quel est le mouvement mondial des droits de l''homme depuis 1948 et ses avancées et limites ?', '["Un mouvement récent sans impact","La DUDH (1948) a établi des standards universels ; des progrès réels ont été faits (abolition de l''apartheid, tribunaux pénaux internationaux) mais des violations persistent partout, soulignant la tension entre souveraineté des États et universalité des droits","Les droits de l''homme sont uniquement théoriques","Les droits sont uniquement civils et politiques"]'::jsonb, 'La DUDH (1948) a établi des standards universels ; des progrès réels ont été faits (abolition de l''apartheid, tribunaux pénaux internationaux) mais des violations persistent partout, soulignant la tension entre souveraineté des États et universalité des droits', 'La CPI (1998), les tribunaux ad hoc (Rwanda, ex-Yougoslavie) représentent des avancées ; l''universalité des droits reste contestée.', 'Difficile');
  END IF;
END $$;
