-- Supplement Géologie (matiere_id=12) — NS3 et NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 12 AND titre = 'Séismes et volcans : risques naturels' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la différence entre le foyer (hypocentre) et l''épicentre d''un séisme ?', '["Ils désignent le même point","Le foyer est le point de rupture dans la croûte où le séisme se déclenche ; l''épicentre est le point en surface directement au-dessus du foyer","L''épicentre est plus profond","Le foyer est à la surface"]'::jsonb, 'Le foyer est le point de rupture dans la croûte où le séisme se déclenche ; l''épicentre est le point en surface directement au-dessus du foyer', 'Le foyer du séisme d''Haïti 2010 se trouvait à ~13 km de profondeur ; son épicentre était près de Léogâne.', 'Facile'),
    (chap_id, 'Quelle est la différence entre l''échelle de Richter et l''échelle de Mercalli ?', '["Elles mesurent la même chose","Richter (magnitude) mesure l''énergie libérée par le séisme ; Mercalli (intensité) mesure les effets ressentis en un lieu précis","Mercalli mesure la profondeur","Richter mesure la durée"]'::jsonb, 'Richter (magnitude) mesure l''énergie libérée par le séisme ; Mercalli (intensité) mesure les effets ressentis en un lieu précis', 'Magnitude = énergie (objective) ; intensité = effets locaux (subjective). Un séisme a une magnitude unique mais des intensités variables.', 'Moyen'),
    (chap_id, 'Quels sont les deux types principaux d''ondes sismiques et leurs caractéristiques ?', '["Ondes alpha et bêta","Ondes P (primaires, longitudinales, traversant tous les milieux) et ondes S (secondaires, transversales, ne traversant pas les liquides)","Ondes X et Y","Ondes de surface uniquement"]'::jsonb, 'Ondes P (primaires, longitudinales, traversant tous les milieux) et ondes S (secondaires, transversales, ne traversant pas les liquides)', 'Les ondes P (plus rapides) arrivent en premier ; les ondes S et de surface (Love, Rayleigh) causent la majorité des dégâts.', 'Moyen'),
    (chap_id, 'Comment se forme un tsunami et quelles sont les conditions nécessaires ?', '["Un vent fort sur l''océan","Un tremblement de terre sous-marin (ou glissement de terrain) qui déplace verticalement une grande masse d''eau, créant des vagues longues et rapides en haute mer (qui amplifient en approchant des côtes)","Une éruption volcanique terrestre uniquement","Une marée exceptionnelle"]'::jsonb, 'Un tremblement de terre sous-marin (ou glissement de terrain) qui déplace verticalement une grande masse d''eau, créant des vagues longues et rapides en haute mer (qui amplifient en approchant des côtes)', 'Le tsunami de 2004 en Asie (magnitude 9.1) a tué 230 000 personnes ; les Caraïbes sont exposées aux tsunamis sismiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la liquéfaction des sols lors d''un séisme et pourquoi est-elle dangereuse ?', '["Un phénomène volcanique","Le comportement de certains sols saturés en eau (sables fins) qui perdent leur résistance lors d''un séisme et se comportent comme un liquide, engloutissant les fondations","Un type de faille","Un glissement de terrain classique"]'::jsonb, 'Le comportement de certains sols saturés en eau (sables fins) qui perdent leur résistance lors d''un séisme et se comportent comme un liquide, engloutissant les fondations', 'La liquéfaction a aggravé les dégâts du séisme de 2010 en Haïti dans les zones côtières et de remblai.', 'Moyen'),
    (chap_id, 'Quels sont les deux grands types de volcans selon leur structure et leur mode d''éruption ?', '["Petits et grands","Volcans boucliers (basaltiques, coulées fluides, peu explosifs) et stratovolcans (andésitiques/rhyolitiques, explosifs avec pyroclastes et nuées ardentes)","Volcans actifs et éteints","Volcans sous-marins et terrestres"]'::jsonb, 'Volcans boucliers (basaltiques, coulées fluides, peu explosifs) et stratovolcans (andésitiques/rhyolitiques, explosifs avec pyroclastes et nuées ardentes)', 'Mauna Loa (Hawaii) = bouclier peu dangereux ; Pelée (Martinique), Vésuve = stratovolcans très dangereux.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une nuée ardente et quel est son exemple historique le plus célèbre ?', '["Un nuage de vapeur d''eau","Un écoulement pyroclastique rapide de gaz chauds, cendres et roches (>700°C, >700 km/h) qui ne peut être survécue ; la Montagne Pelée en Martinique (1902, 30 000 morts) en est l''exemple classique","Une coulée de lave lente","Un tsunami volcanique"]'::jsonb, 'Un écoulement pyroclastique rapide de gaz chauds, cendres et roches (>700°C, >700 km/h) qui ne peut être survécue ; la Montagne Pelée en Martinique (1902, 30 000 morts) en est l''exemple classique', 'La nuée ardente (courant pyroclastique) de la Pelée a détruit Saint-Pierre en 3 minutes ; seul un prisonnier en réchappa.', 'Moyen'),
    (chap_id, 'Comment se définit le risque sismique et quels sont ses facteurs ?', '["Le risque = magnitude uniquement","Le risque sismique = aléa (probabilité d''un séisme) × vulnérabilité (qualité des constructions, densité de population) × exposition (valeur des biens et vies exposés)","Le risque = nombre de séismes","Le risque est identique partout"]'::jsonb, 'Le risque sismique = aléa (probabilité d''un séisme) × vulnérabilité (qualité des constructions, densité de population) × exposition (valeur des biens et vies exposés)', 'Haïti a un aléa modéré mais une vulnérabilité extrême (constructions précaires) → risque catastrophique (2010 : ~220 000 morts).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le parc de prévention et les systèmes d''alerte sismique précoce ?', '["Des boucliers contre les séismes","Des réseaux de capteurs sismiques qui détectent les ondes P (plus rapides, moins destructrices) et envoient un avertissement automatique avant l''arrivée des ondes S (destructrices)","Des constructions parasismiques","Des abris souterrains"]'::jsonb, 'Des réseaux de capteurs sismiques qui détectent les ondes P (plus rapides, moins destructrices) et envoient un avertissement automatique avant l''arrivée des ondes S (destructrices)', 'Le Japon utilise un système d''alerte précoce efficace (SkyAlert) donnant quelques secondes précieuses avant l''arrivée des ondes S.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la sismicité induite et comment les activités humaines peuvent-elles causer des séismes ?', '["Les séismes sont uniquement naturels","L''injection de fluides en profondeur (fracturation hydraulique, stockage CO2, remplissage de barrages) peut modifier les contraintes sur les failles et déclencher des séismes","L''exploitation minière ne cause pas de séismes","Les séismes induits sont toujours plus forts que les naturels"]'::jsonb, 'L''injection de fluides en profondeur (fracturation hydraulique, stockage CO2, remplissage de barrages) peut modifier les contraintes sur les failles et déclencher des séismes', 'L''Oklahoma (USA) est devenu la zone la plus sismique des USA en raison de l''injection de déchets issus du pétrole de schiste.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le géorisque en Haïti et comment y faire face ?', '["Haïti n''a pas de risques géologiques","Haïti est exposée à des séismes majeurs (failles Enriquillo et Septentrional), des glissements de terrain (déforestation), des tsunamis et des éruptions (à moindre niveau) ; la réduction du risque passe par la réglementation des constructions, la cartographie et l''éducation","Les risques sont uniquement climatiques","Les séismes en Haïti sont mineurs"]'::jsonb, 'Haïti est exposée à des séismes majeurs (failles Enriquillo et Septentrional), des glissements de terrain (déforestation), des tsunamis et des éruptions (à moindre niveau) ; la réduction du risque passe par la réglementation des constructions, la cartographie et l''éducation', 'La DPC (Direction de la Protection Civile) haïtienne travaille à la cartographie des risques et aux plans d''évacuation locaux.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la construction parasismique et ses principes fondamentaux ?', '["Construire en béton lourd","Construire des bâtiments capables d''absorber l''énergie sismique sans s''effondrer, en utilisant des matériaux flexibles, des fondations isolées et des systèmes d''amortissement","Construire sous terre","Construire en matériaux légers uniquement"]'::jsonb, 'Construire des bâtiments capables d''absorber l''énergie sismique sans s''effondrer, en utilisant des matériaux flexibles, des fondations isolées et des systèmes d''amortissement', 'Le code parasismique japonais permet de survivre à des séismes de magnitude 8+ ; son application en Haïti est un enjeu majeur.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 12 AND titre = 'Ressources naturelles et géologie économique' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Comment se forment les gisements de pétrole et de gaz naturel ?', '["Par refroidissement du magma","Par la décomposition de matière organique marine (plancton) enfouie sous des sédiments pendant des millions d''années, transformée en hydrocarbures sous l''effet de la chaleur et de la pression","Par métamorphisme des roches calcaires","Par l''érosion du granite"]'::jsonb, 'Par la décomposition de matière organique marine (plancton) enfouie sous des sédiments pendant des millions d''années, transformée en hydrocarbures sous l''effet de la chaleur et de la pression', 'Les hydrocarbures nécessitent : roche mère (kérogène), maturation thermique, roche réservoir poreuse et roche couverture imperméable.', 'Moyen'),
    (chap_id, 'Comment se forment les gisements de minerais métalliques ?', '["Par précipitation atmosphérique","Par concentration hydrothermale (circulations de fluides chauds dissolvant les métaux), magmatique (pegmatites) ou sédimentaire (évaporites, bauxite, fer rubané)","Par érosion uniquement","Par refroidissement rapide de la lave"]'::jsonb, 'Par concentration hydrothermale (circulations de fluides chauds dissolvant les métaux), magmatique (pegmatites) ou sédimentaire (évaporites, bauxite, fer rubané)', 'L''or (hydrothermal), le cuivre (porphyre), la bauxite (latéritisation tropicale) : chaque métal a son processus de concentration.', 'Moyen'),
    (chap_id, 'Quels sont les potentiels miniers d''Haïti selon les études géologiques récentes ?', '["Aucun potentiel","Des gisements d''or, cuivre et argent (notamment dans le nord, région de Morne Bossa), ainsi que du marbre et des roches ornementales","Uniquement du calcaire","Uniquement du pétrole offshore"]'::jsonb, 'Des gisements d''or, cuivre et argent (notamment dans le nord, région de Morne Bossa), ainsi que du marbre et des roches ornementales', 'Le Bureau des Mines et de l''Énergie (BME) d''Haïti a identifié des ressources aurifères significatives ; leur exploitation soulève des débats environnementaux.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''énergie géothermique et comment peut-elle être exploitée ?', '["L''énergie solaire","L''exploitation de la chaleur interne de la Terre : forages dans des zones à fort gradient géothermique (volcanism), production de vapeur pour générer de l''électricité ou chauffer des bâtiments","L''énergie des marées","L''énergie nucléaire"]'::jsonb, 'L''exploitation de la chaleur interne de la Terre : forages dans des zones à fort gradient géothermique (volcanism), production de vapeur pour générer de l''électricité ou chauffer des bâtiments', 'L''Islande (géothermie volcanique) couvre ~25% de son électricité par géothermie ; les Antilles ont un potentiel géothermique (Guadeloupe).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géologie environnementale et ses applications ?', '["L''étude des fossiles","L''application de la géologie à la résolution de problèmes environnementaux : gestion des aquifères, contamination des sols, choix de sites de déchets, études d''impact","L''astronomie","La géologie marine uniquement"]'::jsonb, 'L''application de la géologie à la résolution de problèmes environnementaux : gestion des aquifères, contamination des sols, choix de sites de déchets, études d''impact', 'La géologie environnementale est essentielle en Haïti pour la gestion des bassins versants et la réduction de l''érosion.', 'Moyen'),
    (chap_id, 'Comment la déforestation en Haïti amplifie-t-elle les risques géologiques ?', '["Elle n''a aucun effet","En enlevant le couvert végétal, elle accélère l''érosion des sols, augmente les glissements de terrain et les crues soudaines lors des cyclones, et réduit la recharge des nappes phréatiques","Elle favorise la minéralisation","Elle réduit le risque sismique"]'::jsonb, 'En enlevant le couvert végétal, elle accélère l''érosion des sols, augmente les glissements de terrain et les crues soudaines lors des cyclones, et réduit la recharge des nappes phréatiques', 'Haïti a perdu ~98% de sa couverture forestière originale ; chaque cyclone amplifie les catastrophes de terrain en l''absence d''arbres.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la gestion durable des ressources minières ?', '["L''exploitation maximale sans contrainte","L''exploitation des ressources minières en minimisant l''impact environnemental, en restaurant les sites exploités et en assurant que les bénéfices profitent aux communautés locales","L''arrêt total de l''exploitation","L''exploitation uniquement par des entreprises étrangères"]'::jsonb, 'L''exploitation des ressources minières en minimisant l''impact environnemental, en restaurant les sites exploités et en assurant que les bénéfices profitent aux communautés locales', 'Les principes de l''Initiative pour la Transparence dans les Industries Extractives (ITIE) promeuvent la gouvernance des ressources minières.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les aquifères et leur importance en Haïti ?', '["Des roches sans eau","Des formations géologiques poreuses et perméables contenant de l''eau souterraine exploitable ; en Haïti, les aquifères calcaires (karst) dans les plaines sont des sources d''eau potable essentielles","Des volcans sous-marins","Des formations de basalte"]'::jsonb, 'Des formations géologiques poreuses et perméables contenant de l''eau souterraine exploitable ; en Haïti, les aquifères calcaires (karst) dans les plaines sont des sources d''eau potable essentielles', 'Les plaines du Cul-de-Sac et de l''Artibonite abritent des aquifères importants mais vulnérables à la surexploitation et la contamination.', 'Moyen'),
    (chap_id, 'Comment les changements climatiques affectent-ils les ressources en eau souterraine ?', '["Sans effet","En modifiant les régimes de pluie et en augmentant l''évapotranspiration, les changements climatiques réduisent la recharge des aquifères et augmentent la compétition pour l''eau","En augmentant les aquifères","En créant de nouveaux aquifères"]'::jsonb, 'En modifiant les régimes de pluie et en augmentant l''évapotranspiration, les changements climatiques réduisent la recharge des aquifères et augmentent la compétition pour l''eau', 'Dans les Caraïbes, les projections climatiques prévoient une réduction des précipitations et une intensification des sécheresses.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la télédétection et les SIG (Systèmes d''Information Géographique) en géologie ?', '["Des instruments de forage","Des outils permettant l''analyse spatiale des données géologiques : la télédétection (satellites, drones) cartographie les formations géologiques ; les SIG intègrent les données pour la gestion des risques et des ressources","Des techniques de datation","Des méthodes de laboratoire uniquement"]'::jsonb, 'Des outils permettant l''analyse spatiale des données géologiques : la télédétection (satellites, drones) cartographie les formations géologiques ; les SIG intègrent les données pour la gestion des risques et des ressources', 'La télédétection (Landsat, SPOT) a révolutionné la cartographie géologique et la surveillance des risques naturels en Haïti.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géologie isotopique et ses applications à la géochimie ?', '["L''étude des roches uniquement","L''étude des rapports isotopiques dans les minéraux et fluides pour reconstituer les paléoclimats, dater les formations, tracer l''origine des magmas et des fluides hydrothermaux","Une technique d''exploration pétrolière uniquement","L''étude des isotopes radioactifs médicaux"]'::jsonb, 'L''étude des rapports isotopiques dans les minéraux et fluides pour reconstituer les paléoclimats, dater les formations, tracer l''origine des magmas et des fluides hydrothermaux', 'Les isotopes stables (O18/O16, C13/C12) enregistrent les paléoclimats dans les carottes glaciaires et les carbonates marins.', 'Difficile'),
    (chap_id, 'Comment la géologie contribue-t-elle à la compréhension du changement climatique passé et futur ?', '["La géologie n''est pas liée au climat","Les archives géologiques (carottes de glace, sédiments marins, spéléothèmes) enregistrent les paléoclimats sur millions d''années, permettant de calibrer les modèles climatiques et de replacer le réchauffement actuel dans son contexte géologique","La géologie concerne uniquement les roches solides","Les géologues ne s''intéressent pas au climat"]'::jsonb, 'Les archives géologiques (carottes de glace, sédiments marins, spéléothèmes) enregistrent les paléoclimats sur millions d''années, permettant de calibrer les modèles climatiques et de replacer le réchauffement actuel dans son contexte géologique', 'Les géologues ont identifié des périodes de CO2 élevé (PETM, il y a 56 Ma) montrant des analogues du réchauffement actuel.', 'Difficile');
  END IF;
END $$;
