-- Supplement Philosophie NS1-NS2 (matiere_id=16)
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'Introduction à la philosophie : qu''est-ce que philosopher ?' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel philosophe grec est considéré comme le père de la philosophie occidentale ?', '["Platon","Aristote","Socrate","Thalès"]'::jsonb, 'Socrate', 'Socrate (470-399 av. J.-C.) est considéré comme le fondateur de la philosophie morale et de la méthode dialectique.', 'Facile'),
    (chap_id, 'Que signifie étymologiquement le mot "philosophie" ?', '["Amour du savoir","Science de la nature","Art de la parole","Connaissance des dieux"]'::jsonb, 'Amour du savoir', 'Philosophia vient du grec philo (amour) + sophia (sagesse/savoir).', 'Facile'),
    (chap_id, 'Quelle est la méthode philosophique de Socrate fondée sur le dialogue ?', '["La dialectique","La rhétorique","La maïeutique","La sophistique"]'::jsonb, 'La maïeutique', 'La maïeutique socriatique (art d''accoucher les esprits) guide l''interlocuteur à découvrir la vérité par lui-même.', 'Moyen'),
    (chap_id, 'Selon Aristote, l''être humain se distingue des animaux principalement par ?', '["Sa force physique","Sa beauté","Le logos (raison et langage)","Sa longévité"]'::jsonb, 'Le logos (raison et langage)', 'Aristote définit l''homme comme "animal rationnel" (zoon logikon) doué de logos.', 'Moyen'),
    (chap_id, 'Quelle attitude intellectuelle est au fondement de la démarche philosophique selon Platon ?', '["La certitude","L''étonnement (thaumazein)","L''indifférence","La croyance"]'::jsonb, 'L''étonnement (thaumazein)', 'Platon et Aristote voient dans l''étonnement (thaumazein) le commencement de toute philosophie.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre la doxa et l''épistémè chez Platon ?', '["Aucune différence","Doxa = opinion","Doxa = science, épistémè = opinion","Doxa = forme, épistémè = matière"]'::jsonb, 'Doxa = opinion', 'La doxa est l''opinion changeante, l''épistémè est la connaissance stable fondée sur la raison.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''allégorie de la caverne de Platon illustre ?', '["La géographie de la Grèce","Le passage de l''ignorance à la","La nature des dieux","La politique d''Athènes"]'::jsonb, 'Le passage de l''ignorance à la', 'La caverne illustre le passage des ombres (apparences) à la lumière (Formes/Idées), métaphore de l''éducation philosophique.', 'Difficile'),
    (chap_id, 'Quelle discipline philosophique s''interroge sur la nature de la connaissance ?', '["L''ontologie","L''épistémologie","La métaphysique","L''éthique"]'::jsonb, 'L''épistémologie', 'L''épistémologie (théorie de la connaissance) étudie les conditions, les limites et la valeur du savoir.', 'Moyen'),
    (chap_id, 'Que signifie le terme "éthique" en philosophie ?', '["Science des lois naturelles","Réflexion sur la morale et les règles","Étude de la beauté","Théorie de la connaissance"]'::jsonb, 'Réflexion sur la morale et les règles', 'L''éthique interroge ce qui est bien, juste, et les fondements de nos obligations morales.', 'Facile'),
    (chap_id, 'Quel philosophe a écrit "Je pense donc je suis" (Cogito ergo sum) ?', '["Descartes","Kant","Rousseau","Locke"]'::jsonb, 'Descartes', 'Descartes dans les Méditations Métaphysiques (1641) trouve dans le Cogito la première certitude indubitable.', 'Facile'),
    (chap_id, 'Qu''est-ce que la métaphysique étudie ?', '["Les êtres vivants","Les fondements de l''être et de la","Les lois physiques","La politique"]'::jsonb, 'Les fondements de l''être et de la', 'La métaphysique s''interroge sur l''être en tant qu''être, l''existence, l''identité et la causalité.', 'Moyen'),
    (chap_id, 'Quelle est la question fondamentale de Leibniz : "Pourquoi y a-t-il quelque chose plutôt que rien ?" ?', '["Une question de physique","La question métaphysique fondamentale","Une question d''éthique","Une question religieuse sans intérêt philosophique"]'::jsonb, 'La question métaphysique fondamentale', 'C''est la question métaphysique par excellence, posée par Leibniz, sur le fondement de l''existence.', 'Difficile'),
    (chap_id, 'Que désigne la "philosophie première" chez Aristote ?', '["La logique","L''éthique","La métaphysique","La rhétorique"]'::jsonb, 'La métaphysique', 'Aristote appelle "philosophie première" l''étude des causes premières et de l''être en général.', 'Difficile'),
    (chap_id, 'Quelle discipline philosophique étudie la beauté et l''art ?', '["L''éthique","L''épistémologie","L''esthétique","La logique"]'::jsonb, 'L''esthétique', 'L''esthétique s''interroge sur la nature du beau, du sublime et l''expérience artistique.', 'Facile'),
    (chap_id, 'Selon Platon, les Idées (ou Formes) sont ?', '["Des représentations mentales subjectives","Des réalités objectives éternelles et","Des opinions communes","Des concepts scientifiques"]'::jsonb, 'Des réalités objectives éternelles et', 'Pour Platon, les Idées existent indépendamment du monde sensible et sont plus réelles que lui.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'Le sujet : conscience, identité et liberté' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la définition de la conscience chez Descartes ?', '["La certitude du monde extérieur","La pensée en acte","Le corps et l''âme réunis","Les instincts naturels"]'::jsonb, 'La pensée en acte', 'Pour Descartes, la conscience est la res cogitans (chose pensante), fondement du Cogito.', 'Moyen'),
    (chap_id, 'Sartre affirme que "l''existence précède l''essence". Que signifie cette formule ?', '["L''homme naît avec une nature déterminée","L''homme est d''abord existence et se","La conscience précède la matière","L''âme est immortelle"]'::jsonb, 'L''homme est d''abord existence et se', 'Contre l''essentialisme, Sartre soutient que l''homme n''a pas de nature fixe : il se crée par ses choix.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le libre arbitre ?', '["La liberté de faire ce qu''on veut sans contrainte","La capacité de la volonté à se","L''absence de lois","L''instinct naturel"]'::jsonb, 'La capacité de la volonté à se', 'Le libre arbitre est la faculté de choisir librement entre plusieurs possibles, sans être entièrement déterminé.', 'Moyen'),
    (chap_id, 'Selon Spinoza, la liberté est ?', '["L''absence de toute contrainte","La connaissance et l''acceptation de la","Le libre arbitre absolu","L''indépendance économique"]'::jsonb, 'La connaissance et l''acceptation de la', 'Pour Spinoza, la vraie liberté est d''agir selon sa propre nature, non par contrainte extérieure.', 'Difficile'),
    (chap_id, 'Que désigne le "moi" dans la philosophie de Hume ?', '["Une substance permanente","Un faisceau de perceptions sans","L''âme immortelle","La conscience transcendantale"]'::jsonb, 'Un faisceau de perceptions sans', 'Hume nie la permanence du moi : ce n''est qu''une collection de perceptions changeantes.', 'Difficile'),
    (chap_id, 'Quelle est la différence entre liberté et licence pour Rousseau ?', '["Aucune","La liberté respecte la loi morale","La licence est plus noble","La liberté est naturelle, la licence est civile"]'::jsonb, 'La liberté respecte la loi morale', 'Rousseau distingue la vraie liberté (soumission aux lois qu''on s''est données) de la licence (absence de règles).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la mauvaise foi chez Sartre ?', '["Le mensonge délibéré","Se fuir soi-même en prétendant être","L''ignorance des valeurs","La lâcheté morale"]'::jsonb, 'Se fuir soi-même en prétendant être', 'La mauvaise foi, c''est nier sa liberté et sa responsabilité en se comportant comme si on était une chose.', 'Difficile'),
    (chap_id, 'Selon Locke, l''identité personnelle est fondée sur ?', '["L''âme immortelle","La continuité de la conscience et de la","Le corps physique","La volonté divine"]'::jsonb, 'La continuité de la conscience et de la', 'Locke fonde l''identité personnelle sur la mémoire : je suis la même personne que j''ai été parce que je m''en souviens.', 'Difficile'),
    (chap_id, 'Quel philosophe a développé la notion de "sujet transcendantal" ?', '["Hegel","Kant","Descartes","Sartre"]'::jsonb, 'Kant', 'Le sujet transcendantal kantien est la condition de possibilité de toute expérience, indépendant du sujet empirique.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le déterminisme en philosophie ?', '["La croyance en la liberté totale","La thèse que tout événement est","L''indéterminisme quantique","La fatalité religieuse"]'::jsonb, 'La thèse que tout événement est', 'Le déterminisme affirme que nos actions résultent nécessairement de causes antérieures (nature, environnement).', 'Moyen'),
    (chap_id, 'Que signifie la "conscience de soi" chez Hegel ?', '["La simple introspection","Un processus dialectique de","La certitude cartésienne","L''instinct de survie"]'::jsonb, 'Un processus dialectique de', 'Pour Hegel, la conscience de soi se réalise dans la rencontre avec autrui (dialectique maître-esclave).', 'Difficile'),
    (chap_id, 'Quelle est la position compatibiliste sur liberté et déterminisme ?', '["Ils sont incompatibles","Le déterminisme n''empêche pas une forme","La liberté est une illusion","Le déterminisme est faux"]'::jsonb, 'Le déterminisme n''empêche pas une forme', 'Le compatibilisme (Hume, Hobbes) affirme que liberté et déterminisme sont compatibles : être libre = agir selon ses désirs.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''inconscient selon Freud remet en question ?', '["La liberté économique","La transparence de la conscience à","La réalité du monde extérieur","Le déterminisme"]'::jsonb, 'La transparence de la conscience à', 'L''inconscient freudien montre que le sujet n''est pas maître de sa propre maison psychique.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''authenticité chez les existentialistes ?', '["Se conformer aux normes sociales","Assumer pleinement sa liberté et vivre","Vivre sans se soucier des autres","Rechercher le bonheur matériel"]'::jsonb, 'Assumer pleinement sa liberté et vivre', 'L''authenticité existentialiste est le courage d''assumer sa liberté et sa responsabilité face à l''existence.', 'Moyen'),
    (chap_id, 'Selon Kant, qu''est-ce qui distingue la personne d''une chose ?', '["La personne est vivante","La personne a une valeur intrinsèque","La personne est consciente","La personne a des droits légaux"]'::jsonb, 'La personne a une valeur intrinsèque', 'Kant dans la Fondation de la métaphysique des mœurs : les personnes ont une dignité qui ne peut être échangée.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'La connaissance et la vérité' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel courant philosophique affirme que toute connaissance vient de l''expérience sensible ?', '["Le rationalisme","L''empirisme","L''idéalisme","Le scepticisme"]'::jsonb, 'L''empirisme', 'L''empirisme (Locke, Hume, Bacon) affirme que l''esprit est une tabula rasa alimentée par l''expérience.', 'Moyen'),
    (chap_id, 'Quel courant affirme que la raison est la source principale de la connaissance vraie ?', '["L''empirisme","L''utilitarisme","Le rationalisme","Le pragmatisme"]'::jsonb, 'Le rationalisme', 'Le rationalisme (Descartes, Leibniz, Spinoza) fonde la connaissance sur la raison et les idées innées.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le scepticisme philosophique ?', '["La certitude absolue","Le doute méthodique sur la possibilité","L''agnosticisme religieux","Le relativisme moral"]'::jsonb, 'Le doute méthodique sur la possibilité', 'Les sceptiques (Pyrrhon, Sextus Empiricus) suspendent leur jugement (épochè) face à l''incertitude.', 'Moyen'),
    (chap_id, 'Que signifie la "révolution copernicienne" de Kant en philosophie ?', '["La rotation de la Terre","Ce n''est plus l''objet qui détermine la","La fin du géocentrisme","La naissance de la physique moderne"]'::jsonb, 'Ce n''est plus l''objet qui détermine la', 'Kant inverse la relation : c''est notre faculté cognitive qui structure l''expérience, non l''inverse.', 'Difficile'),
    (chap_id, 'Quel philosophe a distingué les jugements analytiques et synthétiques a priori ?', '["Hume","Descartes","Kant","Hegel"]'::jsonb, 'Kant', 'Kant dans la Critique de la raison pure distingue les jugements analytiques (explicatifs) et synthétiques a priori (qui augmentent la connaissance).', 'Difficile'),
    (chap_id, 'Qu''est-ce que le pragmatisme affirme sur la vérité ?', '["La vérité est éternelle","Une idée est vraie si elle est utile et","La vérité est subjective","La vérité n''existe pas"]'::jsonb, 'Une idée est vraie si elle est utile et', 'Le pragmatisme (James, Dewey, Peirce) évalue les idées à leur efficacité et leurs conséquences pratiques.', 'Difficile'),
    (chap_id, 'Que réfute Descartes par son doute hyperbolique ?', '["Seulement les opinions vulgaires","Toutes les croyances pouvant être mises","Uniquement la religion","La morale"]'::jsonb, 'Toutes les croyances pouvant être mises', 'Le doute hyperbolique de Descartes est une méthode pour ne garder que les certitudes absolument indubitables.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une vérité a priori ?', '["Une vérité vérifiée par l''expérience","Une vérité connue indépendamment de","Une vérité probable","Une vérité empirique"]'::jsonb, 'Une vérité connue indépendamment de', 'Les vérités a priori (mathématiques, logiques) valent nécessairement sans besoin d''expérience.', 'Moyen'),
    (chap_id, 'Quel est le problème de l''induction soulevé par Hume ?', '["La déduction est impossible","On ne peut logiquement justifier le","Les mathématiques sont incertaines","Le raisonnement déductif est circulaire"]'::jsonb, 'On ne peut logiquement justifier le', 'Hume montre que l''induction repose sur la croyance et l''habitude, non sur une nécessité logique.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la correspondance comme théorie de la vérité ?', '["La vérité est ce qui est utile","Une proposition est vraie si elle","La vérité est cohérence interne","La vérité est consensus"]'::jsonb, 'Une proposition est vraie si elle', 'La théorie de la correspondance (Aristote, Tarski) : une affirmation est vraie si les faits qu''elle décrit existent réellement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le rationalisme critique de Karl Popper ?', '["Rejeter toute théorie non prouvée","Toute théorie scientifique doit être","Accepter toutes les théories","Confier la vérité à l''expérience seule"]'::jsonb, 'Toute théorie scientifique doit être', 'Pour Popper, la falsifiabilité distingue la science de la non-science.', 'Difficile'),
    (chap_id, 'Quelle est la différence entre vérité et certitude ?', '["Ce sont des synonymes","La vérité est objective","La certitude est objective","La vérité est plus subjective"]'::jsonb, 'La vérité est objective', 'On peut être certain de quelque chose de faux, et incertain d''une vérité.', 'Moyen'),
    (chap_id, 'Quel philosophe a critiqué la "vérité comme consensus" par son éthique de la discussion ?', '["Nietzsche","Habermas","Foucault","Derrida"]'::jsonb, 'Habermas', 'Habermas développe une théorie de la vérité par consensus dans des conditions idéales de communication.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le relativisme épistémologique ?', '["La vérité est absolue","La vérité dépend du contexte culturel","L''empirie est la seule source de vérité","La logique est subjective"]'::jsonb, 'La vérité dépend du contexte culturel', 'Le relativisme épistémologique affirme qu''il n''existe pas de vérité universelle, mais des vérités relatives.', 'Moyen'),
    (chap_id, 'Quelle affirmation résume la position d''Aristote sur la vérité ?', '["Dire du vrai ce qui est vrai et du faux","La vérité est dans les Idées de Platon","La vérité dépend de l''opinion","Toute vérité est relative à la culture"]'::jsonb, 'Dire du vrai ce qui est vrai et du faux', 'Aristote dans la Métaphysique : la vérité consiste à affirmer ce qui est et nier ce qui n''est pas.', 'Facile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'La morale et l''éthique : fondements et enjeux' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que l''impératif catégorique de Kant ?', '["Agis de manière à obtenir le plus de bonheur","Agis seulement selon la maxime que tu","Respecte les lois de ton pays","Suis tes instincts naturels"]'::jsonb, 'Agis seulement selon la maxime que tu', 'L''impératif catégorique kantien est le principe suprême de la morale déontologique.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''utilitarisme défend ?', '["La morale du devoir","La plus grande utilité pour le plus","L''égoïsme rationnel","La vertu aristotélicienne"]'::jsonb, 'La plus grande utilité pour le plus', 'Bentham et Mill fondent la morale sur le principe d''utilité : maximiser le bonheur collectif.', 'Moyen'),
    (chap_id, 'Selon Aristote, qu''est-ce que la vertu ?', '["Le respect des lois","Un juste milieu entre deux extrêmes","L''obéissance divine","La recherche du plaisir"]'::jsonb, 'Un juste milieu entre deux extrêmes', 'La vertu aristotélicienne (arété) est une disposition stable à choisir le juste milieu (mésotès).', 'Difficile'),
    (chap_id, 'Quelle est la différence entre morale et éthique selon Ricoeur ?', '["Aucune","La morale = norme universelle","La morale est plus récente","L''éthique est plus contraignante"]'::jsonb, 'La morale = norme universelle', 'Ricoeur distingue l''éthique (aspiration à la vie bonne) de la morale (normes universelles contraignantes).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la morale du devoir (déontologie) ?', '["Agir pour maximiser les conséquences positives","L''obligation d''agir conformément au","Suivre les normes sociales","Développer les vertus"]'::jsonb, 'L''obligation d''agir conformément au', 'La déontologie (Kant) juge les actes selon leur conformité au devoir, non leurs effets.', 'Moyen'),
    (chap_id, 'Selon Nietzsche, quelle est la "généalogie de la morale" ?', '["L''origine divine de la morale","La morale des esclaves comme","L''évolution naturelle des normes","L''utilitarisme primitif"]'::jsonb, 'La morale des esclaves comme', 'Nietzsche montre que la morale chrétienne/ascétique est une inversion des valeurs nobles (force → faiblesse valorisée).', 'Difficile'),
    (chap_id, 'Quelle est la position stoïcienne sur la morale ?', '["Rechercher le plaisir","Agir selon la raison et la nature","Obéir aux lois civiles","Maximiser son intérêt"]'::jsonb, 'Agir selon la raison et la nature', 'Les stoïciens (Marc Aurèle, Épictète) prônent la vie selon la raison (logos) et la maîtrise des passions.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le contrat social selon Rousseau ?', '["Un accord économique","Un pacte par lequel les individus","Un traité international","Une loi naturelle"]'::jsonb, 'Un pacte par lequel les individus', 'Le contrat social fonde la légitimité politique sur la volonté générale et le consentement des citoyens.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le relativisme moral ?', '["Il existe des valeurs morales universelles","Les valeurs morales varient selon les","La morale est fondée sur Dieu","La morale naturelle prime"]'::jsonb, 'Les valeurs morales varient selon les', 'Le relativisme moral conteste l''universalité des normes éthiques, affirmant leur variabilité culturelle.', 'Moyen'),
    (chap_id, 'Quel est le paradoxe du trolley (Foot) en éthique ?', '["Un paradoxe économique","Un dilemme illustrant les tensions","Un exemple de logique formelle","Un problème politique"]'::jsonb, 'Un dilemme illustrant les tensions', 'Le trolley problem oppose sauver 5 vies en tuant 1 (conséquentialisme) vs l''interdiction de tuer (déontologie).', 'Difficile'),
    (chap_id, 'Selon l''éthique de la vertu, qu''est-ce qui est moral ?', '["Ce qui respecte des règles","Ce que ferait une personne vertueuse","Ce qui maximise l''utilité","Ce qui respecte le droit"]'::jsonb, 'Ce que ferait une personne vertueuse', 'L''éthique de la vertu (Aristote, MacIntyre) centre la morale sur le caractère et les vertus du sujet.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''éthique du care ?', '["Une éthique des droits individuels","Une éthique centrée sur les relations","Une éthique utilitariste","L''éthique kantienne appliquée aux soins"]'::jsonb, 'Une éthique centrée sur les relations', 'L''éthique du care (Gilligan, Noddings) valorise l''interdépendance, le soin et la relation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la règle d''or éthique présente dans de nombreuses traditions ?', '["Fais aux autres ce que tu voudrais","Maximise ton bonheur","Obéis toujours à l''autorité","Respecte la loi naturelle"]'::jsonb, 'Fais aux autres ce que tu voudrais', 'La règle d''or se retrouve dans le christianisme, le confucianisme, l''islam et d''autres traditions morales.', 'Facile'),
    (chap_id, 'Qu''est-ce que la conscience morale ?', '["La simple connaissance des lois","La faculté intérieure de discerner le","Le surmoi freudien uniquement","Les règles sociales intériorisées"]'::jsonb, 'La faculté intérieure de discerner le', 'La conscience morale est cette "voix intérieure" qui guide et juge nos actions moralement.', 'Moyen'),
    (chap_id, 'Quel philosophe a développé la notion de "justice comme équité" ?', '["Rawls","Nozick","Habermas","Walzer"]'::jsonb, 'Rawls', 'Rawls dans Théorie de la Justice (1971) développe la justice fondée sur le voile d''ignorance et les principes d''égalité.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 16 AND titre = 'La politique : État, pouvoir et démocratie' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel philosophe a théorisé la séparation des pouvoirs ?', '["Hobbes","Locke","Montesquieu","Rousseau"]'::jsonb, 'Montesquieu', 'Dans L''Esprit des lois (1748), Montesquieu théorise la séparation des pouvoirs législatif, exécutif et judiciaire.', 'Moyen'),
    (chap_id, 'Quelle est la conception de l''État selon Hobbes dans le Léviathan ?', '["Un État minimal","Un État fort issu d''un contrat social","Un État démocratique","Un État fondé sur la religion"]'::jsonb, 'Un État fort issu d''un contrat social', 'Hobbes : sans État, la vie est "solitaire, pauvre, nasty, brutish and short" ; d''où la nécessité d''un souverain absolu.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la démocratie directe ?', '["Les citoyens votent pour des représentants","Les citoyens participent directement","Le gouvernement des experts","Le régime présidentiel"]'::jsonb, 'Les citoyens participent directement', 'La démocratie directe athénienne permettait aux citoyens de voter directement sur les lois et décisions.', 'Facile'),
    (chap_id, 'Qu''est-ce que la volonté générale chez Rousseau ?', '["La somme des volontés individuelles","L''intérêt commun de tous les citoyens","La volonté du roi","L''opinion de la majorité"]'::jsonb, 'L''intérêt commun de tous les citoyens', 'La volonté générale vise le bien commun, contrairement à la "volonté de tous" qui agrège les intérêts privés.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la légitimité du pouvoir politique ?', '["La force militaire","Le droit reconnu d''exercer l''autorité","Le nombre de sujets","La richesse du gouvernant"]'::jsonb, 'Le droit reconnu d''exercer l''autorité', 'La légitimité (Weber : traditionnelle, charismatique, légale-rationnelle) fonde l''acceptation du pouvoir.', 'Moyen'),
    (chap_id, 'Selon Marx, qu''est-ce que l''État dans la société capitaliste ?', '["Un arbitre neutre","L''instrument de domination de la classe","Une institution divine","Un garant des droits naturels"]'::jsonb, 'L''instrument de domination de la classe', 'Pour Marx, l''État "n''est que le comité qui gère les affaires communes de la bourgeoisie".', 'Difficile'),
    (chap_id, 'Quelle forme de gouvernement Aristote considère comme la meilleure en pratique ?', '["L''oligarchie","La démocratie pure","La politie (constitution mixte)","La monarchie absolue"]'::jsonb, 'La politie (constitution mixte)', 'Aristote préfère la politie, un régime mixte combinant oligarchie et démocratie, pour sa stabilité.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le libéralisme politique ?', '["L''État doit contrôler l''économie","La priorité des droits individuels et","L''État doit diriger la société","La démocratie directe universelle"]'::jsonb, 'La priorité des droits individuels et', 'Le libéralisme politique (Locke, Mill, Rawls) place les droits naturels et les libertés au-dessus de l''autorité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la désobéissance civile selon Thoreau ?', '["Une rébellion armée","Le refus non violent de se soumettre à","La démocratie directe","L''anarchisme"]'::jsonb, 'Le refus non violent de se soumettre à', 'Thoreau et King prônent la désobéissance civile non violente pour protester contre des lois immorales.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le totalitarisme selon Hannah Arendt ?', '["Un État autoritaire ordinaire","Un régime cherchant à dominer tous les","Une dictature militaire","Un régime monarchique absolu"]'::jsonb, 'Un régime cherchant à dominer tous les', 'Arendt dans Les Origines du totalitarisme analyse le nazisme et le stalinisme comme phénomènes radicalement nouveaux.', 'Difficile'),
    (chap_id, 'Quelle est la position anarchiste sur l''État ?', '["L''État est nécessaire","L''État doit être minimal","L''État est une domination illégitime","L''État doit être démocratique"]'::jsonb, 'L''État est une domination illégitime', 'Les anarchistes (Proudhon, Bakounine) rejettent tout gouvernement comme oppression de la liberté individuelle.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe de tolérance en philosophie politique ?', '["Accepter toutes les opinions comme vraies","Permettre l''expression des opinions","L''indifférence face aux injustices","L''acceptation de toute loi"]'::jsonb, 'Permettre l''expression des opinions', 'La tolérance (Locke, Mill) est un principe fondamental des démocraties libérales.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le voile d''ignorance de Rawls ?', '["Un principe religieux","Un dispositif de pensée où on choisit","Un type de censure","Un mythe philosophique"]'::jsonb, 'Un dispositif de pensée où on choisit', 'Rawls : derrière le voile d''ignorance, on choisirait des principes justes car on ignore sa position dans la société.', 'Difficile'),
    (chap_id, 'Quelle est la différence entre liberté négative et positive selon Berlin ?', '["Aucune","Négative = absence de contrainte","Négative est plus récente","Positive est plus libérale"]'::jsonb, 'Négative = absence de contrainte', 'Berlin distingue liberté négative (freedom from) et positive (freedom to) dans Deux Concepts de la liberté.', 'Difficile'),
    (chap_id, 'Selon Platon dans La République, qui devrait gouverner la cité idéale ?', '["Les guerriers","Les philosophes-rois","Les artisans","Le peuple"]'::jsonb, 'Les philosophes-rois', 'Platon confie le gouvernement aux philosophes, seuls capables de connaître le Bien et de gouverner selon la raison.', 'Moyen');
  END IF;
END $$;
