-- Supplement Littérature Universelle NS1-NS3 (matiere_id=20)
-- ATTENTION : NS1, NS2, NS3 SEULEMENT — aucun chapitre NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 20 AND titre = 'Les grands genres littéraires et leurs caractéristiques' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel genre littéraire se caractérise par une narration en prose d''une histoire fictive développée ?', '["La poésie","Le roman","La nouvelle","La fable"]'::jsonb, 'Le roman', 'Le roman est un long récit en prose comportant des personnages, une intrigue et un univers fictif développé.', 'Facile'),
    (chap_id, 'Quelle figure de style compare deux éléments avec un outil de comparaison (comme, tel...) ?', '["La métaphore","La comparaison","L''allégorie","L''hyperbole"]'::jsonb, 'La comparaison', 'La comparaison utilise un comparant, un comparé et un outil de comparaison explicite.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une tragédie au sens classique du terme ?', '["Un roman triste","Une pièce mettant en scène des personnages nobles dont la chute est inévitable","Un poème épique","Une comédie noire"]'::jsonb, 'Une pièce mettant en scène des personnages nobles dont la chute est inévitable', 'La tragédie (Sophocle, Racine) respecte les trois unités et vise la catharsis (purification des passions).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la catharsis dans le théâtre grec ?', '["La décoration de la scène","La purification des émotions du spectateur par l''identification aux personnages","Le chant du chœur","Le dénouement heureux"]'::jsonb, 'La purification des émotions du spectateur par l''identification aux personnages', 'Aristote dans la Poétique : la tragédie produit pitié et crainte qui se "purgent" à la fin de la pièce.', 'Difficile'),
    (chap_id, 'Quel est le schéma narratif canonique d''un récit selon Propp/Larivaille ?', '["Introduction, développement, conclusion","Situation initiale, élément perturbateur, péripéties, résolution, situation finale","Exposition, nœud, dénouement","Début, milieu, fin"]'::jsonb, 'Situation initiale, élément perturbateur, péripéties, résolution, situation finale', 'Le schéma quinaire du récit (Larivaille) comprend cinq étapes articulées autour du déséquilibre/rééquilibre.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le narrateur intradiégétique ?', '["Un narrateur extérieur au récit","Un narrateur qui est personnage dans l''histoire qu''il raconte","Le lecteur implicite","L''auteur réel"]'::jsonb, 'Un narrateur qui est personnage dans l''histoire qu''il raconte', 'Le narrateur intradiégétique (ex : Robinson Crusoé) participe à l''histoire qu''il narre.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un sonnet ?', '["Un poème de longueur libre","Un poème de 14 vers divisé en 2 quatrains et 2 tercets","Un poème épique","Une ballade médiévale"]'::jsonb, 'Un poème de 14 vers divisé en 2 quatrains et 2 tercets', 'Le sonnet (Pétrarque, Du Bellay, Baudelaire) : 2 quatrains (ABBA) + 2 tercets (CCD, EDE).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''épopée comme genre littéraire ?', '["Un roman moderne","Un long poème narratif racontant les exploits d''un héros fondateur","Une tragédie musicale","Un dialogue philosophique"]'::jsonb, 'Un long poème narratif racontant les exploits d''un héros fondateur', 'L''épopée (Iliade, Énéide, Odyssée) narre en vers les aventures d''un héros et fonde une identité culturelle.', 'Moyen'),
    (chap_id, 'Quelle figure de style consiste à attribuer des qualités humaines à des objets ou abstractions ?', '["La comparaison","La métonymie","La personnification","L''euphémisme"]'::jsonb, 'La personnification', 'La personnification (prosopopée) attribue des traits humains à des entités non humaines.', 'Facile'),
    (chap_id, 'Qu''est-ce que la focalisation interne dans un récit ?', '["Voir la scène de l''extérieur","Le lecteur ne sait que ce que sait le personnage focal","Tout voir de l''extérieur","Vision omnisciente"]'::jsonb, 'Le lecteur ne sait que ce que sait le personnage focal', 'La focalisation interne (Genette) : la narration est filtrée par la conscience d''un personnage.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le réalisme littéraire du XIXe siècle vise ?', '["Idéaliser la réalité","Représenter fidèlement la réalité sociale et humaine, y compris ses aspects sombres","Fuir la réalité","Créer des mondes fantastiques"]'::jsonb, 'Représenter fidèlement la réalité sociale et humaine, y compris ses aspects sombres', 'Le réalisme (Balzac, Flaubert, Dickens) observe et décrit objectivement la société contemporaine.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''ironie dans un texte littéraire ?', '["Dire exactement ce qu''on pense","Dire le contraire de ce qu''on pense pour créer un effet critique ou humoristique","Exagérer pour choquer","Comparer deux éléments"]'::jsonb, 'Dire le contraire de ce qu''on pense pour créer un effet critique ou humoristique', 'L''ironie exploite le décalage entre sens littéral et sens réel ; elle peut être douce ou mordante.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la nouvelle comme genre littéraire ?', '["Un roman court","Un récit bref en prose centré sur un événement singulier avec peu de personnages","Un poème narratif","Un extrait de roman"]'::jsonb, 'Un récit bref en prose centré sur un événement singulier avec peu de personnages', 'La nouvelle (Maupassant, Poe, Tchékhov) est concentrée, avec une chute souvent inattendue.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''allégorie dans la littérature ?', '["Une simple comparaison","Un récit fictif représentant de façon symbolique une vérité abstraite","Un jeu de mots","Une figure sonore"]'::jsonb, 'Un récit fictif représentant de façon symbolique une vérité abstraite', 'L''allégorie (La Fontaine, Kafka) représente des abstractions (justice, mort) par des personnages ou histoires.', 'Moyen'),
    (chap_id, 'Que désigne le terme "intertextualité" en littérature ?', '["Les notes de bas de page","Les relations entre un texte et les textes antérieurs qui l''influencent ou qu''il cite","La biographie de l''auteur","L''index d''un livre"]'::jsonb, 'Les relations entre un texte et les textes antérieurs qui l''influencent ou qu''il cite', 'Kristeva : tout texte est une "mosaïque de citations", transformant et absorbant d''autres textes.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 20 AND titre = 'Littérature antique et médiévale' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui est l''auteur présumé de l''Iliade et de l''Odyssée ?', '["Virgile","Homère","Sophocle","Hésiode"]'::jsonb, 'Homère', 'Homère (VIIIe s. av. J.-C.) est l''aède auquel la tradition attribue les deux grandes épopées grecques.', 'Facile'),
    (chap_id, 'Quel est le thème central de l''Odyssée d''Homère ?', '["La guerre de Troie","Le retour d''Ulysse à Ithaque après la guerre de Troie","La fondation de Rome","Les travaux d''Hercule"]'::jsonb, 'Le retour d''Ulysse à Ithaque après la guerre de Troie', 'L''Odyssée narre les dix ans d''errance d''Ulysse (Odysseus) pour rentrer chez lui après la guerre.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''Énéide de Virgile raconte ?', '["Les guerres de Julio César","Les pérégrinations d''Énée, ancêtre mythique de Rome","La vie d''Auguste","La chute de Carthage"]'::jsonb, 'Les pérégrinations d''Énée, ancêtre mythique de Rome', 'L''Énéide (29-19 av. J.-C.) narre le voyage d''Énée de Troie en ruines jusqu''à la fondation de Rome.', 'Moyen'),
    (chap_id, 'Quel auteur grec a écrit Œdipe Roi et Antigone ?', '["Euripide","Aristophane","Sophocle","Eschyle"]'::jsonb, 'Sophocle', 'Sophocle (497-406 av. J.-C.) est l''un des trois grands tragédiens grecs avec Eschyle et Euripide.', 'Moyen'),
    (chap_id, 'Qu''est-ce que La Divine Comédie de Dante Alighieri ?', '["Un poème lyrique","Un voyage allégorique à travers l''Enfer, le Purgatoire et le Paradis","Un roman médiéval","Une chanson de geste"]'::jsonb, 'Un voyage allégorique à travers l''Enfer, le Purgatoire et le Paradis', 'Dante (1265-1321) décrit son voyage imaginaire guidé par Virgile (Enfer/Purgatoire) puis Béatrice (Paradis).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une chanson de geste au Moyen Âge ?', '["Un poème lyrique d''amour","Un long poème épique narrant les exploits de héros guerriers","Un conte moral","Un roman courtois"]'::jsonb, 'Un long poème épique narrant les exploits de héros guerriers', 'Les chansons de geste (La Chanson de Roland, XIe s.) célèbrent les guerriers chrétiens contre les Sarrasins.', 'Moyen'),
    (chap_id, 'Quel est le thème de l''amour courtois dans la littérature médiévale ?', '["La guerre et la gloire","Un amour idéalisé, souvent adultère, où le chevalier sert et vénère sa dame","La religion monacale","La politique féodale"]'::jsonb, 'Un amour idéalisé, souvent adultère, où le chevalier sert et vénère sa dame', 'L''amour courtois (Tristan et Iseut, Lancelot) exalte la passion inaccessible et la soumission amoureuse.', 'Moyen'),
    (chap_id, 'Qui a écrit Les Métamorphoses (recueil de mythes de la création à César) ?', '["Virgile","Homère","Ovide","Horace"]'::jsonb, 'Ovide', 'Ovide (43 av. J.-C. - 17 ap.) compile 250 mythes grecs et romains, tous liés à des transformations.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le Roman de la Rose (XIIIe s.) ?', '["Un roman policier","Un long poème allégorique sur la conquête amoureuse","Un traité politique","Un livre de prières"]'::jsonb, 'Un long poème allégorique sur la conquête amoureuse', 'Le Roman de la Rose (Guillaume de Lorris, Jean de Meung) allègue la conquête d''une rose symbolisant la femme aimée.', 'Moyen'),
    (chap_id, 'Qu''est-ce que Le Décaméron de Boccace ?', '["Un poème épique","Un recueil de 100 nouvelles racontées par 10 personnes fuyant la peste de Florence","Un traité de philosophie","Un récit de voyage"]'::jsonb, 'Un recueil de 100 nouvelles racontées par 10 personnes fuyant la peste de Florence', 'Boccace (1313-1375) inaugure avec le Décaméron la nouvelle littéraire italienne de la Renaissance.', 'Moyen'),
    (chap_id, 'Quelle est la particularité du théâtre grec antique concernant le chœur ?', '["Le chœur dirige les acteurs","Le chœur commente l''action, représente l''opinion collective et dialogue avec les acteurs","Le chœur joue tous les rôles","Le chœur est silencieux"]'::jsonb, 'Le chœur commente l''action, représente l''opinion collective et dialogue avec les acteurs', 'Le chœur (choreutes) est fondamental dans la tragédie grecque : il moralise, prédit et réagit à l''action.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''épopée de Gilgamesh représente dans l''histoire littéraire ?', '["Le premier roman","L''une des premières œuvres littéraires de l''humanité, précurseur des thèmes universels","Un texte religieux mineur","Un texte mathématique"]'::jsonb, 'L''une des premières œuvres littéraires de l''humanité, précurseur des thèmes universels', 'L''épopée de Gilgamesh (Mésopotamie, ~2100 av. J.-C.) aborde l''amitié, la mort et la quête d''immortalité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le Beowulf dans la littérature médiévale anglaise ?', '["Un roman d''amour","Un poème épique anglo-saxon narrant les combats d''un héros contre des monstres","Un traité chrétien","Une chronique historique"]'::jsonb, 'Un poème épique anglo-saxon narrant les combats d''un héros contre des monstres', 'Beowulf (VIIe-Xe s.) est la plus ancienne œuvre majeure en vieil anglais, mêlant héroïsme germanique et christianisme.', 'Difficile'),
    (chap_id, 'Quelle œuvre latine de Virgile conseille-t-elle sur l''agriculture et célèbre la campagne romaine ?', '["L''Énéide","Les Géorgiques","Les Bucoliques","L''Iliade latine"]'::jsonb, 'Les Géorgiques', 'Les Géorgiques (29 av. J.-C.) sont un poème didactique sur l''agriculture célébrant la vie rurale romaine.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 20 AND titre = 'Littérature de la Renaissance au XVIIIe siècle' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui a écrit Don Quichotte, considéré comme le premier roman moderne ?', '["Dante","Cervantès","Rabelais","Shakespeare"]'::jsonb, 'Cervantès', 'Miguel de Cervantès (1605-1615) invente avec Don Quichotte la modernité romanesque et la parodie des romans de chevalerie.', 'Moyen'),
    (chap_id, 'Quel est le thème central des Essais de Montaigne ?', '["La politique française","L''étude de soi-même comme objet philosophique universel","La religion réformée","La géographie du monde"]'::jsonb, 'L''étude de soi-même comme objet philosophique universel', 'Montaigne inaugure l''introspection moderne : "Chaque homme porte la forme entière de l''humaine condition."', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''humanisme de la Renaissance littéraire ?', '["Le rejet de l''Antiquité","Le retour aux textes antiques et la mise en valeur de l''homme dans sa dignité","Le protestantisme littéraire","Le réalisme social"]'::jsonb, 'Le retour aux textes antiques et la mise en valeur de l''homme dans sa dignité', 'L''humanisme (Érasme, Rabelais, Montaigne) place l''homme au centre et valorise l''éducation et la raison.', 'Moyen'),
    (chap_id, 'Quelle pièce de Shakespeare met en scène un prince danois confronté à la mort de son père ?', '["Macbeth","Othello","Hamlet","Le Roi Lear"]'::jsonb, 'Hamlet', 'Hamlet (1603) explore le doute, la vengeance et la mort. "To be or not to be" est sa question centrale.', 'Facile'),
    (chap_id, 'Qu''est-ce que le baroque littéraire (XVIIe s.) ?', '["Un style simple et équilibré","Un style exubérant, complexe, aux contrastes violents et aux métaphores surprenantes","Le classicisme français","Le réalisme du XVIIe siècle"]'::jsonb, 'Un style exubérant, complexe, aux contrastes violents et aux métaphores surprenantes', 'Le baroque (Góngora, Gryphius) exprime l''instabilité du monde par des formes tourmentées.', 'Moyen'),
    (chap_id, 'Quelle est la règle des trois unités dans le théâtre classique français ?', '["Unité de style, de langue et de personnages","Unité de temps (24h), de lieu (un seul) et d''action (une intrigue principale)","Unité d''auteur, de genre et de public","Unité de décors, de musique et de danse"]'::jsonb, 'Unité de temps (24h), de lieu (un seul) et d''action (une intrigue principale)', 'Le classicisme (Corneille, Racine, Molière) codifie ces règles héritées d''Aristote pour vraisemblance et bienséance.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les Lumières (XVIIIe s.) défendent en littérature ?', '["La tradition et la religion","La raison, la liberté et la critique des préjugés et de l''obscurantisme","Le retour au Moyen Âge","L''absolutisme royal"]'::jsonb, 'La raison, la liberté et la critique des préjugés et de l''obscurantisme', 'L''Encyclopédie (Diderot, d''Alembert), Voltaire, Rousseau diffusent les idées de raison et de progrès.', 'Moyen'),
    (chap_id, 'Qu''est-ce que Candide de Voltaire critique principalement ?', '["La démocratie","L''optimisme béat de Leibniz face aux malheurs du monde","La religion catholique seulement","L''esclavage uniquement"]'::jsonb, 'L''optimisme béat de Leibniz face aux malheurs du monde', 'Candide (1759) confronte "tout est pour le mieux dans le meilleur des mondes" à des catastrophes réelles (Lisbonne).', 'Moyen'),
    (chap_id, 'Quel genre littéraire philosophique des Lumières expose des idées sous forme de voyage imaginaire ?', '["Le conte philosophique","La tragédie classique","Le roman réaliste","La poésie lyrique"]'::jsonb, 'Le conte philosophique', 'Le conte philosophique (Voltaire, Swift) utilise la fiction comme vecteur de critique sociale et philosophique.', 'Moyen'),
    (chap_id, 'Qui a écrit Gulliver''s Travels, satire de la société anglaise du XVIIIe s. ?', '["Daniel Defoe","Jonathan Swift","Henry Fielding","Samuel Richardson"]'::jsonb, 'Jonathan Swift', 'Swift (1726) utilise les voyages de Gulliver pour satiriser la politique, la science et la nature humaine.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le roman épistolaire au XVIIIe siècle ?', '["Un roman historique","Un roman écrit sous forme de lettres échangées entre personnages","Un roman policier","Un roman d''apprentissage"]'::jsonb, 'Un roman écrit sous forme de lettres échangées entre personnages', 'Le roman épistolaire (Laclos : Les Liaisons dangereuses, Rousseau : La Nouvelle Héloïse) favorise la subjectivité.', 'Moyen'),
    (chap_id, 'Quelle œuvre de Rabelais met en scène des géants voyageant pour l''éducation humaniste ?', '["Les Essais","Pantagruel et Gargantua","Les Fables","L''Heptaméron"]'::jsonb, 'Pantagruel et Gargantua', 'Rabelais (1532-1535) crée une satire comique et humaniste à travers les aventures de géants géniaux.', 'Moyen'),
    (chap_id, 'Que signifie la notion de "vraisemblance" dans la poétique classique ?', '["Ce qui est vrai","Ce qui paraît crédible et acceptable au public même si fictif","Ce qui respecte l''histoire","Ce qui est scientifiquement prouvé"]'::jsonb, 'Ce qui paraît crédible et acceptable au public même si fictif', 'La vraisemblance classique exige que l''action soit crédible selon la raison et la bienséance.', 'Moyen'),
    (chap_id, 'Quel mouvement littéraire du XVIIIe s. préfigure le romantisme avec le culte de la sensibilité ?', '["Le classicisme","Le Sturm und Drang","Le réalisme","L''encyclopédisme"]'::jsonb, 'Le Sturm und Drang', 'Le Sturm und Drang (Goethe, Schiller) exalte la passion, la nature et le génie contre les normes classiques.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 20 AND titre = 'Littérature des XIXe et XXe siècles' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le romantisme littéraire (XIXe s.) valorise ?', '["La raison et l''ordre","Le moi, la nature, l''émotion, l''histoire et l''évasion contre le classicisme","La société industrielle","Le positivisme scientifique"]'::jsonb, 'Le moi, la nature, l''émotion, l''histoire et l''évasion contre le classicisme', 'Le romantisme (Hugo, Lamartine, Byron, Goethe) place le sentiment et l''individualité au-dessus de la raison.', 'Moyen'),
    (chap_id, 'Qui est l''auteur de Crime et Châtiment et des Frères Karamazov ?', '["Tolstoï","Dostoïevski","Tchékhov","Tourgueniev"]'::jsonb, 'Dostoïevski', 'Dostoïevski (1821-1881) explore la psychologie des profondeurs, la culpabilité et la rédemption.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le naturalisme littéraire (Zola) ?', '["L''idéalisation de la nature","L''application des méthodes scientifiques à la littérature pour étudier l''hérédité et le milieu","Le romantisme tardif","L''exotisme colonial"]'::jsonb, 'L''application des méthodes scientifiques à la littérature pour étudier l''hérédité et le milieu', 'Zola dans Les Rougon-Macquart applique le déterminisme biologique et social à la fiction.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le symbolisme poétique (Mallarmé, Verlaine, Rimbaud) recherche ?', '["La description objective","Suggérer les états d''âme par des symboles et les sonorités plutôt que nommer les choses","La narration réaliste","La satire sociale"]'::jsonb, 'Suggérer les états d''âme par des symboles et les sonorités plutôt que nommer les choses', 'Mallarmé : "Peindre non la chose mais l''effet qu''elle produit" — la suggestion et la musique du langage.', 'Moyen'),
    (chap_id, 'Quel roman de Kafka met en scène un homme transformé en insecte ?', '["Le Procès","La Métamorphose","Le Château","Amerika"]'::jsonb, 'La Métamorphose', 'La Métamorphose (1915) : Gregor Samsa se réveille transformé en vermine, allégorie de l''aliénation moderne.', 'Facile'),
    (chap_id, 'Qu''est-ce que le courant de conscience (stream of consciousness) dans le roman moderniste ?', '["Un résumé de l''action","La technique narrative rendant le flux ininterrompu de la pensée intérieure d''un personnage","Un monologue théâtral","La focalisation externe"]'::jsonb, 'La technique narrative rendant le flux ininterrompu de la pensée intérieure d''un personnage', 'Joyce (Ulysse), Woolf, Faulkner plongent dans la conscience sans filtre narratif traditionnel.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''absurde dans le théâtre de Beckett et Ionesco ?', '["Un théâtre comique","Un courant dramatique qui met en scène l''absurdité de la condition humaine et l''échec du langage","Le théâtre réaliste","La comédie classique"]'::jsonb, 'Un courant dramatique qui met en scène l''absurdité de la condition humaine et l''échec du langage', 'En attendant Godot, La Cantatrice chauve : personnages qui attendent sans qu''il ne se passe rien.', 'Moyen'),
    (chap_id, 'Qui a écrit À la Recherche du Temps Perdu, célèbre roman de la mémoire ?', '["Flaubert","Zola","Marcel Proust","Gide"]'::jsonb, 'Marcel Proust', 'Proust (1913-1927) explore la mémoire involontaire et le temps dans une œuvre de 7 volumes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''existentialisme de Sartre en littérature (La Nausée, Les Mouches) ?', '["L''art pour l''art","La liberté radicale, la responsabilité et l''absurde comme thèmes littéraires centraux","Le réalisme social","La tradition classique"]'::jsonb, 'La liberté radicale, la responsabilité et l''absurde comme thèmes littéraires centraux', 'Sartre unit littérature et philosophie : l''œuvre littéraire illustre la condition humaine libre et angoissée.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le réalisme magique dans la littérature latino-américaine ?', '["Le réalisme ordinaire","L''insertion d''éléments magiques dans un cadre réaliste sans que cela ne surprenne les personnages","Le réalisme socialiste","La science-fiction tropicale"]'::jsonb, 'L''insertion d''éléments magiques dans un cadre réaliste sans que cela ne surprenne les personnages', 'García Márquez (Cent Ans de Solitude), Carpentier : le magique est naturel dans la réalité latino-américaine.', 'Moyen'),
    (chap_id, 'Qui a reçu le prix Nobel de Littérature pour One Hundred Years of Solitude ?', '["Pablo Neruda","Gabriel García Márquez","Borges","Vargas Llosa"]'::jsonb, 'Gabriel García Márquez', 'García Márquez (Nobel 1982) est le maître du réalisme magique avec Cent Ans de Solitude (1967).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le nouveau roman (Robbe-Grillet, Sarraute) dans la littérature française ?', '["Le roman policier","Un courant refusant les conventions romanesques (psychologie, intrigue, chronologie linéaire)","Le roman autobiographique","Le roman historique"]'::jsonb, 'Un courant refusant les conventions romanesques (psychologie, intrigue, chronologie linéaire)', 'Le nouveau roman (années 1950-60) déconstruit le roman classique, privilégiant objets et perceptions.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la dystopie dans la littérature du XXe siècle ?', '["Une utopie réalisée","Une fiction dépeignant une société totalitaire, oppressive, en opposition à l''utopie","Un genre de science-fiction optimiste","Un roman historique"]'::jsonb, 'Une fiction dépeignant une société totalitaire, oppressive, en opposition à l''utopie', '1984 (Orwell), Le Meilleur des Mondes (Huxley), Fahrenheit 451 (Bradbury) sont des dystopies fondatrices.', 'Moyen'),
    (chap_id, 'Quel auteur russe a écrit Guerre et Paix et Anna Karénine ?', '["Dostoïevski","Tourgueniev","Léon Tolstoï","Gorki"]'::jsonb, 'Léon Tolstoï', 'Tolstoï (1828-1910) est l''un des plus grands romanciers réalistes, peignant la société russe dans son ensemble.', 'Moyen');
  END IF;
END $$;
