-- Supplement Chimie (matiere_id=10) — tous niveaux
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Structure de la matière et tableau périodique' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui a proposé le tableau périodique des éléments et en quelle année ?', '["Dalton en 1803","Dmitri Mendeleïev en 1869","Einstein en 1905","Lavoisier en 1789"]'::jsonb, 'Dmitri Mendeleïev en 1869', 'Mendeleïev a prédit l''existence d''éléments inconnus (gallium, germanium) par les lacunes dans son tableau ; ses prédictions furent confirmées.', 'Facile'),
    (chap_id, 'Qu''est-ce que le numéro atomique Z et le nombre de masse A d''un élément ?', '["Z est le nombre de neutrons, A est le nombre de protons","Z est le nombre de protons dans le noyau","Z est la masse atomique","A est le numéro de période"]'::jsonb, 'Z est le nombre de protons dans le noyau', 'Un élément est défini par Z ; ses isotopes ont même Z mais N différent (ex. ¹²C et ¹⁴C : Z=6, A=12 ou 14).', 'Facile'),
    (chap_id, 'Qu''est-ce que la configuration électronique d''un atome et comment la détermine-t-on ?', '["L''arrangement des protons","La distribution des électrons dans les","Le nombre de neutrons","La masse atomique"]'::jsonb, 'La distribution des électrons dans les', 'La configuration électronique détermine la position dans le tableau périodique et les propriétés chimiques de l''élément.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les électrons de valence et pourquoi sont-ils importants en chimie ?', '["Tous les électrons d''un atome","Les électrons de la couche externe","Les électrons du noyau","Les électrons de cœur"]'::jsonb, 'Les électrons de la couche externe', 'Les métaux alcalins (groupe 1) ont 1 électron de valence ; les halogènes (groupe 17) en ont 7 ; les gaz nobles (groupe 18) ont 8 (couche complète).', 'Moyen'),
    (chap_id, 'Quelles sont les tendances générales de l''électronégativité dans le tableau périodique ?', '["L''électronégativité augmente de droite à gauche","L''électronégativité augmente de gauche","L''électronégativité est constante","L''électronégativité augmente de haut en bas"]'::jsonb, 'L''électronégativité augmente de gauche', 'L''électronégativité (Pauling) mesure l''attirance d''un atome pour les électrons d''une liaison ; elle détermine la polarité des liaisons.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les isotopes d''un élément et en quoi diffèrent-ils ?', '["Des éléments différents","Des atomes du même élément (même Z)","Des ions de charge différente","Des composés chimiques différents"]'::jsonb, 'Des atomes du même élément (même Z)', 'Les isotopes ont des propriétés chimiques presque identiques mais des propriétés nucléaires différentes (stabilité, radioactivité).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un ion et comment se forme-t-il ?', '["Un atome neutre","Un atome ou groupe d''atomes ayant perdu","Un mélange d''éléments","Une molécule neutre"]'::jsonb, 'Un atome ou groupe d''atomes ayant perdu', 'Les ions se forment lors des réactions d''oxydoréduction et des dissociations ; ils transportent le courant électrique dans les solutions.', 'Facile'),
    (chap_id, 'Qu''est-ce que la différence entre un métal, un métalloïde et un non-métal dans le tableau périodique ?', '["Il n''y a pas de distinction","Les métaux (à gauche) sont conducteurs","Tous les éléments sont des métaux","Les non-métaux sont toujours liquides"]'::jsonb, 'Les métaux (à gauche) sont conducteurs', 'Les métalloïdes (silicium, germanium) sont la base de l''électronique moderne (semi-conducteurs, transistors, puces).', 'Facile'),
    (chap_id, 'Qu''est-ce que la règle de l''octet et ses exceptions ?', '["Tous les atomes veulent 4 électrons de valence","La tendance des atomes à acquérir une","La règle s''applique à tous les atomes sans exception","Seul le carbone suit cette règle"]'::jsonb, 'La tendance des atomes à acquérir une', 'La règle de l''octet (Lewis) explique la formation des liaisons covalentes et ioniques pour les éléments de la 2ème période.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''énergie d''ionisation et ses tendances dans le tableau périodique ?', '["L''énergie libérée lors d''une liaison","L''énergie nécessaire pour arracher un","La chaleur de combustion","L''énergie de liaison C-H"]'::jsonb, 'L''énergie nécessaire pour arracher un', 'Les métaux alcalins (Li, Na, K) ont de faibles énergies d''ionisation → facilement oxydés ; les gaz nobles ont les plus élevées.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Liaisons chimiques et propriétés des composés' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la différence entre une liaison ionique et une liaison covalente ?', '["Elles sont identiques","Liaison ionique","La liaison covalente implique des métaux","La liaison ionique forme des molécules"]'::jsonb, 'Liaison ionique', 'La différence d''électronégativité décide : ΔEN > 1,7 → ionique ; 0,4-1,7 → covalente polaire ; < 0,4 → covalente apolaire.', 'Facile'),
    (chap_id, 'Qu''est-ce que la liaison hydrogène et son importance en chimie ?', '["Une liaison covalente forte","Une liaison faible entre un H lié à un","Une liaison ionique","Une liaison métallique"]'::jsonb, 'Une liaison faible entre un H lié à un', 'Les liaisons H expliquent pourquoi l''eau est liquide à T ambiante (PE=100°C vs -60°C attendu) et la stabilité de l''ADN (bases appariées).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géométrie moléculaire selon la théorie VSEPR ?', '["Les molécules sont toujours sphériques","La forme géométrique d''une molécule est","Toutes les molécules sont linéaires","La géométrie ne dépend que des liaisons doubles"]'::jsonb, 'La forme géométrique d''une molécule est', 'VSEPR (Valence Shell Electron Pair Repulsion) : les paires se disposent pour minimiser les répulsions ; détermine les angles de liaison.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la polarité d''une molécule et quels en sont les exemples ?', '["Toutes les molécules sont polaires","Une molécule est polaire si elle","Les molécules polaires ne se dissolvent pas dans l''eau","La polarité ne dépend pas de la géométrie"]'::jsonb, 'Une molécule est polaire si elle', 'Règle «like dissolves like» : polaire (eau) dissout polaire (sel) ; apolaire (hexane) dissout apolaire (graisses).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la liaison métallique et comment explique-t-elle les propriétés des métaux ?', '["Une liaison ionique forte","Un nuage d''électrons délocalisés autour","Une liaison covalente polaire","Une liaison de Van der Waals"]'::jsonb, 'Un nuage d''électrons délocalisés autour', 'La liaison métallique (mer d''électrons de Drude) explique toutes les propriétés caractéristiques des métaux.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la structure de Lewis d''une molécule et comment la dessiner ?', '["Un diagramme des niveaux d''énergie","La représentation des liaisons et des","Un spectre d''absorption","La configuration électronique"]'::jsonb, 'La représentation des liaisons et des', 'G.N. Lewis (1916) a proposé ces structures ; elles permettent de déduire la géométrie VSEPR et la réactivité chimique.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une liaison covalente simple, double et triple et leurs caractéristiques ?', '["Toutes les liaisons sont identiques","Liaison simple (σ","Les liaisons doubles sont plus faibles que les simples","Les liaisons triples sont les plus longues"]'::jsonb, 'Liaison simple (σ', 'Ex. : N₂ (N≡N, très stable, 945 kJ/mol) vs. F₂ (F-F, 159 kJ/mol, facilement rompu) ; les liaisons π sont plus réactives que σ.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la résonance en chimie et quand s''applique-t-elle ?', '["Une vibration moléculaire","Lorsqu''une structure de Lewis unique ne","Une réaction réversible","Un type de liaison ionique"]'::jsonb, 'Lorsqu''une structure de Lewis unique ne', 'Le benzène (Kekulé, 1865) est l''exemple classique : ses 6 liaisons C-C sont équivalentes, ni simples ni doubles, grâce à la délocalistion.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les interactions de Van der Waals et leur importance ?', '["Des liaisons covalentes faibles","Les forces intermoléculaires faibles","Des liaisons ioniques","Des liaisons hydrogène renforcées"]'::jsonb, 'Les forces intermoléculaires faibles', 'Les forces de London (dispersion) existent entre toutes les molécules ; elles augmentent avec la masse molaire et la surface de contact.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Réactions chimiques et stœchiométrie' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la stœchiométrie et la mole en chimie ?', '["L''étude des propriétés des matériaux","L''étude quantitative des réactifs et","L''étude des catalyseurs","La mesure de la vitesse des réactions"]'::jsonb, 'L''étude quantitative des réactifs et', 'La stœchiométrie et la mole sont fondamentales pour calculer les quantités dans les réactions : «autant de moles d''A réagissent avec n moles de B».', 'Moyen'),
    (chap_id, 'Comment équilibre-t-on une équation chimique et quelle loi respecte-t-on ?', '["En ajoutant des éléments","En ajustant les coefficients","En changeant les formules chimiques","En ajoutant des flèches"]'::jsonb, 'En ajustant les coefficients', 'Lavoisier (1789) : «rien ne se perd, rien ne se crée, tout se transforme» ; les atomes sont conservés dans une réaction chimique.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un réactif limitant dans une réaction chimique ?', '["Le réactif le plus abondant","Le réactif qui est entièrement consommé","Le réactif le moins réactif","Le réactif dont la masse molaire est la plus grande"]'::jsonb, 'Le réactif qui est entièrement consommé', 'Identifier le réactif limitant : calculer les ratios molaires et comparer avec les coefficients stœchiométriques de l''équation.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le rendement d''une réaction et comment le calcule-t-on ?', '["Toujours 100%","η = (quantité obtenue / quantité","η = masse des réactifs / masse des produits","η = vitesse de réaction"]'::jsonb, 'η = (quantité obtenue / quantité', 'En industrie chimique, optimiser le rendement est un enjeu économique et environnemental majeur (réduction des déchets).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une réaction d''oxydoréduction (redox) et ses composants ?', '["Une réaction acide-base uniquement","Une réaction avec transfert d''électrons","Une réaction de précipitation","Une réaction uniquement inorganique"]'::jsonb, 'Une réaction avec transfert d''électrons', 'Mnémotechnique : OIL RIG = Oxidation Is Loss (of electrons), Reduction Is Gain. Les réactions redox incluent combustion, corrosion, photosynthèse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la théorie acide-base de Brønsted-Lowry ?', '["Les acides ont un goût sucré","Un acide de Brønsted-Lowry est un","Seuls les hydroxides sont des bases","Les acides sont uniquement inorganiques"]'::jsonb, 'Un acide de Brønsted-Lowry est un', 'Brønsted-Lowry (1923) étend la définition d''Arrhenius (H⁺/OH⁻ en solution) aux réactions sans eau (Lewis plus générale encore).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le pH et comment se calcule-t-il ?', '["La pression hydrostatique","pH = -log[H₃O⁺]","pH = [H₃O⁺]","pH = masse molaire / volume"]'::jsonb, 'pH = -log[H₃O⁺]', 'Le pH du sang humain est 7,35-7,45 (légèrement basique) ; un écart de ±0,2 est fatal (acidose ou alcalose).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un équilibre chimique et la constante d''équilibre K ?', '["Une réaction qui n''avance pas","L''état où les vitesses de la réaction","Une réaction complète","Une réaction sans produits"]'::jsonb, 'L''état où les vitesses de la réaction', 'L''équilibre chimique (Guldberg et Waage, 1864) est dynamique : les deux sens se poursuivent simultanément à l''équilibre.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe de Le Chatelier et comment s''applique-t-il ?', '["Les équilibres ne peuvent pas être déplacés","Si on perturbe un système à l''équilibre","L''équilibre est immuable","La température ne déplace pas l''équilibre"]'::jsonb, 'Si on perturbe un système à l''équilibre', 'Le Chatelier (1888) permet de prédire les effets des modifications sur les équilibres industriels (synthèse de l''ammoniac, Haber-Bosch).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la cinétique chimique et les facteurs influençant la vitesse de réaction ?', '["L''étude de l''énergie des réactions","L''étude de la vitesse des réactions","La stœchiométrie uniquement","L''équilibre chimique"]'::jsonb, 'L''étude de la vitesse des réactions', 'La loi d''Arrhenius (k = A·e^(-Ea/RT)) montre l''effet de la température ; les enzymes sont des biocatalyseurs abaissant l''énergie d''activation.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Chimie organique : structure et réactivité' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la chimie organique et pourquoi le carbone est-il au cœur de cette chimie ?', '["L''étude des organismes vivants uniquement","L''étude des composés du carbone","La chimie des métaux","La chimie des minéraux"]'::jsonb, 'L''étude des composés du carbone', 'Le carbone forme plus de 10 millions de composés connus ; sa capacité à former des chaînes (catenation) est unique.', 'Facile'),
    (chap_id, 'Quels sont les groupes fonctionnels principaux en chimie organique et leurs propriétés ?', '["Uniquement les alcools","Alcool (-OH)","Uniquement les acides","Uniquement les esters"]'::jsonb, 'Alcool (-OH)', 'Les groupes fonctionnels déterminent la réactivité ; une molécule peut en avoir plusieurs (ex. acides aminés : -NH₂ + -COOH).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''isomérie en chimie organique et quels en sont les types ?', '["Des molécules identiques","Des composés de même formule brute mais","Des molécules de masses différentes","Des allotropes du carbone"]'::jsonb, 'Des composés de même formule brute mais', 'La thalidomide (R = sédatif, S = tératogène) illustre l''importance dramatique de la stéréoisomérie en pharmacologie.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les réactions de substitution nucléophile (SN1/SN2) en chimie organique ?', '["Des réactions d''oxydation","Des réactions où un nucléophile (riche","Des réactions d''addition uniquement","Des réactions de polymérisation"]'::jsonb, 'Des réactions où un nucléophile (riche', 'SN2 : substrat primaire + nucléophile fort ; SN1 : substrat tertiaire + nucléophile faible, via carbocation intermédiaire.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la polymérisation et ses types principaux ?', '["La décomposition des polymères","La réaction assemblant de nombreuses","Une réaction de combustion","Une réaction d''hydrolyse"]'::jsonb, 'La réaction assemblant de nombreuses', 'Les polymères sont omniprésents : plastiques (PE, PP, PVC), fibres synthétiques (Nylon, Dacron), caoutchouc, biopolymères (ADN, protéines).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la nomenclature IUPAC des composés organiques et ses règles de base ?', '["Un système arbitraire","Un système international basant le nom","Le nom vulgaire des composés","Un système uniquement français"]'::jsonb, 'Un système international basant le nom', 'IUPAC : méth(1C)-éth(2C)-prop(3C)-but(4C)-pent(5C)-hex(6C) + suffixe selon fonction (-ane,-ène,-anol,-al,-one,-anoïque,-anoate).', 'Moyen'),
    (chap_id, 'Qu''est-ce que les hydrocarbures aromatiques (benzène et dérivés) et leurs propriétés ?', '["Des composés aliphatiques","Des composés cycliques insaturés","Des alcanes cycliques","Des polymères naturels"]'::jsonb, 'Des composés cycliques insaturés', 'L''aromaticité (critère de Hückel : 4n+2 électrons π) confère stabilité exceptionnelle ; le benzène est cancérigène avéré.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les lipides en chimie organique et leur structure ?', '["Des glucides","Des biomolécules hydrophobes incluant","Des protéines non polaires","Des acides nucléiques"]'::jsonb, 'Des biomolécules hydrophobes incluant', 'La saponification (hydrolyse basique des triglycérides) produit du savon et du glycérol ; connue depuis l''Antiquité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les glucides (saccharides) et leur structure en chimie organique ?', '["Des lipides","Des biomolécules de formule générale","Des acides aminés","Des nucléotides"]'::jsonb, 'Des biomolécules de formule générale', 'Le glucose (C₆H₁₂O₆) est la principale source d''énergie cellulaire ; la cellulose (même formule que l''amidon, liaison β-1,4) est indigeste.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la chimie verte (chimie durable) et ses 12 principes ?', '["La chimie des plantes vertes","La philosophie de conception chimique","La chimie uniquement biologique","La chimie des pesticides"]'::jsonb, 'La philosophie de conception chimique', 'Les 12 principes de la chimie verte (Anastas & Warner, 1998) guident l''industrie chimique vers la durabilité et la prévention de la pollution.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 10 AND titre = 'Électrochimie et applications' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''une pile électrochimique et comment produit-elle de l''électricité ?', '["Un condensateur","Un dispositif transformant l''énergie","Un transformateur","Un générateur mécanique"]'::jsonb, 'Un dispositif transformant l''énergie', 'La pile de Volta (1800) est la première pile électrochimique ; les piles modernes (lithium-ion) fonctionnent sur le même principe.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''électrolyse et comment diffère-t-elle d''une pile galvanique ?', '["L''électrolyse est spontanée","L''électrolyse utilise de l''électricité","L''électrolyse produit de l''électricité","L''électrolyse et la pile sont identiques"]'::jsonb, 'L''électrolyse utilise de l''électricité', 'La production d''aluminium (Hall-Héroult) et de chlore (électrolyse de NaCl) sont des procédés industriels majeurs par électrolyse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la corrosion et comment la prévenir ?', '["Un processus bénéfique","La dégradation électrochimique d''un","Un simple ternissement","Une réaction de combustion"]'::jsonb, 'La dégradation électrochimique d''un', 'La corrosion coûte ~3,4% du PIB mondial annuellement ; en Haïti, le climat tropical humide et salin accélère la rouille des infrastructures.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la force électromotrice (FEM) d''une pile et comment la calculer ?', '["La résistance interne","E = E°_cathode - E°_anode","La charge de la pile","L''intensité du courant"]'::jsonb, 'E = E°_cathode - E°_anode', 'La FEM (Volta) mesure la «pression» électrique de la pile ; E°(Zn²⁺/Zn) = -0,76 V vs SHE (électrode de référence).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une batterie lithium-ion et pourquoi domine-t-elle dans les appareils portables ?', '["Une pile zinc-carbone améliorée","Une batterie rechargeable où les ions","Une batterie au plomb","Une batterie à combustible"]'::jsonb, 'Une batterie rechargeable où les ions', 'Goodenough, Whittingham et Yoshino (Nobel 2019) ont développé les batteries Li-ion ; elles équipent smartphones, laptops et véhicules électriques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les lois de Faraday en électrolyse ?', '["Des lois de la thermodynamique","1ère","Les lois d''Ohm généralisées","Les lois de Newton appliquées aux ions"]'::jsonb, '1ère', 'F = 96 485 C/mol (constante de Faraday) = charge d''une mole d''électrons ; les lois de Faraday sont fondamentales pour l''industrie électrolytique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les piles à combustible et leur potentiel pour l''énergie propre ?', '["Des batteries rechargeables classiques","Des dispositifs électrochimiques","Des moteurs à explosion améliorés","Des panneaux solaires"]'::jsonb, 'Des dispositifs électrochimiques', 'Les piles à combustible à H₂ (Toyota Mirai, bus à hydrogène) ont un rendement ~60% vs ~25-30% pour les moteurs thermiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la photochimie et l''effet photovoltaïque en chimie ?', '["Un type de chromographie","L''étude des réactions déclenchées par","Un type d''électrolyse","Un procédé de synthèse thermique"]'::jsonb, 'L''étude des réactions déclenchées par', 'Les cellules photovoltaïques (rendement ~15-22%) sont une source d''énergie prometteuse pour Haïti (fort ensoleillement caribéen).', 'Moyen'),
    (chap_id, 'Comment la chimie contribue-t-elle à la sécurité alimentaire et à l''agriculture en Haïti ?', '["La chimie n''a aucun rôle en agriculture","La chimie fournit les engrais minéraux","Uniquement les pesticides","Uniquement les engrais chimiques"]'::jsonb, 'La chimie fournit les engrais minéraux', 'La révolution verte (Borlaug) a multiplié les rendements via N-P-K et OGM ; les alternatives agro-écologiques sont essentielles dans les pays à faibles intrants.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la spectroscopie et son utilisation en chimie analytique ?', '["Une technique de séparation","L''ensemble des techniques d''analyse","Une méthode de synthèse","Une technique de filtration"]'::jsonb, 'L''ensemble des techniques d''analyse', 'La RMN (IRM médicale), la spectrométrie de masse (protéomique), l''IR (identification fonctionnels) sont les outils analytiques de référence.', 'Moyen');
  END IF;
END $$;
