-- Supplement Histoire-Géographie (matiere_id=13) — NS1 et NS2
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 13 AND titre = 'Civilisations antiques et premières grandes cités' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Entre quels fleuves la Mésopotamie, considérée comme un berceau de la civilisation, est-elle située ?', '["Nil et Congo","Tigre et Euphrate","Indus et Gange","Huang He et Yangtsé"]'::jsonb, 'Tigre et Euphrate', 'La Mésopotamie (actuel Irak) = «pays entre les fleuves» ; Sumer, Akkad, Babylone y ont développé écriture et droit.', 'Facile'),
    (chap_id, 'Quelle est l''une des premières formes d''écriture connue de l''humanité et dans quelle civilisation est-elle apparue ?', '["L''alphabet latin","Le cunéiforme (écriture à coins) apparu à Sumer vers 3500 av. J.-C., utilisé pour les comptes administratifs","Les hiéroglyphes égyptiens","L''alphabet grec"]'::jsonb, 'Le cunéiforme (écriture à coins) apparu à Sumer vers 3500 av. J.-C., utilisé pour les comptes administratifs', 'Le cunéiforme et les hiéroglyphes égyptiens sont parmi les premières écritures ; elles sont nées des besoins comptables.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le Code d''Hammurabi et quelle est son importance historique ?', '["Un texte religieux","Un ensemble de 282 lois gravées sur une stèle babylonienne (~1750 av. J.-C.), l''un des premiers codes juridiques écrits de l''histoire","Un traité commercial","Un récit mythologique"]'::jsonb, 'Un ensemble de 282 lois gravées sur une stèle babylonienne (~1750 av. J.-C.), l''un des premiers codes juridiques écrits de l''histoire', 'Le Code d''Hammurabi consacre le principe de lex talionis («œil pour œil») et protège les plus faibles selon leur statut social.', 'Moyen'),
    (chap_id, 'Quel est le rôle du Nil dans la civilisation égyptienne antique ?', '["Un obstacle à la civilisation","La source de fertilité des terres grâce à ses crues annuelles déposant du limon, permettant l''agriculture intensive qui nourrissait une grande population et permettait de construire les pyramides","Une frontière uniquement","Un moyen de défense"]'::jsonb, 'La source de fertilité des terres grâce à ses crues annuelles déposant du limon, permettant l''agriculture intensive qui nourrissait une grande population et permettait de construire les pyramides', 'Hérodote disait : «L''Égypte est un don du Nil» ; les crues prévisibles ont structuré le calendrier et la vie sociale égyptienne.', 'Facile'),
    (chap_id, 'Quelle est la signification historique des pyramides de Gizeh ?', '["Des greniers à céréales","Des tombeaux monumentaux des pharaons (Khéops, Khéphren, Mykérinos), manifestations de la puissance divine du pharaon et du développement de l''État centralisé égyptien","Des observatoires astronomiques","Des fortifications militaires"]'::jsonb, 'Des tombeaux monumentaux des pharaons (Khéops, Khéphren, Mykérinos), manifestations de la puissance divine du pharaon et du développement de l''État centralisé égyptien', 'Les pyramides (~2570-2500 av. J.-C.) témoignent de l''organisation centralisée de l''État, de la main-d''œuvre et de la maîtrise technique.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la démocratie athénienne du Ve siècle av. J.-C. et quelles en étaient les limites ?', '["Une démocratie universelle","Un système où les citoyens libres mâles adultes participaient directement aux décisions ; en excluant les femmes, les esclaves (~1/3 de la pop.) et les étrangers","Un régime aristocratique","Une monarchie éclairée"]'::jsonb, 'Un système où les citoyens libres mâles adultes participaient directement aux décisions ; en excluant les femmes, les esclaves (~1/3 de la pop.) et les étrangers', 'La démocratie d''Athènes (Périclès, Ve s.) est la matrice de la démocratie moderne mais exclut la majorité de la population.', 'Moyen'),
    (chap_id, 'Comment Alexandre le Grand a-t-il transformé le monde méditerranéen entre 336 et 323 av. J.-C. ?', '["Il a unifié l''Europe","En conquérant un empire s''étendant de la Grèce à l''Inde, diffusant la culture grecque (hellénisme) et créant une civilisation syncrétique gréco-orientale","Il a fondé Rome","Il a colonisé l''Afrique"]'::jsonb, 'En conquérant un empire s''étendant de la Grèce à l''Inde, diffusant la culture grecque (hellénisme) et créant une civilisation syncrétique gréco-orientale', 'L''Empire d''Alexandre (323 av. J.-C.) a hellénisé le Proche-Orient ; la Koiné grecque est devenue la lingua franca.', 'Moyen'),
    (chap_id, 'Quelles sont les principales contributions de la civilisation romaine à l''Europe et au monde occidental ?', '["Uniquement militaires","Le droit romain (base des systèmes juridiques modernes), le latin (ancêtre des langues romanes), l''architecture, le réseau routier, le christianisme comme religion d''État","Uniquement artistiques","Uniquement architecturales"]'::jsonb, 'Le droit romain (base des systèmes juridiques modernes), le latin (ancêtre des langues romanes), l''architecture, le réseau routier, le christianisme comme religion d''État', 'Roma aeterna : le droit romain (Digeste), le latin (→ français, espagnol), le droit canonique ont façonné l''Occident.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la civilisation maya et où s''était-elle développée ?', '["En Amérique du Nord","En Mésoamérique (Guatemala, Mexique, Belize, Honduras), développant une écriture hiéroglyphique, un calendrier astronomique précis, les mathématiques (zéro) et des cités-états monumentales","En Amérique du Sud","En Amérique du Nord-Est"]'::jsonb, 'En Mésoamérique (Guatemala, Mexique, Belize, Honduras), développant une écriture hiéroglyphique, un calendrier astronomique précis, les mathématiques (zéro) et des cités-états monumentales', 'Les Mayas (2000 av. J.-C.-1500 ap. J.-C.) ont inventé le zéro indépendamment et possédaient une astronomie sophistiquée.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les premiers habitants d''Haïti (les Taïnos) et quelle était leur civilisation ?', '["Des Africains","Des Amérindiens (sous-groupe Arawak) habitant Hispaniola avant Colomb, organisés en cacicats, pratiquant l''agriculture (manioc, maïs) et une riche vie spirituelle, quasi décimés après 1492","Des Européens pré-colombiens","Des Asiatiques"]'::jsonb, 'Des Amérindiens (sous-groupe Arawak) habitant Hispaniola avant Colomb, organisés en cacicats, pratiquant l''agriculture (manioc, maïs) et une riche vie spirituelle, quasi décimés après 1492', 'La population taïno d''Hispaniola (>500 000 en 1492) a été décimée en moins de 50 ans par maladies, esclavage et violence.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la Route de la Soie et son importance dans l''histoire des échanges ?', '["Un itinéraire exclusivement maritime","Un réseau de routes commerciales reliant la Chine à la Méditerranée (Ier s. av. J.-C. - XVe s. ap. J.-C.), véhiculant soieries, épices mais aussi idées, religions et techniques","Une route militaire romaine","Une route africaine uniquement"]'::jsonb, 'Un réseau de routes commerciales reliant la Chine à la Méditerranée (Ier s. av. J.-C. - XVe s. ap. J.-C.), véhiculant soieries, épices mais aussi idées, religions et techniques', 'La Route de la Soie a véhiculé le bouddhisme, l''islam, la peste noire et les technologies (papier, poudre à canon).', 'Moyen'),
    (chap_id, 'Quel fut le rôle de Constantinople (Byzance) comme carrefour entre Orient et Occident ?', '["Une ville secondaire","La capitale de l''Empire byzantin (330-1453), carrefour commercial et culturel entre Europe et Asie, gardienne de la culture grecque et chrétienne orientale jusqu''à la conquête ottomane","Une cité phénicienne","Une colonie romaine mineure"]'::jsonb, 'La capitale de l''Empire byzantin (330-1453), carrefour commercial et culturel entre Europe et Asie, gardienne de la culture grecque et chrétienne orientale jusqu''à la conquête ottomane', 'Constantinople (Istanbul) contrôlait le Bosphore, clé du commerce entre Méditerranée et mer Noire.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 13 AND titre = 'Révolutions et transformations du monde moderne (XVe-XVIIIe siècle)' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle date marque le «premier voyage» de Christophe Colomb en Amérique et quelle en a été la conséquence pour Haïti ?', '["1415","1492, avec l''arrivée à Hispaniola (actuelle Haïti-RD) le 5 décembre, début de la colonisation espagnole et du génocide taïno","1519","1607"]'::jsonb, '1492, avec l''arrivée à Hispaniola (actuelle Haïti-RD) le 5 décembre, début de la colonisation espagnole et du génocide taïno', 'Colomb est arrivé à Hispaniola en décembre 1492 ; il a fondé La Navidad, premier établissement européen en Amérique.', 'Facile'),
    (chap_id, 'Qu''est-ce que la traite négrière transatlantique et quel fut son impact sur Haïti ?', '["Un commerce de marchandises","Le commerce d''esclaves africains vers les Amériques (XVIe-XIXe s.) ; Saint-Domingue (Haïti) a reçu ~800 000 à 1 million d''Africains, devenant la colonie esclavagiste la plus productive du monde","Un échange culturel","Une migration volontaire"]'::jsonb, 'Le commerce d''esclaves africains vers les Amériques (XVIe-XIXe s.) ; Saint-Domingue (Haïti) a reçu ~800 000 à 1 million d''Africains, devenant la colonie esclavagiste la plus productive du monde', 'À la veille de 1789, Saint-Domingue produisait 40% du sucre et 60% du café mondiaux avec une main-d''œuvre esclave.', 'Moyen'),
    (chap_id, 'Quelle est la signification de la Révolution américaine (1775-1783) dans l''histoire mondiale ?', '["Un conflit purement local","La première révolution des colonies contre une métropole européenne, instaurant la première démocratie constitutionnelle moderne, et inspirant les révolutions française et haïtienne","Une guerre civile anglaise","Un conflit commercial mineur"]'::jsonb, 'La première révolution des colonies contre une métropole européenne, instaurant la première démocratie constitutionnelle moderne, et inspirant les révolutions française et haïtienne', 'La Déclaration d''Indépendance (1776) avec «tous les hommes sont créés égaux» a directement inspiré la révolution haïtienne.', 'Moyen'),
    (chap_id, 'Quelles sont les causes et les principales phases de la Révolution française (1789) ?', '["Uniquement une querelle dynastique","Les inégalités fiscales et sociales de l''Ancien Régime, la crise financière et les Lumières ont déclenché la Révolution ; phases : Monarchie constitutionnelle, Convention (Terreur), Directoire, Empire","Un coup d''État militaire simple","Une révolution purement économique"]'::jsonb, 'Les inégalités fiscales et sociales de l''Ancien Régime, la crise financière et les Lumières ont déclenché la Révolution ; phases : Monarchie constitutionnelle, Convention (Terreur), Directoire, Empire', 'La Révolution française (1789-1799) a produit la DDHC (1789) qui a servi de référence pour la Constitution haïtienne de 1801.', 'Moyen'),
    (chap_id, 'Quel est le rôle de Toussaint Louverture dans la révolution haïtienne ?', '["Un planteur français","L''ex-esclave devenu chef militaire exceptionnel qui a réuni les esclaves, vaincu les armées espagnole, anglaise et française, et rédigé la première Constitution haïtienne (1801) qui abolissait l''esclavage","Un gouverneur colonial","Un révolutionnaire français"]'::jsonb, 'L''ex-esclave devenu chef militaire exceptionnel qui a réuni les esclaves, vaincu les armées espagnole, anglaise et française, et rédigé la première Constitution haïtienne (1801) qui abolissait l''esclavage', 'Toussaint (1743-1803) est capturé par la France en 1802 et meurt au Fort de Joux ; il est le «Précurseur» de l''indépendance.', 'Moyen'),
    (chap_id, 'Quelle est la signification de la Bataille de Vertières (18 novembre 1803) dans l''histoire haïtienne ?', '["Une défaite haïtienne","La dernière grande bataille de la révolution haïtienne, où les forces de Jean-Jacques Dessalines ont vaincu l''armée napoléonienne, ouvrant la voie à l''indépendance","Une bataille contre l''Espagne","Une rébellion interne"]'::jsonb, 'La dernière grande bataille de la révolution haïtienne, où les forces de Jean-Jacques Dessalines ont vaincu l''armée napoléonienne, ouvrant la voie à l''indépendance', 'À Vertières (Cap-Haïtien), François Capois «La Mort» et Dessalines ont battu Rochambeau ; l''indépendance fut proclamée le 1er janvier 1804.', 'Facile'),
    (chap_id, 'Pourquoi la révolution haïtienne de 1804 est-elle unique dans l''histoire mondiale ?', '["Elle n''est pas unique","C''est la seule révolution d''esclaves réussie de l''histoire ayant abouti à la création d''un État indépendant (première République noire du monde et deuxième des Amériques)","Elle a été aidée par les États-Unis","Elle était pacifique"]'::jsonb, 'C''est la seule révolution d''esclaves réussie de l''histoire ayant abouti à la création d''un État indépendant (première République noire du monde et deuxième des Amériques)', 'Haïti 1804 a bouleversé l''ordre mondial esclavagiste et terrorisé les puissances coloniales ; elle a inspiré les luttes pour la liberté mondiale.', 'Facile'),
    (chap_id, 'Qu''est-ce que la Révolution industrielle (XVIIIe-XIXe siècle) et où a-t-elle débuté ?', '["Une révolution agricole","La transformation économique débutée en Angleterre basée sur la mécanisation (machine à vapeur de Watt), la production en usine, l''exploitation du charbon et de l''acier","Une révolution politique","Une révolution française"]'::jsonb, 'La transformation économique débutée en Angleterre basée sur la mécanisation (machine à vapeur de Watt), la production en usine, l''exploitation du charbon et de l''acier', 'La Révolution industrielle anglaise (1760-1840) a transformé les sociétés : urbanisation, prolétariat, capitalisme industriel.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le colonialisme européen du XIXe siècle et ses justifications idéologiques ?', '["Un processus bénéfique","L''expansion territoriale des puissances européennes en Afrique et en Asie, justifiée par la «mission civilisatrice», le racisme scientifique et les intérêts économiques (matières premières, marchés)","Un échange équitable","Un phénomène limité à l''Asie"]'::jsonb, 'L''expansion territoriale des puissances européennes en Afrique et en Asie, justifiée par la «mission civilisatrice», le racisme scientifique et les intérêts économiques (matières premières, marchés)', 'La Conférence de Berlin (1884-85) a partagé l''Afrique entre puissances européennes sans consulter les Africains.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la dette de l''indépendance haïtienne de 1825 et ses conséquences à long terme ?', '["Un don français","Le paiement imposé par la France à Haïti (150 millions de francs-or) pour reconnaître l''indépendance, remboursé jusqu''en 1947, qui a appauvri le pays pendant plus d''un siècle","Une aide internationale","Un emprunt haïtien volontaire"]'::jsonb, 'Le paiement imposé par la France à Haïti (150 millions de francs-or) pour reconnaître l''indépendance, remboursé jusqu''en 1947, qui a appauvri le pays pendant plus d''un siècle', 'Cette dette (environ 21 milliards $ en valeur actuelle) a saigné l''économie haïtienne et structurellement entravé son développement.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les guerres napoléoniennes et leur impact sur l''Europe et le monde ?', '["Des conflits mineurs","Les guerres menées par Napoléon Bonaparte (1803-1815) qui ont reconfiguré la carte de l''Europe, diffusé les principes révolutionnaires français (Code civil) et déclenché des nationalismes dans les territoires occupés","Des révolutions populaires","Des guerres de religion"]'::jsonb, 'Les guerres menées par Napoléon Bonaparte (1803-1815) qui ont reconfiguré la carte de l''Europe, diffusé les principes révolutionnaires français (Code civil) et déclenché des nationalismes dans les territoires occupés', 'Le Code Napoléon (1804) a influencé le droit de nombreux pays dont Haïti ; Waterloo (1815) a mis fin à l''Empire.', 'Moyen');
  END IF;
END $$;
