-- Supplement Informatique NS3-NS4 (matiere_id=17)
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Algorithmique avancée : complexité et paradigmes' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Que signifie la notation O(n log n) pour un algorithme ?', '["Linéaire","Quasi-linéaire","Quadratique","Constante"]'::jsonb, 'Quasi-linéaire', 'O(n log n) est quasi-linéaire, typique des algorithmes de tri efficaces comme MergeSort.', 'Moyen'),
    (chap_id, 'Quel paradigme décompose un problème en sous-problèmes indépendants résolus récursivement ?', '["Programmation dynamique","Diviser pour régner","Algorithmes gloutons","Backtracking"]'::jsonb, 'Diviser pour régner', 'Diviser pour régner (divide and conquer) divise, résout récursivement, puis combine les résultats.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la programmation dynamique ?', '["Un langage dynamique","Mémoriser les résultats de","Compiler le code à la volée","Une technique de parallélisme"]'::jsonb, 'Mémoriser les résultats de', 'La programmation dynamique utilise la mémoïsation ou la tabulation pour optimiser les récurrences.', 'Difficile'),
    (chap_id, 'Quelle est la complexité du tri fusion (MergeSort) ?', '["O(n)","O(n log n)","O(n²)","O(log n)"]'::jsonb, 'O(n log n)', 'MergeSort divise le tableau en deux moitiés récursivement et fusionne en O(n), total O(n log n).', 'Moyen'),
    (chap_id, 'Quel algorithme résout le problème du plus court chemin dans un graphe pondéré ?', '["BFS","DFS","Dijkstra","Kruskal"]'::jsonb, 'Dijkstra', 'L''algorithme de Dijkstra trouve les chemins les plus courts depuis un sommet source vers tous les autres.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un algorithme glouton (greedy) ?', '["Un algorithme qui teste toutes les solutions","Un algorithme faisant le meilleur choix","Un algorithme récursif sans mémoïsation","Un algorithme de tri parallèle"]'::jsonb, 'Un algorithme faisant le meilleur choix', 'Les algorithmes gloutons choisissent localement l''option optimale sans revenir en arrière.', 'Moyen'),
    (chap_id, 'Quelle classe de problèmes NP-complets est symbolisée par le problème du voyageur de commerce ?', '["P","NP","NP-complet","PSPACE"]'::jsonb, 'NP-complet', 'Le TSP est NP-complet : aucun algorithme polynomial n''est connu pour toutes ses instances.', 'Difficile'),
    (chap_id, 'Quelle est la complexité de la recherche binaire dans un tableau trié de n éléments ?', '["O(1)","O(log n)","O(n)","O(n²)"]'::jsonb, 'O(log n)', 'La recherche binaire divise l''espace de recherche par deux à chaque étape, d''où O(log n).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le backtracking ?', '["Un algorithme de tri","Une technique qui explore des chemins","Un type de récursion terminale","Un algorithme de compression"]'::jsonb, 'Une technique qui explore des chemins', 'Le backtracking explore l''arbre des solutions et abandonne les branches qui ne peuvent mener à une solution.', 'Moyen'),
    (chap_id, 'Quelle structure de données est utilisée dans l''algorithme BFS (Breadth-First Search) ?', '["Pile","File (queue)","Tableau trié","Arbre AVL"]'::jsonb, 'File (queue)', 'BFS utilise une file pour explorer les sommets niveau par niveau, garantissant le plus court chemin non pondéré.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre memoization et tabulation en programmation dynamique ?', '["Aucune","Mémoïsation = top-down (récursif)","Tabulation est plus récente","Mémoïsation ne marche qu''avec les arbres"]'::jsonb, 'Mémoïsation = top-down (récursif)', 'Les deux évitent les calculs redondants ; la mémoïsation part du problème principal vers les cas de base.', 'Difficile'),
    (chap_id, 'Quelle condition doit être satisfaite pour appliquer un algorithme glouton avec succès ?', '["La taille du problème est petite","Le problème possède une propriété de","Le problème est NP-complet","Les données sont triées"]'::jsonb, 'Le problème possède une propriété de', 'Un algorithme glouton est correct seulement si le choix local optimal mène toujours à la solution globale.', 'Difficile'),
    (chap_id, 'Quel algorithme calcule l''arbre couvrant minimal d''un graphe pondéré ?', '["Dijkstra","Bellman-Ford","Prim ou Kruskal","Floyd-Warshall"]'::jsonb, 'Prim ou Kruskal', 'Prim et Kruskal construisent l''arbre couvrant de poids minimal par des stratégies gloutonnes.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la récursion terminale (tail recursion) ?', '["Une récursion sans cas de base","Une récursion où l''appel récursif est","Une récursion indirecte","Une récursion avec mémoïsation"]'::jsonb, 'Une récursion où l''appel récursif est', 'La récursion terminale peut être optimisée par le compilateur pour éviter l''empilement des appels.', 'Difficile'),
    (chap_id, 'Quelle est la complexité en espace de l''algorithme DFS récursif sur un graphe de n sommets et m arêtes ?', '["O(1)","O(n)","O(m)","O(n+m)"]'::jsonb, 'O(n)', 'DFS utilise une pile d''appels dont la profondeur peut atteindre n sommets dans le pire cas.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Cybersécurité et cryptographie' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel type de cryptographie utilise une paire de clés publique/privée ?', '["Cryptographie symétrique","Cryptographie asymétrique","Cryptographie par substitution","Chiffrement par flot"]'::jsonb, 'Cryptographie asymétrique', 'La cryptographie asymétrique (RSA, ECC) utilise une clé publique pour chiffrer et privée pour déchiffrer.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une fonction de hachage cryptographique ?', '["Une fonction réversible","Une fonction qui transforme des données","Une méthode de chiffrement symétrique","Un protocole réseau"]'::jsonb, 'Une fonction qui transforme des données', 'SHA-256 produit une empreinte de 256 bits ; toute modification des données change l''empreinte.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une attaque par force brute ?', '["Une attaque exploitant une vulnérabilité logicielle","Tester toutes les combinaisons","Une attaque de déni de service","Un phishing ciblé"]'::jsonb, 'Tester toutes les combinaisons', 'La force brute essaie systématiquement toutes les valeurs ; son efficacité dépend de la taille de l''espace de recherche.', 'Facile'),
    (chap_id, 'Que signifie SSL/TLS dans la sécurité web ?', '["Standard Security Layer / Transport Layer Security","Secure Sockets Layer / Transport Layer","System Security Login / Token Layer Service","Secured Server Link / Transport Link Security"]'::jsonb, 'Secure Sockets Layer / Transport Layer', 'TLS (successeur de SSL) chiffre les communications entre navigateur et serveur via HTTPS.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''authentification à deux facteurs (2FA) ?', '["Un double mot de passe","Combiner un secret connu + un facteur","Deux serveurs d''authentification","Un certificat numérique double"]'::jsonb, 'Combiner un secret connu + un facteur', 'Le 2FA exige mot de passe + SMS/application OTP ou empreinte, limitant les accès non autorisés.', 'Facile'),
    (chap_id, 'Quelle attaque intercepte les communications entre deux parties à leur insu ?', '["Phishing","Man-in-the-Middle (MitM)","DDoS","Ransomware"]'::jsonb, 'Man-in-the-Middle (MitM)', 'Dans une attaque MitM, l''attaquant se positionne entre deux parties pour intercepter ou modifier les échanges.', 'Moyen'),
    (chap_id, 'Quel algorithme de chiffrement symétrique est standard depuis 2001 ?', '["DES","3DES","AES","RSA"]'::jsonb, 'AES', 'AES (Advanced Encryption Standard) avec des clés de 128, 192 ou 256 bits est le standard mondial de chiffrement symétrique.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un certificat numérique X.509 ?', '["Un mot de passe haché","Un document électronique liant une clé","Un type de pare-feu","Un algorithme de signature"]'::jsonb, 'Un document électronique liant une clé', 'Le certificat X.509 permet d''établir la confiance dans une clé publique via la signature d''une CA.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une vulnérabilité zero-day ?', '["Une attaque très lente","Une faille non encore connue du vendeur","Un virus de type ransomware","Une attaque par déni de service"]'::jsonb, 'Une faille non encore connue du vendeur', 'Les zero-days sont très dangereuses car aucun patch n''existe jusqu''à leur divulgation.', 'Difficile'),
    (chap_id, 'Quel principe de sécurité recommande de n''accorder que les droits strictement nécessaires ?', '["Défense en profondeur","Principe du moindre privilège","Séparation des tâches","Sécurité par obscurité"]'::jsonb, 'Principe du moindre privilège', 'Le moindre privilège limite l''impact d''une compromission en restreignant les accès au minimum nécessaire.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le chiffrement de bout en bout (E2EE) ?', '["Le chiffrement des données sur le disque","Seuls les utilisateurs communiquant","Le chiffrement du trafic réseau","Le chiffrement des mots de passe en base de données"]'::jsonb, 'Seuls les utilisateurs communiquant', 'E2EE garantit que même le fournisseur de service ne peut déchiffrer les communications.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un pare-feu (firewall) ?', '["Un antivirus","Un système qui filtre le trafic réseau","Un protocole de chiffrement","Un type de VPN"]'::jsonb, 'Un système qui filtre le trafic réseau', 'Le pare-feu analyse les paquets entrants et sortants et applique des règles d''autorisation ou de blocage.', 'Facile'),
    (chap_id, 'Quelle technique cryptographique permet à deux parties d''échanger une clé secrète sur un canal non sécurisé ?', '["RSA","Diffie-Hellman","AES","MD5"]'::jsonb, 'Diffie-Hellman', 'L''échange Diffie-Hellman permet de dériver un secret partagé sans jamais le transmettre directement.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un audit de sécurité (pentest) ?', '["Une attaque réelle contre un système","Un test autorisé simulant des attaques","Un logiciel antivirus","Un protocole réseau de sécurité"]'::jsonb, 'Un test autorisé simulant des attaques', 'Un pentest (test de pénétration) est réalisé par des experts mandatés pour évaluer la sécurité d''un système.', 'Moyen'),
    (chap_id, 'Quelle propriété garantit qu''un message n''a pas été altéré pendant la transmission ?', '["Confidentialité","Authenticité","Intégrité","Non-répudiation"]'::jsonb, 'Intégrité', 'L''intégrité assure que les données reçues sont identiques à celles envoyées, grâce aux hachages.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Systèmes d''information et bases de données avancées' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce qu''un système d''information (SI) ?', '["Un ordinateur unique","L''ensemble des ressources","Un logiciel de comptabilité","Un réseau d''entreprise"]'::jsonb, 'L''ensemble des ressources', 'Un SI inclut les personnes, processus, données et technologies qui collectent et distribuent l''information.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une procédure stockée (stored procedure) en SQL ?', '["Un fichier SQL externe","Un bloc de code SQL précompilé stocké","Un type d''index","Un déclencheur automatique"]'::jsonb, 'Un bloc de code SQL précompilé stocké', 'Les procédures stockées améliorent la performance et la sécurité en regroupant la logique côté serveur.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un trigger (déclencheur) SQL ?', '["Une procédure stockée","Un bloc de code exécuté automatiquement","Une contrainte d''intégrité","Un type de JOIN"]'::jsonb, 'Un bloc de code exécuté automatiquement', 'Un trigger se déclenche automatiquement sur INSERT, UPDATE ou DELETE pour maintenir la cohérence.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la réplication de base de données ?', '["Sauvegarder une BDD sur CD","Maintenir des copies synchronisées","Dupliquer des tables dans la même BDD","Exporter des données en CSV"]'::jsonb, 'Maintenir des copies synchronisées', 'La réplication améliore la disponibilité et la tolérance aux pannes en distribuant les données.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un entrepôt de données (data warehouse) ?', '["Une BDD transactionnelle","Un système optimisé pour l''analyse et","Un serveur de fichiers","Un cloud public"]'::jsonb, 'Un système optimisé pour l''analyse et', 'Un data warehouse centralise les données de plusieurs sources pour les analyses décisionnelles (BI).', 'Difficile'),
    (chap_id, 'Quelle est la forme normale qui élimine les dépendances transitives ?', '["1NF","2NF","3NF","BCNF"]'::jsonb, '3NF', 'La 3NF (troisième forme normale) élimine les dépendances entre attributs non-clés.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le sharding dans les bases de données ?', '["Un type de chiffrement","La partition horizontale des données","Une technique de sauvegarde","Un type d''index"]'::jsonb, 'La partition horizontale des données', 'Le sharding distribue les enregistrements d''une table sur plusieurs serveurs pour gérer les grandes volumétries.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une vue (VIEW) SQL ?', '["Une table temporaire","Une requête SELECT sauvegardée comme","Un type d''index","Une procédure stockée"]'::jsonb, 'Une requête SELECT sauvegardée comme', 'Une vue simplifie les requêtes complexes et peut restreindre l''accès à certaines colonnes.', 'Moyen'),
    (chap_id, 'Quel modèle NoSQL organise les données en documents JSON/BSON ?', '["Clé-valeur","Colonne","Document","Graphe"]'::jsonb, 'Document', 'Les BDD documentaires (MongoDB, CouchDB) stockent des documents JSON flexibles sans schéma fixe.', 'Moyen'),
    (chap_id, 'Qu''est-ce que CAP théorème dans les systèmes distribués ?', '["Un algorithme de tri","Un théorème affirmant qu''on ne peut","Un protocole de sécurité","Un modèle de données"]'::jsonb, 'Un théorème affirmant qu''on ne peut', 'Le théorème CAP (Brewer) impose un compromis entre ces trois propriétés dans les systèmes distribués.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''ORM (Object-Relational Mapping) ?', '["Un protocole réseau","Une technique mappant les objets du","Un type de cache","Un algorithme de compression"]'::jsonb, 'Une technique mappant les objets du', 'L''ORM (SQLAlchemy, Hibernate) génère automatiquement le SQL à partir des objets du langage cible.', 'Moyen'),
    (chap_id, 'Quelle propriété SQL garantit qu''une transaction laisse la BDD dans un état valide ?', '["Atomicité","Cohérence","Isolation","Durabilité"]'::jsonb, 'Cohérence', 'La cohérence garantit que toutes les contraintes d''intégrité sont respectées avant et après la transaction.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le Big Data et quelles sont ses caractéristiques (3V) ?', '["Données très volumineuses uniquement","Volume, Vélocité, Variété","Données chiffrées distribuées","Bases de données relationnelles massives"]'::jsonb, 'Volume, Vélocité, Variété', 'Le Big Data se caractérise par des volumes massifs, une génération rapide et des formats hétérogènes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le ETL dans le contexte des données ?', '["Un protocole réseau","Extract, Transform, Load","Un type de BDD","Un algorithme de hachage"]'::jsonb, 'Extract, Transform, Load', 'ETL extrait les données de sources variées, les transforme selon les besoins et les charge dans le data warehouse.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la dénormalisation d''une base de données ?', '["Supprimer les contraintes","Introduire intentionnellement de la","Normaliser en 4NF","Supprimer les index"]'::jsonb, 'Introduire intentionnellement de la', 'Dans les data warehouses, la dénormalisation réduit les jointures coûteuses au prix de redondance.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Intelligence artificielle, machine learning et éthique du numérique' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la différence entre IA faible et IA forte ?', '["L''IA faible est moins rapide","L''IA faible est spécialisée","L''IA forte utilise moins de données","L''IA faible est plus ancienne"]'::jsonb, 'L''IA faible est spécialisée', 'L''IA actuelle est "faible" : excellente dans des tâches spécifiques mais sans compréhension générale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''apprentissage supervisé (supervised learning) ?', '["L''IA apprend sans données","L''IA apprend à partir d''exemples","L''IA découvre des patterns sans labels","L''IA apprend par essai-erreur avec récompenses"]'::jsonb, 'L''IA apprend à partir d''exemples', 'En apprentissage supervisé, le modèle s''entraîne sur des paires (entrée, sortie attendue).', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un réseau de neurones artificiels ?', '["Un réseau informatique biologique","Un modèle de calcul inspiré du cerveau","Un algorithme de tri","Un protocole de communication"]'::jsonb, 'Un modèle de calcul inspiré du cerveau', 'Les réseaux de neurones apprennent des représentations hiérarchiques des données en ajustant des poids.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le surapprentissage (overfitting) en machine learning ?', '["Le modèle ne s''entraîne pas assez","Le modèle mémorise les données","Le modèle est trop simple","Le modèle prend trop de temps"]'::jsonb, 'Le modèle mémorise les données', 'L''overfitting se produit quand le modèle est trop complexe ; il faut régulariser ou augmenter les données.', 'Moyen'),
    (chap_id, 'Quel algorithme de ML est utilisé pour les problèmes de classification par séparation linéaire ?', '["K-Means","Forêts aléatoires","SVM (Support Vector Machine)","K-Plus Proches Voisins"]'::jsonb, 'SVM (Support Vector Machine)', 'SVM trouve l''hyperplan maximisant la marge entre les classes, efficace pour les espaces de haute dimension.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''apprentissage par renforcement (reinforcement learning) ?', '["Apprendre sur des données étiquetées","Un agent apprend en interagissant avec","Regrouper des données sans labels","Apprendre à partir d''exemples non supervisés"]'::jsonb, 'Un agent apprend en interagissant avec', 'Le RL est utilisé pour les jeux (AlphaGo), la robotique et les systèmes de recommandation.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un biais algorithmique ?', '["Une erreur de programmation","Des discriminations systématiques","Un problème de performance","Un type de bug logiciel"]'::jsonb, 'Des discriminations systématiques', 'Les biais dans les données d''entraînement sont amplifiés par les modèles, produisant des décisions injustes.', 'Moyen'),
    (chap_id, 'Que signifie NLP (Natural Language Processing) ?', '["Network Layer Protocol","Traitement automatique du langage","New Learning Program","Neural Logic Processing"]'::jsonb, 'Traitement automatique du langage', 'NLP permet aux machines de comprendre, générer et traduire le langage humain (chatbots, traduction).', 'Facile'),
    (chap_id, 'Quel principe éthique recommande que les décisions d''une IA puissent être expliquées ?', '["Efficacité","Explicabilité (explainability)","Automatisation","Scalabilité"]'::jsonb, 'Explicabilité (explainability)', 'L''explicabilité (XAI) exige que les décisions des modèles IA soient compréhensibles par les humains.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le deep learning ?', '["Un machine learning avec peu de données","Un sous-domaine du ML utilisant des","Un algorithme de tri","Une technique de compression"]'::jsonb, 'Un sous-domaine du ML utilisant des', 'Le deep learning excelle en vision par ordinateur, NLP et reconnaissance vocale grâce aux CNN, RNN, Transformers.', 'Moyen'),
    (chap_id, 'Quelle est la problématique du RGPD vis-à-vis de l''IA ?', '["La vitesse de traitement","La protection des données personnelles","Le coût des algorithmes","La compatibilité des langages"]'::jsonb, 'La protection des données personnelles', 'Le RGPD exige consentement, transparence et droit à l''effacement, impactant la collecte de données pour l''IA.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le transfert d''apprentissage (transfer learning) ?', '["Copier un modèle","Réutiliser un modèle pré-entraîné sur","Partager des données entre modèles","Un type de fédération"]'::jsonb, 'Réutiliser un modèle pré-entraîné sur', 'Le transfer learning réduit le besoin en données et en calcul en réutilisant des représentations apprises.', 'Difficile'),
    (chap_id, 'Quel algorithme non supervisé regroupe les données en clusters ?', '["Régression linéaire","K-Means","Forêt aléatoire","SVM"]'::jsonb, 'K-Means', 'K-Means partitionne les données en K groupes en minimisant la distance intra-cluster.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe de non-malveillance dans l''éthique de l''IA ?', '["L''IA doit être rapide","L''IA ne doit pas causer de tort aux","L''IA doit être open source","L''IA doit être précise"]'::jsonb, 'L''IA ne doit pas causer de tort aux', 'Non-malveillance est l''un des principes éthiques fondamentaux : l''IA doit éviter les dommages.', 'Moyen'),
    (chap_id, 'Quelle mesure évalue la performance d''un modèle de classification sur toutes les classes ?', '["Précision (accuracy)","F1-Score","Rappel (recall)","AUC-ROC"]'::jsonb, 'F1-Score', 'Le F1-Score est la moyenne harmonique de la précision et du rappel, équilibrant les deux pour les classes déséquilibrées.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 17 AND titre = 'Nouvelles technologies : IoT, cloud et transformation numérique' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Que signifie IoT (Internet of Things) ?', '["Internet of Technology","L''Internet des Objets","Internal Operating Technology","Input/Output Transmission"]'::jsonb, 'L''Internet des Objets', 'L''IoT connecte des objets (capteurs, appareils) à Internet pour collecter et échanger des données.', 'Facile'),
    (chap_id, 'Quels sont les trois principaux modèles de service cloud ?', '["FaaS, BaaS, SaaS","IaaS, PaaS, SaaS","HaaS, NaaS, DaaS","CaaS, DBaaS, AIaaS"]'::jsonb, 'IaaS, PaaS, SaaS', 'IaaS (infrastructure), PaaS (plateforme) et SaaS (logiciel) sont les trois modèles standard du cloud.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''edge computing ?', '["Un type de cloud centralisé","Le traitement des données près de leur","Un protocole réseau","Un système d''exploitation"]'::jsonb, 'Le traitement des données près de leur', 'L''edge computing réduit la latence en traitant les données localement, crucial pour l''IoT et le temps réel.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la blockchain ?', '["Une base de données centralisée","Un registre distribué","Un protocole de chiffrement","Un réseau social décentralisé"]'::jsonb, 'Un registre distribué', 'La blockchain stocke des transactions en blocs chaînés cryptographiquement, sans autorité centrale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le DevOps ?', '["Un langage de programmation","Une culture combinant développement et","Un type de base de données","Un protocole réseau"]'::jsonb, 'Une culture combinant développement et', 'DevOps associe pratiques CI/CD, automatisation et collaboration entre dev et ops pour des déploiements fréquents.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la conteneurisation (Docker, Kubernetes) ?', '["Un type de virtualisation matérielle","Empaqueter une application et ses","Un protocole de sécurité","Un service cloud"]'::jsonb, 'Empaqueter une application et ses', 'Les conteneurs isolent les applications sans OS complet, plus légers que les machines virtuelles.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la transformation numérique d''une organisation ?', '["Acheter de nouveaux ordinateurs","Intégrer les technologies numériques","Migrer vers le cloud uniquement","Former les employés à l''informatique"]'::jsonb, 'Intégrer les technologies numériques', 'La transformation numérique implique culture, processus et technologie pour s''adapter à l''ère numérique.', 'Moyen'),
    (chap_id, 'Quel protocole léger est souvent utilisé pour la communication entre appareils IoT ?', '["HTTP","FTP","MQTT","SMTP"]'::jsonb, 'MQTT', 'MQTT (Message Queuing Telemetry Transport) est un protocole léger de messagerie publish/subscribe pour l''IoT.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la scalabilité horizontale dans le cloud ?', '["Augmenter la puissance d''un seul serveur","Ajouter davantage de serveurs pour","Réduire le nombre de serveurs","Augmenter la capacité disque"]'::jsonb, 'Ajouter davantage de serveurs pour', 'La scalabilité horizontale (scale-out) distribue la charge sur plus de nœuds, contrairement au scale-up.', 'Moyen'),
    (chap_id, 'Quel est l''impact environnemental du numérique et du cloud computing ?', '["Nul, le numérique est propre","Consommation d''énergie et d''eau","Réduction de l''empreinte carbone uniquement","Impact uniquement sur les réseaux"]'::jsonb, 'Consommation d''énergie et d''eau', 'Le numérique représente ~4% des émissions mondiales de GES, avec des data centers très énergivores.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le CI/CD dans le développement logiciel moderne ?', '["Contrôle d''identité/Code de déploiement","Intégration Continue/Déploiement Continu","Compilation instantanée/Code dynamique","Certification infrastructure/Cloud delivery"]'::jsonb, 'Intégration Continue/Déploiement Continu', 'CI/CD automatise la construction, les tests et le déploiement pour des livraisons fréquentes et fiables.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le fog computing par rapport à l''edge computing ?', '["Ce sont des synonymes","Le fog est une couche intermédiaire","Le fog est plus centralisé que le cloud","Le edge est plus puissant que le fog"]'::jsonb, 'Le fog est une couche intermédiaire', 'Le fog computing ajoute une couche d''agrégation entre les appareils IoT (edge) et le cloud central.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une architecture microservices ?', '["Une application monolithique légère","Une application décomposée en petits","Un protocole de communication","Un type de base de données distribuée"]'::jsonb, 'Une application décomposée en petits', 'Les microservices permettent le déploiement et la mise à l''échelle indépendants de chaque composant.', 'Difficile'),
    (chap_id, 'Quel est l''enjeu de la souveraineté des données numériques ?', '["La vitesse de traitement des données","Le droit d''un État ou individu à","La sécurité des mots de passe","La compression des données"]'::jsonb, 'Le droit d''un État ou individu à', 'La souveraineté numérique soulève des questions juridiques sur les données stockées dans des clouds étrangers.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le serverless computing ?', '["Un ordinateur sans système d''exploitation","Un modèle où le fournisseur cloud gère","Un réseau sans serveurs physiques","Un type de cloud privé"]'::jsonb, 'Un modèle où le fournisseur cloud gère', 'Le serverless (FaaS) comme AWS Lambda exécute des fonctions à la demande sans gérer de serveurs.', 'Difficile');
  END IF;
END $$;
