-- Supplement Économie NS1-NS2 (matiere_id=15)
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'Introduction à l''économie : besoins, ressources et choix' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le problème économique fondamental qui justifie l''existence de l''économie ?', '["La pauvreté","La rareté des ressources face à des","L''inégalité des revenus","Le chômage"]'::jsonb, 'La rareté des ressources face à des', 'L''économie naît de la rareté : les ressources disponibles sont insuffisantes pour satisfaire tous les besoins.', 'Facile'),
    (chap_id, 'Qu''est-ce que le coût d''opportunité ?', '["Le prix d''un bien","La valeur de la meilleure alternative","Le coût de production","La taxe sur un bien"]'::jsonb, 'La valeur de la meilleure alternative', 'Tout choix implique un renoncement ; le coût d''opportunité mesure ce qu''on sacrifie.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre besoin et désir en économie ?', '["Aucune","Le besoin est vital/essentiel","Le désir est économique, le besoin est biologique","Le besoin est illimité, le désir est limité"]'::jsonb, 'Le besoin est vital/essentiel', 'Les économistes distinguent les besoins primaires (nourriture, logement) des désirs plus subjectifs.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un bien économique ?', '["Tout objet matériel","Tout bien ou service rare ayant une","Un bien gratuit","Un service public"]'::jsonb, 'Tout bien ou service rare ayant une', 'Un bien économique est rare (à la différence d''un bien libre), donc il a un prix ou un coût.', 'Facile'),
    (chap_id, 'Que représente la courbe de possibilités de production (CPP) ?', '["La demande totale","Les combinaisons maximales de deux","Le niveau de prix","Le PIB"]'::jsonb, 'Les combinaisons maximales de deux', 'La CPP illustre les arbitrages productifs et le coût d''opportunité entre deux biens.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre microéconomie et macroéconomie ?', '["La microéconomie étudie les pays riches","Micro = comportements","La macro est plus précise","La micro étudie les prix mondiaux"]'::jsonb, 'Micro = comportements', 'La microéconomie analyse les décisions des agents ; la macroéconomie étudie les agrégats nationaux.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un facteur de production ?', '["Un produit vendu","Une ressource utilisée pour produire","Un impôt","Un indicateur économique"]'::jsonb, 'Une ressource utilisée pour produire', 'Les facteurs de production classiques sont la terre (ressources naturelles), le travail et le capital.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''utilité marginale ?', '["L''utilité totale","Le gain de satisfaction procuré par une","Le prix d''un bien","La demande du marché"]'::jsonb, 'Le gain de satisfaction procuré par une', 'L''utilité marginale décroissante : chaque unité supplémentaire procure moins de satisfaction.', 'Moyen'),
    (chap_id, 'Quel est le rôle du signal prix dans une économie de marché ?', '["Fixer les salaires","Transmettre l''information sur la rareté","Redistribuer les revenus","Contrôler la production"]'::jsonb, 'Transmettre l''information sur la rareté', 'Les prix agrègent des millions d''informations dispersées et guident les producteurs et consommateurs.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une externalité en économie ?', '["Un coût de production","Un effet (positif ou négatif) d''une","Un impôt sur la production","Un bien public"]'::jsonb, 'Un effet (positif ou négatif) d''une', 'La pollution est une externalité négative ; la vaccination est une externalité positive.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la loi des rendements décroissants ?', '["Plus on produit, plus c''est rentable","Au-delà d''un certain niveau","Les prix baissent toujours","La productivité augmente indéfiniment"]'::jsonb, 'Au-delà d''un certain niveau', 'À capital fixe, chaque travailleur supplémentaire produit moins que le précédent (ex : trop de cuisiniers).', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''avantage comparatif dans le commerce international ?', '["Produire moins cher que les autres","Produire à un coût d''opportunité","Avoir la meilleure technologie","Exporter davantage qu''importer"]'::jsonb, 'Produire à un coût d''opportunité', 'Ricardo : même si un pays est moins efficace absolument, il gagne à se spécialiser où il est relativement meilleur.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la valeur d''usage et la valeur d''échange selon Marx ?', '["Aucune différence","Usage = utilité pour le possesseur","Usage = prix de marché, échange = coût de production","Usage = valeur morale, échange = valeur commerciale"]'::jsonb, 'Usage = utilité pour le possesseur', 'Marx reprend la distinction classique : la valeur d''échange (prix) est fondée sur le travail abstrait moyen.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'L''offre et la demande : mécanismes de marché' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Que se passe-t-il sur la demande quand le prix d''un bien augmente (toutes choses égales) ?', '["La demande augmente","La demande diminue","La demande reste stable","La demande s''inverse"]'::jsonb, 'La demande diminue', 'La loi de la demande : relation inverse entre prix et quantité demandée (ceteris paribus).', 'Facile'),
    (chap_id, 'Que représente l''élasticité-prix de la demande ?', '["Le prix optimal","La sensibilité de la quantité demandée","La variation de l''offre","Le revenu des consommateurs"]'::jsonb, 'La sensibilité de la quantité demandée', 'Élasticité = % variation Qd / % variation P. Si |ε| > 1 : demande élastique ; < 1 : inélastique.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un bien de Giffen ?', '["Un bien de luxe","Un bien inférieur dont la demande","Un bien normal","Un bien complémentaire"]'::jsonb, 'Un bien inférieur dont la demande', 'L''effet de revenu domine l''effet de substitution pour les biens de Giffen (rares, ex : pain pour très pauvres).', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un bien substituable ?', '["Un bien complémentaire","Un bien pouvant remplacer un autre","Un bien inférieur","Un bien Giffen"]'::jsonb, 'Un bien pouvant remplacer un autre', 'Les biens substituables ont une élasticité-prix croisée positive : si le prix du beurre monte, on demande plus de margarine.', 'Moyen'),
    (chap_id, 'Quel est le prix d''équilibre sur un marché concurrentiel ?', '["Le prix fixé par l''État","Le prix où la quantité offerte est","Le prix maximum","Le coût de production"]'::jsonb, 'Le prix où la quantité offerte est', 'L''équilibre de marché (clearing) : offre = demande, ni surplus ni pénurie.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''un surplus du consommateur ?', '["Le profit du producteur","La différence entre ce qu''un","L''excédent de production","Le chiffre d''affaires"]'::jsonb, 'La différence entre ce qu''un', 'Le surplus mesure le gain net du consommateur : il représente l''aire sous la courbe de demande au-dessus du prix.', 'Moyen'),
    (chap_id, 'Que provoque un prix plancher (prix minimum légal) supérieur au prix d''équilibre ?', '["Un déficit (pénurie)","Un surplus (excédent d''offre)","L''équilibre parfait","Une hausse de la demande"]'::jsonb, 'Un surplus (excédent d''offre)', 'Un prix plancher > Péquilibre génère une offre > demande : excédent invendu (ex : salaire minimum).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la concurrence parfaite ?', '["Quelques vendeurs dominants","Un marché avec de nombreux acheteurs et","Un monopole compétitif","Un marché régulé"]'::jsonb, 'Un marché avec de nombreux acheteurs et', 'La concurrence parfaite est le modèle de référence théorique ; les agents sont "price-takers".', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une défaillance de marché ?', '["Une crise boursière","Une situation où le marché libre","Un monopole naturel","Une externalité positive"]'::jsonb, 'Une situation où le marché libre', 'Les défaillances incluent externalités, biens publics, asymétries d''information, pouvoirs de marché.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un bien public au sens économique ?', '["Un bien vendu par l''État","Un bien non rival et non excluable","Un bien subventionné","Un bien avec TVA réduite"]'::jsonb, 'Un bien non rival et non excluable', 'Non rival = ma consommation n''empêche pas la tienne ; non excluable = on ne peut exclure personne.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''asymétrie d''information ?', '["Des prix différents selon les marchés","Quand une partie dispose de plus","Un manque de communication","La publicité mensongère"]'::jsonb, 'Quand une partie dispose de plus', 'L''asymétrie d''information (Akerlof) mène à la sélection adverse et l''aléa moral.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un monopole naturel ?', '["Un monopole illégal","Un marché où une seule entreprise peut","Un bien public","Un oligopole"]'::jsonb, 'Un marché où une seule entreprise peut', 'Les monopoles naturels ont des coûts fixes très élevés et des coûts marginaux très bas, rendant la concurrence inefficace.', 'Moyen'),
    (chap_id, 'Quel est l''effet d''une subvention sur l''offre d''un bien ?', '["Elle diminue l''offre","Elle augmente l''offre et baisse le prix","Elle n''affecte pas l''offre","Elle augmente la demande seulement"]'::jsonb, 'Elle augmente l''offre et baisse le prix', 'La subvention réduit le coût de production, déplaçant la courbe d''offre vers la droite et baissant le prix.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'La monnaie et le système financier' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelles sont les trois fonctions classiques de la monnaie ?', '["Épargne, investissement, spéculation","Intermédiaire des échanges","Moyen de paiement, crédit, assurance","Production, distribution, consommation"]'::jsonb, 'Intermédiaire des échanges', 'La monnaie facilite les échanges, mesure les valeurs et permet de stocker du pouvoir d''achat.', 'Facile'),
    (chap_id, 'Qu''est-ce que la masse monétaire M1 ?', '["Toute l''épargne nationale","Les billets, pièces et dépôts à vue","Les obligations d''État","Les réserves de change"]'::jsonb, 'Les billets, pièces et dépôts à vue', 'M1 est l''agrégat monétaire le plus étroit, comprenant la monnaie la plus liquide.', 'Moyen'),
    (chap_id, 'Quel est le rôle principal d''une banque centrale ?', '["Accorder des crédits aux entreprises","Réguler la politique monétaire","Gérer le budget de l''État","Superviser la bourse"]'::jsonb, 'Réguler la politique monétaire', 'La banque centrale (Fed, BCE, BRH) gère l''offre de monnaie et vise la stabilité des prix.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''inflation ?', '["Une hausse du chômage","Une hausse générale et durable du","Une crise financière","Une baisse de la production"]'::jsonb, 'Une hausse générale et durable du', 'L''inflation érode le pouvoir d''achat ; elle est mesurée par l''Indice des Prix à la Consommation (IPC).', 'Facile'),
    (chap_id, 'Qu''est-ce que le taux directeur d''une banque centrale ?', '["Le taux de change","Le taux auquel la banque centrale prête","Le taux d''imposition","Le taux de croissance"]'::jsonb, 'Le taux auquel la banque centrale prête', 'En abaissant ce taux, la banque centrale stimule le crédit et l''économie ; en le montant, elle freine l''inflation.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la création monétaire par les banques commerciales ?', '["Imprimer des billets","Octroyer des crédits qui créent des","Stocker de l''or","Transférer de l''argent"]'::jsonb, 'Octroyer des crédits qui créent des', 'Les banques commerciales créent de la monnaie en accordant des prêts, sous contrainte des réserves obligatoires.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le taux de change ?', '["Le prix d''une action","Le prix d''une monnaie exprimé en une","Le taux d''intérêt","Le coût du crédit"]'::jsonb, 'Le prix d''une monnaie exprimé en une', 'Le taux de change détermine combien d''unités d''une devise s''échangent contre une unité d''une autre devise.', 'Facile'),
    (chap_id, 'Qu''est-ce qu''une bulle spéculative ?', '["Une inflation normale","Une hausse excessive des prix d''actifs","Un déficit budgétaire","Une crise de liquidité"]'::jsonb, 'Une hausse excessive des prix d''actifs', 'Les bulles (immobilier, bourse) se forment par anticipations autoréalisatrices et éclatent brutalement.', 'Moyen'),
    (chap_id, 'Quel instrument financier représente une part de propriété dans une entreprise ?', '["Une obligation","Une action","Un bon du trésor","Un certificat de dépôt"]'::jsonb, 'Une action', 'Une action confère des droits de propriété, dividendes et vote aux actionnaires.', 'Facile'),
    (chap_id, 'Qu''est-ce que la politique monétaire expansionniste ?', '["Augmenter les impôts","Abaisser les taux d''intérêt et","Réduire les dépenses publiques","Limiter les crédits"]'::jsonb, 'Abaisser les taux d''intérêt et', 'La politique accommodante (quantitative easing) stimule l''investissement et la consommation.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la stagflation ?', '["Une forte croissance avec inflation","La coexistence d''inflation et de","Une déflation rapide","Une récession sans inflation"]'::jsonb, 'La coexistence d''inflation et de', 'La stagflation (années 1970) contredit la courbe de Phillips et rend la politique économique difficile.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le risque systémique dans le système financier ?', '["Le risque d''un seul emprunteur","Le risque qu''une défaillance locale se","Le risque de change","Le risque d''inflation"]'::jsonb, 'Le risque qu''une défaillance locale se', 'La crise de 2008 illustre le risque systémique : la faillite de Lehman Brothers contamine l''ensemble du système.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'La croissance économique et ses déterminants' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le PIB (Produit Intérieur Brut) ?', '["La valeur des exportations","La valeur totale des biens et services","Le revenu des ménages","La somme des profits des entreprises"]'::jsonb, 'La valeur totale des biens et services', 'Le PIB mesure la richesse créée sur le territoire national, indépendamment de la nationalité des producteurs.', 'Facile'),
    (chap_id, 'Quels sont les facteurs classiques de la croissance économique selon Solow ?', '["Consommation et épargne","Accumulation du capital","Importations et exportations","Dépenses publiques et impôts"]'::jsonb, 'Accumulation du capital', 'Le modèle de Solow (1956) : K, L et technologie déterminent la croissance ; le progrès technique est exogène.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le développement durable ?', '["La croissance économique rapide","Un développement qui satisfait les","La protection de l''environnement uniquement","Le développement des pays pauvres"]'::jsonb, 'Un développement qui satisfait les', 'Définition du rapport Brundtland (1987) : triple pilier économique, social, environnemental.', 'Facile'),
    (chap_id, 'Qu''est-ce que le capital humain ?', '["Les machines d''une entreprise","Les compétences","Les ressources naturelles","Le capital financier"]'::jsonb, 'Les compétences', 'Becker : le capital humain est un investissement productif qui augmente la productivité et les salaires.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une récession économique ?', '["Une croissance lente","Deux trimestres consécutifs de","Un chômage élevé uniquement","Une inflation forte"]'::jsonb, 'Deux trimestres consécutifs de', 'La définition technique de la récession est deux trimestres successifs de PIB négatif.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''Indice de Développement Humain (IDH) mesure ?', '["Uniquement le PIB","Une mesure composite de l''espérance de","La croissance économique","L''inégalité des revenus"]'::jsonb, 'Une mesure composite de l''espérance de', 'L''IDH (PNUD, Mahbub ul Haq) complète le PIB par des dimensions humaines : santé, éducation, niveau de vie.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "destruction créatrice" selon Schumpeter ?', '["La crise industrielle","Le processus par lequel l''innovation","La politique budgétaire","Le protectionnisme"]'::jsonb, 'Le processus par lequel l''innovation', 'Schumpeter : l''entrepreneur innovateur est le moteur du capitalisme, créant et détruisant en même temps.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le multiplicateur keynésien ?', '["Le taux de croissance","Une augmentation des dépenses qui","L''effet d''une hausse des impôts","Le ratio PIB/emploi"]'::jsonb, 'Une augmentation des dépenses qui', 'Keynes : 1 gourde de dépense publique peut créer plus d''1 gourde de revenu via les effets de propagation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la convergence économique en économie du développement ?', '["Les pays riches s''appauvrissent","Les pays pauvres tendent à croître plus","Les pays convergent vers la même monnaie","L''harmonisation fiscale"]'::jsonb, 'Les pays pauvres tendent à croître plus', 'La convergence conditionnelle (Solow) : les pays moins capitalisés ont des rendements marginaux plus élevés.', 'Difficile'),
    (chap_id, 'Que mesure le coefficient de Gini ?', '["Le PIB par habitant","Le degré d''inégalité dans la","Le chômage structurel","L''inflation"]'::jsonb, 'Le degré d''inégalité dans la', 'Plus le Gini est élevé, plus les revenus sont inégalement répartis dans la population.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la politique budgétaire contra-cyclique ?', '["Augmenter les dépenses en période de","Augmenter les dépenses en récession et réduire en période de croissance forte","Équilibrer toujours le budget","Réduire la dette en toute circonstance"]'::jsonb, 'Augmenter les dépenses en période de', 'La politique contra-cyclique lisse les cycles économiques via les stabilisateurs automatiques et discrétionnaires.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le commerce intra-branche ?', '["Échange de biens différents","Échange de biens du même secteur entre","Commerce entre pays du Sud","Le protectionnisme sectoriel"]'::jsonb, 'Échange de biens du même secteur entre', 'Le commerce intra-branche (Krugman) s''explique par les économies d''échelle et la différentiation des produits.', 'Difficile');
  END IF;
END $$;
