-- Supplement Géologie (matiere_id=12) — NS3 et NS4
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 12 AND titre = 'Séismes et volcans : risques naturels' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la différence entre le foyer (hypocentre) et l''épicentre d''un séisme ?', '["Ils désignent le même point","Le foyer est le point de rupture dans","L''épicentre est plus profond","Le foyer est à la surface"]'::jsonb, 'Le foyer est le point de rupture dans', 'Le foyer du séisme d''Haïti 2010 se trouvait à ~13 km de profondeur ; son épicentre était près de Léogâne.', 'Facile'),
    (chap_id, 'Quelle est la différence entre l''échelle de Richter et l''échelle de Mercalli ?', '["Elles mesurent la même chose","Richter (magnitude) mesure l''énergie","Mercalli mesure la profondeur","Richter mesure la durée"]'::jsonb, 'Richter (magnitude) mesure l''énergie', 'Magnitude = énergie (objective) ; intensité = effets locaux (subjective). Un séisme a une magnitude unique mais des intensités variables.', 'Moyen'),
    (chap_id, 'Quels sont les deux types principaux d''ondes sismiques et leurs caractéristiques ?', '["Ondes alpha et bêta","Ondes P (primaires","Ondes X et Y","Ondes de surface uniquement"]'::jsonb, 'Ondes P (primaires', 'Les ondes P (plus rapides) arrivent en premier ; les ondes S et de surface (Love, Rayleigh) causent la majorité des dégâts.', 'Moyen'),
    (chap_id, 'Comment se forme un tsunami et quelles sont les conditions nécessaires ?', '["Un vent fort sur l''océan","Un tremblement de terre sous-marin (ou","Une éruption volcanique terrestre uniquement","Une marée exceptionnelle"]'::jsonb, 'Un tremblement de terre sous-marin (ou', 'Le tsunami de 2004 en Asie (magnitude 9.1) a tué 230 000 personnes ; les Caraïbes sont exposées aux tsunamis sismiques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la liquéfaction des sols lors d''un séisme et pourquoi est-elle dangereuse ?', '["Un phénomène volcanique","Le comportement de certains sols","Un type de faille","Un glissement de terrain classique"]'::jsonb, 'Le comportement de certains sols', 'La liquéfaction a aggravé les dégâts du séisme de 2010 en Haïti dans les zones côtières et de remblai.', 'Moyen'),
    (chap_id, 'Quels sont les deux grands types de volcans selon leur structure et leur mode d''éruption ?', '["Petits et grands","Volcans boucliers (basaltiques","Volcans actifs et éteints","Volcans sous-marins et terrestres"]'::jsonb, 'Volcans boucliers (basaltiques', 'Mauna Loa (Hawaii) = bouclier peu dangereux ; Pelée (Martinique), Vésuve = stratovolcans très dangereux.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une nuée ardente et quel est son exemple historique le plus célèbre ?', '["Un nuage de vapeur d''eau","Un écoulement pyroclastique rapide de","Une coulée de lave lente","Un tsunami volcanique"]'::jsonb, 'Un écoulement pyroclastique rapide de', 'La nuée ardente (courant pyroclastique) de la Pelée a détruit Saint-Pierre en 3 minutes ; seul un prisonnier en réchappa.', 'Moyen'),
    (chap_id, 'Comment se définit le risque sismique et quels sont ses facteurs ?', '["Le risque = magnitude uniquement","Le risque sismique = aléa (probabilité","Le risque = nombre de séismes","Le risque est identique partout"]'::jsonb, 'Le risque sismique = aléa (probabilité', 'Haïti a un aléa modéré mais une vulnérabilité extrême (constructions précaires) → risque catastrophique (2010 : ~220 000 morts).', 'Moyen'),
    (chap_id, 'Qu''est-ce que le parc de prévention et les systèmes d''alerte sismique précoce ?', '["Des boucliers contre les séismes","Des réseaux de capteurs sismiques qui","Des constructions parasismiques","Des abris souterrains"]'::jsonb, 'Des réseaux de capteurs sismiques qui', 'Le Japon utilise un système d''alerte précoce efficace (SkyAlert) donnant quelques secondes précieuses avant l''arrivée des ondes S.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la sismicité induite et comment les activités humaines peuvent-elles causer des séismes ?', '["Les séismes sont uniquement naturels","L''injection de fluides en profondeur","L''exploitation minière ne cause pas de séismes","Les séismes induits sont toujours plus forts que les naturels"]'::jsonb, 'L''injection de fluides en profondeur', 'L''Oklahoma (USA) est devenu la zone la plus sismique des USA en raison de l''injection de déchets issus du pétrole de schiste.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le géorisque en Haïti et comment y faire face ?', '["Haïti n''a pas de risques géologiques","Haïti est exposée à des séismes majeurs","Les risques sont uniquement climatiques","Les séismes en Haïti sont mineurs"]'::jsonb, 'Haïti est exposée à des séismes majeurs', 'La DPC (Direction de la Protection Civile) haïtienne travaille à la cartographie des risques et aux plans d''évacuation locaux.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la construction parasismique et ses principes fondamentaux ?', '["Construire en béton lourd","Construire des bâtiments capables","Construire sous terre","Construire en matériaux légers uniquement"]'::jsonb, 'Construire des bâtiments capables', 'Le code parasismique japonais permet de survivre à des séismes de magnitude 8+ ; son application en Haïti est un enjeu majeur.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 12 AND titre = 'Ressources naturelles et géologie économique' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Comment se forment les gisements de pétrole et de gaz naturel ?', '["Par refroidissement du magma","Par la décomposition de matière","Par métamorphisme des roches calcaires","Par l''érosion du granite"]'::jsonb, 'Par la décomposition de matière', 'Les hydrocarbures nécessitent : roche mère (kérogène), maturation thermique, roche réservoir poreuse et roche couverture imperméable.', 'Moyen'),
    (chap_id, 'Comment se forment les gisements de minerais métalliques ?', '["Par précipitation atmosphérique","Par concentration hydrothermale","Par érosion uniquement","Par refroidissement rapide de la lave"]'::jsonb, 'Par concentration hydrothermale', 'L''or (hydrothermal), le cuivre (porphyre), la bauxite (latéritisation tropicale) : chaque métal a son processus de concentration.', 'Moyen'),
    (chap_id, 'Quels sont les potentiels miniers d''Haïti selon les études géologiques récentes ?', '["Aucun potentiel","Des gisements d''or","Uniquement du calcaire","Uniquement du pétrole offshore"]'::jsonb, 'Des gisements d''or', 'Le Bureau des Mines et de l''Énergie (BME) d''Haïti a identifié des ressources aurifères significatives ; leur exploitation soulève des débats environnementaux.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''énergie géothermique et comment peut-elle être exploitée ?', '["L''énergie solaire","L''exploitation de la chaleur interne de","L''énergie des marées","L''énergie nucléaire"]'::jsonb, 'L''exploitation de la chaleur interne de', 'L''Islande (géothermie volcanique) couvre ~25% de son électricité par géothermie ; les Antilles ont un potentiel géothermique (Guadeloupe).', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géologie environnementale et ses applications ?', '["L''étude des fossiles","L''application de la géologie à la","L''astronomie","La géologie marine uniquement"]'::jsonb, 'L''application de la géologie à la', 'La géologie environnementale est essentielle en Haïti pour la gestion des bassins versants et la réduction de l''érosion.', 'Moyen'),
    (chap_id, 'Comment la déforestation en Haïti amplifie-t-elle les risques géologiques ?', '["Elle n''a aucun effet","En enlevant le couvert végétal","Elle favorise la minéralisation","Elle réduit le risque sismique"]'::jsonb, 'En enlevant le couvert végétal', 'Haïti a perdu ~98% de sa couverture forestière originale ; chaque cyclone amplifie les catastrophes de terrain en l''absence d''arbres.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la gestion durable des ressources minières ?', '["L''exploitation maximale sans contrainte","L''exploitation des ressources minières","L''arrêt total de l''exploitation","L''exploitation uniquement par des entreprises étrangères"]'::jsonb, 'L''exploitation des ressources minières', 'Les principes de l''Initiative pour la Transparence dans les Industries Extractives (ITIE) promeuvent la gouvernance des ressources minières.', 'Moyen'),
    (chap_id, 'Qu''est-ce que les aquifères et leur importance en Haïti ?', '["Des roches sans eau","Des formations géologiques poreuses et","Des volcans sous-marins","Des formations de basalte"]'::jsonb, 'Des formations géologiques poreuses et', 'Les plaines du Cul-de-Sac et de l''Artibonite abritent des aquifères importants mais vulnérables à la surexploitation et la contamination.', 'Moyen'),
    (chap_id, 'Comment les changements climatiques affectent-ils les ressources en eau souterraine ?', '["Sans effet","En modifiant les régimes de pluie et en","En augmentant les aquifères","En créant de nouveaux aquifères"]'::jsonb, 'En modifiant les régimes de pluie et en', 'Dans les Caraïbes, les projections climatiques prévoient une réduction des précipitations et une intensification des sécheresses.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la télédétection et les SIG (Systèmes d''Information Géographique) en géologie ?', '["Des instruments de forage","Des outils permettant l''analyse","Des techniques de datation","Des méthodes de laboratoire uniquement"]'::jsonb, 'Des outils permettant l''analyse', 'La télédétection (Landsat, SPOT) a révolutionné la cartographie géologique et la surveillance des risques naturels en Haïti.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la géologie isotopique et ses applications à la géochimie ?', '["L''étude des roches uniquement","L''étude des rapports isotopiques dans","Une technique d''exploration pétrolière uniquement","L''étude des isotopes radioactifs médicaux"]'::jsonb, 'L''étude des rapports isotopiques dans', 'Les isotopes stables (O18/O16, C13/C12) enregistrent les paléoclimats dans les carottes glaciaires et les carbonates marins.', 'Difficile'),
    (chap_id, 'Comment la géologie contribue-t-elle à la compréhension du changement climatique passé et futur ?', '["La géologie n''est pas liée au climat","Les archives géologiques (carottes de","La géologie concerne uniquement les roches solides","Les géologues ne s''intéressent pas au climat"]'::jsonb, 'Les archives géologiques (carottes de', 'Les géologues ont identifié des périodes de CO2 élevé (PETM, il y a 56 Ma) montrant des analogues du réchauffement actuel.', 'Difficile');
  END IF;
END $$;
