-- Supplément Géographie NS1-NS2 (matiere_id=28) — +18 questions/chapitre pour atteindre 20 minimum

-- Chapitre 1 : Géographie physique d'Haïti : relief, hydrographie et climat NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 28 AND titre = 'Géographie physique d''Haïti : relief, hydrographie et climat' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Sur quelle île Haïti est-elle située ?', '["Cuba", "Porto Rico", "Hispaniola (Haïti/Quisqueya)", "La Jamaïque"]'::jsonb, 'Hispaniola (Haïti/Quisqueya)', 'Haïti occupe le tiers occidental de l''île d''Hispaniola (appelée aussi Ayiti ou Quisqueya par les Taïnos), qu''elle partage avec la République Dominicaine. C''est la deuxième plus grande île des Grandes Antilles.', 'Facile'),
    (chap_id, 'Quelle est la superficie approximative d''Haïti ?', '["10 000 km²", "18 000 km²", "27 750 km²", "45 000 km²"]'::jsonb, '27 750 km²', 'Haïti couvre une superficie d''environ 27 750 km², ce qui en fait l''un des plus petits pays des Amériques. Malgré cette taille modeste, sa géographie est extrêmement diverse avec des montagnes, des plaines et des côtes variées.', 'Facile'),
    (chap_id, 'Quel est le point culminant d''Haïti et dans quelle chaîne de montagnes se trouve-t-il ?', '["Le Pic Macaya (2 347 m) dans le Massif de la Hotte", "La Selle (2 680 m) dans le Massif de la Selle", "Le Bonnet à l''Évêque (2 674 m) dans le Massif du Nord", "Le Pic Trois Rivières (2 100 m) dans la Chaîne des Matheux"]'::jsonb, 'La Selle (2 680 m) dans le Massif de la Selle', 'Le point culminant d''Haïti est La Selle, avec 2 680 mètres d''altitude, situé dans le Massif de la Selle (péninsule du Sud-Est). C''est dans ce massif que se trouve également la Forêt des Pins, principale forêt de pins d''Haïti.', 'Moyen'),
    (chap_id, 'Quel est le fleuve le plus long d''Haïti ?', '["La Rivière du Nord", "Le Fleuve Artibonite", "La Rivière Trois Rivières", "Le Grand Rivière du Nord"]'::jsonb, 'Le Fleuve Artibonite', 'L''Artibonite est le plus long fleuve d''Haïti (285 km) et de l''île d''Hispaniola. Il traverse la plaine de l''Artibonite, le "grenier à riz" d''Haïti, et se jette dans la Mer des Caraïbes. Le barrage de Péligre (1956) y a créé un lac artificiel utilisé pour l''irrigation et l''hydroélectricité.', 'Facile'),
    (chap_id, 'Quelles sont les deux saisons de pluies en Haïti ?', '["Janvier-mars et juillet-septembre", "Avril-juin et août-octobre", "Février-avril et novembre-décembre", "Mai-juillet et octobre-novembre"]'::jsonb, 'Avril-juin et août-octobre', 'Haïti connaît deux saisons pluvieuses : la principale d''avril à juin et la secondaire d''août à octobre. Les saisons sèches correspondent aux périodes entre ces saisons. Le pays est aussi exposé aux ouragans de juin à novembre.', 'Moyen'),
    (chap_id, 'Comment s''appelle le principal lac d''eau saumâtre d''Haïti, situé dans la plaine du Cul-de-Sac ?', '["Lac Azuei", "Lac Miragoane", "Lac des Cayes", "Étang de Miragoâne"]'::jsonb, 'Lac Azuei', 'Le Lac Azuei (aussi appelé Étang Saumâtre) est le plus grand lac d''Haïti, situé dans la plaine du Cul-de-Sac près de Port-au-Prince. C''est un lac d''eau saumâtre qui abrite des crocodiles et de nombreuses espèces d''oiseaux migrateurs.', 'Moyen'),
    (chap_id, 'Quel type de relief caractérise principalement le territoire haïtien ?', '["Essentiellement plat avec quelques collines", "Très montagneux (plus de 60 % du territoire est montagneux)", "Principalement constitué de plateaux élevés", "Essentiellement côtier et bas"]'::jsonb, 'Très montagneux (plus de 60 % du territoire est montagneux)', 'Haïti est un pays très montagneux : plus de 60 % de son territoire est constitué de reliefs montagneux. Ce caractère montagneux a des conséquences importantes sur l''agriculture, les communications et l''exposition aux risques naturels (glissements de terrain, inondations en zones basses).', 'Facile'),
    (chap_id, 'Quelle chaîne de montagnes sépare le Nord d''Haïti de la partie centrale du pays ?', '["Le Massif de la Selle", "Le Massif de la Hotte", "La Chaîne du Bonnet à l''Évêque", "La Chaîne des Matheux / Montagnes Noires"]'::jsonb, 'La Chaîne des Matheux / Montagnes Noires', 'La Chaîne des Matheux et les Montagnes Noires séparent la plaine de l''Artibonite et la plaine du Cul-de-Sac des massifs du Nord. Elles constituent une barrière naturelle qui influe sur la distribution des précipitations entre le nord et le sud du pays.', 'Difficile'),
    (chap_id, 'Quelle est la principale zone de production agricole de plaine en Haïti ?', '["La Plaine du Cul-de-Sac", "La Plaine de l''Artibonite", "La Plaine des Cayes", "La Plaine des Gonaïves"]'::jsonb, 'La Plaine de l''Artibonite', 'La Plaine de l''Artibonite est la plus grande plaine d''Haïti et la principale zone de production de riz. Irriguée par le fleuve Artibonite et le barrage de Péligre, elle constitue le "grenier à riz" du pays et joue un rôle fondamental dans la sécurité alimentaire haïtienne.', 'Moyen'),
    (chap_id, 'Quelle mer borde la côte nord d''Haïti ?', '["La Mer des Caraïbes", "L''Océan Atlantique Nord", "Le Golfe du Mexique", "La Mer des Sargasses"]'::jsonb, 'L''Océan Atlantique Nord', 'La côte nord d''Haïti borde l''Océan Atlantique Nord (plus précisément la mer adjacente parfois appelée Mer d''Hispaniola ou Canal du Vent). La côte sud borde la Mer des Caraïbes. Cette double exposition explique les différences climatiques entre le nord et le sud du pays.', 'Moyen'),
    (chap_id, 'Pourquoi Haïti est-elle particulièrement vulnérable aux ouragans ?', '["Parce qu''elle est trop plate pour résister aux vents", "Parce qu''elle est située dans la ceinture des ouragans de l''Atlantique tropical, avec des côtes exposées et une déforestation massive aggravant les inondations", "Parce qu''elle n''a pas de montagnes pour bloquer les vents", "Parce que les ouragans ne touchent que les pays pauvres"]'::jsonb, 'Parce qu''elle est située dans la ceinture des ouragans de l''Atlantique tropical, avec des côtes exposées et une déforestation massive aggravant les inondations', 'Haïti est vulnérable aux ouragans pour plusieurs raisons : sa position géographique dans la zone de passage des ouragans atlantiques, ses côtes très étendues, et surtout sa déforestation massive qui aggrave les inondations et glissements de terrain lors des tempêtes. L''ouragan Matthew (2016) a causé des destructions considérables.', 'Moyen'),
    (chap_id, 'Comment s''appelle la péninsule la plus au sud d''Haïti, qui abrite le Massif de la Hotte ?', '["La Péninsule du Nord", "La Péninsule de Saint-Nicolas (Tiburon)", "La Péninsule du Cap Tiburon / du Sud", "La Presqu''île de Jérémie"]'::jsonb, 'La Péninsule du Cap Tiburon / du Sud', 'La Péninsule du Sud (aussi appelée Péninsule du Cap Tiburon) est la plus longue des deux péninsules haïtiennes. Elle abrite le Massif de la Hotte (avec le Pic Macaya, 2 347 m, deuxième sommet d''Haïti), le Parc National de la Hotte et la ville de Jérémie.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''effet de Fœhn (ou effet de versant) et comment influence-t-il le climat haïtien ?', '["Un phénomène de réchauffement des océans qui crée des sécheresses", "Le vent humide est bloqué par les montagnes : le versant exposé reçoit de la pluie, le versant sous le vent est sec", "Une perturbation thermique des plaines côtières", "Un phénomène de brouillard dense dans les vallées"]'::jsonb, 'Le vent humide est bloqué par les montagnes : le versant exposé reçoit de la pluie, le versant sous le vent est sec', 'L''effet de versant (Fœhn) explique les grandes disparités pluviométriques en Haïti : les versants nord et est reçoivent beaucoup de pluie (alizés humides), tandis que les versants sous le vent (sud-ouest de certaines chaînes) créent des zones sèches comme les Gonaïves. Cela contribue à la diversité des paysages haïtiens.', 'Difficile'),
    (chap_id, 'Où se situe la Presqu''île du Nord-Ouest d''Haïti, connue pour ses conditions arides ?', '["Dans le département du Sud", "Dans le département du Nord-Ouest, autour de Port-de-Paix et de la ville de Môle Saint-Nicolas", "Dans le département de l''Ouest, près de Port-au-Prince", "Dans le département de l''Artibonite"]'::jsonb, 'Dans le département du Nord-Ouest, autour de Port-de-Paix et de la ville de Môle Saint-Nicolas', 'Le département du Nord-Ouest, notamment la péninsule du Môle Saint-Nicolas, est l''une des zones les plus arides d''Haïti. Cette sécheresse est due à l''effet de versant combiné à la déforestation, ce qui la distingue nettement des régions verdoyantes du Nord et du Centre.', 'Difficile'),
    (chap_id, 'Quel est le principal danger naturel lié au relief montagneux et à la déforestation en Haïti ?', '["Les éruptions volcaniques", "Les glissements de terrain et les inondations lors des pluies intenses", "Les tempêtes de sable", "Les avalanches de neige"]'::jsonb, 'Les glissements de terrain et les inondations lors des pluies intenses', 'La combinaison du relief montagneux et de la déforestation massive (moins de 2 % de couvert forestier) rend Haïti extrêmement vulnérable aux glissements de terrain et aux inondations lors des pluies intenses. Les cyclones Matthew (2016) et Sandy (2012) ont provoqué des catastrophes humanitaires majeures.', 'Moyen'),
    (chap_id, 'Quel département haïtien possède la plus grande superficie ?', '["Le département de l''Ouest", "Le département de l''Artibonite", "Le département du Sud-Est", "Le département du Nord"]'::jsonb, 'Le département de l''Artibonite', 'Le département de l''Artibonite est le plus grand d''Haïti en superficie (4 887 km²), suivi par le département du Sud-Est. Il contient la plaine de l''Artibonite, principal grenier agricole du pays, et sa ville principale est Gonaïves, capitale historique d''Haïti.', 'Difficile'),
    (chap_id, 'Combien de départements compte Haïti ?', '["8", "10", "12", "15"]'::jsonb, '10', 'Haïti est divisée en 10 départements : Ouest, Nord, Nord-Est, Nord-Ouest, Artibonite, Centre, Sud, Sud-Est, Nippes et Grande-Anse. Ces 10 départements remplacent les 9 originaux créés en 2003 avec l''ajout du département des Nippes.', 'Facile'),
    (chap_id, 'Quel lac artificiel haïtien a été créé par le barrage de Péligre sur le fleuve Artibonite ?', '["Le Lac Azuei", "Le Lac de Miragoane", "Le Lac de Péligre", "Le Lac des Cayes"]'::jsonb, 'Le Lac de Péligre', 'Le Lac de Péligre est un lac artificiel créé par le barrage de Péligre (construit en 1956) sur le fleuve Artibonite, dans le département du Centre. Ce barrage fournit une partie de l''électricité d''Haïti et irrigue la plaine de l''Artibonite pour la production de riz.', 'Moyen');
  END IF;
END $$;

-- Chapitre 2 : Géographie humaine et économique d'Haïti NS1
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 28 AND titre = 'Géographie humaine et économique d''Haïti' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelle est la population approximative d''Haïti ?', '["3 millions", "6 millions", "11 millions", "20 millions"]'::jsonb, '11 millions', 'Haïti compte environ 11 à 12 millions d''habitants (données 2023), ce qui en fait la nation la plus densément peuplée des Caraïbes. La densité de population est d''environ 400 habitants/km², avec une forte concentration dans les plaines côtières et autour de Port-au-Prince.', 'Facile'),
    (chap_id, 'Quelle est la capitale d''Haïti et dans quel département se trouve-t-elle ?', '["Cap-Haïtien, département du Nord", "Port-au-Prince, département de l''Ouest", "Les Cayes, département du Sud", "Gonaïves, département de l''Artibonite"]'::jsonb, 'Port-au-Prince, département de l''Ouest', 'Port-au-Prince est la capitale et la plus grande ville d''Haïti, située dans le département de l''Ouest au fond du Golfe de la Gonâve. L''aire métropolitaine de Port-au-Prince concentre environ 3 à 4 millions d''habitants, soit presque un tiers de la population du pays.', 'Facile'),
    (chap_id, 'Quelle est la deuxième ville d''Haïti par sa taille et son importance historique ?', '["Gonaïves", "Jacmel", "Cap-Haïtien", "Les Cayes"]'::jsonb, 'Cap-Haïtien', 'Cap-Haïtien (anciennement Cap-Français, "Le Cap"), dans le département du Nord, est la deuxième ville d''Haïti. Elle fut la capitale coloniale de Saint-Domingue et reste un centre économique et culturel majeur, notamment pour la région du Nord.', 'Facile'),
    (chap_id, 'Quel secteur économique emploie la majorité de la population haïtienne ?', '["L''industrie manufacturière", "Le secteur des services (secteur informel)", "L''agriculture", "Le tourisme"]'::jsonb, 'L''agriculture', 'L''agriculture emploie environ 50-60 % de la population active haïtienne, bien qu''elle ne représente qu''une fraction du PIB. Les principales cultures sont : le café, les mangues, la canne à sucre, le cacao, les haricots et les céréales. La majorité est une agriculture de subsistance.', 'Facile'),
    (chap_id, 'Quelle culture d''exportation est historiquement la plus importante pour l''économie haïtienne ?', '["Le coton", "La canne à sucre", "Le café", "La banane"]'::jsonb, 'Le café', 'Le café est la principale culture d''exportation traditionnelle d''Haïti. Le café haïtien, notamment le café de montagne du massif de la Selle, est réputé pour sa qualité et représente une source importante de devises étrangères. Haïti fut l''un des premiers producteurs mondiaux de café au XIXe siècle.', 'Moyen'),
    (chap_id, 'Quelle est la principale industrie moderne d''Haïti en termes d''emploi et d''exportation ?', '["La production pétrolière", "L''industrie textile et de l''assemblage (zones franches industrielles)", "La production d''aluminium", "L''industrie minière"]'::jsonb, 'L''industrie textile et de l''assemblage (zones franches industrielles)', 'L''industrie textile et d''assemblage dans les zones franches industrielles (notamment à Port-au-Prince) est le principal secteur manufacturier moderne haïtien. Elle emploie des dizaines de milliers de travailleurs et exporte essentiellement vers les États-Unis grâce à des accords commerciaux préférentiels (HOPE Act).', 'Moyen'),
    (chap_id, 'Quelle proportion de la population haïtienne vit en milieu rural ?', '["Moins de 20 %", "Environ 35 %", "Environ 55-60 %", "Plus de 80 %"]'::jsonb, 'Environ 55-60 %', 'Malgré une urbanisation croissante, environ 55 à 60 % de la population haïtienne vit encore en milieu rural. Ce taux d''urbanisation est plus faible que dans la plupart des pays caribéens, bien que la croissance de Port-au-Prince ait été très rapide ces dernières décennies.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "diaspora haïtienne" et quel rôle joue-t-elle dans l''économie nationale ?', '["La population haïtienne des zones rurales", "Les Haïtiens vivant à l''étranger, qui envoient des remises financières essentielles à l''économie haïtienne", "Les entrepreneurs haïtiens de Port-au-Prince", "Les paysans sans terres en Haïti"]'::jsonb, 'Les Haïtiens vivant à l''étranger, qui envoient des remises financières essentielles à l''économie haïtienne', 'La diaspora haïtienne compte environ 2 à 3 millions de personnes, principalement aux États-Unis, au Canada, en France, en République Dominicaine et aux Bahamas. Les transferts de fonds (remises) de la diaspora représentent environ 30 % du PIB haïtien, dépassant les exportations et l''aide internationale.', 'Moyen'),
    (chap_id, 'Quel est l''indicateur de développement humain (IDH) d''Haïti par rapport aux autres pays caribéens ?', '["Haïti a l''IDH le plus élevé des Caraïbes", "Haïti a un IDH moyen comparable à la moyenne caribéenne", "Haïti a le plus bas IDH des Amériques et figure parmi les plus bas des Caraïbes", "Haïti a un IDH légèrement inférieur à la moyenne caribéenne"]'::jsonb, 'Haïti a le plus bas IDH des Amériques et figure parmi les plus bas des Caraïbes', 'Haïti est classée parmi les pays à faible développement humain. Avec un IDH d''environ 0,535 (2022), elle est le pays le plus pauvre des Amériques et figure parmi les pays les moins développés des Caraïbes. Cela se reflète dans les indicateurs de santé, d''éducation et de revenus.', 'Moyen'),
    (chap_id, 'Quel est le principal obstacle au développement économique d''Haïti selon les économistes ?', '["Le manque de ressources naturelles", "L''instabilité politique chronique, la faiblesse de l''État, la corruption et l''insécurité", "L''absence de main-d''œuvre qualifiée", "L''isolement géographique"]'::jsonb, 'L''instabilité politique chronique, la faiblesse de l''État, la corruption et l''insécurité', 'Les économistes identifient l''instabilité politique chronique, la faiblesse des institutions étatiques, la corruption endémique et l''insécurité comme les principaux obstacles au développement. Ces facteurs découragent l''investissement étranger, paralysent les services publics et empêchent l''accumulation de capital nécessaire au développement.', 'Moyen'),
    (chap_id, 'Quelle est la principale source d''énergie domestique en Haïti, responsable en partie de la déforestation ?', '["Le gaz naturel", "L''hydroélectricité", "Le bois et le charbon de bois (bwa chabon)", "L''énergie solaire"]'::jsonb, 'Le bois et le charbon de bois (bwa chabon)', 'La grande majorité des ménages haïtiens utilisent le bois ou le charbon de bois comme source d''énergie pour cuisiner. Cette dépendance au bois est l''une des principales causes de la déforestation massive d''Haïti (moins de 2 % de couvert forestier), avec des conséquences graves sur les sols et les risques d''inondation.', 'Moyen'),
    (chap_id, 'Quelles sont les principales ressources minières d''Haïti ?', '["Le pétrole et le gaz naturel offshore", "L''or, le cuivre et la bauxite (peu exploités)", "Le diamant et le platine", "Le fer et l''acier"]'::jsonb, 'L''or, le cuivre et la bauxite (peu exploités)', 'Haïti possède des réserves d''or, de cuivre, de bauxite et d''autres minerais dans le Nord et le Centre du pays. Cependant, ces ressources restent très peu exploitées en raison de l''instabilité politique, du manque d''infrastructure et des controverses environnementales et sociales sur l''exploitation minière.', 'Difficile'),
    (chap_id, 'Quel est l''impact du tremblement de terre de janvier 2010 sur la géographie humaine d''Haïti ?', '["Il n''a eu aucun impact significatif sur la distribution de la population", "Il a provoqué la mort de plus de 200 000 personnes, un exode massif de Port-au-Prince et des déplacements internes durables", "Il a entraîné une urbanisation accélérée de Port-au-Prince", "Il a amélioré les infrastructures de transport"]'::jsonb, 'Il a provoqué la mort de plus de 200 000 personnes, un exode massif de Port-au-Prince et des déplacements internes durables', 'Le séisme du 12 janvier 2010 (magnitude 7.0) a tué plus de 200 000 personnes, en blessé 300 000 et laissé 1,5 million de sans-abri à Port-au-Prince. Il a provoqué un exode vers les zones rurales et les villes de province, modifiant temporairement la distribution de la population haïtienne.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un "marché périodique" (mache) dans la géographie économique haïtienne ?', '["Un supermarché moderne à Port-au-Prince", "Un marché en plein air qui se tient à intervalles réguliers dans les villes et villages, organisé par des marchandes (madan sara)", "Un marché financier informel haïtien", "Un système de troc rural entre paysans"]'::jsonb, 'Un marché en plein air qui se tient à intervalles réguliers dans les villes et villages, organisé par des marchandes (madan sara)', 'Les marchés périodiques (mache) sont au cœur de l''économie informelle haïtienne. Les "madan sara" (marchandes itinérantes) jouent un rôle crucial dans la distribution des produits agricoles entre les zones rurales et urbaines. Ces marchés sont des espaces sociaux et économiques fondamentaux de la vie haïtienne.', 'Moyen'),
    (chap_id, 'Quel pourcentage de la population haïtienne n''a pas accès à l''électricité de réseau ?', '["Moins de 10 %", "Environ 25 %", "Environ 50 %", "Plus de 65 %"]'::jsonb, 'Plus de 65 %', 'Plus de 65 % de la population haïtienne n''a pas accès à l''électricité du réseau national (Électricité d''Haïti, EDH). Même ceux qui y ont accès bénéficient d''un service très irrégulier. Cette carence énergétique est un frein majeur au développement économique et à la qualité de vie.', 'Difficile'),
    (chap_id, 'Quel est le rôle des "tap-tap" dans la géographie des transports en Haïti ?', '["Des bateaux de pêche artisanale sur les côtes haïtiennes", "Des camionnettes ou autobus décorés constituant le principal moyen de transport public en Haïti", "Des motocyclettes taxis dans les zones rurales", "Des routes nationales pavées reliant les départements"]'::jsonb, 'Des camionnettes ou autobus décorés constituant le principal moyen de transport public en Haïti', 'Les tap-tap (camionnettes ou autobus colorés et décorés, souvent avec des messages religieux) constituent le principal moyen de transport public en Haïti. En l''absence d''un système de transport en commun public organisé, ils assurent la mobilité de millions de personnes dans les villes et entre les régions.', 'Facile'),
    (chap_id, 'Quel impact a la concentration de la population à Port-au-Prince sur le développement du pays ?', '["Elle favorise le développement équilibré de toutes les régions", "Elle crée une macrocéphalie urbaine qui aspire les ressources humaines et économiques des provinces, accentuant les inégalités régionales", "Elle permet une meilleure gestion centralisée des ressources nationales", "Elle a peu d''impact sur les régions périphériques"]'::jsonb, 'Elle crée une macrocéphalie urbaine qui aspire les ressources humaines et économiques des provinces, accentuant les inégalités régionales', 'La concentration excessive de la population, des services et des activités économiques à Port-au-Prince (macrocéphalie) crée de profondes inégalités régionales. Les provinces sont sous-équipées en services de base (hôpitaux, universités, routes), ce qui alimente l''exode rural vers la capitale et perpétue le déséquilibre.', 'Difficile'),
    (chap_id, 'Quel fruit tropical haïtien est une importante culture d''exportation depuis les années 1990 ?', '["La banane plantain", "La mangue Francisque", "La papaye", "L''ananas"]'::jsonb, 'La mangue Francisque', 'La mangue Francisque (Mangifera indica var. Francisque) est une variété spécifique à Haïti et l''une des principales cultures d''exportation depuis les années 1990. Exportée principalement vers les États-Unis et le Canada, elle représente une source de revenus importante pour les producteurs haïtiens.', 'Moyen');
  END IF;
END $$;

-- Chapitre 3 : Géographie de la Caraïbe et de l'Amérique latine NS2
DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 28 AND titre = 'Géographie de la Caraïbe et de l''Amérique latine' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que la région Caraïbe comprend géographiquement ?', '["Seulement les grandes îles (Cuba, Haïti, Porto Rico, Jamaïque)", "L''ensemble des îles de la mer des Caraïbes ainsi que les territoires côtiers de l''Amérique centrale et du Nord de l''Amérique du Sud riverains de cette mer", "L''Amérique centrale et le Mexique uniquement", "Seulement les anciennes colonies françaises et britanniques"]'::jsonb, 'L''ensemble des îles de la mer des Caraïbes ainsi que les territoires côtiers de l''Amérique centrale et du Nord de l''Amérique du Sud riverains de cette mer', 'La région Caraïbe (ou Antilles) englobe les îles de la mer des Caraïbes et les zones côtières continentales qui y sont bordées. Elle se divise géographiquement en Grandes Antilles (Cuba, Haïti/République Dominicaine, Porto Rico, Jamaïque) et Petites Antilles (arc insulaire au nord-est).', 'Moyen'),
    (chap_id, 'Quelle est la plus grande île des Caraïbes ?', '["Hispaniola", "Cuba", "Porto Rico", "La Jamaïque"]'::jsonb, 'Cuba', 'Cuba, avec 109 884 km², est la plus grande île des Caraïbes et des Grandes Antilles. Sa position stratégique à l''entrée du Golfe du Mexique lui a donné une importance géopolitique majeure, illustrée notamment lors de la crise des missiles de 1962.', 'Facile'),
    (chap_id, 'Qu''est-ce que la CARICOM ?', '["Une organisation militaire des Caraïbes", "La Communauté caribéenne, organisation régionale de coopération économique et politique regroupant des États membres anglophones et quelques membres associés", "Un traité commercial entre Haïti et les États-Unis", "L''organisation des pays producteurs de rhum"]'::jsonb, 'La Communauté caribéenne, organisation régionale de coopération économique et politique regroupant des États membres anglophones et quelques membres associés', 'La CARICOM (Caribbean Community) fondée en 1973 regroupe 15 États membres des Caraïbes et 5 membres associés. Son siège est à Georgetown (Guyana). Haïti est membre depuis 2002. La CARICOM vise à promouvoir la coopération économique, la libre circulation des personnes et la coordination politique entre ses membres.', 'Moyen'),
    (chap_id, 'Quel est le plus grand pays d''Amérique latine en superficie et en population ?', '["Le Mexique", "L''Argentine", "Le Brésil", "La Colombie"]'::jsonb, 'Le Brésil', 'Le Brésil est le plus grand pays d''Amérique latine et le 5e plus grand du monde (8,5 millions de km²). Sa population d''environ 215 millions d''habitants en fait aussi le pays le plus peuplé d''Amérique latine. Sa langue officielle est le portugais, contrairement à la majorité des autres pays latins-américains hispanophones.', 'Facile'),
    (chap_id, 'Quel est le plus grand fleuve du monde en volume d''eau, qui traverse l''Amérique du Sud ?', '["Le Rio de la Plata", "L''Orénoque", "Le Parana", "L''Amazone"]'::jsonb, 'L''Amazone', 'L''Amazone est le plus grand fleuve du monde par son débit (déversant 20 % de l''eau douce mondiale dans l''Atlantique). Long d''environ 6 400 km, il traverse le Brésil, le Pérou et la Colombie, drainant le plus grand bassin forestier tropical du monde.', 'Facile'),
    (chap_id, 'Dans quelle chaîne de montagnes se trouve le point culminant des Amériques, l''Aconcagua ?', '["Les Andes", "La Sierra Madre", "Les Appalaches", "La Cordillère des Caraïbes"]'::jsonb, 'Les Andes', 'L''Aconcagua (6 961 m, Argentine) est le point culminant des Amériques et de l''hémisphère occidental. Il se trouve dans les Andes, la plus longue chaîne de montagnes du monde (7 000 km), qui borde la côte Pacifique de l''Amérique du Sud du Venezuela à la Terre de Feu.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''isthme de Panama et quel est son importance géographique ?', '["Un grand lac en Amérique centrale", "La étroite bande de terre reliant l''Amérique centrale à l''Amérique du Sud, et site du Canal de Panama", "Une chaîne de montagnes entre le Costa Rica et la Colombie", "Un archipel dans la mer des Caraïbes"]'::jsonb, 'La étroite bande de terre reliant l''Amérique centrale à l''Amérique du Sud, et site du Canal de Panama', 'L''isthme de Panama est le passage terrestre reliant l''Amérique du Nord/centrale à l''Amérique du Sud. Le Canal de Panama (inauguré en 1914, élargi en 2016) y permet le passage des navires entre l''Atlantique (mer des Caraïbes) et le Pacifique, révolutionnant le commerce maritime mondial.', 'Moyen'),
    (chap_id, 'Quelles sont les Petites Antilles et comment sont-elles organisées géographiquement ?', '["L''ensemble des îles et pays caribéens de moins de 10 000 km²", "L''arc insulaire qui s''étend de Porto Rico au Venezuela, divisé en Antilles-au-Vent (nord) et Antilles-sous-le-Vent (sud)", "Les territoires ultramarins français des Caraïbes seulement", "Les îles situées au sud de Cuba et au nord d''Haïti"]'::jsonb, 'L''arc insulaire qui s''étend de Porto Rico au Venezuela, divisé en Antilles-au-Vent (nord) et Antilles-sous-le-Vent (sud)', 'Les Petites Antilles forment un arc de petites îles de Porto Rico (à l''ouest) jusqu''au large du Venezuela (à l''est). Elles se subdivisent en : Antilles-au-Vent (exposées aux alizés : Martinique, Guadeloupe, Sainte-Lucie, Barbade...) et Antilles-sous-le-Vent (plus abritées : Curaçao, Aruba, Trinidad-et-Tobago...).', 'Difficile'),
    (chap_id, 'Quel est le principal problème environnemental commun à la majorité des pays caribéens ?', '["L''aridité et le manque d''eau", "La vulnérabilité aux cyclones et à la montée du niveau des mers liée au changement climatique", "La pollution de l''air industriel", "La désertification des terres agricoles"]'::jsonb, 'La vulnérabilité aux cyclones et à la montée du niveau des mers liée au changement climatique', 'Les pays caribéens sont parmi les plus vulnérables au changement climatique : ouragans de plus en plus intenses, montée du niveau des mers menaçant les zones côtières et basses (comme les Bahamas), érosion côtière, blanchissement des coraux et salinisation des nappes phréatiques dans les petites îles.', 'Moyen'),
    (chap_id, 'Quelle est l''économie dominante des petites îles caribéennes comme la Barbade, la Jamaïque ou Saint-Martin ?', '["L''agriculture vivrière", "L''extraction pétrolière et minière", "Le tourisme international et les services financiers offshore", "L''industrie lourde"]'::jsonb, 'Le tourisme international et les services financiers offshore', 'La plupart des petites îles caribéennes ont des économies fondées sur le tourisme international (plages, croisières) et les services financiers offshore. Ces activités représentent souvent plus de 50 % du PIB de ces pays, les rendant vulnérables aux chocs externes (pandémies, récessions mondiales).', 'Moyen'),
    (chap_id, 'Quel détroit sépare Cuba et Haïti des États-Unis (Floride) ?', '["Le Détroit de Gibraltar", "Le Canal du Vent (Windward Passage) et le Détroit de Floride", "Le Détroit de Drake", "Le Canal de Yucatan"]'::jsonb, 'Le Canal du Vent (Windward Passage) et le Détroit de Floride', 'Le Détroit de Floride (entre Cuba et la Floride, environ 150 km) et le Canal du Vent (Windward Passage, entre Haïti et Cuba, environ 80 km) sont les passages maritimes stratégiques séparant les Caraïbes du sud-est des États-Unis. Leur importance géopolitique est considérable pour le commerce maritime américain.', 'Difficile'),
    (chap_id, 'Quel pays d''Amérique latine est le seul dont la langue officielle est le portugais ?', '["L''Uruguay", "Le Paraguay", "L''Argentine", "Le Brésil"]'::jsonb, 'Le Brésil', 'Le Brésil est l''unique pays d''Amérique latine dont la langue officielle est le portugais (héritage de la colonisation portugaise depuis 1500). Tous les autres pays d''Amérique latine ont l''espagnol comme langue officielle principale, à l''exception de Haïti (créole et français) et quelques territoires non-indépendants.', 'Facile'),
    (chap_id, 'Qu''est-ce que le bassin amazonien représente sur le plan écologique mondial ?', '["La plus grande étendue désertique du monde", "Le plus grand écosystème de forêt tropicale humide du monde, qui joue un rôle crucial dans la régulation du climat mondial", "La principale source mondiale d''eau douce souterraine", "La zone avec la plus grande biodiversité marine au monde"]'::jsonb, 'Le plus grand écosystème de forêt tropicale humide du monde, qui joue un rôle crucial dans la régulation du climat mondial', 'L''Amazonie est le plus grand écosystème forestier tropical du monde (6,7 millions de km²). Elle abrite une biodiversité extraordinaire (10 % des espèces connues), régule le cycle mondial de l''eau et stocke d''immenses quantités de carbone. Sa déforestation constitue l''une des crises environnementales majeures du XXIe siècle.', 'Moyen'),
    (chap_id, 'Comment s''appelle le phénomène océanique qui affecte périodiquement les côtes du Pacifique sud-américain et perturbe les précipitations en Amérique latine et dans les Caraïbes ?', '["La Nina", "El Niño (ENSO)", "L''Alizé", "Le Gulf Stream"]'::jsonb, 'El Niño (ENSO)', 'El Niño (ENSO : El Niño-Southern Oscillation) est un réchauffement périodique des eaux de surface du Pacifique tropical. Il perturbe les précipitations mondiales : sécheresses en Amérique centrale et au Brésil, pluies excessives sur les côtes Pacifiques de l''Amérique du Sud, et affecte les cyclones caribéens.', 'Difficile'),
    (chap_id, 'Quelles sont les deux principales langues officielles des pays membres de la CARICOM ?', '["Le français et l''espagnol", "L''anglais et le néerlandais", "L''anglais (dominant) et le français (Haïti)", "Le créole et l''anglais"]'::jsonb, 'L''anglais (dominant) et le français (Haïti)', 'La CARICOM est majoritairement anglophone (Jamaïque, Barbade, Trinité-et-Tobago, Guyana, etc.). Haïti est le seul membre où les langues officielles sont le créole haïtien et le français. Quelques pays membres ou associés utilisent le néerlandais (Suriname) ou l''espagnol (Cuba est non-membre).', 'Moyen'),
    (chap_id, 'Quel est l''enjeu géopolitique principal du Canal de Panama pour les Caraïbes ?', '["Il fournit de l''eau potable à tous les pays caribéens", "Il contrôle le passage maritime entre l''Atlantique et le Pacifique, déterminant les flux commerciaux mondiaux qui transitent par les ports caribéens", "Il génère des ressources hydrauliques pour l''irrigation en Amérique centrale", "Il est une frontière naturelle entre le nord et le sud des Amériques"]'::jsonb, 'Il contrôle le passage maritime entre l''Atlantique et le Pacifique, déterminant les flux commerciaux mondiaux qui transitent par les ports caribéens', 'Le Canal de Panama est l''une des voies de navigation les plus importantes du monde. Il permet le transit de milliers de navires par an entre l''Atlantique et le Pacifique, renforçant l''importance stratégique des ports caribéens comme points de transit et de ravitaillement du commerce maritime mondial.', 'Difficile'),
    (chap_id, 'Comment la relation géographique entre Haïti et la République Dominicaine illustre-t-elle des contrastes de développement ?', '["Les deux pays ont un niveau de développement identique malgré leur histoire commune", "L''économie dominicaine est basée sur le pétrole, l''haïtienne sur le café", "Les deux pays partagent la même île mais présentent des contrastes frappants : la République Dominicaine est plus développée, plus boisée et touristiquement plus active", "Les frontières géographiques ont empêché tout échange économique entre les deux pays"]'::jsonb, 'Les deux pays partagent la même île mais présentent des contrastes frappants : la République Dominicaine est plus développée, plus boisée et touristiquement plus active', 'Haïti et la République Dominicaine partagent l''île d''Hispaniola mais présentent des contrastes saisissants visibles même depuis l''espace (la frontière est visible par la déforestation du côté haïtien). La RD a un PIB par habitant 8 fois supérieur, une industrie touristique florissante et un taux de déforestation bien plus faible.', 'Moyen'),
    (chap_id, 'Quelle est la principale langue de l''Amérique centrale continentale (Guatemala, Honduras, Nicaragua, Costa Rica, El Salvador, Panama) ?', '["Le portugais", "Le créole anglais", "L''espagnol", "Le quechua"]'::jsonb, 'L''espagnol', 'L''espagnol est la langue officielle de tous les pays d''Amérique centrale continentale, héritage de la colonisation espagnole (XVIe siècle). Le Belize est l''exception : pays d''Amérique centrale dont l''anglais est la langue officielle (ancienne colonie britannique, membre de la CARICOM).', 'Facile');
  END IF;
END $$;
