-- Supplement Géologie (matiere_id=12) — NS1 et NS2
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 12 AND titre = 'Structure interne de la Terre' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quelles sont les trois couches principales de la structure interne de la Terre, de l''extérieur vers l''intérieur ?', '["Eau, roche, métal","Croûte, manteau, noyau","Sol, granite, fer","Lithosphère, atmosphère, hydrosphère"]'::jsonb, 'Croûte, manteau, noyau', 'La Terre est structurée en couches concentriques : croûte (0-70 km), manteau (70-2900 km), noyau (2900-6371 km).', 'Facile'),
    (chap_id, 'Comment les scientifiques étudient-ils l''intérieur de la Terre qu''ils ne peuvent pas observer directement ?', '["Par des forages jusqu''au centre","En analysant les ondes sismiques (P et S) qui se propagent dans la Terre et changent de vitesse selon les milieux traversés","Par des volcans uniquement","Par des satellites"]'::jsonb, 'En analysant les ondes sismiques (P et S) qui se propagent dans la Terre et changent de vitesse selon les milieux traversés', 'Les ondes sismiques traversent différents milieux ; l''onde S ne passe pas dans le noyau externe liquide, révélant sa nature.', 'Moyen'),
    (chap_id, 'Quelle est la différence entre la croûte océanique et la croûte continentale ?', '["Aucune différence","La croûte océanique est plus dense (basalte, ~3 g/cm³, 5-10 km d''épaisseur) que la croûte continentale (granite, ~2,7 g/cm³, 30-70 km)","La croûte continentale est plus dense","Elles ont la même composition"]'::jsonb, 'La croûte océanique est plus dense (basalte, ~3 g/cm³, 5-10 km d''épaisseur) que la croûte continentale (granite, ~2,7 g/cm³, 30-70 km)', 'Ces différences de densité expliquent la subduction : la croûte océanique s''enfonce sous la continentale.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le manteau terrestre et quel est son état ?', '["Un liquide homogène","Une couche solide (mais pouvant se déformer sur de longues périodes) composée principalement de péridotite, entre la croûte et le noyau","Un gaz","Uniquement du fer"]'::jsonb, 'Une couche solide (mais pouvant se déformer sur de longues périodes) composée principalement de péridotite, entre la croûte et le noyau', 'Le manteau est solide mais viscoélastique (comme une cire) ; sa convection entraîne les plaques tectoniques.', 'Moyen'),
    (chap_id, 'Quelle est la composition probable du noyau terrestre et son état ?', '["Granite solide","Un noyau externe liquide et un noyau interne solide, principalement composés de fer et de nickel","Du basalte liquide","Du calcium et du magnésium"]'::jsonb, 'Un noyau externe liquide et un noyau interne solide, principalement composés de fer et de nickel', 'Le noyau externe liquide (Fe-Ni) génère le champ magnétique terrestre par effet dynamo ; le noyau interne est solide.', 'Moyen'),
    (chap_id, 'Qu''est-ce que l''isostasie terrestre ?', '["La rigidité de la croûte","L''équilibre gravitationnel entre la croûte terrestre et le manteau : les parties légères flottent plus haut (montagnes à racines profondes), les parties denses s''enfoncent","La solidité du noyau","Le gradient géothermique"]'::jsonb, 'L''équilibre gravitationnel entre la croûte terrestre et le manteau : les parties légères flottent plus haut (montagnes à racines profondes), les parties denses s''enfoncent', 'L''isostasie (comme des icebergs) explique le rebond isostatique post-glaciaire et les racines profondes des chaînes de montagnes.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le gradient géothermique et quelle est sa valeur approximative ?', '["La variation de pression avec la profondeur","L''augmentation de température avec la profondeur : environ 30°C/km dans la croûte, avec des variations selon les régions","La conductivité électrique de la croûte","La densité de la croûte"]'::jsonb, 'L''augmentation de température avec la profondeur : environ 30°C/km dans la croûte, avec des variations selon les régions', 'Le gradient géothermique (chaleur interne de la Terre) est plus élevé aux dorsales océaniques et dans les zones volcaniques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la lithosphère et l''asthénosphère ?', '["Deux types de roches","La lithosphère est la partie rigide externe (croûte + manteau supérieur) découpée en plaques ; l''asthénosphère est le manteau ductile sur lequel flottent les plaques","Deux couches du noyau","Des zones atmosphériques"]'::jsonb, 'La lithosphère est la partie rigide externe (croûte + manteau supérieur) découpée en plaques ; l''asthénosphère est le manteau ductile sur lequel flottent les plaques', 'La lithosphère (~100 km) se divise en plaques tectoniques qui se déplacent sur l''asthénosphère semi-fluide.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le champ magnétique terrestre et comment se forme-t-il ?', '["Il est permanent et immuable","Il est généré par la rotation du noyau externe liquide (fer-nickel conducteur) créant un effet dynamo ; il nous protège du vent solaire","Il provient de la croûte","Il est généré par les volcans"]'::jsonb, 'Il est généré par la rotation du noyau externe liquide (fer-nickel conducteur) créant un effet dynamo ; il nous protège du vent solaire', 'La magnétosphère terrestre dévie les particules du vent solaire ; les aurores polaires se forment là où les particules entrent.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le forage scientifique de Kola (Russie) a révélé sur l''intérieur de la Terre ?', '["Il a atteint le manteau","À 12 km de profondeur, il a confirmé l''augmentation de température (180°C, plus que prévu) et la présence d''eau à grande profondeur, contredisant certains modèles","Il n''a rien découvert","Il a trouvé du fer pur"]'::jsonb, 'À 12 km de profondeur, il a confirmé l''augmentation de température (180°C, plus que prévu) et la présence d''eau à grande profondeur, contredisant certains modèles', 'Le Puits ultra-profond de Kola (1970-1994, 12,26 km) reste le forage scientifique le plus profond de l''histoire.', 'Moyen'),
    (chap_id, 'Comment les météorites nous informent-elles sur la composition du noyau terrestre ?', '["Elles ne fournissent aucune information","Les chondrites métalliques (composées de fer-nickel) sont considérées comme analogues au matériau du noyau terrestre, car issues d''une même nébuleuse solaire","Les météorites sont composées de granit","Les météorites sont uniquement utiles pour dater la Terre"]'::jsonb, 'Les chondrites métalliques (composées de fer-nickel) sont considérées comme analogues au matériau du noyau terrestre, car issues d''une même nébuleuse solaire', 'Les météorites métalliques Fe-Ni et la modélisation sismologique convergent pour confirmer la composition du noyau.', 'Moyen'),
    (chap_id, 'Quel est l''âge estimé de la Terre et comment le détermine-t-on ?', '["10 000 ans","4,54 milliards d''années, déterminé par la datation radiométrique (isotopes radioactifs comme l''uranium-plomb) de météorites et des plus anciennes roches terrestres","100 millions d''années","1 milliard d''années"]'::jsonb, '4,54 milliards d''années, déterminé par la datation radiométrique (isotopes radioactifs comme l''uranium-plomb) de météorites et des plus anciennes roches terrestres', 'La datation Pb-Pb de météorites (Clair Patterson, 1956) a établi l''âge du système solaire à ~4,56 Ga.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 12 AND titre = 'Tectonique des plaques' AND niveau_v4 = 'NS1';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qui a proposé la théorie de la dérive des continents et sur quelles preuves ?', '["Isaac Newton","Alfred Wegener en 1912, basé sur la complémentarité des côtes, les fossiles communs et les similitudes géologiques entre continents aujourd''hui séparés","Charles Darwin","Albert Einstein"]'::jsonb, 'Alfred Wegener en 1912, basé sur la complémentarité des côtes, les fossiles communs et les similitudes géologiques entre continents aujourd''hui séparés', 'Wegener n''avait pas de mécanisme convaincant ; la tectonique des plaques, confirmée dans les années 1960, a validé son intuition.', 'Facile'),
    (chap_id, 'Qu''est-ce que la dorsale océanique et quel est son rôle dans la tectonique des plaques ?', '["Une fosse océanique","Une chaîne de montagnes sous-marines où du nouveau fond océanique est créé par remontée de magma (expansion océanique ou «seafloor spreading»)","Un volcan continental","Un archipel de corail"]'::jsonb, 'Une chaîne de montagnes sous-marines où du nouveau fond océanique est créé par remontée de magma (expansion océanique ou «seafloor spreading»)', 'La dorsale médio-atlantique est le siège de l''expansion océanique qui éloigne l''Amérique et l''Europe.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la subduction et dans quel contexte se produit-elle ?', '["La création de croûte","L''enfoncement d''une plaque océanique dense sous une autre plaque (océanique ou continentale) dans le manteau, créant des fosses, des volcans et des séismes","Un mouvement horizontal des plaques","L''ouverture d''un rift"]'::jsonb, 'L''enfoncement d''une plaque océanique dense sous une autre plaque (océanique ou continentale) dans le manteau, créant des fosses, des volcans et des séismes', 'La subduction (ex. Pacifique sous l''Amérique du Sud) crée les Andes, les Antilles et les fosses océaniques profondes.', 'Moyen'),
    (chap_id, 'Quel est le mécanisme moteur du déplacement des plaques tectoniques ?', '["La rotation de la Terre","La convection du manteau asthenosphérique : la chaleur interne crée des courants de matière qui entraînent les plaques","Les marées océaniques","Le vent solaire"]'::jsonb, 'La convection du manteau asthenosphérique : la chaleur interne crée des courants de matière qui entraînent les plaques', 'La convection mantellique (+ le poids des plaques qui plongent en subduction) est le moteur principal de la tectonique.', 'Moyen'),
    (chap_id, 'Comment se forment les chaînes de montagnes selon la tectonique des plaques ?', '["Par l''érosion uniquement","Par la collision de plaques tectoniques (orogénèse) : la collision Inde-Eurasie a formé l''Himalaya, les Alpes résultent de la collision Afrique-Europe","Par les volcans uniquement","Par les tremblements de terre uniquement"]'::jsonb, 'Par la collision de plaques tectoniques (orogénèse) : la collision Inde-Eurasie a formé l''Himalaya, les Alpes résultent de la collision Afrique-Europe', 'L''orogénèse par collision (zones de convergence) plisse et épaissit la croûte continentale, créant les grandes chaînes.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''une faille transformante et quel en est un exemple célèbre ?', '["Une faille normale","Une faille où deux plaques glissent horizontalement l''une par rapport à l''autre, sans création ni destruction de croûte ; ex. la faille de San Andreas en Californie","Une zone de subduction","Une dorsale océanique"]'::jsonb, 'Une faille où deux plaques glissent horizontalement l''une par rapport à l''autre, sans création ni destruction de croûte ; ex. la faille de San Andreas en Californie', 'Les failles transformantes connectent les dorsales ; la faille Enriquillo en Haïti est un exemple régional (séisme 2010).', 'Moyen'),
    (chap_id, 'Quelle est la vitesse typique de déplacement des plaques tectoniques ?', '["Quelques mètres par an","Quelques centimètres par an (2-15 cm/an selon les plaques), comparable à la croissance des ongles","Quelques kilomètres par an","Immobiles"]'::jsonb, 'Quelques centimètres par an (2-15 cm/an selon les plaques), comparable à la croissance des ongles', 'La dorsale médio-atlantique s''ouvre à ~2 cm/an ; la plaque Pacifique se déplace à ~10 cm/an.', 'Facile'),
    (chap_id, 'Qu''est-ce que le volcanisme de point chaud et comment diffère-t-il du volcanisme de zone de subduction ?', '["Ils sont identiques","Les points chauds sont des panaches de magma remontant du manteau profond, créant des îles en milieu océanique (Hawaï, Islande) indépendamment des frontières de plaques","Les points chauds se trouvent uniquement aux dorsales","Le volcanisme de subduction est plus calme"]'::jsonb, 'Les points chauds sont des panaches de magma remontant du manteau profond, créant des îles en milieu océanique (Hawaï, Islande) indépendamment des frontières de plaques', 'Les chaînes d''îles hawaïennes illustrent le point chaud fixe : la plaque se déplace au-dessus, créant une succession d''îles.', 'Moyen'),
    (chap_id, 'Comment la tectonique des plaques influence-t-elle la géologie des Caraïbes et d''Haïti ?', '["Les Caraïbes ne sont pas concernées","La plaque Caraïbe est coincée entre les plaques nord-américaine et sud-américaine ; Haïti est traversée par des failles majeures (Enriquillo, Septentrional) causant une forte sismicité et du volcanisme","Les Antilles sont sur une seule plaque","Il n''y a pas de tectonique dans les Caraïbes"]'::jsonb, 'La plaque Caraïbe est coincée entre les plaques nord-américaine et sud-américaine ; Haïti est traversée par des failles majeures (Enriquillo, Septentrional) causant une forte sismicité et du volcanisme', 'Le séisme de 2010 (magnitude 7.0) résulte du glissement de la faille Enriquillo-Plantain Garden à la frontière des plaques.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la paléomagnétisme et comment a-t-il confirmé l''expansion océanique ?', '["L''étude des aimants","L''étude du magnétisme fossile des roches, montrant des bandes symétriques d''inversions magnétiques de part et d''autre des dorsales, preuve de l''expansion du fond océanique","L''étude de la boussole","La datation par le carbone 14"]'::jsonb, 'L''étude du magnétisme fossile des roches, montrant des bandes symétriques d''inversions magnétiques de part et d''autre des dorsales, preuve de l''expansion du fond océanique', 'Le paléomagnétisme (Vine, Matthews, Morley, 1963) a fourni la preuve décisive de l''expansion des fonds océaniques.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le supercontinent Pangée et quand a-t-il existé ?', '["Un continent actuel","Le supercontinent unique regroupant toutes les terres émergées actuelles, qui existait il y a environ 300-200 millions d''années avant de se fragmenter","Un continent hypothétique futur","L''Antarctique seul"]'::jsonb, 'Le supercontinent unique regroupant toutes les terres émergées actuelles, qui existait il y a environ 300-200 millions d''années avant de se fragmenter', 'La Pangée (Wegener) s''est fragmentée en Laurasie (nord) et Gondwana (sud), puis en continents actuels.', 'Facile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 12 AND titre = 'Les roches et le cycle des roches' AND niveau_v4 = 'NS2';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quels sont les trois grands types de roches et comment se forment-ils ?', '["Marbre, calcaire, granit","Ignées (refroidissement du magma), sédimentaires (compaction de sédiments) et métamorphiques (transformation par chaleur/pression)","Sable, argile, basalte","Diamant, charbon, quartz"]'::jsonb, 'Ignées (refroidissement du magma), sédimentaires (compaction de sédiments) et métamorphiques (transformation par chaleur/pression)', 'Les trois types de roches forment un cycle continu interconnecté par les processus géologiques.', 'Facile'),
    (chap_id, 'Comment différencie-t-on les roches magmatiques plutoniques des roches volcaniques ?', '["Par leur couleur","Les plutoniques (granite) se forment par refroidissement lent en profondeur, formant de grands cristaux ; les volcaniques (basalte) se forment par refroidissement rapide en surface, formant de petits cristaux ou une texture vitreuse","Par leur âge","Par leur composition chimique uniquement"]'::jsonb, 'Les plutoniques (granite) se forment par refroidissement lent en profondeur, formant de grands cristaux ; les volcaniques (basalte) se forment par refroidissement rapide en surface, formant de petits cristaux ou une texture vitreuse', 'La texture des roches magmatiques (grenue, microlithique, vitreuse) reflète la vitesse de refroidissement du magma.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le métamorphisme et quels facteurs le contrôlent ?', '["La formation de roches sédimentaires","La transformation de roches préexistantes par augmentation de température et/ou pression sans fusion, modifiant la minéralogie et la texture","La solidification du magma","L''érosion des roches"]'::jsonb, 'La transformation de roches préexistantes par augmentation de température et/ou pression sans fusion, modifiant la minéralogie et la texture', 'Le métamorphisme de contact (chaleur du magma) et régional (enfouissement en subduction) créent des minéraux caractéristiques.', 'Moyen'),
    (chap_id, 'Comment se forment les roches sédimentaires et quel est leur intérêt pour la géologie ?', '["Par refroidissement du magma","Par l''accumulation, le compaction et la cimentation de sédiments (détritiques, chimiques ou biochimiques) ; elles contiennent des fossiles et enregistrent l''histoire de la Terre","Par métamorphisme","Par fusion des roches"]'::jsonb, 'Par l''accumulation, le compaction et la cimentation de sédiments (détritiques, chimiques ou biochimiques) ; elles contiennent des fossiles et enregistrent l''histoire de la Terre', 'Les roches sédimentaires couvrent 75% de la surface terrestre et contiennent 99,9% des fossiles connus.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le cycle des roches et quels processus y participent ?', '["Un cycle uniquement magmatique","Le cycle géologique dans lequel les roches passent par différents états (magmatique, sédimentaire, métamorphique) via l''érosion, la sédimentation, l''enfouissement, le métamorphisme et la fusion","Un cycle uniquement sédimentaire","Un processus irréversible"]'::jsonb, 'Le cycle géologique dans lequel les roches passent par différents états (magmatique, sédimentaire, métamorphique) via l''érosion, la sédimentation, l''enfouissement, le métamorphisme et la fusion', 'Le cycle des roches est le grand cycle géologique à long terme (millions d''années) qui recycle la matière terrestre.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la diagenèse dans la formation des roches sédimentaires ?', '["La fusion des roches","L''ensemble des transformations physico-chimiques qui transforment des sédiments meubles en roche sédimentaire dure (compaction + cimentation)","Le métamorphisme regional","L''érosion chimique"]'::jsonb, 'L''ensemble des transformations physico-chimiques qui transforment des sédiments meubles en roche sédimentaire dure (compaction + cimentation)', 'La diagenèse se produit à basse température et pression lors de l''enfouissement des sédiments.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la minéralogie et quel est le minéral le plus abondant de la croûte terrestre ?', '["L''étude des fossiles","L''étude scientifique des minéraux ; les feldspaths sont les minéraux les plus abondants de la croûte (plus de 50%), suivis du quartz","L''étude des roches","L''étude des volcans"]'::jsonb, 'L''étude scientifique des minéraux ; les feldspaths sont les minéraux les plus abondants de la croûte (plus de 50%), suivis du quartz', 'Les feldspaths (alumino-silicates de K, Na, Ca) et le quartz (SiO2) dominent la composition de la croûte continentale.', 'Moyen'),
    (chap_id, 'Comment la datation radiométrique permet-elle de dater les roches ?', '["Par la couleur des roches","En mesurant le rapport isotope parent/isotope fils radioactif dans une roche, et en connaissant la demi-vie du radioélement (ex. U-Pb pour les très anciennes roches)","Par la dureté des minéraux","Par la position stratigraphique uniquement"]'::jsonb, 'En mesurant le rapport isotope parent/isotope fils radioactif dans une roche, et en connaissant la demi-vie du radioélement (ex. U-Pb pour les très anciennes roches)', 'La datation U-Pb (demi-vie 4,47 Ga) date les roches très anciennes ; le C-14 (demi-vie 5730 ans) les matériaux organiques récents.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le principe de superposition en stratigraphie et qui l''a établi ?', '["La couche la plus ancienne est au sommet","Dans une séquence sédimentaire non perturbée, la couche la plus récente est au sommet et la plus ancienne à la base (Sténon, XVIIe siècle)","Les couches sont toujours horizontales","Les couches se forment verticalement"]'::jsonb, 'Dans une séquence sédimentaire non perturbée, la couche la plus récente est au sommet et la plus ancienne à la base (Sténon, XVIIe siècle)', 'Le principe de Sténon (1669) est fondamental pour lire l''histoire géologique dans les coupes stratigraphiques.', 'Facile'),
    (chap_id, 'Qu''est-ce que la géologie haïtienne et quels types de roches y trouve-t-on ?', '["Haïti n''a que des roches sédimentaires","Haïti présente des roches volcaniques (basaltes), métamorphiques (schistes, quartzites), sédimentaires carbonatées (calcaires) et des intrusions de granite, reflétant son histoire tectonique complexe","Haïti ne présente que du granite","Haïti n''a aucune roche volcanique"]'::jsonb, 'Haïti présente des roches volcaniques (basaltes), métamorphiques (schistes, quartzites), sédimentaires carbonatées (calcaires) et des intrusions de granite, reflétant son histoire tectonique complexe', 'La géologie haïtienne (caldeira, roches calcaires karstiques, minéraux précieux dans le Nord) est variée et économiquement importante.', 'Moyen');
  END IF;
END $$;
