-- Supplement Économie NS3-NS4 (matiere_id=15)
-- Objectif : porter chaque chapitre à ≥ 20 questions

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'Commerce international et mondialisation' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quel est le théorème HOS (Heckscher-Ohlin-Samuelson) sur le commerce international ?', '["Les pays échangent des biens identiques","Chaque pays se spécialise dans les","Le libre-échange est toujours bénéfique","Le protectionnisme augmente le bien-être"]'::jsonb, 'Chaque pays se spécialise dans les', 'HOS : un pays abondant en travail exporte des biens intensifs en travail et importe des biens intensifs en capital.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''un tarif douanier et son effet ?', '["Une taxe sur les importations qui","Une subvention aux exportateurs","Un quota d''importation","Un accord commercial"]'::jsonb, 'Une taxe sur les importations qui', 'Le tarif réduit les importations, protège les producteurs nationaux mais pénalise les consommateurs.', 'Moyen'),
    (chap_id, 'Qu''est-ce qu''un quota d''importation ?', '["Une taxe sur les biens importés","Une limite quantitative sur les","Une subvention à l''exportation","Un accord de libre-échange"]'::jsonb, 'Une limite quantitative sur les', 'Le quota fixe un plafond aux importations, créant une rente pour les importateurs disposant des licences.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la balance commerciale ?', '["Le total des dettes d''un pays","La différence entre exportations et","Le PIB net","Le solde budgétaire"]'::jsonb, 'La différence entre exportations et', 'Si X > M : excédent commercial ; si X < M : déficit commercial. Composante du compte courant.', 'Facile'),
    (chap_id, 'Quel organisme régule le commerce international depuis 1995 ?', '["FMI","Banque Mondiale","OMC (Organisation Mondiale du Commerce)","OCDE"]'::jsonb, 'OMC (Organisation Mondiale du Commerce)', 'L''OMC succède au GATT et supervise les règles du commerce international, le règlement des différends.', 'Facile'),
    (chap_id, 'Qu''est-ce que le dumping dans le commerce international ?', '["Exporter des matières premières","Vendre un bien à l''étranger en dessous","Un accord commercial bilatéral","Une subvention cachée"]'::jsonb, 'Vendre un bien à l''étranger en dessous', 'Le dumping est considéré comme une pratique déloyale ; l''OMC autorise des droits antidumping en réponse.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la balance des paiements ?', '["Le budget de l''État","Le document qui enregistre toutes les","Le solde commercial","La dette extérieure"]'::jsonb, 'Le document qui enregistre toutes les', 'La balance des paiements comprend le compte courant, le compte de capital et le compte financier.', 'Moyen'),
    (chap_id, 'Quel est le paradoxe de Leontief ?', '["Les États-Unis exportent des biens","Les pays pauvres exportent plus","Le libre-échange nuit aux riches","Les tarifs stimulent la croissance"]'::jsonb, 'Les États-Unis exportent des biens', 'Leontief (1953) contredit HOS : les USA, très capitalisés, exportent des biens travail-intensifs (en réalité capital humain).', 'Difficile'),
    (chap_id, 'Qu''est-ce que la globalisation financière ?', '["L''unification des monnaies","L''intégration croissante des marchés","Le commerce de marchandises","L''aide internationale"]'::jsonb, 'L''intégration croissante des marchés', 'La globalisation financière depuis les années 1980 accélère les flux de capitaux mais amplifie les crises.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la "triade" dans le commerce mondial ?', '["Trois grandes banques","Les États-Unis","Trois matières premières","Les trois plus grands pays exportateurs"]'::jsonb, 'Les États-Unis', 'La triade de Kenichi Ohmae désigne les trois pôles dominants de la mondialisation économique.', 'Difficile'),
    (chap_id, 'Quel est l''argument de l''industrie naissante pour le protectionnisme ?', '["Protéger les industries déclinantes","Protéger temporairement une nouvelle","Restreindre toutes les importations","Subventionner les exportations"]'::jsonb, 'Protéger temporairement une nouvelle', 'Friedrich List : les pays en développement ont intérêt à protéger leurs industries embryonnaires.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la "maladie hollandaise" ?', '["Une pandémie économique","La désindustrialisation causée par","Un problème bancaire","Une crise de la dette"]'::jsonb, 'La désindustrialisation causée par', 'La découverte de gaz naturel en Hollande (1960s) renchérit la monnaie et déstabilisa l''industrie manufacturière.', 'Difficile'),
    (chap_id, 'Qu''est-ce qu''une zone de libre-échange ?', '["Un pays sans douane interne","Un accord entre pays supprimant les","Une union monétaire","Un accord tarifaire commun"]'::jsonb, 'Un accord entre pays supprimant les', 'Ex : ALENA/USMCA. Différent de l''union douanière qui fixe un tarif extérieur commun.', 'Moyen');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'Macroéconomie : chômage, inflation et politiques économiques' AND niveau_v4 = 'NS3';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Qu''est-ce que le chômage frictionnel ?', '["Le chômage dû à la crise","Le chômage temporaire lié à la","Le chômage de longue durée","Le sous-emploi"]'::jsonb, 'Le chômage temporaire lié à la', 'Le chômage frictionnel est inévitable et bénin : il correspond aux délais normaux de recherche d''emploi.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la courbe de Phillips originale (années 1960) établit ?', '["Une relation positive entre inflation et chômage","Une relation inverse entre inflation et","Une relation entre PIB et emploi","La neutralité de la monnaie"]'::jsonb, 'Une relation inverse entre inflation et', 'Phillips (1958) : baisse du chômage → hausse des salaires → hausse des prix. Arbitrage inflation/chômage.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le taux de chômage naturel (NAIRU) ?', '["Zéro chômage","Le taux de chômage compatible avec une","Le taux de chômage en pleine crise","Le plein emploi absolu"]'::jsonb, 'Le taux de chômage compatible avec une', 'Le NAIRU (Friedman, Phelps) est le taux d''équilibre à long terme ; toute tentative de le dépasser génère de l''inflation.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la politique budgétaire ?', '["La politique de la banque centrale","L''utilisation des dépenses publiques et","La politique commerciale","La régulation financière"]'::jsonb, 'L''utilisation des dépenses publiques et', 'La politique budgétaire (gouvernement) stimule (déficit) ou freine (excédent) l''économie.', 'Facile'),
    (chap_id, 'Qu''est-ce que le déficit public ?', '["La dette totale d''un pays","L''excès des dépenses publiques sur les","Le déficit commercial","L''inflation budgétaire"]'::jsonb, 'L''excès des dépenses publiques sur les', 'Déficit = dépenses - recettes > 0. Il s''accumule pour former la dette publique.', 'Facile'),
    (chap_id, 'Qu''est-ce que l''austérité budgétaire et ses effets débattus ?', '["Des dépenses illimitées","Réduction du déficit par coupes dans","Une politique de relance","La nationalisation d''entreprises"]'::jsonb, 'Réduction du déficit par coupes dans', 'Le débat austérité/relance oppose ordolibéraux/FMI à Keynes/Krugman sur les multiplicateurs en récession.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le quantitative easing (QE) ?', '["Un impôt sur les transactions","Des achats d''actifs par la banque","Une réforme fiscale","Un contrôle des capitaux"]'::jsonb, 'Des achats d''actifs par la banque', 'Le QE (Fed, BCE) a été massivement utilisé après 2008 pour stimuler l''économie quand les taux étaient à zéro.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la trappe à liquidité (Keynes) ?', '["Un excès d''épargne","Une situation où la politique monétaire","Une crise bancaire","Un déficit de consommation"]'::jsonb, 'Une situation où la politique monétaire', 'Dans la trappe à liquidité, les agents thésaurisent au lieu d''investir même avec des taux nuls.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la règle de Taylor en politique monétaire ?', '["Un accord international","Une règle prescrivant le taux directeur","Un indicateur de croissance","Un modèle de change"]'::jsonb, 'Une règle prescrivant le taux directeur', 'La règle de Taylor (1993) : i = r* + π + 0.5(π-π*) + 0.5(y-y*). Guide les banques centrales.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''effet d''éviction en politique budgétaire ?', '["Un effet multiplicateur positif","Des dépenses publiques financées par","Une réduction des impôts","Un effet de la politique monétaire"]'::jsonb, 'Des dépenses publiques financées par', 'L''effet d''éviction atténue l''impact du multiplicateur : l''État emprunte au détriment du secteur privé.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la théorie quantitative de la monnaie (MV = PQ) ?', '["La valeur de la monnaie","La relation entre masse monétaire (M)","Le taux de change","Le multiplicateur de crédit"]'::jsonb, 'La relation entre masse monétaire (M)', 'Fisher : toute augmentation de M non compensée par Q génère de l''inflation (P augmente).', 'Difficile'),
    (chap_id, 'Qu''est-ce que le paradoxe de l''épargne (Keynes) ?', '["Épargner est toujours bénéfique","Ce qui est raisonnable pour un ménage","L''épargne est inutile","L''investissement dépend du revenu"]'::jsonb, 'Ce qui est raisonnable pour un ménage', 'Le paradoxe de parcimonie : une hausse collective de l''épargne réduit la demande et le revenu global.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le "taper tantrum" et quel risque illustre-t-il ?', '["Un type de crise agricole","La volatilité des marchés émergents","Une crise de la zone euro","Un choc pétrolier"]'::jsonb, 'La volatilité des marchés émergents', 'Le taper tantrum (2013) illustre la dépendance des marchés émergents à la liquidité mondiale américaine.', 'Difficile');
  END IF;
END $$;

DO $$
DECLARE chap_id INTEGER;
BEGIN
  SELECT id INTO chap_id FROM chapitres WHERE matiere_id = 15 AND titre = 'Économie du développement et Haïti' AND niveau_v4 = 'NS4';
  IF chap_id IS NOT NULL THEN
    INSERT INTO questions (chapitre_id, enonce, choix, bonne_reponse, explication, niveau_complexite) VALUES
    (chap_id, 'Quels sont les principaux indicateurs de la pauvreté selon la Banque Mondiale ?', '["PIB et exportations","Pauvreté monétaire (seuil < 2","Taux de change et inflation","Dette extérieure et déficit"]'::jsonb, 'Pauvreté monétaire (seuil < 2', 'La Banque Mondiale utilise le seuil de 2,15 $ PPA/jour et des indicateurs multidimensionnels.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le cercle vicieux de la pauvreté (Nurkse) ?', '["Les pauvres ne veulent pas travailler","Faible revenu → faible épargne → faible","La corruption gouvernementale","Le manque d''aide internationale"]'::jsonb, 'Faible revenu → faible épargne → faible', 'Nurkse : les pays pauvres sont pris dans un équilibre de faible niveau d''où ils peinent à sortir sans aide.', 'Difficile'),
    (chap_id, 'Quel rôle jouent les transferts de la diaspora pour les économies comme Haïti ?', '["Aucun rôle significatif","Principal flux de revenus extérieurs","Uniquement des investissements","Un fardeau pour l''économie"]'::jsonb, 'Principal flux de revenus extérieurs', 'En Haïti, les remises de la diaspora représentent une part majeure du PIB (>30%), source vitale de devises.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "dutch disease" (maladie hollandaise) appliqué aux pays pétroliers ?', '["Une épidémie économique","L''appréciation de la monnaie et la","Un avantage concurrentiel","La dépendance aux importations"]'::jsonb, 'L''appréciation de la monnaie et la', 'Les pays pétroliers voient leur monnaie s''apprécier, rendant leurs exportations non-pétrolières non compétitives.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''ajustement structurel imposé par le FMI aux pays en développement ?', '["Des aides sans conditions","Des réformes libérales conditionnant","Des nationalisations","Des politiques protectionnistes"]'::jsonb, 'Des réformes libérales conditionnant', 'Les PAS (Plans d''Ajustement Structurel) des années 1980-90 ont été critiqués pour leurs effets sociaux.', 'Difficile'),
    (chap_id, 'Qu''est-ce que l''économie informelle dans les pays en développement ?', '["L''économie souterraine criminelle","L''ensemble des activités économiques","Le secteur agricole","Le commerce de rue légal"]'::jsonb, 'L''ensemble des activités économiques', 'En Haïti et dans les PED, le secteur informel représente souvent plus de 50% de l''emploi.', 'Moyen'),
    (chap_id, 'Quel est l''impact du séisme de 2010 sur l''économie haïtienne ?', '["Un impact mineur","Une destruction d''une part considérable","Une opportunité de croissance","Un renforcement des institutions"]'::jsonb, 'Une destruction d''une part considérable', 'Le séisme de janvier 2010 a causé des dégâts estimés à 120% du PIB haïtien, amplifiant la vulnérabilité.', 'Moyen'),
    (chap_id, 'Qu''est-ce que la microfinance comme outil de développement ?', '["Des prêts aux grandes entreprises","Des services financiers (microcrédit","Une politique monétaire","Des subventions directes"]'::jsonb, 'Des services financiers (microcrédit', 'La microfinance (Grameen Bank, Yunus) vise à réduire la pauvreté en donnant accès au crédit aux exclus.', 'Moyen'),
    (chap_id, 'Qu''est-ce que le "big push" en économie du développement (Rosenstein-Rodan) ?', '["Une aide humanitaire","L''idée qu''un investissement massif et","Une politique commerciale","Un plan d''austérité"]'::jsonb, 'L''idée qu''un investissement massif et', 'Le "grand bond" nécessite un investissement simultané dans plusieurs secteurs pour créer des externalités réciproques.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la dépendance au sentier (path dependency) appliquée aux économies ? ', '["Un pays ne peut jamais changer","Les choix passés (institutions","Le développement linéaire","Le déterminisme géographique"]'::jsonb, 'Les choix passés (institutions', 'North : les institutions héritées de l''histoire créent des "lock-in" qui perpétuent des équilibres sous-optimaux.', 'Difficile'),
    (chap_id, 'Qu''est-ce que le consensus de Washington et ses critiques ?', '["Un accord de paix","Un ensemble de politiques libérales","Un traité commercial","Une doctrine militaire"]'::jsonb, 'Un ensemble de politiques libérales', 'Williamson (1989) : 10 politiques. Critiqué par Stiglitz pour ses effets sociaux et son uniformité.', 'Difficile'),
    (chap_id, 'Qu''est-ce que la trappe à conflits (Paul Collier) et comment affecte-t-elle les PED ?', '["Un problème alimentaire","La tendance des pays pauvres et","La dépendance à l''aide","Le protectionnisme militaire"]'::jsonb, 'La tendance des pays pauvres et', 'Collier dans Le Milliard du bas : les conflits civils détruisent le capital et les institutions, piégeant les pays.', 'Difficile'),
    (chap_id, 'Quel est le rôle des institutions dans le développement économique selon North et Acemoglu ?', '["Aucun rôle","Les institutions inclusives créent les","Seule la géographie détermine le développement","L''aide internationale suffit"]'::jsonb, 'Les institutions inclusives créent les', 'Acemoglu et Robinson dans Why Nations Fail : institutions inclusives vs extractives déterminent la prospérité.', 'Difficile');
  END IF;
END $$;
